/**
 * Copyright (c) 2026 Kumara Swamy — github.com/bkumars22
 * Supply Chain Intelligence Platform
 * Licensed under MIT License — see LICENSE file for details
 */
// Auto-generated by agent25_playwright_generator.py
import { test, expect } from "@playwright/test";
import { APP_URL, loginViaUI } from "./helpers/auth";

test.describe("Main dashboard", () => {

  test.beforeEach(async ({ page }) => {
    await loginViaUI(page);
  });

  test("dashboard page loads without errors", async ({ page }) => {
    await page.goto(APP_URL + "/dashboard");
    await page.waitForLoadState("networkidle");
    // No JS errors
    const errors: string[] = [];
    page.on("pageerror", (err) => errors.push(err.message));
    await page.waitForTimeout(2000);
    // Filter known benign errors
    const realErrors = errors.filter(e =>
      !e.includes("ResizeObserver") &&
      !e.includes("Non-Error promise rejection")
    );
    expect(realErrors).toHaveLength(0);
  });

  test("dashboard page has visible content", async ({ page }) => {
    await page.goto(APP_URL + "/dashboard");
    await page.waitForLoadState("networkidle");
    await expect(page.locator("body")).toBeVisible();
    // Should have some content rendered
    const bodyText = await page.locator("body").innerText();
    expect(bodyText.length).toBeGreaterThan(10);
  });

  test("dashboard page has no broken images", async ({ page }) => {
    await page.goto(APP_URL + "/dashboard");
    await page.waitForLoadState("networkidle");
    const images = page.locator("img");
    const count  = await images.count();
    for (let i = 0; i < Math.min(count, 10); i++) {
      const src = await images.nth(i).getAttribute("src");
      if (src && !src.startsWith("data:")) {
        const status = await page.evaluate(async (imgSrc) => {
          const r = await fetch(imgSrc).catch(() => ({ status: 0 }));
          return r.status;
        }, src);
        expect(status).not.toBe(404);
      }
    }
  });

  test("dashboard page is responsive", async ({ page }) => {
    // Mobile viewport
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(APP_URL + "/dashboard");
    await page.waitForLoadState("networkidle");
    await expect(page.locator("body")).toBeVisible();
    // Back to desktop
    await page.setViewportSize({ width: 1280, height: 720 });
  });

});
