#Provides settings for the online help


#Context_mappings
mcm.help.context.Dashboard=Main.html#src-294245153_id-.MainOHv23.2-Dashboard
mcm.help.context.UploadFile=Main.html#src-294245153_id-.MainOHv23.2-Upload
mcm.help.context.LoadJob-Search=Main.html#src-294245153_id-.MainOHv23.2-ManageUploadJobs
mcm.help.context.Review-Alerts=Main.html#src-294245153_id-.MainOHv23.2-ReviewAlerts

mcm.help.context.Cost-Create=Pricing.html#src-340077171_id-.PricingOHv24.1-NewSourcingLane
mcm.help.context.Cost-Search=Pricing.html#src-340077171_id-.PricingOHv24.1-SearchSourcingLane
mcm.help.context.Cost-SearchDetail=Pricing.html#src-340077171_id-.PricingOHv24.1-SearchCostRecords
mcm.help.context.Price-Variance-Report=Pricing.html#src-340077171_id-.PricingOHv24.1-PriceVarianceReport
mcm.help.context.Search-CostRecordException=Pricing.html#src-340077171_id-.PricingOHv24.1-NewExceptionRequest

mcm.help.context.Rebate-Detail=rebates.html#src-601957089_id-.RebatesOHv26.1-NewRebateProgram
mcm.help.context.Rebate-Search=rebates.html#src-601957089_id-.RebatesOHv26.1-SearchRebateProgram

mcm.help.context.MDM-Item=master_data_management.html#src-601957097_id-.MasterDataManagementOHv26.1-ItemAssignment
mcm.help.context.MDM-Commodity=master_data_management.html#src-601957097_id-.MasterDataManagementOHv26.1-CommodityManagement
mcm.help.context.MDM-BOM=master_data_management.html#src-601957097_id-.MasterDataManagementOHv26.1-BOMManagement

mcm.help.context.SA-Create=supply_allocation_sub_tier.html#src-294245159_id-.SupplyAllocationSubTierOHv23.2-NewSupplyAllocation
mcm.help.context.SA-Search=supply_allocation_sub_tier.html#src-294245159_id-.SupplyAllocationSubTierOHv23.2-SearchSupplyAllocation

mcm.help.context.Forecast-Create=cost_forecast.html#src-601957091_id-.CostForecastOHv26.1-NewCostForecast
mcm.help.context.Forecast-Search=cost_forecast.html#src-601957091_id-.CostForecastOHv26.1-SearchCostForecast
Cost%20Forecast%20Variance%20Report=cost_forecast.html#src-601957091_id-.CostForecastOHv26.1-ForecastVarianceReport

mcm.help.context.Manage-FunctionalGroup=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-ManageFunctionalGroup
mcm.help.context.Manage-ParentFunctionalGroup=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-ManageParentGroup
mcm.help.context.FunctionalGroupAuditHistory=Supply_Allocation.html#src-504179064_safe-id-aWQtLlN1cHBseUFsbG9jYXRpb25PSDF2MjUuMi1BdWRpdEhpc3RvcnkoRnVuY3Rpb25hbEdyb3VwKQ

mcm.help.context.Allocation=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-ManageAllocation
mcm.help.context.TAMAuditHistory=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-SupplyAllocationAuditHistory
mcm.help.context.Download-TAM=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-DownloadAllocation
Supply%20Allocation%20exception=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-SupplyAllocationException
Manage-PriceTAM=Supply_Allocation.html#src-504179064_id-.SupplyAllocationOH1v25.2-XLOBPriceTAM

mcm.help.context.On-Demand-Reports=Reports.html#src-294245169_id-.ReportsOHv23.2-Reports
mcm.help.context.ReportViewer=Reports.html#src-294245169_safe-id-aWQtLlJlcG9ydHNPSHYyMy4yLVN1Ym1pdC9WaWV3UmVwb3J0cw

mcm.help.context.Search-Item=Search2.html#src-340090148_id-.SearchOHv24.1-Items
mcm.help.context.Search-Item-AVL=Search2.html#src-340090148_id-.SearchOHv24.1-ItemAVL
mcm.help.context.Search-BOM=Search2.html#src-340090148_id-.SearchOHv24.1-BOMs

mcm.help.context.UserProfile=administration.html#src-601957109_id-.AdministrationOHv26.1-EditProfile
mcm.help.context.Admin-Message=administration.html#src-601957109_id-.AdministrationOHv26.1-ChangeDashboardNews
mcm.help.context.AlertSubscription=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageAlerts
mcm.help.context.Admin-Item=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageItems
mcm.help.context.Admin-Role=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageRoles
mcm.help.context.Admin-Contact=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageContacts
mcm.help.context.Admin-BusinessEntity=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageBusinessEntities
mcm.help.context.Admin-User=administration.html#src-601957109_id-.AdministrationOHv26.1-ManageUsers
mcm.help.context.AuditHistory=administration.html#src-601957109_id-.AdministrationOHv26.1-AuditHistory
mcm.help.context.Admin-Upload=administration.html#src-601957109_id-.AdministrationOHv26.1-AdminUpload
mcm.help.context.Search-CommodityProfile=administration.html#src-601957109_id-.AdministrationOHv26.1-CommodityProfile
mcm.help.context.Search-UserCommodityProfileMapping=administration.html#src-601957109_id-.AdministrationOHv26.1-UserCommodityProfile