# ${app.rootdir} will be replaced with the root path of the container
report_dir=${app.rootdir}report
filter_dir=${app.rootdir}report

#Directories to scan for fonts.  You can specify more than one
font_dir=${scplatform.deploy.root}/webapps/scplatform.ear/scplatform.war/report/fonts

#Font mapping for PDF fonts
#You can specify by Os using font_map.linux or font_map.windows
#All reports that need unicode characters use the alias Arial Unicode MS.  
#When running on systems without this font, 
#the following maps can be used to assign an appropriate font
#to the alias 'Arial Unicode MS'
#font_map.windows.Arial Unicode MS=${font_dir}/fireflysung.ttf
#font_map.windows.Arial Unicode MS=${font_dir}/wt005.ttf
#Windows system have the font as ARIALUNI.ttf

#This is a free Adobe font available from www.adobe.com
#http://www.adobe.com/products/acrobat/acrrasianfontpack.html
#font_map.linux.Arial Unicode MS=${font_dir}/AdobeMingStd-Light.otf

#Additional fonts http://www.travelphrases.info/fonts.html

#font_map.linux.Arial Unicode MS=${font_dir}/wt005.ttf

generator_class=com.test.common.reporting.JasperReportGenerator
connection_provider=com.test.common.reporting.ReportResourceProvider
connection_provider_datasource_name=java:scplatformDS-RPT
context_provider=com.test.common.reporting.ReportResourceProvider
