/*
 * @SSPNav.java@
 * Created on Jul 08, 2019
 *
 * Copyright (c) 2017 E2open, Inc.
 * All Rights Reserved.
 *
 * THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF E2open
 * The copyright notice above does not evidence any
 * actual or intended publication of such source code.
 *
 */
package com.test.selenium.scplatform.navigation;

import com.test.selenium.common.JLog;

/**
 * @author AutoGenerated
 *
 *         Created on 2019-07-08T20:59:02.898Z from
 *         com.test.selenium.common.navigation.unity.NavigationBuilder
 */
public class HarmonyMTCMNavigation {

	String functionalGroupName = "";

	/**
	 * Home
	 */
	public static String[] Home() {
		return new String[] { "Home|name=serviceHome" };
	}

	/**
	 * My Workspace
	 */
	public static String[] MyWorkspace() {
		return new String[] { "My Workspace|name=thePortalPage" };
	}
	
	/**
	 * My Workspace
	 */
	public static String[] Admin() {
		return new String[] { "Admin|name=Administration" };
	}

	 /**
     * Navigation: Administration -> Change Dashboard News
     */
//    public boolean ChangeDashboardNews() {
//        String[] nav = { "Administration", "Change Dashboard News" };
//        boolean sucess = this.open(nav);
//        if ((!sucess) && (failOnError))
//            JLog.fail(errorMsg);
//
//        return sucess;
//    }

	
	// ===========================================================================

	/**
	 * MENU: Supply Allocation
	 */
//	public static class MainMenu {
//		private MainMenu() {
//		}

		/**
		 * main menu --> sub menu
		 */

		public static String[] SubMenu(String mainMenu, String subMenu) {
			return new String[] { mainMenu, subMenu + "|name=" + subMenu };
		}

//	}
}
