// Mock data for GitHub Pages demo mode — no backend required

export const MOCK_SUPPLIERS = [
  {
    supplierId: "SUPP-001",
    supplierName: "TechParts India Pvt Ltd",
    country: "India",
    tier: "PROBATION",
    compositeScore: 38.4,
    otdScore: 42.0,
    qualityScore: 36.5,
    responsivenessScore: 44.2,
    totalDeliveries: 120,
    onTimeDeliveries: 50,
    atRisk: true,
    riskLevel: "HIGH",
    anomaly: true,
  },
  {
    supplierId: "SUPP-002",
    supplierName: "GlobalComp Singapore",
    country: "Singapore",
    tier: "PREFERRED",
    compositeScore: 91.2,
    otdScore: 91.0,
    qualityScore: 92.5,
    responsivenessScore: 90.1,
    totalDeliveries: 310,
    onTimeDeliveries: 282,
    atRisk: false,
    riskLevel: "LOW",
    anomaly: false,
  },
  {
    supplierId: "SUPP-003",
    supplierName: "SwiftLogix Dubai",
    country: "UAE",
    tier: "APPROVED",
    compositeScore: 67.8,
    otdScore: 67.0,
    qualityScore: 70.3,
    responsivenessScore: 66.1,
    totalDeliveries: 185,
    onTimeDeliveries: 124,
    atRisk: false,
    riskLevel: "MEDIUM",
    anomaly: false,
  },
  {
    supplierId: "SUPP-004",
    supplierName: "PrecisionMfg Chennai",
    country: "India",
    tier: "PROBATION",
    compositeScore: 29.6,
    otdScore: 38.0,
    qualityScore: 22.8,
    responsivenessScore: 28.0,
    totalDeliveries: 95,
    onTimeDeliveries: 36,
    atRisk: true,
    riskLevel: "CRITICAL",
    anomaly: true,
  },
  {
    supplierId: "SUPP-005",
    supplierName: "NexusParts Germany",
    country: "Germany",
    tier: "PREFERRED",
    compositeScore: 88.7,
    otdScore: 88.0,
    qualityScore: 91.4,
    responsivenessScore: 86.7,
    totalDeliveries: 260,
    onTimeDeliveries: 229,
    atRisk: false,
    riskLevel: "LOW",
    anomaly: false,
  },
];

export const MOCK_SUPPLIER_DELIVERIES = {
  "SUPP-001": [
    { poNumber: "PO-2026-1001", itemCode: "PCB-001", promisedDate: "2026-03-10", actualDate: "2026-03-18", qtyOrdered: 500, qtyReceived: 480, status: "DELAYED", delayDays: 8 },
    { poNumber: "PO-2026-1002", itemCode: "CHIP-002", promisedDate: "2026-04-01", actualDate: "2026-04-12", qtyOrdered: 1000, qtyReceived: 950, status: "DELAYED", delayDays: 11 },
    { poNumber: "PO-2026-1003", itemCode: "PCB-001", promisedDate: "2026-05-15", actualDate: "2026-05-15", qtyOrdered: 300, qtyReceived: 300, status: "ON_TIME", delayDays: 0 },
  ],
  "SUPP-002": [
    { poNumber: "PO-2026-2001", itemCode: "CHIP-001", promisedDate: "2026-02-20", actualDate: "2026-02-20", qtyOrdered: 2000, qtyReceived: 2000, status: "ON_TIME", delayDays: 0 },
    { poNumber: "PO-2026-2002", itemCode: "SENSOR-X", promisedDate: "2026-03-05", actualDate: "2026-03-05", qtyOrdered: 800, qtyReceived: 800, status: "ON_TIME", delayDays: 0 },
    { poNumber: "PO-2026-2003", itemCode: "CHIP-001", promisedDate: "2026-04-18", actualDate: "2026-04-19", qtyOrdered: 1500, qtyReceived: 1500, status: "DELAYED", delayDays: 1 },
  ],
  "SUPP-003": [
    { poNumber: "PO-2026-3001", itemCode: "LOG-BOX-A", promisedDate: "2026-03-01", actualDate: "2026-03-04", qtyOrdered: 50, qtyReceived: 50, status: "DELAYED", delayDays: 3 },
    { poNumber: "PO-2026-3002", itemCode: "LOG-BOX-B", promisedDate: "2026-04-10", actualDate: "2026-04-10", qtyOrdered: 75, qtyReceived: 75, status: "ON_TIME", delayDays: 0 },
  ],
  "SUPP-004": [
    { poNumber: "PO-2026-4001", itemCode: "HYD-VALVE", promisedDate: "2026-02-15", actualDate: "2026-03-02", qtyOrdered: 200, qtyReceived: 180, status: "DELAYED", delayDays: 15 },
    { poNumber: "PO-2026-4002", itemCode: "SENSOR-Y", promisedDate: "2026-03-20", actualDate: "2026-04-01", qtyOrdered: 400, qtyReceived: 360, status: "DELAYED", delayDays: 12 },
  ],
  "SUPP-005": [
    { poNumber: "PO-2026-5001", itemCode: "CAP-100UF", promisedDate: "2026-03-08", actualDate: "2026-03-08", qtyOrdered: 5000, qtyReceived: 5000, status: "ON_TIME", delayDays: 0 },
    { poNumber: "PO-2026-5002", itemCode: "RES-10K", promisedDate: "2026-04-22", actualDate: "2026-04-22", qtyOrdered: 10000, qtyReceived: 10000, status: "ON_TIME", delayDays: 0 },
    { poNumber: "PO-2026-5003", itemCode: "CAP-100UF", promisedDate: "2026-05-30", actualDate: "2026-05-30", qtyOrdered: 5000, qtyReceived: 5000, status: "ON_TIME", delayDays: 0 },
  ],
};

export const MOCK_DASHBOARD_KPIS = {
  activeAlerts: 3,
  totalBoms: 10,
  pendingApprovals: 1,
  atRiskSuppliers: 2,
  unreadAlerts: 3,
  activeBoms: 10,
  pendingBoms: 1,
  totalSuppliers: 47,
  avgOtd: 73.4,
  costSavings: 2400000,
};

export const MOCK_ALERTS = [
  {
    id: "ALT-001",
    alertLabel: "TechParts India OTD Below Threshold",
    alertType: "CRITICAL_RISK",
    shortSummary: "OTD score dropped to 42% — below 45% minimum threshold",
    longSummary: "High risk supplier detected. OTD score of 42% indicates systemic delivery failures. Recommend immediate supplier review and qualification of backup supplier.",
    created: "2026-06-18",
  },
  {
    id: "ALT-002",
    alertLabel: "PrecisionMfg Defect Rate Exceeded",
    alertType: "CRITICAL_RISK",
    shortSummary: "Defect rate 11.7% — 3x above acceptable 4% threshold",
    longSummary: "Critical quality issue detected. Defect rate of 11.7% is 3x above acceptable threshold. Recommend production hold and root cause analysis.",
    created: "2026-06-17",
  },
  {
    id: "ALT-003",
    alertLabel: "Lead Time Variance Increased 40%",
    alertType: "WARNING",
    shortSummary: "Supply chain disruption detected in logistics routing",
    longSummary: "Supply chain disruption detected. Lead time variance suggests logistics bottleneck. Recommend route diversification.",
    created: "2026-06-16",
  },
];

export const MOCK_COST_RECORDS = [
  {
    id: "CR-2026-001",
    itemKey: "CR-2026-001",
    itemCode: "RAW-MAT-Q2",
    proposedCost: 340000,
    previousCost: 310000,
    status: "APPROVED",
    justification: "Raw materials Q2 procurement — bulk discount negotiated with 3 vendors",
    effectiveDate: "2026-04-01",
    createdBy: "kumar",
  },
  {
    id: "CR-2026-002",
    itemKey: "CR-2026-002",
    itemCode: "LOG-OPT-2026",
    proposedCost: 89500,
    previousCost: 120000,
    status: "DRAFT",
    justification: "Logistics optimization via new routing algorithm — 25% cost reduction",
    effectiveDate: "2026-07-01",
    createdBy: "kumar",
  },
  {
    id: "CR-2026-003",
    itemKey: "CR-2026-003",
    itemCode: "AUDIT-PROG",
    proposedCost: 45200,
    previousCost: 38000,
    status: "APPROVED",
    justification: "Supplier audit program expanded to cover high-risk tier suppliers",
    effectiveDate: "2026-05-15",
    createdBy: "kumar",
  },
  {
    id: "CR-2026-004",
    itemKey: "CR-2026-004",
    itemCode: "EMRG-PROC",
    proposedCost: 127800,
    previousCost: null,
    status: "PENDING_APPROVAL",
    justification: "Emergency procurement triggered by TechParts India supply disruption",
    effectiveDate: "2026-06-20",
    createdBy: "kumar",
  },
];

export const MOCK_BOMS = [
  {
    bomKey: "BOM-2026-001",
    bomName: "PCB Assembly v2.3",
    bomExternalId: "PCB-ASM-V23",
    bomDescription: "Main PCB assembly for industrial controller series",
    item: { itemNumber: "FG-PCB-V23" },
    status: "APPROVED",
    lines: [
      { itemNumber: "CAP-100UF", description: "100µF electrolytic capacitor", itemQuantity: 12, rollupFlag: "Y", notes: "Rated 50V" },
      { itemNumber: "RES-10K", description: "10kΩ resistor 1/4W", itemQuantity: 48, rollupFlag: "Y", notes: "" },
      { itemNumber: "IC-555", description: "NE555 timer IC", itemQuantity: 4, rollupFlag: "Y", notes: "SMD package" },
      { itemNumber: "CONN-DB9", description: "DB9 connector male", itemQuantity: 2, rollupFlag: "N", notes: "Panel mount" },
      { itemNumber: "PCB-BARE", description: "Bare PCB substrate FR4", itemQuantity: 1, rollupFlag: "Y", notes: "2oz copper" },
    ],
  },
  {
    bomKey: "BOM-2026-002",
    bomName: "Hydraulic Module A",
    bomExternalId: "HYD-MOD-A",
    bomDescription: "Hydraulic control module for heavy machinery line",
    item: { itemNumber: "FG-HYD-A" },
    status: "APPROVED",
    lines: [
      { itemNumber: "HYD-VALVE", description: "Solenoid valve 24V DC", itemQuantity: 3, rollupFlag: "Y", notes: "IP67 rated" },
      { itemNumber: "SENSOR-P", description: "Pressure sensor 0-300 bar", itemQuantity: 2, rollupFlag: "Y", notes: "" },
      { itemNumber: "PUMP-GEAR", description: "Gear pump 15L/min", itemQuantity: 1, rollupFlag: "Y", notes: "Replace every 5000h" },
    ],
  },
  {
    bomKey: "BOM-2026-003",
    bomName: "Sensor Array Kit",
    bomExternalId: "SENS-ARR-KT",
    bomDescription: "Multi-sensor array kit for environmental monitoring",
    item: { itemNumber: "FG-SENS-ARR" },
    status: "CONDITIONAL",
    lines: [
      { itemNumber: "SENSOR-T", description: "Temperature sensor NTC 10kΩ", itemQuantity: 8, rollupFlag: "Y", notes: "-40 to +125°C" },
      { itemNumber: "SENSOR-H", description: "Humidity sensor SHT31", itemQuantity: 4, rollupFlag: "Y", notes: "±2% RH" },
      { itemNumber: "SENSOR-Y", description: "Vibration sensor MEMS", itemQuantity: 4, rollupFlag: "Y", notes: "3-axis" },
      { itemNumber: "CABLE-SHLD", description: "Shielded cable 4-core 1m", itemQuantity: 8, rollupFlag: "N", notes: "" },
    ],
  },
];

export const MOCK_USERS = [
  { userId: "admin", userName: "Admin User", emailId: "admin@scip.com", roleName: "ADMIN", isEnabled: true, hasPassword: true },
  { userId: "demo", userName: "Demo User", emailId: "demo@scip.com", roleName: "BUS_ADMIN", isEnabled: true, hasPassword: true },
  { userId: "qa.engineer", userName: "QA Engineer", emailId: "qa@scip.com", roleName: "GUEST", isEnabled: true, hasPassword: true },
  { userId: "scm.manager", userName: "Supply Chain Manager", emailId: "scm@scip.com", roleName: "BUS_ADMIN", isEnabled: true, hasPassword: true },
];

export const MOCK_ROLES = [
  { roleName: "ADMIN" },
  { roleName: "BUS_ADMIN" },
  { roleName: "GUEST" },
];

export const MOCK_FORECASTS = [
  {
    forecastKey: "FC-2026-001",
    itemNumber: "PCB-001",
    forecastType: "DEMAND",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-06-30",
    values: [
      { periodLabel: "Jan 2026", forecastQty: 1200, actualQty: 1150, variance: -50, variancePct: -4.2 },
      { periodLabel: "Feb 2026", forecastQty: 1350, actualQty: 1410, variance: 60, variancePct: 4.4 },
      { periodLabel: "Mar 2026", forecastQty: 1400, actualQty: 1380, variance: -20, variancePct: -1.4 },
      { periodLabel: "Apr 2026", forecastQty: 1500, actualQty: 1620, variance: 120, variancePct: 8.0 },
      { periodLabel: "May 2026", forecastQty: 1450, actualQty: 1390, variance: -60, variancePct: -4.1 },
      { periodLabel: "Jun 2026", forecastQty: 1600, actualQty: null, variance: null, variancePct: null },
    ],
  },
  {
    forecastKey: "FC-2026-002",
    itemNumber: "CHIP-001",
    forecastType: "SUPPLY",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-06-30",
    values: [
      { periodLabel: "Jan 2026", forecastQty: 5000, actualQty: 4800, variance: -200, variancePct: -4.0 },
      { periodLabel: "Feb 2026", forecastQty: 5500, actualQty: 5500, variance: 0, variancePct: 0.0 },
      { periodLabel: "Mar 2026", forecastQty: 5200, actualQty: 5800, variance: 600, variancePct: 11.5 },
      { periodLabel: "Apr 2026", forecastQty: 6000, actualQty: 5200, variance: -800, variancePct: -13.3 },
      { periodLabel: "May 2026", forecastQty: 5800, actualQty: 6100, variance: 300, variancePct: 5.2 },
    ],
  },
  {
    forecastKey: "FC-2026-003",
    itemNumber: "HYD-VALVE",
    forecastType: "INVENTORY",
    effectiveFrom: "2026-03-01",
    effectiveTo: "2026-08-31",
    values: [
      { periodLabel: "Mar 2026", forecastQty: 200, actualQty: 185, variance: -15, variancePct: -7.5 },
      { periodLabel: "Apr 2026", forecastQty: 220, actualQty: 240, variance: 20, variancePct: 9.1 },
      { periodLabel: "May 2026", forecastQty: 210, actualQty: 195, variance: -15, variancePct: -7.1 },
      { periodLabel: "Jun 2026", forecastQty: 230, actualQty: null, variance: null, variancePct: null },
    ],
  },
];

export const MOCK_ANOMALIES = [
  {
    id: "ANO-001",
    severity: "CRITICAL",
    category: "Supplier Risk",
    itemCode: "SUPP-001",
    description: "TechParts India OTD score dropped 18% in 30 days — systemic delivery failure pattern detected",
    confidenceScore: 94,
    detectedAt: "2026-06-18T09:14:22",
    affectedItems: [
      { itemCode: "PCB-001", itemName: "PCB Assembly v2.3" },
      { itemCode: "CHIP-002", itemName: "Microcontroller Unit" },
    ],
    recommendation: "Qualify backup supplier immediately. Issue supplier performance notice. Increase safety stock for PCB-001 by 30%.",
  },
  {
    id: "ANO-002",
    severity: "CRITICAL",
    category: "Quality",
    itemCode: "SUPP-004",
    description: "PrecisionMfg defect rate 11.7% — 3x above threshold. Batch rejection events spiking",
    confidenceScore: 91,
    detectedAt: "2026-06-17T14:30:00",
    affectedItems: [
      { itemCode: "HYD-VALVE", itemName: "Solenoid Valve 24V" },
      { itemCode: "SENSOR-Y", itemName: "Vibration Sensor MEMS" },
    ],
    recommendation: "Place hold on new orders from PrecisionMfg Chennai. Initiate root cause analysis. Source HYD-VALVE from NexusParts Germany.",
  },
  {
    id: "ANO-003",
    severity: "WARNING",
    category: "Lead Time",
    itemCode: "LOG-ROUTE-EU",
    description: "EU logistics corridor lead time variance increased 40% — likely port congestion impact",
    confidenceScore: 76,
    detectedAt: "2026-06-16T11:45:00",
    affectedItems: [
      { itemCode: "CAP-100UF", itemName: "Electrolytic Capacitor 100µF" },
      { itemCode: "RES-10K", itemName: "Resistor 10kΩ" },
    ],
    recommendation: "Activate alternate logistics route via Rotterdam. Pre-position 2-week buffer stock for EU-sourced components.",
  },
  {
    id: "ANO-004",
    severity: "WARNING",
    category: "Cost Variance",
    itemCode: "RAW-MAT-STEEL",
    description: "Steel raw material price 22% above Q1 baseline — commodity volatility detected",
    confidenceScore: 68,
    detectedAt: "2026-06-15T08:00:00",
    affectedItems: [
      { itemCode: "HYD-VALVE", itemName: "Solenoid Valve 24V" },
    ],
    recommendation: "Review open POs for steel-dependent components. Consider forward contracts to hedge Q3 exposure.",
  },
];

export const MOCK_TEST_RESULTS = {
  total: 51,
  passed: 51,
  failed: 0,
  skipped: 0,
  duration: 18420,
  timestamp: new Date().toISOString(),
  tests: [
    { group: "Auth Module", name: "BB-AUTH-01: Valid login returns JWT token", status: "passed", duration: 312 },
    { group: "Auth Module", name: "BB-AUTH-02: Wrong password returns 401", status: "passed", duration: 218 },
    { group: "Auth Module", name: "BB-AUTH-03: Unknown user returns 401", status: "passed", duration: 199 },
    { group: "Auth Module", name: "BB-AUTH-04: No token returns 403", status: "passed", duration: 185 },
    { group: "Auth Module", name: "BB-AUTH-05: Malformed token returns 403", status: "passed", duration: 201 },
    { group: "Auth Module", name: "SEC-01: SQL injection in login blocked", status: "passed", duration: 244 },
    { group: "Item Master", name: "BB-ITEM-01: GET returns all 10 items", status: "passed", duration: 156 },
    { group: "Item Master", name: "BB-ITEM-02: Seed data has PCB-001 CHIP-001 FG-LAPTOP-X1", status: "passed", duration: 143 },
    { group: "Item Master", name: "BB-ITEM-03: PCB-001 is COMPONENT type", status: "passed", duration: 138 },
    { group: "Item Master", name: "BB-ITEM-04: POST /api/items returns 201", status: "passed", duration: 290 },
    { group: "Item Master", name: "NEG-ITEM-01: GET without auth returns 403", status: "passed", duration: 122 },
    { group: "BOM", name: "BB-BOM-01: GET returns paginated BOM list", status: "passed", duration: 178 },
    { group: "BOM", name: "BB-BOM-02: Laptop X1 BOM has FG-LAPTOP-X1", status: "passed", duration: 162 },
    { group: "BOM", name: "BB-BOM-03: GET /api/bom/201 returns detail", status: "passed", duration: 195 },
    { group: "BOM", name: "NEG-BOM-01: Non-existent BOM key returns 404", status: "passed", duration: 133 },
    { group: "Cost Records", name: "BB-COST-01: GET /api/cost-records returns 200", status: "passed", duration: 167 },
    { group: "Cost Records", name: "BB-COST-02: POST cost record creates DRAFT", status: "passed", duration: 280 },
    { group: "Cost Records", name: "BB-COST-03: Submit moves to PENDING_APPROVAL", status: "passed", duration: 245 },
    { group: "Cost Records", name: "BB-COST-04: Approve updates status to APPROVED", status: "passed", duration: 263 },
    { group: "Cost Records", name: "NEG-COST-01: GET without auth returns 403", status: "passed", duration: 119 },
    { group: "Suppliers", name: "BB-SUP-01: GET returns supplier list", status: "passed", duration: 188 },
    { group: "Suppliers", name: "BB-SUP-02: Supplier fields present: name, otdScore, tier", status: "passed", duration: 142 },
    { group: "Suppliers", name: "BB-SUP-03: At-risk suppliers correctly flagged", status: "passed", duration: 155 },
    { group: "Suppliers", name: "BB-SUP-04: Deliveries endpoint returns history", status: "passed", duration: 211 },
    { group: "Suppliers", name: "BB-SUP-05: Recalculate tiers endpoint returns 200", status: "passed", duration: 334 },
    { group: "Suppliers", name: "NEG-SUP-01: GET without auth returns 403", status: "passed", duration: 121 },
    { group: "Users", name: "BB-USR-01: GET /api/admin/users returns list", status: "passed", duration: 175 },
    { group: "Users", name: "BB-USR-02: GET /api/admin/roles returns roles", status: "passed", duration: 143 },
    { group: "Users", name: "BB-USR-03: POST create user returns 201", status: "passed", duration: 308 },
    { group: "Users", name: "NEG-USR-01: Duplicate user ID rejected with 409", status: "passed", duration: 189 },
    { group: "Users", name: "SEC-USR-01: Password not returned in user list", status: "passed", duration: 138 },
    { group: "Alerts", name: "BB-ALERT-01: GET /api/alerts/active returns alerts", status: "passed", duration: 161 },
    { group: "Alerts", name: "BB-ALERT-02: Dismiss removes alert from list", status: "passed", duration: 234 },
    { group: "Alerts", name: "BB-ALERT-03: Dashboard activeAlerts count is a number", status: "passed", duration: 148 },
    { group: "Alerts", name: "NEG-ALERT-01: Dismiss non-existent alert returns 404", status: "passed", duration: 172 },
    { group: "Alerts", name: "BB-ALERT-04: All alert filter types work", status: "passed", duration: 155 },
    { group: "Dashboard", name: "BB-DASH-01: GET summary returns KPI fields", status: "passed", duration: 143 },
    { group: "Dashboard", name: "BB-DASH-02: All KPI values are numbers", status: "passed", duration: 118 },
    { group: "Dashboard", name: "BB-DASH-03: ActiveAlerts matches alerts endpoint count", status: "passed", duration: 167 },
    { group: "Dashboard", name: "BB-DASH-04: Quick actions navigate correctly", status: "passed", duration: 299 },
    { group: "Dashboard", name: "BB-DASH-05: Dismiss alert updates dashboard count", status: "passed", duration: 278 },
    { group: "Eval Module", name: "EVAL-01: /eval/results endpoint returns 200", status: "passed", duration: 422 },
    { group: "Eval Module", name: "EVAL-02: Overall score field present on all rows", status: "passed", duration: 338 },
    { group: "Eval Module", name: "EVAL-03: Consistency score between 0 and 1", status: "passed", duration: 311 },
    { group: "Eval Module", name: "EVAL-04: Response latency under 500ms", status: "passed", duration: 289 },
    { group: "Eval Module", name: "EVAL-05: /eval/run returns report + results", status: "passed", duration: 1240 },
    { group: "Eval Module", name: "EVAL-06: Pass threshold correctly applied at 0.7", status: "passed", duration: 305 },
    { group: "Eval Module", name: "EVAL-07: Heuristic mode returns consistent results", status: "passed", duration: 418 },
    { group: "Eval Module", name: "EVAL-08: LLM judge mode uses claude-haiku", status: "passed", duration: 892 },
    { group: "Eval Module", name: "EVAL-09: AI service rate limiting returns 429", status: "passed", duration: 267 },
    { group: "Eval Module", name: "EVAL-10: Eval results persist across sessions", status: "passed", duration: 344 },
  ],
};

export const MOCK_EVAL_SCORES = [
  {
    test_case_id: "EVAL-001",
    category: "supplier_risk",
    input: "Explain the risk profile of TechParts India with OTD 42% and defect rate 8.3%",
    scores: { overall_score: 0.91, answer_relevancy: 0.93, consistency_score: 0.96, response_latency_ms: 12 },
  },
  {
    test_case_id: "EVAL-002",
    category: "alert_classification",
    input: "Classify severity for: supplier defect rate exceeded 10% threshold",
    scores: { overall_score: 0.87, answer_relevancy: 0.89, consistency_score: 0.94, response_latency_ms: 18 },
  },
  {
    test_case_id: "EVAL-003",
    category: "procurement",
    input: "Recommend procurement action for PrecisionMfg Chennai with critical quality issues",
    scores: { overall_score: 0.93, answer_relevancy: 0.95, consistency_score: 0.97, response_latency_ms: 14 },
  },
  {
    test_case_id: "EVAL-004",
    category: "trend_analysis",
    input: "Analyze OTD trend for GlobalComp Singapore: 88%, 91%, 89%, 92%, 91%",
    scores: { overall_score: 0.78, answer_relevancy: 0.81, consistency_score: 0.92, response_latency_ms: 21 },
  },
  {
    test_case_id: "EVAL-005",
    category: "cost_anomaly",
    input: "Explain cost anomaly: steel raw material price 22% above Q1 baseline",
    scores: { overall_score: 0.82, answer_relevancy: 0.84, consistency_score: 0.91, response_latency_ms: 16 },
  },
];

export const MOCK_EVAL_SUMMARY = {
  total_cases: 5,
  avg_overall_score: 0.862,
  pass: true,
  avg_consistency: 0.942,
  mode: "heuristic",
  generated_at: new Date().toISOString(),
  _computed: false,
  _passed: 5,
  _failed: 0,
};
