-- ============================================================
-- Seed data for local H2 development  (create-drop safe)
-- ============================================================

-- ── Roles ────────────────────────────────────────────────────
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (1,'ADMIN','Administrator','Y');
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (2,'BUS_ADMIN','Business Administrator','Y');
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (3,'GUEST','Read Only','Y');
ALTER SEQUENCE PCM_ROLE_SEQ RESTART WITH 100;

-- ── Business entity ──────────────────────────────────────────
INSERT INTO BUSINESS_ENTITY (BUSINESS_ENTITY_KEY,BUSINESS_ENTITY_IDENTIFIER,BUSINESS_ENTITY_NAME,BUSINESS_ENTITY_DESC,BUSINESS_ENTITY_TYPE_KEY,DATA_SOURCE,INSERT_DT,CURRENT_FLAG)
  VALUES (1,'ENTERPRISE','SC Platform Enterprise','Default Enterprise',1,'SCM',CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE BUSINESS_ENTITY_SEQ RESTART WITH 100;

-- ── 5 Users with BCrypt-hashed passwords (cost=10) ──────────
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (1,'ADMIN','Administrator',NULL,NULL,1,TRUE,'$2a$10$MMURX4mhw7e.QBRR8rfU/OhNTXpXE1s9zjvoF4hENfm1lBgbnAYH.');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (2,'kumar','Kumar Swamy',1,NULL,1,TRUE,'$2a$10$VtbLdvpiibeVWy8AknmsZu5l9HM7rqcwIpCyVeagbIwCK33xfxfjC');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (3,'buyer','Buyer User',1,NULL,2,TRUE,'$2a$10$cY2s7pcFHnO7NGtuRPswWuwq6.n2YdPxIBpVLBk8.ypdlcyNQ5i7C');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (4,'analyst','Cost Analyst',1,NULL,2,TRUE,'$2a$10$Fd4F94WfTewPPOgtJlAKKOl10VQlbzPexFR6znJogQwCLYbdgUznq');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (5,'viewer','Read Only Viewer',1,NULL,3,TRUE,'$2a$10$huhc88OxRjO5r/vQvj33..aZtSa3BiaDyvI90tfdFDp2VlJdJxyK6');
ALTER SEQUENCE PCM_USER_SEQ RESTART WITH 100;

-- ── 20 Items ─────────────────────────────────────────────────
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (101,'PCB-001','PCB-001-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (102,'PCB-002','PCB-002-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (103,'PCB-003','PCB-003-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (104,'CHIP-001','CHIP-001-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (105,'CHIP-002','CHIP-002-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (106,'FG-LAPTOP-X1','FG-LAPTOP-X1-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (107,'FG-TABLET-T2','FG-TABLET-T2-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (108,'RAW-COPPER-01','RAW-COPPER-01-v1','RAW_MATERIAL','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (109,'CAP-100UF','CAP-100UF-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (110,'RES-10K','RES-10K-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (111,'INDUCTOR-47UH','INDUCTOR-47UH-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (112,'TRANS-5V-3A','TRANS-5V-3A-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (113,'FG-SERVER-S3','FG-SERVER-S3-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (114,'DIODE-1N4007','DIODE-1N4007-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (115,'LED-RED-5MM','LED-RED-5MM-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (116,'CONN-USB-C','CONN-USB-C-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (117,'FG-ROUTER-R1','FG-ROUTER-R1-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (118,'RAW-ALUMINIUM-02','RAW-ALUMINIUM-02-v1','RAW_MATERIAL','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (119,'BATTERY-3S-5000','BATTERY-3S-5000-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (120,'HEATSINK-40MM','HEATSINK-40MM-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE IF EXISTS ITEM_MASTER_SEQ RESTART WITH 500;

-- ── 10 BOM Headers (STATUS matches controller: Approved/Pending/Active) ──
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (201,'BOM-LAPTOP-001','Laptop X1 BOM','Bill of Materials for Laptop X1','MCM',1,106,TRUE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (202,'BOM-TABLET-001','Tablet T2 BOM','Bill of Materials for Tablet T2','MCM',1,107,TRUE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (203,'BOM-PCB-001','PCB Assembly BOM','Printed Circuit Board Assembly','MCM',1,101,FALSE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (204,'BOM-SERVER-001','Server S3 BOM','Bill of Materials for Server S3','MCM',1,113,TRUE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (205,'BOM-ROUTER-001','Router R1 BOM','Bill of Materials for Router R1','MCM',1,117,TRUE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (206,'BOM-PCB-002','PCB-002 Sub-Assembly','Sub-assembly for PCB-002','MCM',1,102,FALSE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (207,'BOM-PCB-003','PCB-003 Sub-Assembly','Sub-assembly for PCB-003','MCM',1,103,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (208,'BOM-CHIP-001','CHIP-001 Process BOM','Process BOM for CHIP-001','MCM',1,104,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (209,'BOM-BATTERY-001','Battery Pack BOM','BOM for 3S battery pack','MCM',1,119,FALSE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (210,'BOM-CONN-001','Connector Assembly BOM','USB-C connector assembly','MCM',1,116,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE IF EXISTS BOM_HEADER_SEQ RESTART WITH 500;

-- ── 10 Alerts ────────────────────────────────────────────────
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (401,'ACTIVE','kumar','COST_SPIKE','ALERT-001','COST_CHANGE',CURRENT_DATE,'PCB-001 cost increased 25%','PCB-001 cost rose from 48 to 60 USD.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (402,'ACTIVE','kumar','SUPPLIER_RISK','ALERT-002','SUPPLIER_PERFORMANCE',CURRENT_DATE,'SUPP-003 OTD below 70%','Taiwan Semiconductors OTD dropped to 62%.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (403,'ACTIVE','kumar','BOM_CHANGE','ALERT-003','BOM_UPDATE',CURRENT_DATE,'BOM-LAPTOP-001 updated','PCB-002 quantity changed from 1 to 2.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (404,'ACTIVE','kumar','LEAD_TIME','ALERT-004','SUPPLY_RISK',CURRENT_DATE,'CHIP-001 lead time 16 weeks','Foxconn extended lead time.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (405,'ACTIVE','kumar','PENDING_APPROVAL','ALERT-005','WORKFLOW',CURRENT_DATE,'3 cost records pending','CR-002 CR-003 CR-004 awaiting approval.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (406,'ACTIVE','kumar','INVENTORY_LOW','ALERT-006','INVENTORY',CURRENT_DATE,'CAP-100UF below safety stock','150 units remaining.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (407,'ACTIVE','kumar','PRICE_EXPIRY','ALERT-007','CONTRACT',CURRENT_DATE,'Murata contract expiring','RES-10K pricing expires 2025-01-31.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (408,'ACTIVE','kumar','QUALITY_ISSUE','ALERT-008','QUALITY',CURRENT_DATE,'PCB-003 defect rate 3.2%','Above 2.0 percent threshold.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (409,'ACTIVE','kumar','DEMAND_SPIKE','ALERT-009','DEMAND',CURRENT_DATE,'FG-LAPTOP-X1 demand up 40%','Unexpected demand spike from APAC region.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (410,'ACTIVE','kumar','FORECAST_MISS','ALERT-010','FORECAST',CURRENT_DATE,'CHIP-002 forecast accuracy 58%','Below 80% accuracy threshold for Q1.');

-- ── 10 Suppliers (SUPPLIER_PROFILE) ─────────────────────────
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-001','Shenzhen Electronics Co.','China','contact@shenzelec.cn','+86-755-8888-0001','PREFERRED','2020-01-15',88.0,95.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-002','Foxconn Technology Group','Taiwan','procurement@foxconn.com','+886-2-2268-3466','APPROVED','2019-06-01',90.0,78.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-003','Taiwan Semiconductors Ltd','Taiwan','supply@tsmc-ltd.tw','+886-3-563-6688','CONDITIONAL','2021-03-10',75.0,70.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-004','Murata Manufacturing','Japan','global@murata.com','+81-75-951-9111','PREFERRED','2018-09-20',99.0,92.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-005','Delta Electronics India','India','sourcing@delta.in','+91-80-4567-8901','PROBATION','2022-07-01',65.0,60.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-006','Samsung SDI Korea','South Korea','sdi.supply@samsung.com','+82-31-8006-3114','PREFERRED','2017-11-05',97.0,89.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-007','Vishay Intertechnology','USA','orders@vishay.com','+1-610-644-1300','APPROVED','2020-04-22',93.0,85.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-008','TE Connectivity','Switzerland','tecsupply@te.com','+41-52-2241-234','APPROVED','2021-08-15',91.0,82.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-009','Infineon Technologies','Germany','supply@infineon.com','+49-89-234-0','CONDITIONAL','2022-02-28',80.0,74.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-010','STMicroelectronics','Italy','st.supply@st.com','+39-02-3878-1','APPROVED','2020-10-01',87.0,79.0,TRUE);

-- ── 10 Cost Records (MS3_COST_RECORD) ───────────────────────
-- item_code column = FK to ITEM_MASTER.ITEM_KEY
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (101,1,60.00,48.00,25.00,'PENDING_APPROVAL','Shenzhen increased raw material cost 25%','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (102,1,35.50,32.00,10.94,'DRAFT','Annual PCB-002 cost review','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (103,1,28.00,25.00,12.00,'APPROVED','PCB-003 approved after audit','ADMIN',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,approved_by,created_by,created_date) VALUES (104,1,125.00,118.00,5.93,'APPROVED','Chip shortage premium approved','ADMIN','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (105,1,89.00,72.00,23.61,'DRAFT','Spot market pricing CHIP-002','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (109,1,0.85,0.75,13.33,'PENDING_APPROVAL','Delta supply constraint CAP-100UF','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (110,1,0.025,0.020,25.00,'DRAFT','RES-10K annual pricing review','analyst',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (111,1,1.20,0.98,22.45,'PENDING_APPROVAL','Inductor lead time premium','analyst',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,approved_by,created_by,created_date) VALUES (112,1,12.50,11.00,13.64,'APPROVED','Transformer cost approved Q1','ADMIN','buyer',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (119,1,45.00,39.00,15.38,'DRAFT','Battery cell price increase','buyer',CURRENT_TIMESTAMP);

-- ── 10 Forecasts (PCM_FORECAST) ─────────────────────────────
-- Required NOT NULL: FORECAST_TYPE, CALENDAR_NAME, FORECAST_MODEL, INSERT_DT, CURRENT_FLAG, DELETE_FLAG
-- CURRENT_FLAG / DELETE_FLAG use YesNoConverter → 'Y'/'N'
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (601,106,'DEMAND','STANDARD_CALENDAR','CURRENT','APPROVED','Laptop X1 Q1 Demand Forecast','2026-01-01','2026-03-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (602,107,'DEMAND','STANDARD_CALENDAR','CURRENT','APPROVED','Tablet T2 Q1 Demand Forecast','2026-01-01','2026-03-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (603,101,'COST','STANDARD_CALENDAR','ADJUSTABLE','SUBMITTED','PCB-001 Cost Forecast Q2','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (604,104,'COST','STANDARD_CALENDAR','ADJUSTABLE','SUBMITTED','CHIP-001 Cost Forecast Q2','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (605,113,'DEMAND','STANDARD_CALENDAR','CURRENT','DRAFT','Server S3 Q2 Demand Forecast','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (606,117,'DEMAND','STANDARD_CALENDAR','CURRENT','DRAFT','Router R1 Q2 Demand Forecast','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (607,105,'COST','STANDARD_CALENDAR','ADJUSTABLE','APPROVED','CHIP-002 Annual Cost Forecast','2026-01-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (608,109,'COST','STANDARD_CALENDAR','CURRENT','APPROVED','CAP-100UF Annual Cost Forecast','2026-01-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (609,119,'DEMAND','STANDARD_CALENDAR','CURRENT','SUBMITTED','Battery Pack H1 Demand Forecast','2026-01-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (610,110,'COST','STANDARD_CALENDAR','ADJUSTABLE','DRAFT','RES-10K Cost Review H2','2026-07-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
ALTER SEQUENCE IF EXISTS PCM_FORECAST_SEQ RESTART WITH 1000;
