-- ============================================================
-- Seed data for local H2 development  (create-drop safe)
-- ============================================================

-- ── Roles ────────────────────────────────────────────────────
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (1,'ADMIN','Administrator','Y');
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (2,'BUS_ADMIN','Business Administrator','Y');
INSERT INTO PCM_ROLE (ROLE_KEY,ROLE_ID,ROLE_NAME,PERM_ROLE) VALUES (3,'GUEST','Read Only','Y');
ALTER SEQUENCE PCM_ROLE_SEQ RESTART WITH 100;

-- ── Business entity ──────────────────────────────────────────
INSERT INTO BUSINESS_ENTITY (BUSINESS_ENTITY_KEY,BUSINESS_ENTITY_IDENTIFIER,BUSINESS_ENTITY_NAME,BUSINESS_ENTITY_DESC,BUSINESS_ENTITY_TYPE_KEY,DATA_SOURCE,INSERT_DT,CURRENT_FLAG)
  VALUES (1,'ENTERPRISE','SC Platform Enterprise','Default Enterprise',1,'SCM',CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE BUSINESS_ENTITY_SEQ RESTART WITH 100;

-- ── 5 Users with BCrypt-hashed passwords (cost=10) ──────────
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (1,'ADMIN','Administrator',NULL,NULL,1,TRUE,'$2a$10$MMURX4mhw7e.QBRR8rfU/OhNTXpXE1s9zjvoF4hENfm1lBgbnAYH.');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (2,'kumar','Kumar Swamy',1,NULL,1,TRUE,'$2a$10$VtbLdvpiibeVWy8AknmsZu5l9HM7rqcwIpCyVeagbIwCK33xfxfjC');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (3,'buyer','Buyer User',1,NULL,2,TRUE,'$2a$10$cY2s7pcFHnO7NGtuRPswWuwq6.n2YdPxIBpVLBk8.ypdlcyNQ5i7C');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (4,'analyst','Cost Analyst',1,NULL,2,TRUE,'$2a$10$Fd4F94WfTewPPOgtJlAKKOl10VQlbzPexFR6znJogQwCLYbdgUznq');
INSERT INTO PCM_USER (USER_KEY,USER_ID,USER_NAME,BUSINESS_ENTITY_KEY,CONTACT_KEY,ROLE_KEY,ENABLED_FLAG,USER_PASSWORD)
  VALUES (5,'viewer','Read Only Viewer',1,NULL,3,TRUE,'$2a$10$huhc88OxRjO5r/vQvj33..aZtSa3BiaDyvI90tfdFDp2VlJdJxyK6');
ALTER SEQUENCE PCM_USER_SEQ RESTART WITH 100;

-- ── 20 Items ─────────────────────────────────────────────────
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (101,'PCB-001','PCB-001-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (102,'PCB-002','PCB-002-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (103,'PCB-003','PCB-003-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (104,'CHIP-001','CHIP-001-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (105,'CHIP-002','CHIP-002-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (106,'FG-LAPTOP-X1','FG-LAPTOP-X1-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (107,'FG-TABLET-T2','FG-TABLET-T2-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (108,'RAW-COPPER-01','RAW-COPPER-01-v1','RAW_MATERIAL','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (109,'CAP-100UF','CAP-100UF-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (110,'RES-10K','RES-10K-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (111,'INDUCTOR-47UH','INDUCTOR-47UH-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (112,'TRANS-5V-3A','TRANS-5V-3A-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (113,'FG-SERVER-S3','FG-SERVER-S3-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (114,'DIODE-1N4007','DIODE-1N4007-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (115,'LED-RED-5MM','LED-RED-5MM-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (116,'CONN-USB-C','CONN-USB-C-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (117,'FG-ROUTER-R1','FG-ROUTER-R1-v1','FINISHED_GOOD','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (118,'RAW-ALUMINIUM-02','RAW-ALUMINIUM-02-v1','RAW_MATERIAL','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (119,'BATTERY-3S-5000','BATTERY-3S-5000-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
INSERT INTO ITEM_MASTER (ITEM_KEY,ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,ITEM_TYPE,DATA_SOURCE,BUSINESS_ENTITY_KEY,INSERT_DT,CURRENT_FLAG) VALUES (120,'HEATSINK-40MM','HEATSINK-40MM-v1','COMPONENT','MCM',1,CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE IF EXISTS ITEM_MASTER_SEQ RESTART WITH 500;

-- ── 10 BOM Headers (STATUS matches controller: Approved/Pending/Active) ──
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (201,'BOM-LAPTOP-001','Laptop X1 BOM','Bill of Materials for Laptop X1','MCM',1,106,TRUE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (202,'BOM-TABLET-001','Tablet T2 BOM','Bill of Materials for Tablet T2','MCM',1,107,TRUE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (203,'BOM-PCB-001','PCB Assembly BOM','Printed Circuit Board Assembly','MCM',1,101,FALSE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (204,'BOM-SERVER-001','Server S3 BOM','Bill of Materials for Server S3','MCM',1,113,TRUE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (205,'BOM-ROUTER-001','Router R1 BOM','Bill of Materials for Router R1','MCM',1,117,TRUE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (206,'BOM-PCB-002','PCB-002 Sub-Assembly','Sub-assembly for PCB-002','MCM',1,102,FALSE,'Approved',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (207,'BOM-PCB-003','PCB-003 Sub-Assembly','Sub-assembly for PCB-003','MCM',1,103,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (208,'BOM-CHIP-001','CHIP-001 Process BOM','Process BOM for CHIP-001','MCM',1,104,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (209,'BOM-BATTERY-001','Battery Pack BOM','BOM for 3S battery pack','MCM',1,119,FALSE,'Active',CURRENT_TIMESTAMP,'Y');
INSERT INTO BOM_HEADER (BOM_KEY,BOM_EXTERNAL_ID,BOM_NAME,BOM_DESCRIPTION,DATA_SOURCE,BUSINESS_ENTITY_KEY,ITEM_KEY,IS_TOP_LEVEL,STATUS,INSERT_DT,CURRENT_FLAG) VALUES (210,'BOM-CONN-001','Connector Assembly BOM','USB-C connector assembly','MCM',1,116,FALSE,'Pending',CURRENT_TIMESTAMP,'Y');
ALTER SEQUENCE IF EXISTS BOM_HEADER_SEQ RESTART WITH 500;

-- ── 10 Alerts ────────────────────────────────────────────────
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (401,'ACTIVE','kumar','COST_SPIKE','ALERT-001','COST_CHANGE',CURRENT_DATE,'PCB-001 cost increased 25%','PCB-001 cost rose from 48 to 60 USD.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (402,'ACTIVE','kumar','SUPPLIER_RISK','ALERT-002','SUPPLIER_PERFORMANCE',CURRENT_DATE,'SUPP-003 OTD below 70%','Taiwan Semiconductors OTD dropped to 62%.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (403,'ACTIVE','kumar','BOM_CHANGE','ALERT-003','BOM_UPDATE',CURRENT_DATE,'BOM-LAPTOP-001 updated','PCB-002 quantity changed from 1 to 2.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (404,'ACTIVE','kumar','LEAD_TIME','ALERT-004','SUPPLY_RISK',CURRENT_DATE,'CHIP-001 lead time 16 weeks','Foxconn extended lead time.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (405,'ACTIVE','kumar','PENDING_APPROVAL','ALERT-005','WORKFLOW',CURRENT_DATE,'3 cost records pending','CR-002 CR-003 CR-004 awaiting approval.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (406,'ACTIVE','kumar','INVENTORY_LOW','ALERT-006','INVENTORY',CURRENT_DATE,'CAP-100UF below safety stock','150 units remaining.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (407,'ACTIVE','kumar','PRICE_EXPIRY','ALERT-007','CONTRACT',CURRENT_DATE,'Murata contract expiring','RES-10K pricing expires 2025-01-31.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (408,'ACTIVE','kumar','QUALITY_ISSUE','ALERT-008','QUALITY',CURRENT_DATE,'PCB-003 defect rate 3.2%','Above 2.0 percent threshold.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (409,'ACTIVE','kumar','DEMAND_SPIKE','ALERT-009','DEMAND',CURRENT_DATE,'FG-LAPTOP-X1 demand up 40%','Unexpected demand spike from APAC region.');
INSERT INTO SC_ALERT_DETAIL (ID,STATE,USER_LOGIN_ID,ALERT_LABEL,ALERT_ID,ALERT_TYPE,CREATED,SHORT_SUMMARY,LONG_SUMMARY) VALUES (410,'ACTIVE','kumar','FORECAST_MISS','ALERT-010','FORECAST',CURRENT_DATE,'CHIP-002 forecast accuracy 58%','Below 80% accuracy threshold for Q1.');

-- ── 10 Suppliers (SUPPLIER_PROFILE) ─────────────────────────
-- quality_score is stored as a defect rate (lower is better) and
-- responsiveness_score on a 1-10 scale (see SupplierScorecardDto, which
-- does `100 - qualityScore` and `responsivenessScore * 10` when building
-- the display scorecard). The values below are that conversion applied to
-- the intended 0-100 "higher is better" quality/responsiveness scores
-- (e.g. SUPP-001 is meant to read as quality 88, responsiveness 95).
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-001','Shenzhen Electronics Co.','China','contact@shenzelec.cn','+86-755-8888-0001','PREFERRED','2020-01-15',12.0,9.5,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-002','Foxconn Technology Group','Taiwan','procurement@foxconn.com','+886-2-2268-3466','APPROVED','2019-06-01',10.0,7.8,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-003','Taiwan Semiconductors Ltd','Taiwan','supply@tsmc-ltd.tw','+886-3-563-6688','CONDITIONAL','2021-03-10',25.0,7.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-004','Murata Manufacturing','Japan','global@murata.com','+81-75-951-9111','PREFERRED','2018-09-20',1.0,9.2,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-005','Delta Electronics India','India','sourcing@delta.in','+91-80-4567-8901','PROBATION','2022-07-01',35.0,6.0,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-006','Samsung SDI Korea','South Korea','sdi.supply@samsung.com','+82-31-8006-3114','PREFERRED','2017-11-05',3.0,8.9,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-007','Vishay Intertechnology','USA','orders@vishay.com','+1-610-644-1300','APPROVED','2020-04-22',7.0,8.5,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-008','TE Connectivity','Switzerland','tecsupply@te.com','+41-52-2241-234','APPROVED','2021-08-15',9.0,8.2,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-009','Infineon Technologies','Germany','supply@infineon.com','+49-89-234-0','CONDITIONAL','2022-02-28',20.0,7.4,TRUE);
INSERT INTO SUPPLIER_PROFILE (supplier_id,supplier_name,country,contact_email,contact_phone,tier,onboarded_date,quality_score,responsiveness_score,is_active) VALUES ('SUPP-010','STMicroelectronics','Italy','st.supply@st.com','+39-02-3878-1','APPROVED','2020-10-01',13.0,7.9,TRUE);

-- ── Supplier Delivery History (SUPPLIER_DELIVERY) — BB-SUP-03 ──
-- On-time ratio per supplier tuned to match that supplier's SUPPLIER_PROFILE.tier
-- above (PREFERRED>=95%, APPROVED>=85%, CONDITIONAL>=70%, PROBATION<70% — see
-- SupplierService.tierFromOtd). Without this, otdScore/atRisk in the live scorecard
-- (computed from this table) never matched the seeded tier at all.
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -50, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -40, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-001','PO-SUPP-001-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-002','PO-SUPP-002-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -66, CURRENT_DATE),100,100,'LATE',4);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -55, CURRENT_DATE),100,100,'LATE',5);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-003','PO-SUPP-003-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -50, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -40, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-004','PO-SUPP-004-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -30, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -94, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -83, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -72, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -66, CURRENT_DATE),100,100,'LATE',4);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -55, CURRENT_DATE),100,100,'LATE',5);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-005','PO-SUPP-005-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -50, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -40, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-006','PO-SUPP-006-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -30, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-007','PO-SUPP-007-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-008','PO-SUPP-008-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -66, CURRENT_DATE),100,100,'LATE',4);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -55, CURRENT_DATE),100,100,'LATE',5);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-009','PO-SUPP-009-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1000','SEED-ITEM-0',DATEADD('DAY', -220, CURRENT_DATE),DATEADD('DAY', -220, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1001','SEED-ITEM-1',DATEADD('DAY', -210, CURRENT_DATE),DATEADD('DAY', -210, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1002','SEED-ITEM-2',DATEADD('DAY', -200, CURRENT_DATE),DATEADD('DAY', -200, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1003','SEED-ITEM-0',DATEADD('DAY', -190, CURRENT_DATE),DATEADD('DAY', -190, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1004','SEED-ITEM-1',DATEADD('DAY', -180, CURRENT_DATE),DATEADD('DAY', -180, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1005','SEED-ITEM-2',DATEADD('DAY', -170, CURRENT_DATE),DATEADD('DAY', -170, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1006','SEED-ITEM-0',DATEADD('DAY', -160, CURRENT_DATE),DATEADD('DAY', -160, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1007','SEED-ITEM-1',DATEADD('DAY', -150, CURRENT_DATE),DATEADD('DAY', -150, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1008','SEED-ITEM-2',DATEADD('DAY', -140, CURRENT_DATE),DATEADD('DAY', -140, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1009','SEED-ITEM-0',DATEADD('DAY', -130, CURRENT_DATE),DATEADD('DAY', -130, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1010','SEED-ITEM-1',DATEADD('DAY', -120, CURRENT_DATE),DATEADD('DAY', -120, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1011','SEED-ITEM-2',DATEADD('DAY', -110, CURRENT_DATE),DATEADD('DAY', -110, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1012','SEED-ITEM-0',DATEADD('DAY', -100, CURRENT_DATE),DATEADD('DAY', -100, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1013','SEED-ITEM-1',DATEADD('DAY', -90, CURRENT_DATE),DATEADD('DAY', -90, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1014','SEED-ITEM-2',DATEADD('DAY', -80, CURRENT_DATE),DATEADD('DAY', -80, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1015','SEED-ITEM-0',DATEADD('DAY', -70, CURRENT_DATE),DATEADD('DAY', -70, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1016','SEED-ITEM-1',DATEADD('DAY', -60, CURRENT_DATE),DATEADD('DAY', -60, CURRENT_DATE),100,100,'ON_TIME',0);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1017','SEED-ITEM-2',DATEADD('DAY', -50, CURRENT_DATE),DATEADD('DAY', -44, CURRENT_DATE),100,100,'LATE',6);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1018','SEED-ITEM-0',DATEADD('DAY', -40, CURRENT_DATE),DATEADD('DAY', -33, CURRENT_DATE),100,100,'LATE',7);
INSERT INTO SUPPLIER_DELIVERY (supplier_id,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,status,delay_days) VALUES ('SUPP-010','PO-SUPP-010-1019','SEED-ITEM-1',DATEADD('DAY', -30, CURRENT_DATE),DATEADD('DAY', -22, CURRENT_DATE),100,100,'LATE',8);

-- ── Supplier Dependency Graph (SUPPLIER_DEPENDENCY) ──────────
-- A small, real (2-3 tier) dependency chain among the suppliers already
-- seeded above, so /api/suppliers/{id}/cascaded-risk and /structural-risk
-- are demoable without extra setup:
--   Delta Electronics India (SUPP-005, our one at-risk supplier) is the
--   sole source of connector housings for Taiwan Semiconductors (SUPP-003),
--   which in turn feeds silicon wafers to Infineon (SUPP-009) -- a 2-hop
--   chain to exercise decay. Foxconn/Shenzhen is a separate, non-critical,
--   non-sole-source edge for contrast.
INSERT INTO SUPPLIER_DEPENDENCY (dependent_supplier_id,upstream_supplier_id,component_or_material,dependency_criticality,is_sole_source) VALUES ('SUPP-003','SUPP-005','Connector Housings',0.9,TRUE);
INSERT INTO SUPPLIER_DEPENDENCY (dependent_supplier_id,upstream_supplier_id,component_or_material,dependency_criticality,is_sole_source) VALUES ('SUPP-009','SUPP-003','Silicon Wafers',0.7,FALSE);
INSERT INTO SUPPLIER_DEPENDENCY (dependent_supplier_id,upstream_supplier_id,component_or_material,dependency_criticality,is_sole_source) VALUES ('SUPP-002','SUPP-001','PCB Assemblies',0.4,FALSE);

-- ── Supplier ESG Profiles (SUPPLIER_ESG_PROFILE) ─────────────
-- Deliberately incomplete, matching the plan's own note that most
-- suppliers won't have ESG data initially: SUPP-001 has a full profile,
-- SUPP-005 (Delta) has 2 compliance violations -- exercising the
-- esg_compliance_review action suggestion, SUPP-003 has partial data
-- (missing compliance/labor), and every other supplier has no row at all
-- (esg-risk correctly reports "no data" for them, not a fabricated score).
INSERT INTO SUPPLIER_ESG_PROFILE (supplier_id,esg_certifications,carbon_intensity_score,compliance_violations_12mo,labor_audit_score) VALUES ('SUPP-001','ISO14001,SA8000',20.0,0,85.0);
INSERT INTO SUPPLIER_ESG_PROFILE (supplier_id,esg_certifications,carbon_intensity_score,compliance_violations_12mo,labor_audit_score) VALUES ('SUPP-005','ISO14001',45.0,2,60.0);
INSERT INTO SUPPLIER_ESG_PROFILE (supplier_id,carbon_intensity_score) VALUES ('SUPP-003',55.0);

-- ── 10 Cost Records (MS3_COST_RECORD) ───────────────────────
-- item_code column = FK to ITEM_MASTER.ITEM_KEY
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (101,1,60.00,48.00,25.00,'PENDING_APPROVAL','Shenzhen increased raw material cost 25%','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (102,1,35.50,32.00,10.94,'DRAFT','Annual PCB-002 cost review','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (103,1,28.00,25.00,12.00,'APPROVED','PCB-003 approved after audit','ADMIN',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,approved_by,created_by,created_date) VALUES (104,1,125.00,118.00,5.93,'APPROVED','Chip shortage premium approved','ADMIN','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (105,1,89.00,72.00,23.61,'DRAFT','Spot market pricing CHIP-002','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (109,1,0.85,0.75,13.33,'PENDING_APPROVAL','Delta supply constraint CAP-100UF','kumar',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (110,1,0.025,0.020,25.00,'DRAFT','RES-10K annual pricing review','analyst',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (111,1,1.20,0.98,22.45,'PENDING_APPROVAL','Inductor lead time premium','analyst',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,approved_by,created_by,created_date) VALUES (112,1,12.50,11.00,13.64,'APPROVED','Transformer cost approved Q1','ADMIN','buyer',CURRENT_TIMESTAMP);
INSERT INTO MS3_COST_RECORD (item_code,version_number,proposed_cost,previous_cost,change_percent,status,justification,created_by,created_date) VALUES (119,1,45.00,39.00,15.38,'DRAFT','Battery cell price increase','buyer',CURRENT_TIMESTAMP);

-- ── 10 Forecasts (PCM_FORECAST) ─────────────────────────────
-- Required NOT NULL: FORECAST_TYPE, CALENDAR_NAME, FORECAST_MODEL, INSERT_DT, CURRENT_FLAG, DELETE_FLAG
-- CURRENT_FLAG / DELETE_FLAG use YesNoConverter → 'Y'/'N'
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (601,106,'DEMAND','STANDARD_CALENDAR','CURRENT','APPROVED','Laptop X1 Q1 Demand Forecast','2026-01-01','2026-03-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (602,107,'DEMAND','STANDARD_CALENDAR','CURRENT','APPROVED','Tablet T2 Q1 Demand Forecast','2026-01-01','2026-03-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (603,101,'COST','STANDARD_CALENDAR','ADJUSTABLE','SUBMITTED','PCB-001 Cost Forecast Q2','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (604,104,'COST','STANDARD_CALENDAR','ADJUSTABLE','SUBMITTED','CHIP-001 Cost Forecast Q2','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (605,113,'DEMAND','STANDARD_CALENDAR','CURRENT','DRAFT','Server S3 Q2 Demand Forecast','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (606,117,'DEMAND','STANDARD_CALENDAR','CURRENT','DRAFT','Router R1 Q2 Demand Forecast','2026-04-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (607,105,'COST','STANDARD_CALENDAR','ADJUSTABLE','APPROVED','CHIP-002 Annual Cost Forecast','2026-01-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (608,109,'COST','STANDARD_CALENDAR','CURRENT','APPROVED','CAP-100UF Annual Cost Forecast','2026-01-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (609,119,'DEMAND','STANDARD_CALENDAR','CURRENT','SUBMITTED','Battery Pack H1 Demand Forecast','2026-01-01','2026-06-30',CURRENT_TIMESTAMP,'Y','N');
INSERT INTO PCM_FORECAST (FORECAST_KEY,ITEM_KEY,FORECAST_TYPE,CALENDAR_NAME,FORECAST_MODEL,STATUS,DESCRIPTION,EFFECTIVE_FROM_DT,EFFECTIVE_TO_DT,INSERT_DT,CURRENT_FLAG,DELETE_FLAG)
  VALUES (610,110,'COST','STANDARD_CALENDAR','ADJUSTABLE','DRAFT','RES-10K Cost Review H2','2026-07-01','2026-12-31',CURRENT_TIMESTAMP,'Y','N');
ALTER SEQUENCE IF EXISTS PCM_FORECAST_SEQ RESTART WITH 1000;
