WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

SET DEFINE OFF;

-- Bootstrap data
-- This value is used to determine what version of the schema is being loaded
INSERT INTO PCM_APPLICATION_SETTINGS VALUES ('MODEL_VERSION','1.2');
INSERT INTO PCM_APPLICATION_SETTINGS VALUES ('BOOTSTRAP_LOADED_ON',CURRENT_TIMESTAMP);

INSERT INTO BUSINESS_ENTITY_TYPE (BUSINESS_ENTITY_TYPE_KEY, 
	BUSINESS_ENTITY_TYPE_NAME, BUSINESS_ENTITY_TYPE_DESC) VALUES (0, 'OPERATOR', 'Operating Company');
INSERT INTO BUSINESS_ENTITY_TYPE (BUSINESS_ENTITY_TYPE_KEY, 
	BUSINESS_ENTITY_TYPE_NAME, BUSINESS_ENTITY_TYPE_DESC) VALUES (1, 'ENTERPRISE', 'Enterprise');
INSERT INTO BUSINESS_ENTITY_TYPE (BUSINESS_ENTITY_TYPE_KEY, 
	BUSINESS_ENTITY_TYPE_NAME, BUSINESS_ENTITY_TYPE_DESC) VALUES (2, 'MANUFACTURER', 'Manufacturer');
INSERT INTO BUSINESS_ENTITY_TYPE (BUSINESS_ENTITY_TYPE_KEY, 
	BUSINESS_ENTITY_TYPE_NAME, BUSINESS_ENTITY_TYPE_DESC) VALUES (3, 'SUPPLIER', 'Supplier');

INSERT INTO PCM_ROLE (ROLE_KEY, ROLE_ID, ROLE_NAME, PERM_ROLE, BUSINESS_ENTITY_KEY) values (1, 'ADMIN', 'Administrator', 'Y', NULL);
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (10, 'ADMIN', 1, NULL, NULL, 'AdminAlert');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (15, 'ADMIN', 1, NULL, NULL, 'AdminUploadFile');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (20, 'ADMIN', 1, NULL, NULL, 'CreateContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (25, 'ADMIN', 1, NULL, NULL, 'CreateRole');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (30, 'ADMIN', 1, NULL, NULL, 'GlobalVisibility');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (35, 'ADMIN', 1, NULL, NULL, 'ReadBusiness');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (40, 'ADMIN', 1, NULL, NULL, 'ReadContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (45, 'ADMIN', 1, NULL, NULL, 'ReadRole');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (50, 'ADMIN', 1, NULL, NULL, 'ReadUser');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (55, 'ADMIN', 1, NULL, NULL, 'SaveBusiness');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (60, 'ADMIN', 1, NULL, NULL, 'SaveContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (65, 'ADMIN', 1, NULL, NULL, 'SaveItem');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (70, 'ADMIN', 1, NULL, NULL, 'SaveRole');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (75, 'ADMIN', 1, NULL, NULL, 'SaveUser');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (80, 'SYSADMIN', 1, NULL, NULL, 'ManageData');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (85, 'UPLOAD_TYPE', 1, NULL, NULL, 'All');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (90, 'WORKFLOW', 1, NULL, '*', 'Execute');

INSERT INTO PCM_ROLE (ROLE_KEY, ROLE_ID, ROLE_NAME, PERM_ROLE, BUSINESS_ENTITY_KEY) values (2, 'BUS_ADMIN', 'Business Administrator', 'Y', NULL);
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (195, 'ADMIN', 2, NULL, NULL, 'AdminAlert');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (200, 'ADMIN', 2, NULL, NULL, 'CreateContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (205, 'ADMIN', 2, NULL, NULL, 'ReadBusiness');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (210, 'ADMIN', 2, NULL, NULL, 'ReadContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (215, 'ADMIN', 2, NULL, NULL, 'ReadRole');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (220, 'ADMIN', 2, NULL, NULL, 'ReadUser');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (225, 'ADMIN', 2, NULL, NULL, 'SaveBusiness');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (230, 'ADMIN', 2, NULL, NULL, 'SaveContact');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (235, 'ADMIN', 2, NULL, NULL, 'SaveItem');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (240, 'ADMIN', 2, NULL, NULL, 'SaveUser');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (245, 'BOM', 2, NULL, NULL, 'Assign');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (250, 'BOM', 2, NULL, NULL, 'AssignSelf');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (255, 'BOM', 2, NULL, NULL, 'Delegate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (260, 'BOM', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (265, 'BOM', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (270, 'COST_RECORD', 2, NULL, NULL, 'Copy');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (275, 'COST_RECORD', 2, NULL, NULL, 'Create');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (280, 'COST_RECORD', 2, NULL, NULL, 'CreateNote');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (285, 'COST_RECORD', 2, NULL, NULL, 'Delete');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (290, 'COST_RECORD', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (295, 'COST_RECORD', 2, NULL, NULL, 'ReadNote');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (300, 'COST_RECORD', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (305, 'COST_RECORD', 2, NULL, NULL, 'Validate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (310, 'FORECAST', 2, NULL, NULL, 'Copy');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (315, 'FORECAST', 2, NULL, NULL, 'Create');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (320, 'FORECAST', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (325, 'FORECAST', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (330, 'FORECAST', 2, NULL, NULL, 'Validate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (335, 'ITEM_ASSIGNMENT', 2, NULL, NULL, 'Assign');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (340, 'ITEM_ASSIGNMENT', 2, NULL, NULL, 'AssignSelf');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (345, 'ITEM_ASSIGNMENT', 2, NULL, NULL, 'Delegate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (350, 'ITEM_ASSIGNMENT', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (355, 'ITEM_ASSIGNMENT', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (360, 'ITEM_CATEGORY', 2, NULL, NULL, 'Assign');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (365, 'ITEM_CATEGORY', 2, NULL, NULL, 'AssignSelf');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (370, 'ITEM_CATEGORY', 2, NULL, NULL, 'Delegate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (375, 'ITEM_CATEGORY', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (380, 'ITEM_CATEGORY', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (385, 'REBATE', 2, NULL, NULL, 'Copy');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (390, 'REBATE', 2, NULL, NULL, 'Create');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (395, 'REBATE', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (400, 'REBATE', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (405, 'REBATE', 2, NULL, NULL, 'Validate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (410, 'REPORTS', 2, NULL, NULL, 'DeleteReport');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (415, 'REPORTS', 2, NULL, NULL, 'ReadReport');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (420, 'REPORTS', 2, NULL, NULL, 'SubmitReport');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (425, 'SMODEL', 2, NULL, NULL, 'BOM_Approve');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (430, 'SMODEL', 2, NULL, NULL, 'BOM_Close');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (435, 'SMODEL', 2, NULL, NULL, 'BOM_Reject');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (440, 'SMODEL', 2, NULL, NULL, 'BOM_Submit');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (445, 'SMODEL', 2, NULL, NULL, 'Rebate_Approve');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (450, 'SMODEL', 2, NULL, NULL, 'Rebate_Close');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (455, 'SMODEL', 2, NULL, NULL, 'Rebate_Edit');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (460, 'SMODEL', 2, NULL, NULL, 'Rebate_Reject');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (465, 'SMODEL', 2, NULL, NULL, 'Rebate_Submit');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (470, 'SMODEL', 2, NULL, NULL, 'Sourcing_Approve');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (475, 'SMODEL', 2, NULL, NULL, 'Sourcing_Close');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (480, 'SMODEL', 2, NULL, NULL, 'Sourcing_Edit');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (485, 'SMODEL', 2, NULL, NULL, 'Sourcing_Reject');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (490, 'SMODEL', 2, NULL, NULL, 'Sourcing_Reopen');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (495, 'SMODEL', 2, NULL, NULL, 'Sourcing_Submit');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (500, 'SOURCING_LANE', 2, NULL, NULL, 'Copy');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (505, 'SOURCING_LANE', 2, NULL, NULL, 'Create');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (510, 'SOURCING_LANE', 2, NULL, NULL, 'Delete');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (515, 'SOURCING_LANE', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (520, 'SOURCING_LANE', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (525, 'SOURCING_LANE', 2, NULL, NULL, 'Validate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (530, 'SOURCING_LANE', 2, NULL, NULL, 'ViewSummary');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (535, 'SUPPLY_ALLOC', 2, NULL, NULL, 'Delete');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (540, 'SUPPLY_ALLOC', 2, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (545, 'SUPPLY_ALLOC', 2, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (550, 'UPDOWN', 2, NULL, NULL, 'ClearUploadEvent');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (555, 'UPDOWN', 2, NULL, NULL, 'CorrectBEAliasEvent');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (560, 'UPDOWN', 2, NULL, NULL, 'DeleteJob');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (565, 'UPDOWN', 2, NULL, NULL, 'DownloadFile');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (570, 'UPDOWN', 2, NULL, NULL, 'ReadAnyJob');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (575, 'UPDOWN', 2, NULL, NULL, 'ReadJob');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (580, 'UPDOWN', 2, NULL, NULL, 'UploadFile');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (585, 'UPLOAD_TYPE', 2, NULL, NULL, 'All');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (587, 'UPLOAD_TYPE', 2, NULL, NULL, 'SourcingLaneUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (590, 'UPLOAD_TYPE', 2, NULL, NULL, 'CostRecordUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (593, 'UPLOAD_TYPE', 2, NULL, NULL, 'CostRecordActionUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (594, 'UPLOAD_TYPE', 2, NULL, NULL, 'CostRecordExpireUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (595, 'UPLOAD_TYPE', 2, NULL, NULL, 'ItemAVLUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (600, 'UPLOAD_TYPE', 2, NULL, NULL, 'ItemBOMAVLUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (605, 'UPLOAD_TYPE', 2, NULL, NULL, 'ItemPlatformUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (610, 'UPLOAD_TYPE', 2, NULL, NULL, 'SupplierAllocationUI');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (615, 'UPLOAD_TYPE', 2, NULL, NULL, 'UserProvisioning');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (620, 'WORKFLOW', 2, NULL, 'ADMIN', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (625, 'WORKFLOW', 2, NULL, 'EDIT_USER', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (630, 'WORKFLOW', 2, NULL, 'MDM_ITEM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (635, 'WORKFLOW', 2, NULL, 'SEARCH_BOM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (640, 'WORKFLOW', 2, NULL, 'MAIN_LOADJOB', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (645, 'WORKFLOW', 2, NULL, 'EDIT_PROFILE', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (650, 'WORKFLOW', 2, NULL, 'EDIT_ROLE', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (655, 'WORKFLOW', 2, NULL, 'SEARCH_ITEM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (660, 'WORKFLOW', 2, NULL, 'EDIT_NEWS', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (665, 'WORKFLOW', 2, NULL, 'VIEW_SA', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (670, 'WORKFLOW', 2, NULL, 'RPT_COST', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (675, 'WORKFLOW', 2, NULL, 'RPT_SUBMIT_JOB', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (680, 'WORKFLOW', 2, NULL, 'NEW_RP', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (685, 'WORKFLOW', 2, NULL, 'MDM_ICAT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (690, 'WORKFLOW', 2, NULL, 'EDIT_BE', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (695, 'WORKFLOW', 2, NULL, 'SEARCH_RP', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (700, 'WORKFLOW', 2, NULL, 'EDIT_ITEM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (705, 'WORKFLOW', 2, NULL, 'SEARCH_CR', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (710, 'WORKFLOW', 2, NULL, 'NEW_SL', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (715, 'WORKFLOW', 2, NULL, 'VIEW_AUDIT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (720, 'WORKFLOW', 2, NULL, 'MDM_BOM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (725, 'WORKFLOW', 2, NULL, 'MAIN_DASHBOARD', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (730, 'WORKFLOW', 2, NULL, 'SEARCH_SL', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (735, 'WORKFLOW', 2, NULL, 'MAIN_UPLOAD', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (740, 'WORKFLOW', 2, NULL, 'SEARCH_SA', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (745, 'WORKFLOW', 2, NULL, 'SEARCH', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (750, 'WORKFLOW', 2, NULL, 'RPT', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (755, 'WORKFLOW', 2, NULL, 'SA', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (760, 'WORKFLOW', 2, NULL, 'SL', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (765, 'WORKFLOW', 2, NULL, 'RP', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (770, 'WORKFLOW', 2, NULL, 'MAIN', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (775, 'WORKFLOW', 2, NULL, 'MDM', 'ExecuteAll');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (780, 'WORKFLOW', 2, NULL, 'SEARCH_ITEM_ONLY', 'Execute');

INSERT INTO PCM_ROLE (ROLE_KEY, ROLE_ID, ROLE_NAME, PERM_ROLE, BUSINESS_ENTITY_KEY) values (3, 'GUEST', 'Read Only', 'Y', NULL);
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (880, 'WORKFLOW', 3, NULL, 'MAIN', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (885, 'WORKFLOW', 3, NULL, 'MAIN_DASHBOARD', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (890, 'WORKFLOW', 3, NULL, 'ADMIN', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (895, 'WORKFLOW', 3, NULL, 'EDIT_PROFILE', 'Execute');


INSERT INTO PCM_USER (USER_KEY, USER_ID, USER_NAME, BUSINESS_ENTITY_KEY, CONTACT_KEY, ROLE_KEY, ENABLED_FLAG) 
	VALUES (1, 'ADMIN', 'Administrator', NULL, NULL, 1, 'Y');
	
-- Bootstrap the operator company and operator technical contact user into the DB
DECLARE
  v_business_entity_key business_entity.business_entity_key%TYPE;
  v_user_cnt NUMBER := 0;
BEGIN
  -- get the operator company
  BEGIN
    SELECT business_entity_key INTO v_business_entity_key
    FROM business_entity
    WHERE business_entity_identifier = '@e2.ssp.co.company.id@'
    AND business_entity_type_key = 0;
    
    EXCEPTION
	  WHEN NO_DATA_FOUND THEN NULL;
  END;
  
  -- if the operator company does not exist create it
  IF v_business_entity_key IS NULL THEN
    SELECT business_entity_seq.nextval
    INTO v_business_entity_key
    FROM DUAL;
    
    INSERT INTO BUSINESS_ENTITY (BUSINESS_ENTITY_KEY, BUSINESS_ENTITY_IDENTIFIER, BUSINESS_ENTITY_NAME,
    BUSINESS_ENTITY_EXTERNAL_ID, BUSINESS_ENTITY_TYPE_KEY, DATA_SOURCE, INSERT_DT, UPDATE_DT,
    DELETE_FLAG, CURRENT_FLAG)
    VALUES (v_business_entity_key, '@e2.ssp.co.company.id@', '@e2.ssp.co.company.name@',
    sys_guid(), 0, 'MCM', systimestamp, systimestamp,
    'N', 'Y');
  END IF;
  
  -- check to see if the operator user exists
  BEGIN
    SELECT count(*) INTO
    v_user_cnt
    FROM pcm_user
    WHERE user_id = '@e2.bootstrap.user.0.userid@'
    AND business_entity_key = v_business_entity_key;
    
    EXCEPTION
	  WHEN NO_DATA_FOUND THEN NULL;
  END;

  -- if the operator user does not exist create it
  IF v_user_cnt = 0 THEN
    INSERT INTO PCM_USER (USER_KEY, USER_ID, USER_NAME, BUSINESS_ENTITY_KEY, CONTACT_KEY, ROLE_KEY, ENABLED_FLAG) 
    VALUES (pcm_user_seq.nextval, '@e2.bootstrap.user.0.userid@',
    '@e2.bootstrap.user.0.first.name@'||' '||'@e2.bootstrap.user.0.last.name@', v_business_entity_key, NULL, 1, 'Y');
  END IF;
END;
/

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MAIN','Main','MCM',null,null,1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MAIN_DASHBOARD','Dashboard','MCM','MAIN','dashboard.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MAIN_UPLOAD','Upload','MCM','MAIN','uploadFile.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MAIN_LOADJOB','Manage Upload Jobs','MCM','MAIN','loadJobSearch.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MAIN_ALERTS','Review Alerts','MCM','MAIN','AlertSearch.do',4,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SL','Pricing','MCM',null,null,2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('NEW_SL','New Sourcing Lane','MCM','SL','newSourcingLane.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_SL','Search Sourcing Lane','MCM','SL','searchSourcingLane.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_CR','Search Cost Records','MCM','SL','searchCostRecord.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('CR_ITEM_EXCEPTION','Price Item Assignment Exception','MCM','SL','priceItemAssignmentException.do',6,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('CR_VARIANCE_REPORT','Price Variance Report','MCM','SL','costRecordPriceVariance.do',4,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('RP','Rebates','MCM',null,null,3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('NEW_RP','New Rebate Program','MCM','RP','newRebateProgram.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_RP','Search Rebate Program','MCM','RP','searchRebateProgram.do',2,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SA','Supply Allocation (Sub-Tier)','MCM',null,null,4,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('VIEW_SA','New Supply Allocation','MCM','SA','createItemSupplyAllocation.do?supplierRequired=true',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_SA','Search Supply Allocation','MCM','SA','searchSupplyAllocation.do',2,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MDM','Master Data Management','MCM',null,null,4,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MDM_BOM','BOM Management','MCM','MDM','startBomManagement.do',4,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MDM_ICAT','Commodity Management','MCM','MDM','startCategoryManagement.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MDM_ITEM','Item Assignment','MCM','MDM','startItemManagement.do',1,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('FC','Cost Forecast','MCM',null,null,5,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('NEW_FC','New Forecast','MCM','FC','newForecast.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_FC','Search Forecast','MCM','FC','searchForecast.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SF_VARIANCE_REPORT','Forecast Variance Report','MCM','FC','costForecastVariance.do',3,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('FUNCTIONAL_GROUP','Supply Allocation','MCM',null,null,6,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('ALLOCATION','Manage Allocation','MCM','FUNCTIONAL_GROUP','manageTAM.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MANAGE_GROUP','Manage Functional Group','MCM','FUNCTIONAL_GROUP','manageFunctionalGroup.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('MANAGE_PARENT','Manage Parent Group','MCM','FUNCTIONAL_GROUP','manageParent.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('TAM_DOWNLOAD','Download Allocation','MCM','FUNCTIONAL_GROUP','searchTAMDownload.do',4,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SA_MANAGEMENT_HSTORY','Allocation Management History','MCM','FUNCTIONAL_GROUP','allocationManagementHistory.do',6,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SA_EXCEPTION','Supply Allocation Exception','MCM','FUNCTIONAL_GROUP','supplyAllocationException.do',6,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SA_HISTORY','Supply Allocation Audit History','MCM','FUNCTIONAL_GROUP','supplyAllocationHistory.do',5,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SA_FG_ITEM_EXCEPTION','FG Item Assignment Exception','MCM','FUNCTIONAL_GROUP','functionalGroupItemAssignmentException.do',8,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('PriceTAM','Manage XLOB Price and Allocation','MCM','FUNCTIONAL_GROUP','priceTAMUI.do',8,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) VALUES ('XLOB_DELETE_TEMPLATE', 'XLOB Delete Template', 'MCM', 'FUNCTIONAL_GROUP', 'downloadXLOBDelete.do', 10, NULL);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) VALUES ('TAM_DELETE_TEMPLATE', 'TAM Delete Template', 'MCM', 'FUNCTIONAL_GROUP', 'downloadTAMDelete.do', 10, NULL);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('RPT','Reports','MCM',null,null,8,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('RPT_SUBMIT_JOB','Submit/View Reports','MCM','RPT','initReports.do',1,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('RPT_COST','Sell Price Report','MCM','RPT','initFilter.do?filterName=CostRecordReport&reportName=CostRecordReport',2,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH','Search','MCM',null,null,9,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_ITEM','Item AVL','MCM','SEARCH','itemSearch.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_BOM','BOMs','MCM','SEARCH','bomSearch.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_ITEM_ONLY','Items','MCM','SEARCH','itemOnlySearch.do',1,null);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('ADMIN','Administration','MCM',null,null,10,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_ALERT_SUB','Manage Alerts','MCM','ADMIN','editAlertSubscription.do',3,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_BE','Manage Business Entities','MCM','ADMIN','searchBusiness.do',7,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_CONTACT','Manage Contacts','MCM','ADMIN','searchContact.do',6,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_ITEM','Manage Items','MCM','ADMIN','searchItemMaintenance.do',4,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_NEWS','Change Dashboard News','MCM','ADMIN','getAlerts.do',2,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_ROLE','Manage Roles','MCM','ADMIN','viewAccessControl.do',5,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('EDIT_USER','Manage Users','MCM','ADMIN','searchUser.do',8,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('VIEW_AUDIT','Audit History','MCM','ADMIN','auditHistorySearch.do',9,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('ADMIN_UPLOAD','Admin Upload','MCM','ADMIN','adminUploadFile.do',10,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_COMPROFILE','Commodity Profile','MCM','ADMIN','commodityProfileSearch.do',11,null);
Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('USER_PROFILE_MAPPING','User Commodity Profile','MCM','ADMIN','userProfileMappingSearch.do',12,null);


DELETE FROM PCM_COST_ELEMENT;
DELETE FROM PCM_COST_TYPE;
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER) 
	values ('BUY', 'BUY',1,'Y','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER)
	values ('SELL', 'SELL',4,'Y','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER)
	values ('LIST', 'LIST',3,'Y','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER)
	values ('ODMBUY', 'ODM BUY',5,'Y','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER)
	values ('SERVICE', 'SERVICE',6,'N','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER)
	values ('EMQUOTE', 'EM QUOTE',2,'N','Y');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER) 
values ('WAP', 'WAP', 8, 'Y', 'N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER) 
values ('XWAP', 'XWAP', 9, 'Y', 'N');


	
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'BUY', 'MATERIAL', 'S',1,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSPORTATION', 'BUY', 'TRANSPORTATION', 'B',2,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('SLC', 'BUY', 'SLC', 'S',3,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('WARRANTY', 'BUY', 'WARRANTY', 'S',4,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSFORMATION', 'BUY', 'TRANSFORMATION', 'S',6,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('PACKAGING', 'BUY', 'PACKAGING', 'S',7,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('NRE', 'BUY', 'NRE', 'S',8,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('ROIC', 'BUY', 'ROIC', 'S',10,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TOOLING', 'BUY', 'TOOLING', 'S',9,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('COM', 'BUY', 'COST OF MONEY', 'S',5,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('OTHER', 'BUY', 'OTHER', 'S',11,'MATERIAL');
	

INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'ODMBUY', 'MATERIAL', 'S',1,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSPORTATION', 'ODMBUY', 'TRANSPORTATION', 'B',2,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('SLC', 'ODMBUY', 'SLC', 'S',3,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('WARRANTY', 'ODMBUY', 'WARRANTY', 'S',4,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSFORMATION', 'ODMBUY', 'TRANSFORMATION', 'S',6,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('PACKAGING', 'ODMBUY', 'PACKAGING', 'S',7,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('NRE', 'ODMBUY', 'NRE', 'S',8,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('ROIC', 'ODMBUY', 'ROIC', 'S',10,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TOOLING', 'ODMBUY', 'TOOLING', 'S',9,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('COM', 'ODMBUY', 'COST OF MONEY', 'S',5,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('OTHER', 'ODMBUY', 'OTHER', 'S',11,'MATERIAL');

INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'SELL', 'MATERIAL', 'S',1,'MATERIAL');

INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'LIST', 'MATERIAL', 'S',1,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSPORTATION', 'LIST', 'TRANSPORTATION', 'B',2,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('OTHER', 'LIST', 'OTHER', 'S',3,'MATERIAL');

INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'SERVICE', 'MATERIAL', 'S',1,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSPORTATION', 'SERVICE', 'TRANSPORTATION', 'B',2,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('SLC', 'SERVICE', 'SLC', 'S',3,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('WARRANTY', 'SERVICE', 'WARRANTY', 'S',4,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('COM', 'SERVICE', 'COST OF MONEY', 'S',5,'MATERIAL');	
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TRANSFORMATION', 'SERVICE', 'TRANSFORMATION', 'S',6,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('PACKAGING', 'SERVICE', 'PACKAGING', 'S',7,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('NRE', 'SERVICE', 'NRE', 'S',8,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('TOOLING', 'SERVICE', 'TOOLING', 'S',9,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('ROIC', 'SERVICE', 'ROIC', 'S',10,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('OTHER', 'SERVICE', 'OTHER', 'S',11,'MATERIAL');


INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('MATERIAL', 'EMQUOTE', 'MATERIAL', 'S',1,'MATERIAL');
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
	values ('OTHER', 'EMQUOTE', 'OTHER', 'S',2,'MATERIAL');
	
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE, IS_REQUIRED) 
	values ('MATERIAL', 'WAP', 'MATERIAL', 'S',1,'MATERIAL',1);
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE, IS_REQUIRED) 
	values ('MATERIAL', 'XWAP', 'MATERIAL', 'S',1,'MATERIAL',1);

-- Not currently used
--INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP)
--	values ('NEGOTIATION', 'NEGOTIATION',7,'Y','MATERIAL');
-- INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE) 
--	values ('MATERIAL', 'NEGOTIATION', 'MATERIAL', 'S',1,'MATERIAL');

insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('AED', 'AED');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BHD', 'BHD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('DZD', 'DZD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('EGP', 'EGP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('IQD', 'IQD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('JOD', 'JOD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('KWD', 'KWD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('LBP', 'LBP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('LYD', 'LYD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('MAD', 'MAD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('OMR', 'OMR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('QAR', 'QAR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SAR', 'SAR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SDD', 'SDD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SYP', 'SYP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('TND', 'TND');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('YER', 'YER');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('INR', 'INR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('ILS', 'ILS');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('JPY', 'JPY');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('KRW', 'KRW');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('THB', 'THB');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('VND', 'VND');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CNY', 'CNY');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('HKD', 'HKD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('TWD', 'TWD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BYR', 'BYR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BGN', 'BGN');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('EUR', 'EUR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CZK', 'CZK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('DKK', 'DKK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CHF', 'CHF');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('AUD', 'AUD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CAD', 'CAD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('GBP', 'GBP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('NZD', 'NZD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('ZAR', 'ZAR');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('ARS', 'ARS');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BOB', 'BOB');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CLP', 'CLP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('COP', 'COP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CRC', 'CRC');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('DOP', 'DOP');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('USD', 'USD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('GTQ', 'GTQ');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('HNL', 'HNL');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('MXN', 'MXN');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('NIO', 'NIO');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('PAB', 'PAB');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('PEN', 'PEN');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('PYG', 'PYG');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SVC', 'SVC');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('UYU', 'UYU');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('VEB', 'VEB');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('EEK', 'EEK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('HRK', 'HRK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('HUF', 'HUF');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('ISK', 'ISK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('LTL', 'LTL');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('LVL', 'LVL');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('MKD', 'MKD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('NOK', 'NOK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('PLN', 'PLN');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BRL', 'BRL');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('RON', 'RON');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('RUB', 'RUB');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SKK', 'SKK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SIT', 'SIT');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('ALL', 'ALL');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('BAM', 'BAM');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('CSD', 'CSD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SEK', 'SEK');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('TRY', 'TRY');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('UAH', 'UAH');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('SGD', 'SGD');
insert into CURRENCY_CODE (CURRENCY_CODE, CURRENCY_CODE_NAME) values ('MYR', 'MYR');

DELETE FROM PCM_RESPONSIBILITY;
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('PRODUCTION', 'Production', 1, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('SERVICE', 'Service', 2, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('REGIONAL', 'Regional', 3, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('FINANCE', 'Finance', 4, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('THIRD_PARTY', 'Third Party', 5, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('SCM', 'Supply Chain Manager', 6, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('VIEWER', 'Viewer', 7, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE) 
	values ('BUYER', 'Buyer', 8, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE) 
	values ('OWNER', 'Owner', 0, 'IC');

DELETE FROM PCM_ROLE_RESPONSIBILITY;
declare
	v_admin pcm_role.role_key%TYPE;
	v_bus_admin pcm_role.role_key%TYPE;
begin
	select role_key into v_admin from pcm_role where role_id = 'ADMIN';
	select role_key into v_bus_admin from pcm_role where role_id = 'BUS_ADMIN';
	
	-- Administrator Role
	INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	SELECT v_admin,RESPONSIBILITY_KEY
	FROM PCM_RESPONSIBILITY
	WHERE RESPONSIBILITY_KEY != 'VIEWER'
	AND RESPONSIBILITY_KEY != 'BUYER';
	
	-- Business Administrator Role
	INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	SELECT v_bus_admin,RESPONSIBILITY_KEY
	FROM PCM_RESPONSIBILITY
	WHERE RESPONSIBILITY_KEY != 'VIEWER'
	AND RESPONSIBILITY_KEY != 'BUYER';
	
	-- All Roles
	INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	SELECT ROLE_KEY,'VIEWER'
	FROM PCM_ROLE;
end;
/

insert into ITEM_CATEGORY (ITEM_CATEGORY_KEY,ITEM_CATEGORY_IDENTIFIER,ITEM_CATEGORY_NAME,BUSINESS_ENTITY_KEY,PARENT_CATEGORY_KEY,PRODUCT_FAMILY,MANAGED_FLAG)
values (-1,-1,'ALL',10,NULL,NULL,NULL);

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) values ('SEARCH_EXCEPTION','Search Exception Request','MCM','SL','searchExceptionRequest.do',7,null);

insert into PCM_WORKFLOW
values('MAIN_UPLOAD_MANAGE', 'Upload/Manage Job', 'MCM', NULL, NULL, 9, NULL);

delete from PCM_WORKFLOW where workflow_key = 'MAIN_UPLOAD';

update PCM_WORKFLOW set WORKFLOW_PARENT_KEY = 'MAIN_UPLOAD_MANAGE' where workflow_key = 'MAIN_LOADJOB';


insert into PCM_WORKFLOW
values('UPLOAD_ADMIN', 'Admin', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=admin', 1, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_COST_FORECAST', 'Cost Forecast', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=cost_forecast', 4, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_XLOB', 'XLOB Price and Allocation', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=XLOB_Allocation', 5, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_MISCELLANEOUS', 'Miscellaneous', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=miscellaneous', 6, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_PRICING', 'Pricing', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=pricing', 2, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_SA', 'Supply Allocation', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=supply_allocation', 3, NULL);