WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

CREATE SEQUENCE ATTRIBUTE_GROUP_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE ATTRIBUTE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE BOM_GROUP_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;        
CREATE SEQUENCE BOM_HEADER_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE BOM_LINE_ITEM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
-- Bootstrap data so start with 10 for this sequence
CREATE SEQUENCE BUSINESS_ENTITY_SEQ
        INCREMENT BY 1
        START WITH 10
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE BUSINESS_ENTITY_ALT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE BUSINESS_ENTITY_TYPE_KEY
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE CONTACT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE ITEM_CATEGORY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE ITEM_CHAR_KEY
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE ITEM_MASTER_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;        
CREATE SEQUENCE ITEM_PLATFORM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE SITE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE  SEQUENCE ITEM_AVL_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE  SEQUENCE ITEM_CHANGE_AUDIT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;     

CREATE TABLE CURRENCY_CODE
(
	CURRENCY_CODE VARCHAR2(6) NOT NULL,
	CURRENCY_CODE_NAME VARCHAR2(64) NULL,
	CONSTRAINT XCUCODE_PK PRIMARY KEY(CURRENCY_CODE)
		USING INDEX TABLESPACE AUDIT_INDEX
);
        
CREATE TABLE CURRENCY_RATE
(
    FROM_CURRENCY_CODE VARCHAR2(3) NOT NULL,
    TO_CURRENCY_CODE VARCHAR2(3) NOT NULL,
    EXCHANGE_RATE NUMBER(19,6) NOT NULL,
    CONSTRAINT CUR_RATE_FCUR_FK FOREIGN KEY(FROM_CURRENCY_CODE) 
    	REFERENCES CURRENCY_CODE ON DELETE CASCADE,
    CONSTRAINT CUR_RATE_TCUR_FK FOREIGN KEY(TO_CURRENCY_CODE) 
    	REFERENCES CURRENCY_CODE ON DELETE CASCADE,    	
    CONSTRAINT CUR_RATE_PK PRIMARY KEY(FROM_CURRENCY_CODE,TO_CURRENCY_CODE)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;
        
CREATE TABLE SITE_ADD_ATTRIBUTE
(
        ATTRIBUTE_KEY NUMBER(19) NOT NULL,
        SITE_KEY NUMBER(19) NOT NULL,
        ATTRIBUTE_NAME VARCHAR2(255) NOT NULL,
        ATTRIBUTE_TYPE VARCHAR2(255) NULL,
        ATTRIBUTE_VALUE VARCHAR2(255) NULL,
        ATTRIBUTE_GROUP_KEY NUMBER(19) NULL,
        DESCRIPTION VARCHAR2(1024) NULL,
        CONSTRAINT XSITEAA_PK PRIMARY KEY (ATTRIBUTE_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XSITEAA_U1
 ON SITE_ADD_ATTRIBUTE(
    SITE_KEY ASC
    ,ATTRIBUTE_NAME ASC
    ,ATTRIBUTE_TYPE ASC
    ,ATTRIBUTE_GROUP_KEY ASC
    ,ATTRIBUTE_VALUE ASC
) TABLESPACE AUDIT_INDEX;

CREATE TABLE BUSINESS_ENTITY_ADD_ATTRIBUTE
(
	ATTRIBUTE_KEY NUMBER(19) NOT NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,ATTRIBUTE_NAME VARCHAR2(255) NOT NULL
	,ATTRIBUTE_TYPE VARCHAR2(255) NULL
	,ATTRIBUTE_VALUE VARCHAR2(255) NULL
	,ATTRIBUTE_GROUP_KEY NUMBER(19) NULL
	,DESCRIPTION VARCHAR2(1024) NULL
    ,CONSTRAINT XBSETAA_PK PRIMARY KEY (ATTRIBUTE_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBSETAA_U1
    ON BUSINESS_ENTITY_ADD_ATTRIBUTE(
    BUSINESS_ENTITY_KEY ASC
    ,ATTRIBUTE_NAME ASC
    ,ATTRIBUTE_TYPE ASC
    ,ATTRIBUTE_GROUP_KEY ASC
    ,ATTRIBUTE_VALUE ASC
) TABLESPACE AUDIT_INDEX;

CREATE TABLE ITEM_ADD_ATTRIBUTE
(
	ATTRIBUTE_KEY NUMBER(19) NOT NULL
	,ITEM_KEY NUMBER(19) NOT NULL
	,ATTRIBUTE_NAME VARCHAR2(255) NOT NULL
	,ATTRIBUTE_TYPE VARCHAR2(255) NULL
	,ATTRIBUTE_VALUE VARCHAR2(255) NULL
	,ATTRIBUTE_GROUP_KEY NUMBER(19) NULL
	,DESCRIPTION VARCHAR2(1024) NULL
	,ATTRIBUTE_VALUE_NUM   NUMBER (19, 4)
    ,ATTRIBUTE_VALUE_DT    TIMESTAMP (6)
    ,CONSTRAINT XITMAA_PK PRIMARY KEY (ATTRIBUTE_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE ITEM_AVL_ADD_ATTRIBUTE
(
    ATTRIBUTE_KEY NUMBER(19) NOT NULL,
    AVL_KEY NUMBER(19) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(255) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR2(255) NULL,
    ATTRIBUTE_VALUE VARCHAR2(255) NULL,
    ATTRIBUTE_GROUP_KEY NUMBER(19) NULL,
    DESCRIPTION VARCHAR2(1024) NULL,
    ATTRIBUTE_VALUE_NUM NUMBER(19, 4),
    ATTRIBUTE_VALUE_DT TIMESTAMP(6),
    CONSTRAINT XITAAA_PK PRIMARY KEY (ATTRIBUTE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XITMAA_U1
    ON ITEM_ADD_ATTRIBUTE(
     ITEM_KEY ASC
    ,ATTRIBUTE_NAME ASC
    ,ATTRIBUTE_TYPE ASC
    ,ATTRIBUTE_VALUE ASC
    ,ATTRIBUTE_GROUP_KEY ASC
) TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX XITAAA_U1
ON ITEM_AVL_ADD_ATTRIBUTE(
 AVL_KEY ASC
,ATTRIBUTE_NAME ASC
,ATTRIBUTE_TYPE ASC
,ATTRIBUTE_VALUE ASC
,ATTRIBUTE_GROUP_KEY ASC
) TABLESPACE AUDIT_INDEX;

CREATE INDEX ITEM_AVL_ATTR_KEY ON ITEM_AVL_ADD_ATTRIBUTE(AVL_KEY) TABLESPACE AUDIT_INDEX;

CREATE TABLE BOM_LINE_ITEM_ADD_ATTRIBUTE
(
        ATTRIBUTE_KEY NUMBER(19) NOT NULL
,ATTRIBUTE_TYPE VARCHAR2(255) NULL
,BOM_LINE_ITEM_KEY NUMBER(19) NOT NULL
,ATTRIBUTE_NAME VARCHAR2(255) NOT NULL
,ATTRIBUTE_VALUE VARCHAR2(255) NULL
,ATTRIBUTE_GROUP_KEY NUMBER(19) NULL
,DESCRIPTION VARCHAR2(1024) NULL
        ,CONSTRAINT XBMLIAA_PK PRIMARY KEY (ATTRIBUTE_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBMLIAA_U1
        ON BOM_LINE_ITEM_ADD_ATTRIBUTE(
            BOM_LINE_ITEM_KEY ASC
    ,ATTRIBUTE_NAME ASC
    ,ATTRIBUTE_TYPE ASC
    ,ATTRIBUTE_GROUP_KEY ASC
    ,ATTRIBUTE_VALUE ASC
        ) TABLESPACE AUDIT_INDEX;
        
CREATE TABLE ATTRIBUTE_GROUP
(
    ATTRIBUTE_GROUP_KEY NUMBER(19) NOT NULL
	,ATTRIBUTE_GROUP_NAME VARCHAR2(255) NOT NULL
	,OBJECT_TYPE VARCHAR2(64) NULL
    ,CONSTRAINT XATRGRP_PK PRIMARY KEY (ATTRIBUTE_GROUP_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XATRGRP_U1 ON ATTRIBUTE_GROUP
(
    OBJECT_TYPE ASC
    ,ATTRIBUTE_GROUP_NAME ASC
) TABLESPACE AUDIT_INDEX;

CREATE TABLE BOM_BOM_GROUP
(
    BOM_KEY NUMBER(19) NOT NULL,
    BOM_GROUP_KEY NUMBER(19) NOT NULL,
    CONSTRAINT XBMBMGP_PK PRIMARY KEY 
       (BOM_KEY, BOM_GROUP_KEY) USING INDEX TABLESPACE AUDIT_DATA
) TABLESPACE AUDIT_DATA;

CREATE TABLE BOM_GROUP
(
    BOM_GROUP_KEY NUMBER(19) NOT NULL,
	GROUP_NAME VARCHAR2(255) NOT NULL,
	OWNER_NAME VARCHAR2(255) NULL,
	BUSINESS_ENTITY_KEY NUMBER(19) NULL,
	DATA_SOURCE VARCHAR2(255) NOT NULL,
	INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_DT TIMESTAMP NULL,
	EFFECTIVE_FROM_DT DATE NULL,
	EFFECTIVE_TO_DT DATE NULL,
	DELETE_FLAG VARCHAR2(1) NULL,
	CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT XBMGRP_PK PRIMARY KEY (BOM_GROUP_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX        
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBMGRP_U1
   	ON BOM_GROUP(GROUP_NAME ASC, DATA_SOURCE ASC) 
	TABLESPACE AUDIT_INDEX;

CREATE TABLE BOM_SITE_LINK
(
    BOM_KEY NUMBER(19) NOT NULL
	,SITE_KEY NUMBER(19) NOT NULL
    ,CONSTRAINT XBMSTLK_PK PRIMARY KEY (BOM_KEY,SITE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE ITEM_AVL
(       
     ITEM_KEY NUMBER(19) NOT NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,SUPPLIER_PART_KEY NUMBER(19) NOT NULL
	,BOM_KEY NUMBER(19) NULL	
	,DESCRIPTION VARCHAR2(1024) NULL
	,PREFERRED_STATUS_CODE VARCHAR2(255) NULL
	,PREFERRED_STATUS_START DATE NULL
	,PREFERRED_STATUS_END DATE NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,AVL_KEY NUMBER(19)  NOT NULL 	
    ,CONSTRAINT XITMAVL_PK PRIMARY KEY 
        (AVL_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE INDEX XIAVL_I1
	ON ITEM_AVL(UPDATE_DT,CURRENT_FLAG) 
		TABLESPACE AUDIT_INDEX;
CREATE UNIQUE INDEX XIAVL_U1
	ON ITEM_AVL(ITEM_KEY, BUSINESS_ENTITY_KEY,
	SUPPLIER_PART_KEY) 
	TABLESPACE AUDIT_INDEX;
	
---create new mapping table -----
CREATE TABLE PCM_ITEM_AVL_SITE
(
    AVL_KEY NUMBER(19) NOT NULL
   ,SITE_KEY NUMBER(19) NOT NULL   
   ,CONSTRAINT ITEMAVLST_PK PRIMARY KEY(AVL_KEY,SITE_KEY)
)TABLESPACE AUDIT_DATA;	


CREATE TABLE ITEM_AML
(
    ITEM_KEY NUMBER(19) NOT NULL
	,MANUFACTURER_ITEM_KEY NUMBER(19) NOT NULL
	,MANUFACTURER_KEY NUMBER(19) NOT NULL
	,BOM_KEY NUMBER(19) NULL
	,SITE_KEY NUMBER(19) NULL
	,DESCRIPTION VARCHAR2(1024) NULL
	,PART_STATUS_CODE VARCHAR2(255) NULL
	,PREFERRED_STATUS VARCHAR2(255) NULL
	,PREFERRED_STATUS_START DATE NULL
	,PREFERRED_STATUS_END DATE NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL		
    ,CONSTRAINT XITMAML_PK PRIMARY KEY 
       (ITEM_KEY ,MANUFACTURER_ITEM_KEY)
       USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE TABLE BOM_LINE_ITEM
(
    BOM_LINE_ITEM_KEY NUMBER(19) NOT NULL
	,BOM_KEY NUMBER(19) NOT NULL
	,ITEM_KEY NUMBER(19) NOT NULL
	,SUB_BOM_KEY NUMBER(19) NULL
	,ITEM_QUANTITY NUMBER(19, 6) NULL
	,DESCRIPTION VARCHAR2(1024) NULL
	,SEQUENCE_IDENTIFIER VARCHAR2(64) NOT NULL
	,NOTES VARCHAR2(255) NULL
	,BOM_TYPE_CODE VARCHAR2(255) NULL
	,BOM_TYPE_CODE_OTHER VARCHAR2(255) NULL
	,MANAGED_FLAG VARCHAR2(64) NULL	
	,IS_SERIALIZATION_REQ NUMBER(1) NULL
	,PRODUCT_QTY_TYPE_CODE VARCHAR2(255) NULL
	,PRODUCT_QTY_TYPE_CODE_OTHER VARCHAR2(255) NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,ROLLUP_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,LEAD_TIME NUMBER(19,4) NULL
	,ATTRITION_RATE NUMBER(19, 4) NULL
    ,GROUP_ID VARCHAR2(255) NULL
	,BOM_LINE_ALT_TYPE VARCHAR2(64) NULL
    ,PRIORITY NUMBER(2) NULL
	,REASON_CODE VARCHAR2(255) NULL
	,STRING_ATTRIBUTE1 VARCHAR2(1024)
	,STRING_ATTRIBUTE2 VARCHAR2(1024)
	,STRING_ATTRIBUTE3 VARCHAR2(1024)
	,STRING_ATTRIBUTE4 VARCHAR2(1024)
	,STRING_ATTRIBUTE5 VARCHAR2(1024)
	,STRING_ATTRIBUTE6 VARCHAR2(1024)
	,STRING_ATTRIBUTE7 VARCHAR2(1024)
	,STRING_ATTRIBUTE8 VARCHAR2(1024)
	,STRING_ATTRIBUTE9 VARCHAR2(1024)
	,STRING_ATTRIBUTE10 VARCHAR2(1024)
	,NUMBER_ATTRIBUTE1 NUMBER 
	,NUMBER_ATTRIBUTE2 NUMBER 
	,NUMBER_ATTRIBUTE3 NUMBER 
	,NUMBER_ATTRIBUTE4 NUMBER 
	,NUMBER_ATTRIBUTE5 NUMBER 
	,NUMBER_ATTRIBUTE6 NUMBER 
	,NUMBER_ATTRIBUTE7 NUMBER 
	,NUMBER_ATTRIBUTE8 NUMBER 
	,NUMBER_ATTRIBUTE9 NUMBER 
	,NUMBER_ATTRIBUTE10 NUMBER
	,FLOAT_ATTRIBUTE1 NUMBER(19,6)
	,FLOAT_ATTRIBUTE2 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE3 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE4 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE5 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE6 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE7 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE8 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE9 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE10 NUMBER(19,6) 
	,DATE_ATTRIBUTE1 DATE 
	,DATE_ATTRIBUTE2 DATE 
	,DATE_ATTRIBUTE3 DATE 
	,DATE_ATTRIBUTE4 DATE 
	,DATE_ATTRIBUTE5 DATE 
	,DATE_ATTRIBUTE6 DATE 
	,DATE_ATTRIBUTE7 DATE 
	,DATE_ATTRIBUTE8 DATE 
	,DATE_ATTRIBUTE9 DATE 
	,DATE_ATTRIBUTE10 DATE
	,CONSTRAINT XBMLIT_PK PRIMARY KEY (BOM_LINE_ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE INDEX XBMLI_BOM_ITEM_I1
	ON BOM_LINE_ITEM(BOM_KEY, ITEM_KEY) 
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XBMLI_BOM_SUBKEY_I2
	ON BOM_LINE_ITEM(SUB_BOM_KEY) 
		TABLESPACE AUDIT_INDEX;
		
CREATE INDEX XBMLI_ITEM_I3
	ON BOM_LINE_ITEM(ITEM_KEY) 
		TABLESPACE AUDIT_INDEX;

CREATE TABLE BOM_HEADER
(
	BOM_KEY NUMBER(19) NOT NULL
	,BOM_EXTERNAL_ID VARCHAR2(255) NULL
	,BOM_NAME VARCHAR2(255) NULL
	,BOM_DESCRIPTION VARCHAR2(1024) NULL
	,OWNER VARCHAR2(255) NULL
	,OWNER_TYPE VARCHAR2(255) NULL
	,ITEM_KEY NUMBER(19) NOT NULL
	,VERSION VARCHAR2(255) NULL
	,REVISION VARCHAR2(255) NULL
	,VERSION_DATE DATE NULL
	,REVISION_DATE DATE NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,BOM_TYPE_CODE VARCHAR2(255) NULL
	,BOM_TYPE_CODE_OTHER VARCHAR2(255) NULL
	,IS_TOP_LEVEL NUMBER(1) NULL
	,DATA_SOURCE VARCHAR2(255) NOT NULL
    ,STATUS VARCHAR2(40) DEFAULT 'NEW' NOT NULL
    ,STATUS_CHANGE_DATE TIMESTAMP    
	,STATUS_LAST_CHANGE_BY VARCHAR2(64)	
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,LEAD_TIME NUMBER(19,4) NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,ROLLUP_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,IS_REPAIRS NUMBER(1) NULL
	,LOAD_SOURCE VARCHAR2(255) NULL
	,CONTEXT_OBJECT_TYPE VARCHAR2(50)
   	,CONTEXT_OBJECT_ID NUMBER(19,0)
	,STRING_ATTRIBUTE1 VARCHAR2(1024)
	,STRING_ATTRIBUTE2 VARCHAR2(1024)
	,STRING_ATTRIBUTE3 VARCHAR2(1024)
	,STRING_ATTRIBUTE4 VARCHAR2(1024)
	,STRING_ATTRIBUTE5 VARCHAR2(1024)
	,STRING_ATTRIBUTE6 VARCHAR2(1024)
	,STRING_ATTRIBUTE7 VARCHAR2(1024)
	,STRING_ATTRIBUTE8 VARCHAR2(1024)
	,STRING_ATTRIBUTE9 VARCHAR2(1024)
	,STRING_ATTRIBUTE10 VARCHAR2(1024)
	,NUMBER_ATTRIBUTE1 NUMBER 
	,NUMBER_ATTRIBUTE2 NUMBER 
	,NUMBER_ATTRIBUTE3 NUMBER 
	,NUMBER_ATTRIBUTE4 NUMBER 
	,NUMBER_ATTRIBUTE5 NUMBER 
	,NUMBER_ATTRIBUTE6 NUMBER 
	,NUMBER_ATTRIBUTE7 NUMBER 
	,NUMBER_ATTRIBUTE8 NUMBER 
	,NUMBER_ATTRIBUTE9 NUMBER 
	,NUMBER_ATTRIBUTE10 NUMBER
	,FLOAT_ATTRIBUTE1 NUMBER(19,6)
	,FLOAT_ATTRIBUTE2 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE3 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE4 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE5 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE6 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE7 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE8 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE9 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE10 NUMBER(19,6) 
	,DATE_ATTRIBUTE1 DATE 
	,DATE_ATTRIBUTE2 DATE 
	,DATE_ATTRIBUTE3 DATE 
	,DATE_ATTRIBUTE4 DATE 
	,DATE_ATTRIBUTE5 DATE 
	,DATE_ATTRIBUTE6 DATE 
	,DATE_ATTRIBUTE7 DATE 
	,DATE_ATTRIBUTE8 DATE 
	,DATE_ATTRIBUTE9 DATE 
	,DATE_ATTRIBUTE10 DATE
    ,CONSTRAINT XBMHDR_PK PRIMARY KEY (BOM_KEY)
         USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBMHDR_U1
    ON BOM_HEADER(        
		ITEM_KEY ASC
		,VERSION ASC
		,REVISION ASC
		,DATA_SOURCE ASC
		,BUSINESS_ENTITY_KEY ASC
		,CONTEXT_OBJECT_TYPE
   		,CONTEXT_OBJECT_ID
   		,EFFECTIVE_FROM_DT
        ,EFFECTIVE_TO_DT
    ) TABLESPACE AUDIT_INDEX;
    
CREATE INDEX XBMHDR_BE_ITEM_I1
	ON BOM_HEADER(BUSINESS_ENTITY_KEY, ITEM_KEY, REVISION, VERSION, EFFECTIVE_FROM_DT) 
		TABLESPACE AUDIT_INDEX;


CREATE INDEX XBMHDR_ITEM_I1
	ON BOM_HEADER(ITEM_KEY, REVISION, VERSION, EFFECTIVE_FROM_DT) 
		TABLESPACE AUDIT_INDEX;

-- This helps when walking the boms
CREATE INDEX XBMHDR_ITEM_VERSION_I3
	ON BOM_HEADER(ITEM_KEY, VERSION DESC, EFFECTIVE_FROM_DT DESC) 
		TABLESPACE AUDIT_INDEX;
		
CREATE TABLE BOM_VERSION
(
	ITEM_KEY NUMBER(19) NOT NULL,
	BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL,	
    CURRENT_VERSION NUMBER(10),
    CONTEXT_OBJECT_TYPE VARCHAR2(50),
   	CONTEXT_OBJECT_ID NUMBER(19,0)
);

-- Site Table start 

CREATE TABLE SITE_DETAILS (
ID NUMBER(19,0) NOT NULL,
MRP_SITE VARCHAR2(255),
INTERFACE_SITE VARCHAR2(255),
COST_NEGOTIATION_FLAG VARCHAR2(1),
DEMAND_FORECAST_FLAG VARCHAR2(1),
TAM_VISIBLE_FLAG VARCHAR2(1),
TAM_PROCESSING_FLAG VARCHAR2(1),
SITE_STATE VARCHAR2(1),
SITE_OWNER VARCHAR2(255),
ODM_SUPPLIER VARCHAR2(255),
COST_VISIBLE_FLAG VARCHAR2(1),
TAM_UPDATE_FLAG VARCHAR2(1),
COST_UPDATE_FLAG VARCHAR2(1),
DISCP_SITE_DESCRIPTION VARCHAR2(255),
MRP_SITE_LEGACY VARCHAR2(255),
SITE_PURPOSE VARCHAR2(255),
EOL_LAST_UPDATE_ON TIMESTAMP,
CONSTRAINT SITE_DETAILS_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE SITE_DETAILS_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
             
CREATE TABLE SITE
(
	SITE_KEY NUMBER(19) NOT NULL
	,SITE_IDENTIFIER VARCHAR2(255) NOT NULL
	,SITE_DESCRIPTION VARCHAR2(1024) NULL
	,CONTACT_KEY NUMBER(19) NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NULL
	,PARENT_SITE_KEY NUMBER(19) NULL
	,SITE_TYPE VARCHAR2(128) NULL
	,DEFAULT_CURRENCY_CODE VARCHAR2(6) NULL
	,DATA_SOURCE VARCHAR2(255) NOT NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,SITE_DETAIL_ID NUMBER(19,0)
	,CONSTRAINT XSITE_CC_FK FOREIGN KEY(DEFAULT_CURRENCY_CODE)
	REFERENCES CURRENCY_CODE ON DELETE SET NULL
	,CONSTRAINT SITE_DETAILS_FG FOREIGN KEY (SITE_DETAIL_ID) REFERENCES SITE_DETAILS(ID)
    ,CONSTRAINT XSITE_PK PRIMARY KEY(SITE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

ALTER TABLE SITE ADD 
(    
    CONSTRAINT SITE_PSITE_FK 
        FOREIGN KEY (PARENT_SITE_KEY) REFERENCES SITE
);

CREATE TABLE CCN_SITE (
ID NUMBER(19,0) NOT NULL,
CCN VARCHAR2(255),
GLOBAL_REGION VARCHAR2(255),
INTERFACE_REGION VARCHAR2(255),
SITE_KEY NUMBER(19,0) NOT NULL,
CONSTRAINT SITE_KEY_CCN_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT SITE_CCN_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE SITE_CCN_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE SITE_FACILITIES (
ID NUMBER(19,0) NOT NULL,
FACILITY VARCHAR2(255),
DEFAULT_FACILITY_FLAG VARCHAR2(1),
SITE_KEY NUMBER(19,0) NOT NULL,
CONSTRAINT SITE_KEY_FACILITIES_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT SITE_FACILITIES_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE SITE_FACILITIES_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
--Site Additional table end

CREATE UNIQUE INDEX XSITE_U1 ON SITE
(
    BUSINESS_ENTITY_KEY ASC,
	SITE_IDENTIFIER ASC,
    DATA_SOURCE ASC
) TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX XSITE_IDENT_I1 ON SITE
(
	SITE_KEY,
	SITE_IDENTIFIER
) TABLESPACE AUDIT_INDEX;

CREATE TABLE ITEM_ITEM_CATEGORY
(
    ITEM_KEY NUMBER(19) NOT NULL
	,ITEM_CATEGORY_KEY NUMBER(19) NOT NULL
    ,CONSTRAINT XITITCT_PK PRIMARY KEY(ITEM_KEY ,ITEM_CATEGORY_KEY)
     	USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

-- NOT CURRENTLY USED
CREATE TABLE ITEM_SERIALNUMBER
(
    ITEM_KEY NUMBER(19) NOT NULL
	,SERIAL_NUMBER VARCHAR2(255) NOT NULL
	,SERIAL_NUMBER_TYPE VARCHAR2(255) NOT NULL
	,SERIAL_NUMBER_DESC VARCHAR2(1024) NULL
	,SERIAL_NUMBER_START VARCHAR2(255) NULL
	,SERIAL_NUMBER_END VARCHAR2(255) NULL
	,CONSTRAINT XITMSRN_PK PRIMARY KEY (ITEM_KEY,SERIAL_NUMBER,SERIAL_NUMBER_TYPE)
    	USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

-- NOT CURRENTLY USED
CREATE TABLE ITEM_CHARACTERISTIC
(
    ITEM_CHAR_KEY NUMBER(19) NOT NULL
	,ITEM_KEY NUMBER(19) NOT NULL
	,CHARACTERISTIC_TYPE VARCHAR2(255) NULL
	,CHARACTERISTIC_SOURCE VARCHAR2(255) NULL
	,CHARACTERISTIC_NAME VARCHAR2(255) NOT NULL
	,CHARACTERISTIC_VALUE VARCHAR2(255) NULL
	,CHARACTERISTIC_UOM VARCHAR2(255) NULL
	,CHARACTERISTIC_NTOLERANCE VARCHAR2(255) NULL
	,CHARACTERISTIC_PTOLERANCE VARCHAR2(255) NULL
	,CONSTRAINT XITMCHR_PK PRIMARY KEY (ITEM_CHAR_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XITMCHR_U1
	ON ITEM_CHARACTERISTIC(
    	ITEM_KEY ASC
    	,CHARACTERISTIC_TYPE ASC
    	,CHARACTERISTIC_SOURCE ASC
    	,CHARACTERISTIC_NAME ASC
	) TABLESPACE AUDIT_INDEX;

CREATE TABLE ITEM_ALTERNATES
(
	ITEM_KEY NUMBER(19) NOT NULL
	,ALTERNATE_ITEM_KEY NUMBER(19) NOT NULL
	,PREFERRED_STATUS_CODE VARCHAR2(255) NULL
	,PREFERRED_STATUS_START DATE NULL
	,PREFERRED_STATUS_END DATE NULL
    ,CONSTRAINT XITMALT_PK PRIMARY KEY(ITEM_KEY,ALTERNATE_ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE ITEM_MASTER
(
    ITEM_KEY NUMBER(19) NOT NULL
	,ITEM_IDENTIFIER VARCHAR2(255) NOT NULL
	,ITEM_UNIQUE_IDENTIFIER VARCHAR2(255) NULL
	,ITEM_DESCRIPTION VARCHAR2(1024) NULL
	,VERSION VARCHAR2(255) NULL
	,REVISION VARCHAR2(255) NOT NULL
	,VERSION_DATE DATE NULL
	,REVISION_DATE DATE NULL
	,ITEM_EXTERNAL_ID VARCHAR2(255) NULL
	,GBL_LFCYCL_PH_CODE VARCHAR2(255) NULL
	,GBL_PROD_LFCYCL_CODE_OTHER VARCHAR2(255) NULL
	,ITEM_CLASSIFICATION VARCHAR2(255) NULL
	,GBL_UOM_CODE VARCHAR2(255) NULL
	,PRODUCT_FAMILY VARCHAR2(1024) NULL
	,OWNER_NAME VARCHAR2(255) NULL
	,OWNER_TYPE VARCHAR2(255) NULL
	,ITEM_TYPE VARCHAR2(3) NULL 
     CONSTRAINT ITEMMTR_ITMTYPE 
         CHECK((ITEM_TYPE IN ('I','M','S','PI','CG','UDG','CFG')))
	,IS_TOP_LEVEL NUMBER(1) NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,CONTACT_KEY NUMBER(19) NULL
    ,BUYER_CODE VARCHAR2(32) NULL
	,MAKE_BUY VARCHAR2(255) NULL
	,MAKE_BUY_OTHER VARCHAR2(255) NULL
	,MANAGED_FLAG VARCHAR2(64) NULL
	,CERTIFICATION_REQUIRED NUMBER(1) NULL
	,SERIALNUMBER_REQUIRED NUMBER(1) NULL
	,DATA_SOURCE NVARCHAR2(765) NOT NULL	
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
	,ITEM_PART_TYPE VARCHAR2(255) NULL
	,COLLABORATION NUMBER(1)
	,INVENTORY DECIMAL(19,6)
	,STRING_ATTRIBUTE1 VARCHAR2(1024)
    ,STRING_ATTRIBUTE2 VARCHAR2(1024)
    ,STRING_ATTRIBUTE3 VARCHAR2(1024)
    ,STRING_ATTRIBUTE4 VARCHAR2(1024)
    ,STRING_ATTRIBUTE5 VARCHAR2(1024)
    ,STRING_ATTRIBUTE6 VARCHAR2(1024)
    ,STRING_ATTRIBUTE7 VARCHAR2(1024)
    ,STRING_ATTRIBUTE8 VARCHAR2(1024)
    ,STRING_ATTRIBUTE9 VARCHAR2(1024)
    ,STRING_ATTRIBUTE10 VARCHAR2(1024)
    ,NUMBER_ATTRIBUTE1 NUMBER
	,NUMBER_ATTRIBUTE2 NUMBER
	,NUMBER_ATTRIBUTE3 NUMBER
	,NUMBER_ATTRIBUTE4 NUMBER
	,NUMBER_ATTRIBUTE5 NUMBER
	,NUMBER_ATTRIBUTE6 NUMBER
	,NUMBER_ATTRIBUTE7 NUMBER
	,NUMBER_ATTRIBUTE8 NUMBER
	,NUMBER_ATTRIBUTE9 NUMBER
	,NUMBER_ATTRIBUTE10 NUMBER
	,FLOAT_ATTRIBUTE1 NUMBER(19,6)
	,FLOAT_ATTRIBUTE2 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE3 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE4 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE5 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE6 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE7 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE8 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE9 NUMBER(19,6) 
	,FLOAT_ATTRIBUTE10 NUMBER(19,6) 
	,DATE_ATTRIBUTE1 DATE
	,DATE_ATTRIBUTE2 DATE
	,DATE_ATTRIBUTE3 DATE
	,DATE_ATTRIBUTE4 DATE
	,DATE_ATTRIBUTE5 DATE
	,DATE_ATTRIBUTE6 DATE
	,DATE_ATTRIBUTE7 DATE
	,DATE_ATTRIBUTE8 DATE
	,DATE_ATTRIBUTE9 DATE
	,DATE_ATTRIBUTE10 DATE
	,EOL VARCHAR2(1)
	,EOL_LAST_CHANGED_ON TIMESTAMP
	,EOL_TYPE VARCHAR2(255)
  	,CONSTRAINT XITMMTR_PK PRIMARY KEY (ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XITM_MSTR_NK 
	ON ITEM_MASTER(ITEM_IDENTIFIER,ITEM_UNIQUE_IDENTIFIER,VERSION,REVISION,BUSINESS_ENTITY_KEY)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_U1 
	ON ITEM_MASTER(ITEM_IDENTIFIER,BUSINESS_ENTITY_KEY)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_BEKEY_U2 
	ON ITEM_MASTER(BUSINESS_ENTITY_KEY)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_CF 
	ON ITEM_MASTER(CURRENT_FLAG)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_DF 
	ON ITEM_MASTER(NVL(DELETE_FLAG,'N'))
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_ITL 
	ON ITEM_MASTER(IS_TOP_LEVEL)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_OWNER 
	ON ITEM_MASTER(OWNER_NAME,INSERT_DT)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_SI_ITMNMR 
	ON ITEM_MASTER (ITEM_IDENTIFIER ASC) 
	TABLESPACE AUDIT_INDEX;    

CREATE INDEX XITM_MSTR_CI_ITMNMR 
	ON ITEM_MASTER (LOWER(ITEM_IDENTIFIER)) 
	TABLESPACE AUDIT_INDEX;    

CREATE INDEX XITM_MSTR_OWNER_CI 
	ON ITEM_MASTER(LOWER(OWNER_NAME),INSERT_DT)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_IUID 
	ON ITEM_MASTER(ITEM_UNIQUE_IDENTIFIER,VERSION,REVISION,BUSINESS_ENTITY_KEY)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_ITYPE 
	ON ITEM_MASTER(ITEM_TYPE)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_INSDT
	ON ITEM_MASTER (INSERT_DT, DELETE_FLAG)
		tablespace audit_index;
    
CREATE INDEX XITM_MSTR_ICOLLAB
	ON ITEM_MASTER (COLLABORATION)
		tablespace audit_index;
    
CREATE TABLE ITEM_GROUP_ITEMS
(
	ITEM_KEY NUMBER(19) NOT NULL
	,ITEM_GROUP_ITEM_KEY NUMBER(19) NOT NULL
    ,CONSTRAINT XITMGRP_PK PRIMARY KEY(ITEM_KEY,ITEM_GROUP_ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
    ,CONSTRAINT ITMGRP_ITM_FK FOREIGN KEY(ITEM_KEY) REFERENCES ITEM_MASTER
    ,CONSTRAINT ITMGRP_ITMGRP_FK FOREIGN KEY(ITEM_GROUP_ITEM_KEY) REFERENCES ITEM_MASTER    
) TABLESPACE AUDIT_DATA;
	
CREATE TABLE ITEM_CATEGORY
(
    ITEM_CATEGORY_KEY NUMBER(19) NOT NULL
	,ITEM_CATEGORY_IDENTIFIER VARCHAR2(255) NOT NULL
	,ITEM_CATEGORY_NAME VARCHAR2(1024) NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,PARENT_CATEGORY_KEY NUMBER(19) NULL
	,PRODUCT_FAMILY VARCHAR2(255) NULL
	,MANAGED_FLAG VARCHAR2(64) NULL
    ,CONSTRAINT XITMCAT_PK PRIMARY KEY (ITEM_CATEGORY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XITMCAT_U1
    ON ITEM_CATEGORY(ITEM_CATEGORY_IDENTIFIER ASC,BUSINESS_ENTITY_KEY ASC)
    	 TABLESPACE AUDIT_INDEX;

CREATE INDEX XITMCAT_CATID_I1
   ON ITEM_CATEGORY(ITEM_CATEGORY_IDENTIFIER ASC)
   	TABLESPACE AUDIT_INDEX;
	  	 
CREATE INDEX XITMCAT_CATNAME_I2
   ON ITEM_CATEGORY(ITEM_CATEGORY_NAME)
   TABLESPACE AUDIT_INDEX;
	  	 
CREATE TABLE BUSINESS_ENTITY
(
    BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,BUSINESS_ENTITY_IDENTIFIER VARCHAR2(255) NOT NULL
	,BUSINESS_ENTITY_NAME VARCHAR2(255) NULL
	,BUSINESS_ENTITY_DESC VARCHAR2(1024) NULL
	,BUSINESS_ENTITY_EXTERNAL_ID VARCHAR2(255) NULL
	,BUSINESS_ENTITY_TYPE_KEY NUMBER(19) NULL
	,CONTACT_KEY NUMBER(19) NULL
	,DATA_SOURCE VARCHAR2(255) NOT NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
    ,CONSTRAINT XBSENT_PK PRIMARY KEY (BUSINESS_ENTITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBSENT_U1
	ON BUSINESS_ENTITY(
    	BUSINESS_ENTITY_IDENTIFIER ASC
    	,DATA_SOURCE ASC
    	,BUSINESS_ENTITY_TYPE_KEY ASC
	) TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX XBSENT_EXTREF_U2
	ON BUSINESS_ENTITY(BUSINESS_ENTITY_EXTERNAL_ID)
	TABLESPACE AUDIT_INDEX;
	
CREATE INDEX XBSENT_CI_NAME 
	ON BUSINESS_ENTITY (LOWER(BUSINESS_ENTITY_NAME)) 
	TABLESPACE AUDIT_INDEX;    

CREATE INDEX XBSENT__NAME 
	ON BUSINESS_ENTITY (BUSINESS_ENTITY_NAME) 
	TABLESPACE AUDIT_INDEX;    

CREATE INDEX XBSENT_TYPE 
	ON BUSINESS_ENTITY (BUSINESS_ENTITY_TYPE_KEY) 
	TABLESPACE AUDIT_INDEX;    

CREATE TABLE BUSINESS_ENTITY_TYPE
(
     BUSINESS_ENTITY_TYPE_KEY NUMBER(19) NOT NULL
	,BUSINESS_ENTITY_TYPE_NAME VARCHAR2(255) NOT NULL
	,BUSINESS_ENTITY_TYPE_DESC VARCHAR2(1024) NULL
	,CONSTRAINT XBSENTT_PK PRIMARY KEY (BUSINESS_ENTITY_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBSENTT_U1
    ON BUSINESS_ENTITY_TYPE(BUSINESS_ENTITY_TYPE_NAME ASC) 
    TABLESPACE AUDIT_INDEX;

CREATE TABLE BUSINESS_ENTITY_ALT(
	BUSINESS_ENTITY_ALT_KEY NUMBER(19) NOT NULL
    ,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
    ,BUSINESS_ENTITY_NAME VARCHAR2(255) NOT NULL
    ,DATA_SOURCE VARCHAR2(255) NOT NULL        
    ,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    ,UPDATE_DT TIMESTAMP NULL
    ,EFFECTIVE_FROM_DT DATE NULL
    ,EFFECTIVE_TO_DT DATE NULL
    ,DELETE_FLAG VARCHAR2(1) NULL
    ,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
    ,CONSTRAINT XBSENTALT_PK 
         PRIMARY KEY (BUSINESS_ENTITY_ALT_KEY)
              USING INDEX TABLESPACE AUDIT_INDEX
    ,CONSTRAINT XBSENTALT_FK FOREIGN KEY
         (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY)
            ON DELETE CASCADE       		
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XBSENTALT_U1
    ON BUSINESS_ENTITY_ALT(BUSINESS_ENTITY_NAME ASC, DATA_SOURCE) 
    TABLESPACE AUDIT_INDEX;

CREATE TABLE BUSINESS_ENTITY_CURRENCY
(
	CURRENCY_CODE VARCHAR2(6) NOT NULL,
	BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL,
	CONSTRAINT XBEC_BE_FK FOREIGN KEY(BUSINESS_ENTITY_KEY)
		REFERENCES BUSINESS_ENTITY ON DELETE CASCADE,
	CONSTRAINT XBEC_CC_FK FOREIGN KEY(CURRENCY_CODE)
		REFERENCES CURRENCY_CODE ON DELETE CASCADE,			
	CONSTRAINT XBEC_PK PRIMARY KEY(CURRENCY_CODE,BUSINESS_ENTITY_KEY)
		USING INDEX TABLESPACE AUDIT_INDEX		
);

CREATE TABLE ITEM_PLATFORM
(
    ITEM_PLATFORM_KEY NUMBER(19) NOT NULL
	,ITEM_PLATFORM_NAME VARCHAR2(255) NOT NULL
	,ITEM_PLATFORM_TYPE VARCHAR2(32) NULL	
	,ITEM_PLATFORM_EXTERNAL_ID VARCHAR2(255) NULL
	,ITEM_PLATFORM_DESC VARCHAR2(1024) NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL
	,CONSTRAINT XITMPLT_BE_FK FOREIGN KEY(BUSINESS_ENTITY_KEY)
		REFERENCES BUSINESS_ENTITY
    ,CONSTRAINT XITMPLT_PK PRIMARY KEY (ITEM_PLATFORM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XITMPL_U1
    ON ITEM_PLATFORM(ITEM_PLATFORM_NAME ASC, ITEM_PLATFORM_TYPE,BUSINESS_ENTITY_KEY) 
    TABLESPACE AUDIT_INDEX;

CREATE TABLE ITEM_ITEM_PLATFORM
(
    ITEM_KEY NUMBER(19) NOT NULL
	,ITEM_PLATFORM_KEY NUMBER(19) NOT NULL
    ,CONSTRAINT XITITPL_ITEM_FK FOREIGN KEY(ITEM_KEY) 
    	REFERENCES ITEM_MASTER ON DELETE CASCADE
    ,CONSTRAINT XITITPL_IPLT_FK FOREIGN KEY(ITEM_PLATFORM_KEY) 
    	REFERENCES ITEM_PLATFORM  ON DELETE CASCADE    		
    ,CONSTRAINT XITITPT_PK PRIMARY KEY(ITEM_KEY ,ITEM_PLATFORM_KEY)
     	USING INDEX TABLESPACE AUDIT_INDEX	
) TABLESPACE AUDIT_DATA;

CREATE TABLE CONTACT
(
	CONTACT_KEY NUMBER(19) NOT NULL
	,CONTACT_NAME VARCHAR2(255) NOT NULL
	,CONTACT_ID VARCHAR2(255) NULL
	,CONTACT_UNIQUE_ID VARCHAR2(255) NULL
	,BUSINESS_ENTITY_KEY NUMBER(19) NULL
	,ADDRESS_LINE1 VARCHAR2(255) NULL
	,ADDRESS_LINE2 VARCHAR2(255) NULL
	,ADDRESS_LINE3 VARCHAR2(255) NULL
	,CITY VARCHAR2(255) NULL
	,REGION VARCHAR2(255) NULL
	,COUNTRY VARCHAR2(255) NULL
	,PHONE_NUMBER VARCHAR2(255) NULL
	,POSTAL_CODE VARCHAR2(255) NULL
	,COUNTRY_CODE VARCHAR2(255) NULL
	,FACSIMILE_NUMBER VARCHAR2(255) NULL
	,DEPARTMENT VARCHAR2(255) NULL
	,BUSINESS_NAME VARCHAR2(255) NULL
	,BUSINESS_IDENTIFIER VARCHAR2(255) NULL
	,EMAIL VARCHAR2(255) NULL
	,URI VARCHAR2(255) NULL
	,STATUS VARCHAR2(255) NULL
	,PARTNER_CLASSIFICATION VARCHAR2(255) NULL
	,CONTACT_ROLE VARCHAR2(255) NULL
	,DIGITAL_CERTIFICATE VARCHAR2(255) NULL
	,DATA_SOURCE VARCHAR2(255) NOT NULL
	,INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	,UPDATE_DT TIMESTAMP NULL
	,EFFECTIVE_FROM_DT DATE NULL
	,EFFECTIVE_TO_DT DATE NULL
	,DELETE_FLAG VARCHAR2(1) NULL
	,CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL
    ,CONSTRAINT XCNT_PK PRIMARY KEY (CONTACT_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE FISCAL_PERIOD
(
	FISCAL_PERIOD_TYPE VARCHAR2(1) NOT NULL,
	FISCAL_PERIOD_NAME VARCHAR2(32) NOT NULL,
	FISCAL_PERIOD NUMBER(4) NOT NULL,
	FISCAL_PERIOD_START_DATE DATE NOT NULL,
	FISCAL_PERIOD_END_DATE DATE NOT NULL,
	CONSTRAINT XFISPER_PK PRIMARY KEY(FISCAL_PERIOD_TYPE,FISCAL_PERIOD,
		FISCAL_PERIOD_START_DATE,FISCAL_PERIOD_END_DATE)
		USING INDEX TABLESPACE AUDIT_INDEX	
);

ALTER TABLE SITE_ADD_ATTRIBUTE ADD 
    CONSTRAINT SITEAA_R01_ATRGRP 
    FOREIGN KEY (ATTRIBUTE_GROUP_KEY) REFERENCES ATTRIBUTE_GROUP;

ALTER TABLE SITE_ADD_ATTRIBUTE ADD 
    CONSTRAINT SITEAA_R02_SITE 
    FOREIGN KEY (SITE_KEY) REFERENCES SITE;

ALTER TABLE BUSINESS_ENTITY_ADD_ATTRIBUTE ADD 
    CONSTRAINT BSUTAA_R01_ATRGRP 
    FOREIGN KEY (ATTRIBUTE_GROUP_KEY) REFERENCES ATTRIBUTE_GROUP;

ALTER TABLE BUSINESS_ENTITY_ADD_ATTRIBUTE ADD 
    CONSTRAINT BSUTAA_R01_BSENT 
    FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;

ALTER TABLE ITEM_ADD_ATTRIBUTE ADD 
    CONSTRAINT ITMAA_R01_ATRGRP 
    FOREIGN KEY (ATTRIBUTE_GROUP_KEY) REFERENCES ATTRIBUTE_GROUP;

ALTER TABLE ITEM_ADD_ATTRIBUTE ADD    
    CONSTRAINT ITMAA_R02_ITMMTR 
    FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE ITEM_AVL_ADD_ATTRIBUTE ADD 
	CONSTRAINT ITAAA_R01_ATRGRP 
	FOREIGN KEY (ATTRIBUTE_GROUP_KEY) REFERENCES ATTRIBUTE_GROUP;

ALTER TABLE ITEM_AVL_ADD_ATTRIBUTE ADD    
	CONSTRAINT ITAAA_R02_AVLMTR 
	FOREIGN KEY (AVL_KEY) REFERENCES ITEM_AVL ON DELETE CASCADE;

ALTER TABLE BOM_LINE_ITEM_ADD_ATTRIBUTE ADD 
    CONSTRAINT BMLIAA_R01_ATRGRP 
    FOREIGN KEY (ATTRIBUTE_GROUP_KEY) REFERENCES ATTRIBUTE_GROUP;

ALTER TABLE BOM_LINE_ITEM_ADD_ATTRIBUTE ADD    
    CONSTRAINT BMLIAA_R02_BMLIT 
    FOREIGN KEY (BOM_LINE_ITEM_KEY) REFERENCES BOM_LINE_ITEM  ON DELETE CASCADE;

ALTER TABLE BOM_BOM_GROUP ADD 
    CONSTRAINT BMBMGP_R01_BMHDR 
    FOREIGN KEY (BOM_KEY) REFERENCES BOM_HEADER  ON DELETE CASCADE;
    
ALTER TABLE BOM_BOM_GROUP ADD    
    CONSTRAINT BMGRP_R01_BMBMGP 
    FOREIGN KEY (BOM_KEY) REFERENCES BOM_GROUP;

ALTER TABLE BOM_GROUP ADD 
    CONSTRAINT BMGRP_R02_BSENT 
    FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;

ALTER TABLE BOM_SITE_LINK ADD 
    CONSTRAINT BMSTLK_R02_SITE 
    FOREIGN KEY (SITE_KEY) REFERENCES SITE;

ALTER TABLE BOM_SITE_LINK ADD
    CONSTRAINT BMSTLK_R01_BMHDR 
    FOREIGN KEY (BOM_KEY) REFERENCES BOM_HEADER;

ALTER TABLE ITEM_AVL ADD
    CONSTRAINT ITMAVL_R05_BMHDR 
    FOREIGN KEY (BOM_KEY) REFERENCES BOM_HEADER;


ALTER TABLE ITEM_AVL ADD 
        CONSTRAINT ITMAVL_R02_BSENT 
        FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;
    
ALTER TABLE ITEM_AVL ADD 
        CONSTRAINT ITMAVL_R01_ITMMTR 
        FOREIGN KEY (SUPPLIER_PART_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;
   
ALTER TABLE ITEM_AVL ADD
        CONSTRAINT ITMAVL_R03_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE PCM_ITEM_AVL_SITE
       ADD  ( CONSTRAINT ITEMAVLST_R01_XITMAVL
              FOREIGN KEY (AVL_KEY)
                             REFERENCES ITEM_AVL ON DELETE CASCADE) ;
                             
ALTER TABLE PCM_ITEM_AVL_SITE
       ADD  ( CONSTRAINT ITEMAVLST_R02_SITE
              FOREIGN KEY (SITE_KEY)
                             REFERENCES SITE ) ;        

ALTER TABLE ITEM_AML ADD 
        CONSTRAINT ITMAML_R05_BMHDR 
        FOREIGN KEY (BOM_KEY) REFERENCES BOM_HEADER ON DELETE CASCADE;

ALTER TABLE ITEM_AML ADD 
        CONSTRAINT ITMAML_R01_SITE 
        FOREIGN KEY (SITE_KEY) REFERENCES SITE;

ALTER TABLE ITEM_AML ADD 
        CONSTRAINT ITMAML_R04_BSENT 
        FOREIGN KEY (MANUFACTURER_KEY) REFERENCES BUSINESS_ENTITY;
        
ALTER TABLE ITEM_AML ADD 
        CONSTRAINT ITMAML_R03_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE ITEM_AML ADD
        CONSTRAINT ITMAML_R02_ITMMTR 
        FOREIGN KEY (MANUFACTURER_ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE BOM_LINE_ITEM ADD
        CONSTRAINT BMLIT_R02_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE BOM_LINE_ITEM ADD
        CONSTRAINT BMLIT_R01_BMHDR 
        FOREIGN KEY (BOM_KEY) REFERENCES BOM_HEADER ON DELETE CASCADE;

ALTER TABLE BOM_LINE_ITEM ADD
        CONSTRAINT BMLIT_R01_BMSUBKEY         
        FOREIGN KEY (SUB_BOM_KEY) REFERENCES BOM_HEADER
        ON DELETE SET NULL;

ALTER TABLE BOM_HEADER ADD
        CONSTRAINT BMHDR_R03_BSENT 
        FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;

ALTER TABLE BOM_HEADER ADD
        CONSTRAINT BMHDR_R02_ITMMTR
         FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER ON DELETE CASCADE;

ALTER TABLE SITE ADD
        CONSTRAINT SITE_R03_BSENT 
        FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY
        	ON DELETE CASCADE;

ALTER TABLE SITE ADD
        CONSTRAINT SITE_R02_CNT 
        FOREIGN KEY (CONTACT_KEY) REFERENCES CONTACT;

ALTER TABLE ITEM_ITEM_CATEGORY ADD
        CONSTRAINT ITITCT_R02_ITMCAT 
        FOREIGN KEY (ITEM_CATEGORY_KEY) REFERENCES ITEM_CATEGORY  ON DELETE CASCADE;

ALTER TABLE ITEM_ITEM_CATEGORY ADD
        CONSTRAINT ITITCT_R01_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER  ON DELETE CASCADE;

ALTER TABLE ITEM_SERIALNUMBER ADD
        CONSTRAINT ITMSRN_R01_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER  ON DELETE CASCADE;

ALTER TABLE ITEM_CHARACTERISTIC ADD
        CONSTRAINT ITMCHR_R01_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER  ON DELETE CASCADE;

ALTER TABLE ITEM_ALTERNATES ADD
        CONSTRAINT ITMALT_R01_ITMMTR 
        FOREIGN KEY (ALTERNATE_ITEM_KEY) REFERENCES ITEM_MASTER  ON DELETE CASCADE;

ALTER TABLE ITEM_ALTERNATES ADD
        CONSTRAINT ITMALT_R02_ITMMTR 
        FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER  ON DELETE CASCADE;

ALTER TABLE ITEM_MASTER ADD
        CONSTRAINT ITMMTR_R04_CNT 
        FOREIGN KEY (CONTACT_KEY) REFERENCES CONTACT ON DELETE SET NULL;

ALTER TABLE ITEM_MASTER ADD
        CONSTRAINT ITMMTR_R01_BSENT 
        FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;

ALTER TABLE ITEM_CATEGORY ADD
        CONSTRAINT ITMCAT_R01_BSENT
        FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY;

ALTER TABLE ITEM_CATEGORY ADD
        CONSTRAINT ITMCAT_R02_ITMCAT 
        FOREIGN KEY (PARENT_CATEGORY_KEY) REFERENCES ITEM_CATEGORY;

ALTER TABLE BUSINESS_ENTITY ADD
        CONSTRAINT BSENT_R03_BSENTT 
        FOREIGN KEY (BUSINESS_ENTITY_TYPE_KEY) REFERENCES BUSINESS_ENTITY_TYPE;

ALTER TABLE BUSINESS_ENTITY ADD
        CONSTRAINT BSENT_R01_CNT 
        FOREIGN KEY (CONTACT_KEY) REFERENCES CONTACT ON DELETE SET NULL;

-- THIS IS ONLY USED WHEN USING THE LOAD EVENT MANAGEMENT
-- FOR BUSINESS ENTITY

CREATE SEQUENCE LOAD_EVENT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE LOAD_JOB
(
    LOAD_JOB_KEY VARCHAR2(32) NOT NULL,
    LOADED_BY VARCHAR2(64),
    LOAD_JOB_TYPE VARCHAR2(128),
    LOAD_STATE VARCHAR2(64),    
    LOAD_STATUS VARCHAR2(64),   
    LOAD_EXTERNAL_ID VARCHAR2(128),
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,    
    LOAD_DATASOURCE VARCHAR2(1024),
    CONSTRAINT XLOADJOB_PK PRIMARY KEY (LOAD_JOB_KEY)
            USING INDEX TABLESPACE AUDIT_INDEX
);

CREATE TABLE LOAD_EVENT
(
	LOAD_EVENT_KEY NUMBER(19) NOT NULL
	,LOAD_JOB_KEY VARCHAR2(32) NOT NULL
	,LOAD_EVENT_TYPE VARCHAR2(64) NOT NULL
	,LOAD_EVENT_DATA VARCHAR2(1024)
	,LOAD_EVENT_CONTEXT VARCHAR2(255)
	,INSERT_DT DATE DEFAULT SYSDATE NOT NULL	
	,CONSTRAINT XLEVT_PK PRIMARY KEY (LOAD_EVENT_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
    ,CONSTRAINT XLEVT_LJ_FK FOREIGN KEY(LOAD_JOB_KEY) 
    	REFERENCES LOAD_JOB ON DELETE CASCADE    		
) TABLESPACE AUDIT_DATA;

-- THIS IS USED TO TRACK ITEM OWNER AND ITEM AVL CHANGES
CREATE TABLE ITEM_CHANGE_AUDIT
(
	ITEM_CHANGE_AUDIT_KEY NUMBER(19) NOT NULL,
	ITEM_KEY NUMBER(19) NOT NULL,
	LAST_CHANGE_DT TIMESTAMP NOT NULL,
	OP_CODE VARCHAR2(255) NOT NULL,
	USER_ID VARCHAR2(60)
) TABLESPACE AUDIT_DATA;

CREATE INDEX XICA_I1
	ON ITEM_CHANGE_AUDIT(OP_CODE, ITEM_KEY, LAST_CHANGE_DT)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XICA_I2
	ON ITEM_CHANGE_AUDIT(OP_CODE)
		TABLESPACE AUDIT_INDEX;

CREATE INDEX XITM_MSTR_ITID_TY ON ITEM_MASTER (ITEM_IDENTIFIER, ITEM_TYPE) TABLESPACE AUDIT_INDEX;

-- Create permanent table for BOM_HIERARCHY
-- Create permanent table for BOM_HIERARCHY
CREATE TABLE BOM_ROLLUP_HIERARCHY_STG (
    USER_KEY                NUMBER,
    ROOT_BOM_KEY            NUMBER,
    BOM_KEY                 NUMBER,
    BOM_LEVEL               NUMBER,
    BOM_ITEM_KEY            NUMBER,
    BOM_LINE_KEY            NUMBER,
    BLI_ITEM_KEY            NUMBER,
    SUB_BOM_KEY             NUMBER,
    ITEM_NAME               VARCHAR2(255),
    COST_RECORD_KEY         NUMBER,
    ITEM_ROLLUP_PRICE       NUMBER,
    ITEM_VA_COST            NUMBER,
    ITEM_PART_NAME          VARCHAR2(255),
    ITEM_PART_TOTAL_PRICE   NUMBER,
    DIRECT_MATERIAL         NUMBER,
    SHARING_COST            NUMBER,
    DIRECT_LABOR            NUMBER,
    VA_COST                 NUMBER,
    DIRECT_LABOR2           NUMBER,
    INDIRECT_LABOR          NUMBER,
    MACHINE_EQUIPMENT       NUMBER,
    MATERIAL_HANDLING       NUMBER,
    MATERIAL_SCRAP          NUMBER,
    FREIGHT                 NUMBER,
    SGA                     NUMBER,
    FINANCIAL_RECEIVABLES   NUMBER,
    PROFIT_MARGIN           NUMBER,
    ADJUSTMENTS_REDUCTIONS  NUMBER,
    MISCELLANEOUS           NUMBER,
    TARIFF                  NUMBER,
    ITEM_PART_ROLLUP_PRICE  NUMBER,
    ITEM_PART_QTY           NUMBER,
    ITEM_PART_SELLING_PRICE NUMBER,
    PRICE_TYPE              VARCHAR2(55),
    CREATED_ON              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CURRENCY_CONVERSION_ERROR_MSG  CLOB
);

-- Create permanent table for COST_DATA
CREATE TABLE BOM_ROLLUP_COST_DATA_STG (
    USER_KEY                NUMBER,
    ROOT_BOM_KEY            NUMBER,
    ITEM_PART_NAME          VARCHAR2(255),
    BLI_ITEM_KEY            NUMBER,
    SL_ITEM_KEY             NUMBER,
    BLI_BUSINESS_ENTITY_KEY NUMBER,
    BUSINESS_ENTITY_KEY     NUMBER,
    SOURCING_LANE_KEY       NUMBER,
    COST_RECORD_KEY         NUMBER,
    SUPPLIER_KEY            NUMBER,
    PRICE_TYPE              VARCHAR2(55),
    PRICE_ORDER             NUMBER,
    TOTAL_COST              NUMBER,
    DIRECT_MATERIAL         NUMBER,
    SHARING_COST            NUMBER,
    DIRECT_LABOR            NUMBER,
    VA_COST                 NUMBER,
    DIRECT_LABOR2           NUMBER,
    INDIRECT_LABOR          NUMBER,
    MACHINE_EQUIPMENT       NUMBER,
    MATERIAL_HANDLING       NUMBER,
    MATERIAL_SCRAP          NUMBER,
    FREIGHT                 NUMBER,
    SGA                     NUMBER,
    FINANCIAL_RECEIVABLES   NUMBER,
    PROFIT_MARGIN           NUMBER,
    ADJUSTMENTS_REDUCTIONS  NUMBER,
    MISCELLANEOUS           NUMBER,
    TARIFF                  NUMBER,
    CURRENCY_CODE           VARCHAR2(3)
    MISSING_BE              VARCHAR2(100)
);

CREATE TABLE BOM_ROLLUP_COST_LOG (
    BOM_ROLLUP_LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique identifier
    ROOT_BOM_KEY NUMBER NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    STATUS NUMBER(1) DEFAULT 0 CHECK (STATUS IN (0, 1, -1, 2)), -- 0: In Progress, 1: Success, -1: Failure, 2: Re-run
    CREATED_ON TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY NUMBER NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    DUPLICATE_REQUEST_BY NUMBER,
    DUPLICATE_REQUEST_ON TIMESTAMP,
    DUPLICATE_REQUEST_COUNT NUMBER DEFAULT 0
);