WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

-- Tables that will have seed data and use a sequence for the PK
-- start at 1000 to allow easy modelling of the seed data and
-- to help identify seed vs transactional data.
-- ACLs start at 10000, as there can be numerous roles
CREATE SEQUENCE PCM_USER_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ROLE_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ACL_SEQ
        INCREMENT BY 1
        START WITH 10000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_USER_ALERTS_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_SEARCH_FILTER_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_SOURCING_LANE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_RECORD_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_RECORD_RANGE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_RECORD_VALUE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_VALUE_DETAIL_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_REBATE_PROGRAM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_REBATE_ITEM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_REBATE_RULE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ASSIGNMENT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_SUPPLIER_ALLOCATION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_FORECAST_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_FORECAST_VALUE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_AUDIT_HISTORY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_ALERT_SUBSCRIPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_ALERT_SUBSCRIPTION_OPT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;      

CREATE  SEQUENCE PCM_ITEM_CATEGORY_CR_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE  SEQUENCE PCM_ITEM_CATEGORY_CRV_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_DEFECT_TYPE_SEQ
		INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;        

CREATE SEQUENCE PCM_EARULE_SEQ 
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ANALYTICS_RUN_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ANALYTICS_RESULT_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE MULTI_PURPOSE_USES_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        
CREATE SEQUENCE FG_LOB_SEQUENCE
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE PCM_APPLICATION_SETTINGS
(
    SETTING_NAME VARCHAR2(64) NOT NULL,
    SETTING_VALUE VARCHAR2(255),
    CONSTRAINT PCMAPPSET_PK PRIMARY KEY
        (SETTING_NAME) USING INDEX TABLESPACE AUDIT_INDEX           
);

CREATE TABLE PCM_ROLE
(
    ROLE_KEY NUMBER(19) NOT NULL,
    ROLE_ID VARCHAR2(50) NOT NULL,  
    ROLE_NAME VARCHAR2(50) NOT NULL,
    PERM_ROLE VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    BUSINESS_ENTITY_KEY NUMBER(19), 
    CONSTRAINT PCMROLE_PK PRIMARY KEY
        (ROLE_KEY) USING INDEX TABLESPACE AUDIT_INDEX,      
    CONSTRAINT PCMROLE_BE_FK FOREIGN KEY
         (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY)              
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX PCM_ROLE_ID_UIDX 
 ON PCM_ROLE(ROLE_ID)
  TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_ROLE_PREFS
(
    ROLE_KEY NUMBER(19) NOT NULL,
    PREF_NAME VARCHAR2(40) NOT NULL,
    PREF_VALUE VARCHAR2(512),
    CONSTRAINT PCMROLEP_FK FOREIGN KEY
         (ROLE_KEY) REFERENCES PCM_ROLE(ROLE_KEY)
         ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_USER
(
    USER_KEY NUMBER(19) NOT NULL,
    USER_ID VARCHAR2(60) NOT NULL,
    USER_NAME VARCHAR2(65),
    BUSINESS_ENTITY_KEY NUMBER(19),    
    CONTACT_KEY NUMBER(19),
    EMAIL_ADDRESS VARCHAR2(255),
    FOREIGN_ID VARCHAR2(255),
    ROLE_KEY NUMBER(19) NOT NULL,
    ENABLED_FLAG VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
    LAST_ACCESS_DATE TIMESTAMP,      
	FAVORITES CLOB,
    CONSTRAINT PCMUSER_PK PRIMARY KEY
        (USER_KEY) USING INDEX TABLESPACE AUDIT_INDEX,
    CONSTRAINT PCMUSER_ROLE_FK FOREIGN KEY
         (ROLE_KEY) REFERENCES PCM_ROLE(ROLE_KEY),
    CONSTRAINT PCMUSER_BUSINESS_FK FOREIGN KEY
         (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY),
    CONSTRAINT PCMUSER_CONTACT_FK FOREIGN KEY
         (CONTACT_KEY) REFERENCES CONTACT(CONTACT_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX PCMUSER_UID_U1
   ON PCM_USER(USER_ID) TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_USER_PREFS
(
    USER_KEY NUMBER(19) NOT NULL,
    PREF_NAME VARCHAR2(40) NOT NULL,
    PREF_VALUE VARCHAR2(512),
    CONSTRAINT PCMUSERP_FK FOREIGN KEY
         (USER_KEY) REFERENCES PCM_USER(USER_KEY)
         ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_USER_DELEGATE
(
   DELEGATE_KEY NUMBER(19) NOT NULL,   
   USER_KEY NUMBER(19) NOT NULL,   
   SITE_KEY NUMBER(19) NULL,
   DELEGATE_USER_ID VARCHAR2(60) NULL,
   DELEGATE_USER_KEY NUMBER(19) NULL,      
   RESPONSIBILITY VARCHAR2(36) NOT NULL,
   EFFECTIVE_FROM_DT DATE NULL,
   EFFECTIVE_TO_DT DATE NULL,
   CONSTRAINT PCM_DELEGATE_PK PRIMARY KEY(DELEGATE_KEY)
       USING INDEX TABLESPACE AUDIT_INDEX,
   CONSTRAINT PCM_DELEGATE_SITE_FK FOREIGN KEY(SITE_KEY)
       REFERENCES SITE ON DELETE SET NULL,
   CONSTRAINT PCM_DELEGATE_USER_FK FOREIGN KEY(USER_KEY)
       REFERENCES PCM_USER ON DELETE CASCADE                         
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_WORKFLOW
(
    WORKFLOW_KEY VARCHAR2(20) NOT NULL,
    WORKFLOW_NAME VARCHAR2(128) NOT NULL,
    WORKFLOW_GROUP VARCHAR2(50),
    WORKFLOW_PARENT_KEY VARCHAR2(20),
    WORKFLOW_URL VARCHAR2(512),
    DISPLAY_ORDER NUMBER(4) NOT NULL,
    WORKFLOW_URL_TARGET VARCHAR2(50),   
    CONSTRAINT PCMWORKFLOW_PK PRIMARY KEY
        (WORKFLOW_KEY) USING INDEX TABLESPACE AUDIT_INDEX,
    CONSTRAINT PCMWORKFLOW_PARENT_FK FOREIGN KEY
        (WORKFLOW_PARENT_KEY) REFERENCES PCM_WORKFLOW(WORKFLOW_KEY)
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ACCESS_CONTROL
(
     ACCESS_CONTROL_KEY NUMBER(19) NOT NULL,
     ENTITY_TYPE VARCHAR2(40) NOT NULL,
     ROLE_KEY NUMBER(19),
     USER_KEY NUMBER(19),     
     TARGET_ENTITY_KEY VARCHAR2(36),     
     ACL VARCHAR2(50) NOT NULL,
     CONSTRAINT PCMACL_PK PRIMARY KEY
        (ACCESS_CONTROL_KEY) USING INDEX TABLESPACE AUDIT_INDEX,     
     CONSTRAINT PCMACL_ROLE_FK FOREIGN KEY
         (ROLE_KEY) REFERENCES PCM_ROLE(ROLE_KEY),
     CONSTRAINT PCMACL_USER_FK FOREIGN KEY
         (USER_KEY) REFERENCES PCM_USER(USER_KEY)
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_SEARCH_FILTER
(
   SEARCH_FILTER_KEY NUMBER(19) NOT NULL,
   SEARCH_FILTER_NAME VARCHAR2(55) NOT NULL,
   IS_PUBLIC VARCHAR2(1) NOT NULL,
   CREATOR_USER_KEY NUMBER(19) NOT NULL,
   FILTER_TYPE VARCHAR2(128) NOT NULL,
   CONSTRAINT PCMSEARCH_FILTER_PK PRIMARY KEY(SEARCH_FILTER_KEY)
       USING INDEX TABLESPACE AUDIT_INDEX,
   CONSTRAINT PCMSEARCH_FILTER_CREATOR_FK FOREIGN KEY(CREATOR_USER_KEY)
       REFERENCES PCM_USER ON DELETE CASCADE 
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_SEARCH_FILTER_VALUE
(
    SEARCH_FILTER_KEY NUMBER(19) NOT NULL,
    SEARCH_FILTER_FIELD_NAME VARCHAR2(50) NOT NULL,
    SEARCH_FILTER_FIELD_TYPE VARCHAR2(50) NOT NULL,        
    SEARCH_FILTER_FIELD_VALUE VARCHAR2(4000) NOT NULL,
    CONSTRAINT PCMSEARCH_FILTER_VALUE_FK FOREIGN KEY(SEARCH_FILTER_KEY)
        REFERENCES PCM_SEARCH_FILTER(SEARCH_FILTER_KEY) ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_USER_ALERTS
(
    ALERT_KEY NUMBER(18) NOT NULL,
    ALERT_DATE DATE NOT NULL,
    ALERT_TITLE VARCHAR2(1024) NOT NULL,
    ALERT_URL VARCHAR2(512),
    ALERT_TARGET VARCHAR2(20),
    ALERT_FILTER VARCHAR2(512),
    CONSTRAINT PCMUSER_ALERT_PK PRIMARY KEY
        (ALERT_KEY) USING INDEX TABLESPACE AUDIT_INDEX         
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_SOURCING_LANE
(
    SOURCING_LANE_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_NAME VARCHAR2(512) NOT NULL,
    SOURCING_LANE_EXTERNAL_ID VARCHAR2(255) NULL,
    ITEM_KEY NUMBER(19) NOT NULL,
    SUPPLIER_KEY NUMBER(19),
    BOM_KEY NUMBER(19),
    FROM_SITE_KEY NUMBER(19),
    TO_SITE_KEY NUMBER(19),
    OWNER_KEY NUMBER(19),
    DATE_OFFSET NUMBER(10),
    PRODUCT_STATE VARCHAR2(32),
    CURRENCY_CODE VARCHAR2(3),
    SYSTEM_DERIVED VARCHAR2(1) DEFAULT 'N' NOT NULL,    
    ENDDATE_REQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DESCRIPTION VARCHAR2(1024),
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    COLLABORATION NUMBER(1),
    COST_PROV_BUSINESS_ENTITY VARCHAR2(255),
    CONSTRAINT PCMSL_SITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,
    CONSTRAINT PCMSL_SBE_FK FOREIGN KEY(SUPPLIER_KEY)
        REFERENCES BUSINESS_ENTITY,         
    CONSTRAINT PCMSL_BOM_FK FOREIGN KEY(BOM_KEY)
        REFERENCES BOM_HEADER,          
    CONSTRAINT PCMSL_USER_FK FOREIGN KEY (OWNER_KEY) 
        REFERENCES PCM_USER,
    CONSTRAINT PCMSL_FS_SITE_FK FOREIGN KEY (FROM_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSL_TS_SITE_FK FOREIGN KEY (TO_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSL_PK PRIMARY KEY(SOURCING_LANE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;

-- Natural Key
CREATE UNIQUE INDEX XSL_NK ON PCM_SOURCING_LANE(ITEM_KEY,SUPPLIER_KEY,
    BOM_KEY,FROM_SITE_KEY,TO_SITE_KEY,CURRENCY_CODE)
    TABLESPACE AUDIT_INDEX;
    
CREATE INDEX XSL_ITEM_N1 ON PCM_SOURCING_LANE(ITEM_KEY) 
    TABLESPACE AUDIT_INDEX;

CREATE INDEX XSL_STATUS_N2 ON PCM_SOURCING_LANE(STATUS) 
    TABLESPACE AUDIT_INDEX;

CREATE INDEX XSL_CURRENT_I1 ON PCM_SOURCING_LANE(CURRENT_FLAG) 
    TABLESPACE AUDIT_INDEX;
    
CREATE INDEX XSL_COLLAB_I2 ON PCM_SOURCING_LANE(COLLABORATION) 
    TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_COST_TYPE
(
   COST_TYPE_KEY VARCHAR2(32) NOT NULL,
   COST_TYPE_NAME VARCHAR2(64) NOT NULL,
   COST_TYPE_ORDER NUMBER(4),
   USE_IN_ROLLUP VARCHAR2(1) NOT NULL,
   ALLOW_MULTI_PROVIDER VARCHAR2(1) DEFAULT 'N' NOT NULL,
   USE_IN_ITEM_CATEGORY_COST VARCHAR2(1) DEFAULT 'N' NOT NULL,
   USE_SUPPLIER_IN_ROLLUP VARCHAR2(1) DEFAULT 'N' NOT NULL,
   CONSTRAINT PCMCT_PK PRIMARY KEY(COST_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                              
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_COST_ELEMENT
(
   COST_ELEMENT_KEY VARCHAR2(32) NOT NULL,
   COST_TYPE_KEY VARCHAR2(32) NOT NULL,
   COST_ELEMENT_NAME VARCHAR2(64) NOT NULL,
   COST_ELEMENT_VALUE_TYPE VARCHAR2(2) NOT NULL,
   COST_ELEMENT_ORDER NUMBER(4),
   COST_ELEMENT_TYPE VARCHAR2(32) NOT NULL,
   IS_REQUIRED NUMBER(1,0),
   CONSTRAINT PCMCE_COSTTYPE_FK FOREIGN KEY (COST_TYPE_KEY) 
        REFERENCES PCM_COST_TYPE,   
   CONSTRAINT PCMCE_PK PRIMARY KEY(COST_ELEMENT_KEY,COST_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX,
   CONSTRAINT PCMCE_CETYPE CHECK (COST_ELEMENT_TYPE in ('MATERIAL','TRANSFORMATION', 'FIXED'))
)  TABLESPACE AUDIT_DATA;


CREATE TABLE PCM_PRICING_SCENARIO
(
    PRICING_SCENARIO_KEY NUMBER(19) NOT NULL,
    PRICING_SCENARIO_NAME VARCHAR2(64) NOT NULL,    
    IS_RANGE_BASED NUMBER(1) DEFAULT 0 NOT NULL,    
    CONSTRAINT PCMPS_ISRANGE_BOOL CHECK (IS_RANGE_BASED in (0,1)),    
    CONSTRAINT PCMPS_PK PRIMARY KEY(PRICING_SCENARIO_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_COST_RECORD
(
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_EXTERNAL_ID VARCHAR2(255) NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_PROVIDER_KEY NUMBER(19) NULL,  
    DESCRIPTION VARCHAR2(1024) NULL,
    REASON_CODE VARCHAR2(128) NULL,
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),  
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP, 
    SYSTEM_ACTION VARCHAR2(1024),
    PRICING_SCENARIO_KEY NUMBER(19) NULL,
    PROJECT_NAME VARCHAR2(255), 
    CREATED_BY VARCHAR2(64) NULL,
    LAST_UPDATED_BY VARCHAR2(64) NULL,
    LAST_LOADED_BY_USER VARCHAR2(64) NULL,
    STRING_ATTRIBUTE1 VARCHAR2(1024),
    STRING_ATTRIBUTE2 VARCHAR2(1024),
    STRING_ATTRIBUTE3 VARCHAR2(1024),
    STRING_ATTRIBUTE4 VARCHAR2(1024),
    STRING_ATTRIBUTE5 VARCHAR2(1024),
    STRING_ATTRIBUTE6 VARCHAR2(1024),
    STRING_ATTRIBUTE7 VARCHAR2(1024),
    STRING_ATTRIBUTE8 VARCHAR2(1024),
    STRING_ATTRIBUTE9 VARCHAR2(1024),
    STRING_ATTRIBUTE10 VARCHAR2(1024),
    NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE,
    CONSTRAINT PCMCR_SLANE_FK FOREIGN KEY(SOURCING_LANE_KEY)
        REFERENCES PCM_SOURCING_LANE ON DELETE CASCADE,
    CONSTRAINT PCMCR_CTYPE_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT PCMCR_CPROV_BE_FK FOREIGN KEY(COST_PROVIDER_KEY)
        REFERENCES BUSINESS_ENTITY ON DELETE SET NULL,
    CONSTRAINT PCMCR_PS_FK FOREIGN KEY(PRICING_SCENARIO_KEY)
        REFERENCES PCM_PRICING_SCENARIO,
    CONSTRAINT PCMCR_PK PRIMARY KEY(COST_RECORD_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;

CREATE INDEX XCR_STATS_I1 ON PCM_COST_RECORD(STATUS)
  TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX XCR_EXTREF_U1 ON PCM_COST_RECORD(COST_RECORD_EXTERNAL_ID)
  TABLESPACE AUDIT_INDEX;

CREATE INDEX XCR_NK ON PCM_COST_RECORD(SOURCING_LANE_KEY,COST_TYPE_KEY,
    COST_PROVIDER_KEY,STATUS,EFFECTIVE_FROM_DT, EFFECTIVE_TO_DT)
  TABLESPACE AUDIT_INDEX;

CREATE INDEX XCR_CURRENT_I1 ON PCM_COST_RECORD(CURRENT_FLAG) 
    TABLESPACE AUDIT_INDEX;
  
    
CREATE TABLE PCM_COST_RECORD_RANGE
(
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    FROM_RANGE DECIMAL(19,4) NOT NULL,
    TO_RANGE DECIMAL(19,4),
    IS_ACTIVE NUMBER(1),
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    CONSTRAINT PCMCRRNG_ACTIVE_BOOL CHECK (IS_ACTIVE in (0,1)),
    CONSTRAINT PCMCRRNG_FRM_LT_TO CHECK (FROM_RANGE < TO_RANGE),
    CONSTRAINT PCMCRRNG_CR_FK FOREIGN KEY(COST_RECORD_KEY)
        REFERENCES PCM_COST_RECORD(COST_RECORD_KEY) ON DELETE CASCADE,
    CONSTRAINT PCMCRRNG_PK PRIMARY KEY(COST_RECORD_RANGE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;

CREATE INDEX XPCMCRRNG_N1 ON PCM_COST_RECORD_RANGE(COST_RECORD_KEY) TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_COST_RECORD_VALUE
(
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_ELEMENT_KEY VARCHAR2(32) NOT NULL,
    COST_VALUE DECIMAL(19,6) NOT NULL,
    COST_UOM VARCHAR2(6) NOT NULL,
    COST_VALUE_TYPE VARCHAR2(2) DEFAULT 'S' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,                 
    CONSTRAINT PCMCRV_CRRNG_FK FOREIGN KEY(COST_RECORD_RANGE_KEY)
        REFERENCES PCM_COST_RECORD_RANGE(COST_RECORD_RANGE_KEY) ON DELETE CASCADE,        
    CONSTRAINT PCMCRV_CELEMENT_FK FOREIGN KEY(COST_TYPE_KEY,COST_ELEMENT_KEY)
        REFERENCES PCM_COST_ELEMENT(COST_TYPE_KEY,COST_ELEMENT_KEY),        
    CONSTRAINT PCMCRV_PK PRIMARY KEY(COST_RECORD_VALUE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                              
)  TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX PCMCRV_CRRNG_UIDX on PCM_COST_RECORD_VALUE(
	COST_RECORD_RANGE_KEY,COST_ELEMENT_KEY)
	TABLESPACE AUDIT_INDEX;
	
CREATE INDEX XCRVALUE_RANGE ON PCM_COST_RECORD_VALUE(
   COST_RECORD_RANGE_KEY,COST_VALUE)
   TABLESPACE AUDIT_INDEX;
   
CREATE TABLE PCM_COST_VALUE_DETAIL
(
    COST_VALUE_DETAIL_KEY NUMBER(19) NOT NULL,
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_VALUE_NAME VARCHAR2(32) NOT NULL,
    COST_VALUE_VALUE DECIMAL(19,6) NOT NULL,
    COST_VALUE_BLEND DECIMAL(6,3) NOT NULL,
    CONSTRAINT PCMCVD_CRV_FK FOREIGN KEY(COST_RECORD_VALUE_KEY)
        REFERENCES PCM_COST_RECORD_VALUE ON DELETE CASCADE,
    CONSTRAINT PCMCVD_PK PRIMARY KEY(COST_VALUE_DETAIL_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                               
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_REBATE_PROGRAM
(
    REBATE_PROGRAM_KEY NUMBER(19) NOT NULL,
    REBATE_NAME VARCHAR2(255) NOT NULL,
    REBATE_TYPE VARCHAR2(255) NULL,
    REBATE_BUSINESS_ENTITY_KEY NUMBER(19) NOT NULL,
    REBATE_EXTERNAL_ID VARCHAR2(255) NULL,
    REBATE_DESCRIPTION VARCHAR2(1024) NULL, 
    CONFIDENCE_FACTOR DECIMAL(6,3),
    PROGRAM_OWNER VARCHAR2(64),
    FINANCIAL_PROGRAM_OWNER VARCHAR2(64),
    PAYMENT_TYPE VARCHAR2(32),
    PROGRAM_TYPE VARCHAR2(32),
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64), 
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,             
    CONSTRAINT PCMRP_BE_FK FOREIGN KEY(REBATE_BUSINESS_ENTITY_KEY)
        REFERENCES BUSINESS_ENTITY,
    CONSTRAINT PCMRP_PK PRIMARY KEY(REBATE_PROGRAM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPCMRB_U1 ON PCM_REBATE_PROGRAM(
   REBATE_NAME)
   TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_REBATE_ITEM
(
    REBATE_ITEM_KEY NUMBER(19) NOT NULL,
    REBATE_PROGRAM_KEY NUMBER(19) NOT NULL,
    ITEM_KEY NUMBER(19) NULL,
    REBATE_AMOUNT DECIMAL(19,6) NOT NULL,
    EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
    CONSTRAINT PCMRI_RP_FK FOREIGN KEY(REBATE_PROGRAM_KEY)
        REFERENCES PCM_REBATE_PROGRAM ON DELETE CASCADE,    
    CONSTRAINT PCMRI_ITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,
    CONSTRAINT PCMRI_PK PRIMARY KEY(REBATE_ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;   
        
CREATE TABLE PCM_REBATE_RULE
(
    REBATE_RULE_KEY NUMBER(19) NOT NULL,
    REBATE_PROGRAM_KEY NUMBER(19) NOT NULL,
    REBATE_RULE_ID VARCHAR2(36) NULL,
    USE_BOM VARCHAR2(1) DEFAULT 'N' NOT NULL,   
    CONSTRAINT PCMRR_RP_FK FOREIGN KEY(REBATE_PROGRAM_KEY)
        REFERENCES PCM_REBATE_PROGRAM  ON DELETE CASCADE,
    CONSTRAINT PCMRR_PK PRIMARY KEY(REBATE_RULE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XREBATE_RULE_NK ON PCM_REBATE_RULE(REBATE_PROGRAM_KEY,
    REBATE_RULE_ID)
    TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_REBATE_RULE_ITEM
(
    REBATE_RULE_KEY NUMBER(19) NOT NULL,    
    ITEM_KEY NUMBER(19) NOT NULL,
    CONSTRAINT PCMRRI_RR_FK FOREIGN KEY(REBATE_RULE_KEY)
        REFERENCES PCM_REBATE_RULE,
    CONSTRAINT PCMRRI_ITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,     
    CONSTRAINT PCMRRI_PK PRIMARY KEY(REBATE_RULE_KEY,ITEM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_REBATE_RULE_PLATFORM
(
    REBATE_RULE_KEY NUMBER(19) NOT NULL,    
    ITEM_PLATFORM_KEY NUMBER(19) NOT NULL,
    CONSTRAINT PCMRRP_RR_FK FOREIGN KEY(REBATE_RULE_KEY)
        REFERENCES PCM_REBATE_RULE,
    CONSTRAINT PCMRRP_PLATFORM_FK FOREIGN KEY(ITEM_PLATFORM_KEY)
        REFERENCES ITEM_PLATFORM,       
    CONSTRAINT PCMRRP_PK PRIMARY KEY(REBATE_RULE_KEY,ITEM_PLATFORM_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_REBATE_RULE_CATEGORY
(
    REBATE_RULE_KEY NUMBER(19) NOT NULL,    
    ITEM_CATEGORY_KEY NUMBER(19) NOT NULL,
    CONSTRAINT PCMRRC_RR_FK FOREIGN KEY(REBATE_RULE_KEY)
        REFERENCES PCM_REBATE_RULE,
    CONSTRAINT PCMRRC_PLATFORM_FK FOREIGN KEY(ITEM_CATEGORY_KEY)
        REFERENCES ITEM_CATEGORY,       
    CONSTRAINT PCMRRC_PK PRIMARY KEY(REBATE_RULE_KEY,ITEM_CATEGORY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;
      
CREATE TABLE PCM_RESPONSIBILITY
(
   RESPONSIBILITY_KEY VARCHAR2(32) NOT NULL,
   RESPONSIBILITY_NAME VARCHAR2(64) NOT NULL,
   RESPONSIBILITY_ORDER NUMBER(4),
   RESPONSIBILITY_TYPE VARCHAR2(2) NOT NULL,
   CONSTRAINT PCMR_PK PRIMARY KEY(RESPONSIBILITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                       
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ROLE_RESPONSIBILITY
(
   ROLE_KEY NUMBER(19) NOT NULL,
   RESPONSIBILITY_KEY VARCHAR2(32) NOT NULL,
   CONSTRAINT PCMROLERRESP_PK PRIMARY KEY(ROLE_KEY,RESPONSIBILITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX, 
   CONSTRAINT PCM_ROLE_RESP_ROLE_FK FOREIGN KEY(ROLE_KEY)
       REFERENCES PCM_ROLE ON DELETE CASCADE,
   CONSTRAINT PCM_ROLE_RESP_RESP_FK FOREIGN KEY(RESPONSIBILITY_KEY)
       REFERENCES PCM_RESPONSIBILITY ON DELETE CASCADE
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ASSIGNMENT
(
   ASSIGNMENT_KEY NUMBER(19) NOT NULL,   
   ASSIGNMENT_TYPE VARCHAR2(2) NOT NULL,
   USER_ID VARCHAR2(60) NULL,
   OBJECT_KEY NUMBER(19) NOT NULL,
   ASSIGNMENT_CODE VARCHAR2(32),
   SITE_KEY NUMBER(19) NULL,
   RESPONSIBILITY VARCHAR2(36) NOT NULL,
   EFFECTIVE_FROM_DT DATE NULL,
   EFFECTIVE_TO_DT DATE NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
   REGION VARCHAR2(255) NULL,
   CONSTRAINT PCM_ASSIGNMENT_PK PRIMARY KEY(ASSIGNMENT_KEY)
       USING INDEX TABLESPACE AUDIT_INDEX,
   CONSTRAINT PCM_ASSIGNMENT_SITE_FK FOREIGN KEY(SITE_KEY)
       REFERENCES SITE ON DELETE SET NULL,
   CONSTRAINT PCM_ASSIGNMENT_RESP_FK FOREIGN KEY(RESPONSIBILITY)
       REFERENCES PCM_RESPONSIBILITY (RESPONSIBILITY_KEY)
) TABLESPACE AUDIT_DATA;
    
CREATE UNIQUE INDEX XASSIGN_NK ON PCM_ASSIGNMENT(ASSIGNMENT_TYPE,
    USER_ID,OBJECT_KEY,RESPONSIBILITY,SITE_KEY)
    TABLESPACE AUDIT_INDEX; 
    
CREATE INDEX XASSIGN_USER_RESP_I1 ON PCM_ASSIGNMENT(USER_ID,RESPONSIBILITY)
    TABLESPACE AUDIT_INDEX; 

CREATE INDEX XASSIGN_OBJKEY_I1 ON PCM_ASSIGNMENT 
	(OBJECT_KEY, RESPONSIBILITY, ASSIGNMENT_TYPE)
	TABLESPACE AUDIT_INDEX;
    
CREATE  INDEX XASSIGN_ITMOWN_I2 ON PCM_ASSIGNMENT
	(OBJECT_KEY,RESPONSIBILITY,ASSIGNMENT_TYPE,USER_ID)
    TABLESPACE AUDIT_INDEX; 


CREATE TABLE PCM_ENTITY_ACTION_RULE 
    ( 
     RULE_KEY NUMBER (19)  NOT NULL , 
     RULE_TYPE VARCHAR2 (50 BYTE)  NOT NULL , 
     ENTITY_TYPE VARCHAR2 (40 BYTE)  NOT NULL , 
     TARGET_ENTITY_KEY VARCHAR2 (32) , 
     ACTN VARCHAR2 (50 BYTE)  NOT NULL , 
     ACTIVE NUMBER (1)  NOT NULL , 
     ITEM_CATEGORY_KEY NUMBER (19) , 
     NUM_DAYS NUMBER (5) , 
     RESPONSIBILITY_KEY VARCHAR2 (32) , 
     ROLE_KEY NUMBER (19),
     STATE VARCHAR2 (50),
     ALLOW NUMBER(1)
    ) 
    TABLESPACE AUDIT_DATA;



COMMENT ON COLUMN PCM_ENTITY_ACTION_RULE.ACTN IS 'Action' 
;

ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_PK PRIMARY KEY ( RULE_KEY ) ;

ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_ITM_CAT_FK FOREIGN KEY 
    ( 
     ITEM_CATEGORY_KEY
    ) 
    REFERENCES ITEM_CATEGORY 
    ( 
     ITEM_CATEGORY_KEY
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_PCM_RESP_FK FOREIGN KEY 
    ( 
     RESPONSIBILITY_KEY
    ) 
    REFERENCES PCM_RESPONSIBILITY 
    ( 
     RESPONSIBILITY_KEY
    ) 
    ON DELETE CASCADE
    NOT DEFERRABLE 
;


ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_PCM_ROLE_FK FOREIGN KEY 
    ( 
     ROLE_KEY
    ) 
    REFERENCES PCM_ROLE 
    ( 
     ROLE_KEY
    )
    ON DELETE CASCADE
    NOT DEFERRABLE 
;

CREATE TABLE PCM_SUPPLIER_ALLOCATION
(
   SUPPLIER_ALLOCATION_KEY NUMBER(19) NOT NULL,
   DESCRIPTION VARCHAR2(1024) NULL,
   SUPPLIER_ALLOCATION_COMMENT VARCHAR2(255) NULL,
   CUSTOMER_ITEM_GROUP_ITEM_KEY NUMBER(19) NULL,
   CUSTOMER_ITEM_KEY NUMBER(19) NULL,
   CUSTOMER_SITE_KEY NUMBER(19) NULL,
   SUPPLIER_ITEM_KEY NUMBER(19) NULL,
   SUPPLIER_BUSINESS_ENTITY_KEY NUMBER(19) NULL,
   SUPPLIER_SITE_KEY NUMBER(19) NULL,
   ALLOCATION NUMBER(19,2) NULL,
   DATA_SOURCE VARCHAR2(255) NOT NULL,
   STATUS VARCHAR2(40) NOT NULL,
   STATUS_CHANGE_DATE TIMESTAMP,    
   STATUS_LAST_CHANGE_BY VARCHAR2(64),     
   INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   UPDATE_DT TIMESTAMP NULL,
   EFFECTIVE_FROM_DT DATE NULL,
   EFFECTIVE_TO_DT DATE NULL,
   DELETE_FLAG VARCHAR2(1) NULL,
   CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   CONTEXT_OBJECT_TYPE VARCHAR2(50),
   CONTEXT_OBJECT_ID   NUMBER(19,0),
   DESTINATION_SITE_KEY NUMBER(19),
   CONSTRAINT PCMSA_CGITEM_FK FOREIGN KEY(CUSTOMER_ITEM_GROUP_ITEM_KEY)
       REFERENCES ITEM_MASTER,
   CONSTRAINT PCMSA_CITEM_FK FOREIGN KEY(CUSTOMER_ITEM_KEY)
       REFERENCES ITEM_MASTER,
   CONSTRAINT PCMSA_CSITE_FK FOREIGN KEY (CUSTOMER_SITE_KEY)
        REFERENCES SITE,
   CONSTRAINT PCMSA_SITEM_FK FOREIGN KEY(SUPPLIER_ITEM_KEY)
       REFERENCES ITEM_MASTER,
   CONSTRAINT PCMSA_SBUSINESS_FK FOREIGN KEY(SUPPLIER_BUSINESS_ENTITY_KEY)
       REFERENCES BUSINESS_ENTITY,
   CONSTRAINT PCMSA_SSITE_FK FOREIGN KEY (SUPPLIER_SITE_KEY)
        REFERENCES SITE,
   CONSTRAINT PCMSA_DSITE_FK FOREIGN KEY (DESTINATION_SITE_KEY)
        REFERENCES SITE,
   CONSTRAINT PCMSA_PK PRIMARY KEY(SUPPLIER_ALLOCATION_KEY)
) TABLESPACE AUDIT_DATA;

-- For Making Supplier Allocation Load Faster    
CREATE INDEX IND_CUST_ITEM_KEY ON PCM_SUPPLIER_ALLOCATION (CUSTOMER_ITEM_KEY) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XSA_U1
    ON PCM_SUPPLIER_ALLOCATION(CUSTOMER_ITEM_GROUP_ITEM_KEY ASC,
    CUSTOMER_ITEM_KEY ASC,SUPPLIER_ITEM_KEY ASC,
    SUPPLIER_BUSINESS_ENTITY_KEY ASC,CUSTOMER_SITE_KEY ASC,SUPPLIER_SITE_KEY ASC,DESTINATION_SITE_KEY ASC,
    EFFECTIVE_FROM_DT ASC,EFFECTIVE_TO_DT ASC,CONTEXT_OBJECT_TYPE ASC,CONTEXT_OBJECT_ID ASC)
 TABLESPACE AUDIT_INDEX;


CREATE TABLE PCM_FORECAST
(
   FORECAST_KEY NUMBER(19) NOT NULL,
   FORECAST_EXTERNAL_ID VARCHAR2(64) NULL,
   DESCRIPTION VARCHAR2(1024) NULL,
   ITEM_KEY NUMBER(19) NOT NULL,
   SITE_KEY NUMBER(19) NULL,
   FORECAST_TYPE VARCHAR2(64) NOT NULL,
   PERIOD_TYPE VARCHAR2(32) NOT NULL,
   CALENDAR_NAME VARCHAR2(32) NOT NULL,
   PERIODIC_ADJUST_TYPE VARCHAR2(32) NULL,   
   PERIODIC_ADJUST_AMOUNT NUMBER(19,6) NULL,
   CONFIDENCE_FACTOR NUMBER(6,3) NULL,
   REMAINING_ROLLOVERS NUMBER(2,0) NULL,
   STATUS VARCHAR2(40) NOT NULL,
   STATUS_CHANGE_DATE TIMESTAMP,    
   STATUS_LAST_CHANGE_BY VARCHAR2(64),     
   INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   UPDATE_DT TIMESTAMP NULL,
   EFFECTIVE_FROM_DT DATE NULL,
   EFFECTIVE_TO_DT DATE NULL,
   DELETE_FLAG VARCHAR2(1) NULL,
   CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   LAST_ROLLOVER_START_DATE DATE,
   SOURCE_FORECAST_KEY NUMBER(19) NULL,
   FORECAST_ORIGIN_EXTERNAL_ID VARCHAR2(64) NULL,
   FORECAST_MODEL VARCHAR2(64) NOT NULL,
   LAST_CHANGE_BY VARCHAR2(64) NULL,
   LAST_LOADED_BY_USER VARCHAR2(64) NULL,
   STRING_ATTRIBUTE1 VARCHAR2(1024),
    STRING_ATTRIBUTE2 VARCHAR2(1024),
    STRING_ATTRIBUTE3 VARCHAR2(1024),
    STRING_ATTRIBUTE4 VARCHAR2(1024),
    STRING_ATTRIBUTE5 VARCHAR2(1024),
    STRING_ATTRIBUTE6 VARCHAR2(1024),
    STRING_ATTRIBUTE7 VARCHAR2(1024),
    STRING_ATTRIBUTE8 VARCHAR2(1024),
    STRING_ATTRIBUTE9 VARCHAR2(1024),
    STRING_ATTRIBUTE10 VARCHAR2(1024),
    NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE,
   CONSTRAINT PCMF_ITEM_FK FOREIGN KEY(ITEM_KEY)
       REFERENCES ITEM_MASTER,
   CONSTRAINT PCMF_SITE_FK FOREIGN KEY (SITE_KEY)
        REFERENCES SITE,
   CONSTRAINT PCMF_PK PRIMARY KEY(FORECAST_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XFOR_U1 
	ON PCM_FORECAST(FORECAST_EXTERNAL_ID)
  TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX XFOR_U2
	ON PCM_FORECAST(ITEM_KEY, SITE_KEY, FORECAST_TYPE, FORECAST_MODEL)
	TABLESPACE AUDIT_INDEX;

CREATE INDEX XFOR_I1
	ON PCM_FORECAST(ITEM_KEY,FORECAST_TYPE)
	TABLESPACE AUDIT_INDEX;
	
CREATE INDEX XFOR_I2
	ON PCM_FORECAST(CURRENT_FLAG,FORECAST_MODEL,FORECAST_TYPE,STATUS)
	TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_FORECAST_VALUE
(
   FORECAST_VALUE_KEY NUMBER(19) NOT NULL,
   FORECAST_KEY NUMBER(19) NOT NULL,   
   FORECAST_VALUE DECIMAL(19,6) NULL,
   FORECAST_UOM VARCHAR2(6) NULL,
   FORECAST_MEASURE_KEY VARCHAR2(64) NOT NULL,
   EFFECTIVE_FROM_DT DATE NOT NULL,
   EFFECTIVE_TO_DT DATE NULL,   
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   ADJUSTABLE_VALUE DECIMAL(19,6) NULL,
   FORECAST_VALUE_TYPE VARCHAR2(1) NOT NULL,
   SAVED_STATES VARCHAR2(1024),
   CONSTRAINT PCMFV_F_FK FOREIGN KEY(FORECAST_KEY)
       REFERENCES PCM_FORECAST ON DELETE CASCADE,   
   CONSTRAINT PCMFV_PK PRIMARY KEY(FORECAST_VALUE_KEY)
) TABLESPACE AUDIT_DATA;    

CREATE UNIQUE INDEX XFORVAL_U1 
  ON PCM_FORECAST_VALUE(FORECAST_KEY, FORECAST_VALUE_TYPE, FORECAST_MEASURE_KEY, EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_FORECAST_VALUE_ADJUSTMENT
(
    FORECAST_VALUE_KEY NUMBER(19) NOT NULL,
    ADJUSTMENT_AMOUNT NUMBER(19,6),
    ADJUSTMENT_TYPE VARCHAR2(32),
    CONSTRAINT PCMFA_FV_FK FOREIGN KEY(FORECAST_VALUE_KEY)
       REFERENCES PCM_FORECAST_VALUE ON DELETE CASCADE,
    CONSTRAINT PCMFA_PK PRIMARY KEY(FORECAST_VALUE_KEY)
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_FORECAST_VALUE_ARCHIVE
(
   FORECAST_VALUE_KEY NUMBER(19) NOT NULL,
   FORECAST_KEY NUMBER(19) NOT NULL,
   FORECAST_VALUE DECIMAL(19,6) NULL,
   FORECAST_UOM VARCHAR2(6) NULL,
   FORECAST_MEASURE_KEY VARCHAR2(64) NOT NULL,
   EFFECTIVE_FROM_DT DATE NOT NULL,
   EFFECTIVE_TO_DT DATE NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   CONSTRAINT PCMFVA_F_FK FOREIGN KEY(FORECAST_KEY)
       REFERENCES PCM_FORECAST ON DELETE CASCADE,
   CONSTRAINT PCMFVA_PK PRIMARY KEY(FORECAST_VALUE_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XFORVALAR_U1 
  ON PCM_FORECAST_VALUE_ARCHIVE(FORECAST_KEY, FORECAST_MEASURE_KEY, EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_FORECAST_AUTO_APPROVE_CAT
(
  ITEM_CATEGORY_KEY NUMBER(19) NOT NULL,
  WAIT_DAYS NUMBER(3) NOT NULL,
  ACTIVE NUMBER(1),
  CONSTRAINT PCMFVAABC_PK PRIMARY KEY(ITEM_CATEGORY_KEY),
  CONSTRAINT PCMFVAABC_IC_FK FOREIGN KEY(ITEM_CATEGORY_KEY)
       REFERENCES ITEM_CATEGORY ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_AUDIT_HISTORY
(
   AUDIT_RECORD_KEY VARCHAR2(32) NOT NULL,
   ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   ACTION_PERFORMED VARCHAR2(512) NOT NULL,
   ACTION_ORDER NUMBER(19) NULL,   
   USER_ID VARCHAR2(100) NOT NULL,
   ROLE_ID VARCHAR2(50) NULL,
   PCM_TARGET_TYPE VARCHAR2(255) NOT NULL,
   PCM_SUB_TARGET_KEY VARCHAR2(36) NULL,   
   PCM_SUB_TARGET_TYPE VARCHAR2(255) NULL,
   ACTION_COMMENT VARCHAR2(1024) NULL,
   LAST_LOADED_BY_USER VARCHAR2(64) NULL,
   CONSTRAINT PCMAH_PK PRIMARY KEY(AUDIT_RECORD_KEY)
) TABLESPACE AUDIT_DATA;

CREATE INDEX XPAH_I1 
  ON PCM_AUDIT_HISTORY(PCM_TARGET_TYPE)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_AUDIT_HISTORY_TARGETS
(
   AUDIT_RECORD_KEY VARCHAR2(32) NOT NULL,
   PCM_TARGET_KEY VARCHAR2(36) NOT NULL,
   CONSTRAINT PCMAHT_PCMAHT_FK FOREIGN KEY(AUDIT_RECORD_KEY)
       REFERENCES PCM_AUDIT_HISTORY ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPAHT_U1 
  ON PCM_AUDIT_HISTORY_TARGETS(AUDIT_RECORD_KEY,PCM_TARGET_KEY)
  TABLESPACE AUDIT_INDEX;


CREATE TABLE ITEM_MASTER_EXTRACT (
ITEM_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGE_DT TIMESTAMP
);
  
create or replace TRIGGER T_DELTA_ITEM_CHANGE
	AFTER INSERT OR UPDATE ON ITEM_MASTER
	FOR EACH ROW
DECLARE
	v_item_key item_master.item_key%TYPE;
BEGIN
	v_item_key := :new.item_key; 
	ITEM_CHANGE_INSERT_PROC(v_item_key);	
END DELTA_ITEM_CHANGE;
/

CREATE TRIGGER T_PCM_AUDIT_HISTORY_ORDER
	BEFORE INSERT ON PCM_AUDIT_HISTORY
	FOR EACH ROW
BEGIN
	SELECT PCM_AUDIT_HISTORY_SEQ.NEXTVAL INTO :NEW.ACTION_ORDER FROM DUAL;
END;
/

CREATE TABLE PCM_EXTRACT_KEY
(
	OBJECT_KEY NUMBER(19) NOT NULL,
	OBJECT_TYPE VARCHAR2(32) NOT NULL,
	OBJECT_LAST_CHANGED_ON TIMESTAMP (6)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPEK_U1 
  ON PCM_EXTRACT_KEY(OBJECT_KEY, OBJECT_TYPE)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_ALERT_SUBSCRIPTION
(
	SUBSCRIPTION_KEY NUMBER(19) NOT NULL,
	ALERT_TYPE VARCHAR2(255) NOT NULL,
	USER_KEY NUMBER(19) NOT NULL,
	SUBSCRIBE_FLAG NUMBER(1),
	CONSTRAINT PCMAS_U_FK FOREIGN KEY(USER_KEY)
       REFERENCES PCM_USER ON DELETE CASCADE,
    CONSTRAINT PCMAS_PK PRIMARY KEY(SUBSCRIPTION_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPAS_U1 
  ON PCM_ALERT_SUBSCRIPTION(ALERT_TYPE, USER_KEY)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_ALERT_SUBSCRIPTION_OPTIONS
(
	OPTION_KEY NUMBER(19) NOT NULL,
	SUBSCRIPTION_KEY NUMBER(19) NOT NULL,
	OPTION_ID VARCHAR2(255) NOT NULL,
	OPTION_VALUE VARCHAR2(1024),
	CONSTRAINT PCMASO_AS_FK FOREIGN KEY(SUBSCRIPTION_KEY)
       REFERENCES PCM_ALERT_SUBSCRIPTION ON DELETE CASCADE,
	CONSTRAINT PCMASO_PK PRIMARY KEY(OPTION_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPASO_U1 
  ON PCM_ALERT_SUBSCRIPTION_OPTIONS(SUBSCRIPTION_KEY, OPTION_ID, OPTION_VALUE)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_ITEM_CATEGORY_COST_RECORD
(
	ITEM_CATEGORY_COST_RECORD_KEY NUMBER(19) NOT NULL,
	ITEM_CATEGORY_KEY NUMBER(19) NOT NULL,
	CONTEXT_OBJECT_TYPE VARCHAR2(50),
   	CONTEXT_OBJECT_ID NUMBER(19,0),
   	DESCRIPTION VARCHAR2(1024),
	INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
	CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
	DELETE_FLAG VARCHAR2(1) NULL,
	CONSTRAINT PCMICCR_IC_FK FOREIGN KEY(ITEM_CATEGORY_KEY)
        REFERENCES ITEM_CATEGORY,
    CONSTRAINT PCMICCR_PK PRIMARY KEY(ITEM_CATEGORY_COST_RECORD_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPCMICCR_U1
    ON PCM_ITEM_CATEGORY_COST_RECORD(ITEM_CATEGORY_KEY, CONTEXT_OBJECT_TYPE, CONTEXT_OBJECT_ID)
    TABLESPACE AUDIT_INDEX;
    
CREATE TABLE PCM_ITEM_CATEGORY_CRV
(
	ITEM_CATEGORY_CRV_KEY NUMBER(19) NOT NULL,
	ITEM_CATEGORY_COST_RECORD_KEY NUMBER(19) NOT NULL,
	COST_TYPE_KEY VARCHAR(32) NOT NULL,
	COST_VALUE DECIMAL(19,6) NOT NULL,
	EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
	CONSTRAINT PCMICCRV_ICCR_FK FOREIGN KEY(ITEM_CATEGORY_COST_RECORD_KEY)
        REFERENCES PCM_ITEM_CATEGORY_COST_RECORD,
    CONSTRAINT PCMICCRV_CTYPE_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT PCMICCRV_PK PRIMARY KEY(ITEM_CATEGORY_CRV_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPCMICCRV_U1 
  ON PCM_ITEM_CATEGORY_CRV(ITEM_CATEGORY_COST_RECORD_KEY,COST_TYPE_KEY,EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_DEFECT_TYPE
(
	DEFECT_TYPE_KEY NUMBER(19) NOT NULL,
	DEFECT_NAME VARCHAR2(64) NOT NULL
) TABLESPACE AUDIT_DATA;


ALTER TABLE PCM_DEFECT_TYPE
	ADD CONSTRAINT PCMDT_PK PRIMARY KEY(DEFECT_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX;
        
CREATE UNIQUE INDEX PCMDT_NAME_UIDX on PCM_DEFECT_TYPE(DEFECT_NAME)
    TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
(
	BOM_LINE_ITEM_KEY NUMBER(19) NOT NULL,
	ITEM_KEY NUMBER(19) NOT NULL,
	DEFECT_TYPE_KEY NUMBER(19) NOT NULL,
	ATTRITION_RATE NUMBER(19,4)
) TABLESPACE AUDIT_DATA;

ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_PK PRIMARY KEY(BOM_LINE_ITEM_KEY,ITEM_KEY,DEFECT_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX;

ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_BLI_FK FOREIGN KEY(BOM_LINE_ITEM_KEY)
        REFERENCES BOM_LINE_ITEM ON DELETE CASCADE;
        
ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_ITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER;
        
ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_PCMDT_FK FOREIGN KEY(DEFECT_TYPE_KEY)
        REFERENCES PCM_DEFECT_TYPE;
        
CREATE TABLE PCM_JOB_STATUS_CONTROL
(
  JOB_ID VARCHAR2(32) NOT NULL,
  JOB_TYPE VARCHAR2(32),
  JOB_STATUS VARCHAR2(32) NOT NULL,
  JOB_START_DATE TIMESTAMP NOT NULL,
  JOB_END_DATE TIMESTAMP,
  CONSTRAINT XJSC_1_PK PRIMARY KEY (JOB_ID)
	USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ANALYTICS_RUN
  (
    RUN_ID NUMBER(19,0) NOT NULL,
    STARTED_AT TIMESTAMP (6) NOT NULL,
    ENDED_AT TIMESTAMP (6),
    ANALYTICS_TYPE VARCHAR2(50) NOT NULL,
    CONSTRAINT XANARUN_PK PRIMARY KEY (RUN_ID) USING INDEX TABLESPACE AUDIT_INDEX
  ) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ANALYTICS_RESULT
  (
    RESULT_ID        NUMBER(19,0) NOT NULL,
    ANALYTICS_RUN_ID NUMBER(19,0) NOT NULL,
    ANALYTICS_RESULT_TYPE VARCHAR2(50) NOT NULL,
    STRINGCOL1       VARCHAR2(255),
    STRINGCOL2       VARCHAR2(255),
    STRINGCOL3       VARCHAR2(255),
    STRINGCOL4       VARCHAR2(255),
    NUMCOL1          NUMBER(19,6),
    NUMCOL2          NUMBER(19,6),
    NUMCOL3          NUMBER(19,6),
    NUMCOL4          NUMBER(19,6),
    DATECOL1 TIMESTAMP (6),
    DATECOL2 TIMESTAMP (6),
    DATECOL3 TIMESTAMP (6),
    DATECOL4 TIMESTAMP (6),
    SERIALIZATION_TYPE VARCHAR2(50),
    SERIALIZED_RESULT BLOB,
    CONSTRAINT XANARES_PK PRIMARY KEY (RESULT_ID) USING INDEX TABLESPACE AUDIT_INDEX
  ) TABLESPACE AUDIT_DATA;

ALTER TABLE PCM_ANALYTICS_RESULT
  ADD CONSTRAINT ANARES_ANARUN_FK FOREIGN KEY(ANALYTICS_RUN_ID) 
  	REFERENCES PCM_ANALYTICS_RUN ON DELETE CASCADE; 
  
create function calculateExpression(expr in varchar) return number
as
        sql_stmt varchar(2000);
        rslt number;
begin
        sql_stmt := 'select ' || expr || ' from dual';
        execute immediate sql_stmt into rslt;
        return rslt;
end;
/

CREATE OR REPLACE FUNCTION concatValues(stmt IN SYS_REFCURSOR, delim IN VARCHAR, maxlen IN NUMBER) RETURN VARCHAR
AS
  v_rslt VARCHAR2(16000);
  v_next VARCHAR2(16000);
  v_end VARCHAR2(3) := '...';
  v_maxvarchar NUMBER := 16000;
  v_length NUMBER := 0;
BEGIN
  IF maxlen > v_maxvarchar THEN
     RAISE_APPLICATION_ERROR(-20000,'max length cannot be greater than ' || v_maxvarchar);
  END IF;

  LOOP
    FETCH stmt INTO v_next;
    EXIT WHEN stmt%NOTFOUND;

    IF v_length = 0 THEN
      v_rslt := v_next;
    ELSE
      IF (v_length + LENGTH(delim) + NVL(LENGTH(v_next),0) > v_maxvarchar) THEN
        v_rslt := SUBSTR(v_rslt||delim||v_next,0,v_maxvarchar - LENGTH(v_end))||v_end;
        EXIT;
      ELSE
        v_rslt := v_rslt||delim||v_next;
      END IF;
    END IF;
    
    v_length := LENGTH(v_rslt);

    IF v_length > maxlen THEN
      IF LENGTH(SUBSTR(v_rslt,0,maxlen) || v_end) > v_maxvarchar THEN
        v_rslt := SUBSTR(v_rslt,0,v_maxvarchar - LENGTH(v_end))||v_end;
      ELSE
        v_rslt := SUBSTR(v_rslt,0,maxlen) || v_end;
      END IF;
      EXIT;
    END IF;
  END LOOP;

  RETURN v_rslt;
END;
/

create table COMMODITY_PROFILE
(
	PROFILE_ID Number(19,0) NOT NULL,
	PROFILE_NAME varchar2(255) NOT NULL,
	COMPANY_ITEM_TYPE varchar2(255) NOT NULL,
	INCLUDE_EXCLUDE_COST_RECORD varchar2(255),
	INCLUDE_EXCLUDE_COST_FORECAST varchar2(255),
	INCLUDE_EXCLUDE_REBATE varchar2(255),
	INCLUDE_EXCLUDE_ITEM varchar2(255),
	INCLUDE_EXCLUDE_BOM varchar2(255),
	ITEM_CATEGORY_KEY Number(19,0),
	INCLUDE_EXCLUDE_TAM varchar2(255),
	INCLUDE_EXCLUDE_PRICE_TAM VARCHAR2(255),
	CONSTRAINT profileid_pk PRIMARY KEY (PROFILE_ID) USING INDEX TABLESPACE AUDIT_INDEX	,
	CONSTRAINT ITEM_CATEGORY_FK FOREIGN KEY (ITEM_CATEGORY_KEY) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_KEY)
);

create table USER_COMMODITYPROFILE_MAPPING
(
	USER_KEY Number(19,0) NOT NULL,
	PROFILE_NAME varchar2(255) NOT NULL,
	CONSTRAINT USER_PROFILE_PK PRIMARY KEY (USER_KEY, PROFILE_NAME)
);


create table PCM_REGIONAL_REGION_MAP
(
	REGION_ID Number(19,0) NOT NULL,
	ASSIGNMENT_KEY Number(19,0) NOT NULL,
    SITE_KEY Number(19,0) NOT NULL,
	CONSTRAINT riogionId_pk PRIMARY KEY (REGION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
	CONSTRAINT ASSIGNMENT_KEY FOREIGN KEY (ASSIGNMENT_KEY) REFERENCES PCM_ASSIGNMENT(ASSIGNMENT_KEY),
    CONSTRAINT SITE_KEY FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
);


CREATE SEQUENCE REGION_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        
create table COMMODITY_PROFILE_COST_TYPE
(
  ID Number(19,0) NOT NULL,
	PROFILE_ID Number(19,0),
	COST_TYPE varchar2(255),
	CONSTRAINT CPCT_ID_PK PRIMARY KEY (ID),
	CONSTRAINT CPCT_PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES COMMODITY_PROFILE(PROFILE_ID) ON DELETE CASCADE ENABLE
); 

CREATE SEQUENCE PROFILE_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE USER_PROFILE_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE CT_PROFILE_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        CREATE SEQUENCE SC_ALERT_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
		
		
	CREATE TABLE SC_ALERT_DETAIL
   (	"ID" NUMBER(19,0), 
	"STATE" VARCHAR2(64 CHAR), 
	"DISMISED_BY" VARCHAR2(64 CHAR), 
	"USER_LOGIN_ID" VARCHAR2(64 CHAR), 
	"ALERT_LABEL" VARCHAR2(255 CHAR), 
	"ALERT_ID" VARCHAR2(512 CHAR), 
	"ALERT_TYPE" VARCHAR2(255 CHAR), 
	"CREATED" DATE, 
	"SHORT_SUMMARY" VARCHAR2(255 CHAR), 
	"LONG_SUMMARY" VARCHAR2(512 CHAR), 
	"EXPIRATION_DATE" DATE, 
	"PUNCHOUT_URL" VARCHAR2(1024 CHAR), 
	"STRING_ATTRIBUTE1" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE2" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE3" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE4" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE5" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE6" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE7" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE8" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE9" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE10" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE11" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE12" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE13" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE14" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE15" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE16" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE17" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE18" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE19" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE20" VARCHAR2(64 CHAR), 
	"DATE_ATTRIBUTE1" DATE, 
	"DATE_ATTRIBUTE2" DATE, 
	"DATE_ATTRIBUTE3" DATE, 
	"DATE_ATTRIBUTE4" DATE, 
	"DATE_ATTRIBUTE5" DATE, 
	"DATE_ATTRIBUTE6" DATE, 
	"DATE_ATTRIBUTE7" DATE, 
	"DATE_ATTRIBUTE8" DATE, 
	"DATE_ATTRIBUTE9" DATE, 
	"DATE_ATTRIBUTE10" DATE, 
	"NUMERIC_ATTRIBUTE1" FLOAT(126), 
	"NUMERIC_ATTRIBUTE2" FLOAT(126), 
	"NUMERIC_ATTRIBUTE3" FLOAT(126), 
	"NUMERIC_ATTRIBUTE4" FLOAT(126), 
	"NUMERIC_ATTRIBUTE5" FLOAT(126), 
	"NUMERIC_ATTRIBUTE6" FLOAT(126), 
	"NUMERIC_ATTRIBUTE7" FLOAT(126), 
	"NUMERIC_ATTRIBUTE8" FLOAT(126), 
	"NUMERIC_ATTRIBUTE9" FLOAT(126), 
	"NUMERIC_ATTRIBUTE10" FLOAT(126),
    CONSTRAINT alertid_pk PRIMARY KEY (ID) USING INDEX TABLESPACE AUDIT_INDEX
   );

--functional group
CREATE TABLE FUNCTIONAL_GROUP (
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
FUNCTIONAL_GROUP_EXTERNAL_ID VARCHAR2(255) UNIQUE NULL,
NAME VARCHAR2(255) UNIQUE NOT NULL,
ALIAS_NAME VARCHAR2(255),
DESCRIPTION VARCHAR2(255),
TYPE VARCHAR2(255),
FG_PLATFORM VARCHAR2(255),
STATUS VARCHAR2(255),
ITEM_PLATFORM_KEY NUMBER(19,0),
STATUS_CHANGED_BY VARCHAR2(255),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
ROLLOVER_COUNT NUMBER(6,0),
PARENT_ITEM_KEY NUMBER(19,0),
ODM_PART_KEY NUMBER(19,0),
CONSTRAINT FG_PK PRIMARY KEY(FUNCTIONAL_GROUP_ID)
        USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT PLATFORM_FK FOREIGN KEY (ITEM_PLATFORM_KEY) REFERENCES ITEM_PLATFORM(ITEM_PLATFORM_KEY),
CONSTRAINT FG_PARENT_ITEM_FK FOREIGN KEY (PARENT_ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT FG_ODM_PART_FK FOREIGN KEY (ODM_PART_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)	
)TABLESPACE AUDIT_DATA;

--parent functional group
CREATE TABLE PARENT_FUNCTIONAL_GROUP (
PARENT_FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
NAME VARCHAR2(255) UNIQUE NOT NULL,
DESCRIPTION VARCHAR2(255),
TYPE VARCHAR2(255),
PURPOSE VARCHAR(255),
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(1024),
CONSTRAINT PFG_PK PRIMARY KEY(PARENT_FUNCTIONAL_GROUP_ID)
        USING INDEX TABLESPACE AUDIT_INDEX   
)TABLESPACE AUDIT_DATA;

CREATE TABLE ITEM_FG_MAP (
ITEM_KEY NUMBER(19,0) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
CONSTRAINT ITEM_IDENTIFIER_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT FUNCTIONAL_GROUP_ID_ITEM_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID)	
)TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX FG_ITEM_UNIQUE ON ITEM_FG_MAP(ITEM_KEY,FUNCTIONAL_GROUP_ID)  TABLESPACE AUDIT_INDEX;

CREATE TABLE FG_PFG_MAP (
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
PARENT_FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
CONSTRAINT FUNCTIONAL_GROUP_ID_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT PARENT_FUNCTIONAL_GRP_ID FOREIGN KEY (PARENT_FUNCTIONAL_GROUP_ID) REFERENCES PARENT_FUNCTIONAL_GROUP(PARENT_FUNCTIONAL_GROUP_ID)
)TABLESPACE AUDIT_DATA;
                            
CREATE SEQUENCE FUNCTIONAL_GROUP_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PARENT_FUNCTIONAL_GROUP_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE FG_AUDIT_HISTORY (
AUDIT_KEY NUMBER(19,0) NOT NULL,
DATE_PERFORMED TIMESTAMP(6),
USER_ID VARCHAR2(255) NOT NULL,
USER_ROLE VARCHAR2(255) NOT NULL,
ACTION VARCHAR2(255),
OPERATION_CODE VARCHAR2(255),
FG_KEY VARCHAR2(255 BYTE), 
PFG_KEY VARCHAR2(255 BYTE), 
TAM_KEY VARCHAR2(255 BYTE),
ITEM_NUMBER NUMBER(19,0),
SUPPLIER NUMBER(19,0),
SITE NUMBER(19,0),
BUCKET_START_DATE TIMESTAMP(6), 
BUCKET_END_DATE TIMESTAMP(6),
COMMENTS VARCHAR2(1024),
AUDIT_SOURCE VARCHAR2(255),
CONSTRAINT FG_AUDIT_HISTORY_PK PRIMARY KEY(AUDIT_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;


CREATE INDEX X_FG_AUDIT_HISTORY_TAM_KEY ON FG_AUDIT_HISTORY (lower(TAM_KEY)) tablespace audit_index;
CREATE INDEX X_FGA_SOURCE ON FG_AUDIT_HISTORY (AUDIT_SOURCE) tablespace audit_index;

CREATE SEQUENCE FG_AUDIT_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;


CREATE TABLE MULTI_PURPOSE_USES (
ID NUMBER(19,0) NOT NULL,
OBJECT_TYPE VARCHAR2(255),
string_param1 VARCHAR2(255),
string_param2 VARCHAR2(255),
string_param3 VARCHAR2(255),
number_param1 NUMBER(19,0),
number_param2 NUMBER(19,0),
number_param3 NUMBER(19,0),
date_param1 TIMESTAMP,
date_param2 TIMESTAMP,
date_param3 TIMESTAMP,
CLOB_DATA CLOB,
CONSTRAINT MULTI_PURPOSE_USES_KEY_SEQ PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

--TAM Allocation Start

CREATE TABLE TAM_ALLOCATION (
TAM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
ALLOW_HEDGING VARCHAR2(1),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
NEXT_ROLLOVER_DATE TIMESTAMP(6),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
ROLL_OVER_COUNT NUMBER(6),
CURRENT_DATA_DELETED VARCHAR2(1),
DISCP_EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
DISCP_ROLLOVER_EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y',
LAST_ROLLOVER_DATE DATE,
CONSTRAINT TAM_AL_PK PRIMARY KEY(TAM_ALLOCATION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT FUNCTIONAL_GROUP_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT SITE_KEY_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
)TABLESPACE AUDIT_DATA;
	
	
CREATE TABLE TAM_SUPPLIER_ALLOCATION (
TAM_SUPPLIER_ALLOCATION_ID NUMBER(19,0) NOT NULL,
TAM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
BUSINESS_ENTITY_KEY NUMBER(19,0) NOT NULL,
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
ALLOCATION NUMBER(10,5),
CONSTRAINT TAM_SUPP_AL_PK PRIMARY KEY(TAM_SUPPLIER_ALLOCATION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT TAM_ALL_KEY_FK FOREIGN KEY (TAM_ALLOCATION_ID) REFERENCES TAM_ALLOCATION(TAM_ALLOCATION_ID),
CONSTRAINT BUSINESS_ENTITY_KEY_FK FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY)
)TABLESPACE AUDIT_DATA;


CREATE TABLE TAM_ITEM_ALLOCATION (
TAM_ITEM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
TAM_SUPPLIER_ALLOCATION_ID NUMBER(19,0) NOT NULL,
ITEM_KEY NUMBER(19,0) NOT NULL,
ALLOCATION NUMBER(10,5),
CONSTRAINT TAM_ITEM_AL_PK PRIMARY KEY(TAM_ITEM_ALLOCATION_ID)  USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT TAM_SUPP_ALL_KEY_FK FOREIGN KEY (TAM_SUPPLIER_ALLOCATION_ID) REFERENCES TAM_SUPPLIER_ALLOCATION(TAM_SUPPLIER_ALLOCATION_ID),
CONSTRAINT ITEM_ALL_KEY_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)
)TABLESPACE AUDIT_DATA;


CREATE SEQUENCE TAM_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE TAM_SUPPLIER_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE TAM_ITEM_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
--TAM Allocation End

--XLOB Allocation start

CREATE SEQUENCE XLOB_ALLOCATION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE XLOB_ITEM_ALLOCATION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE XLOB_ALLOCATION (
ID NUMBER(19) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
LAST_SYSTEM_UPDATED_ON TIMESTAMP(6),
LAST_SYSTEM_UPDATED_BY VARCHAR2(255),
ROLL_OVER_COUNT NUMBER(6),
NEXT_ROLLOVER_DATE TIMESTAMP(6),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
RECORD_SOURCE VARCHAR2(255),
CURRENT_DATA_DELETED VARCHAR2(1),
CONSTRAINT XLOB_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT XLOB_GROUP_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT SITE_KEY_XLOB_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
)TABLESPACE AUDIT_DATA;


CREATE TABLE XLOB_ITEM_ALLOCATION (
ID NUMBER(19) NOT NULL,
XLOB_ALLOCATION_ID NUMBER(19,0) NOT NULL,
BUSINESS_ENTITY_KEY NUMBER(19,0) NOT NULL,
ITEM_KEY NUMBER(19,0) NOT NULL,
MANUFACTURER_PART VARCHAR2(255),
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
ALLOCATION NUMBER(10,5),
CONSTRAINT XLOB_ITEM_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT XLOB_ALLOCATION_KEY_FK FOREIGN KEY (XLOB_ALLOCATION_ID) REFERENCES XLOB_ALLOCATION(ID),
CONSTRAINT XLOB_BUSINESS_ENTITY_FK FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY),
CONSTRAINT XLOB_ITEM_KEY_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)
)TABLESPACE AUDIT_DATA;

--XLOB Allocation end


-- TAM MRP Start        
create table TAM_MRP_VOLUME
(
ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0),
ITEM_KEY NUMBER(19,0),
REGION_KEY NUMBER(19,2),
DATA_MEASURE VARCHAR2(255),
MRP_VALUE NUMBER(10,5),
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
FACILITY VARCHAR2(255),
CCN VARCHAR2(255),
SUB_LEVEL_DATA VARCHAR2(1),
CONSTRAINT SITE_KEY_TAM_MRP_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT REGION_KEY_TAM_MRP_FK FOREIGN KEY (REGION_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT ITEM_KEY_TAM_MRP_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT TAM_MRP_VOLUME_PK PRIMARY KEY(ID,SITE_KEY,ITEM_KEY,START_DATE,END_DATE) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE INDEX TAM_MRP_VOLUME_item_key on TAM_MRP_VOLUME(ITEM_KEY,START_DATE,END_DATE);

CREATE SEQUENCE TAM_MRP_VOLUME_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
-- TAM MRP End        

CREATE TABLE PCM_DB_CONFIGURATION (
	ID NUMBER(19) NOT NULL,
	CONFIG_KEY VARCHAR2(255) NOT NULL,
	CONFIG_VALUE VARCHAR2(255),
	CONFIG_VALUE_TYPE VARCHAR2(255)
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE PCM_DB_CONFIGURATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

-- indexes used by views?
CREATE INDEX XSA_CUSTSITEKEY_I1 ON PCM_SUPPLIER_ALLOCATION(CUSTOMER_SITE_KEY) tablespace audit_index; 
CREATE INDEX XPCMCVD_CRVK_I1 ON PCM_COST_VALUE_DETAIL(COST_RECORD_VALUE_KEY) tablespace audit_index;
CREATE INDEX XITITCT_ITEMCATKEY ON ITEM_ITEM_CATEGORY (ITEM_CATEGORY_KEY) tablespace audit_index;
CREATE INDEX XPCMRI_RPK_I1 ON PCM_REBATE_ITEM(REBATE_PROGRAM_KEY) tablespace audit_index;

CREATE INDEX XBMHDR_STATUS_I4 ON BOM_HEADER(STATUS) tablespace audit_index;
CREATE INDEX dashboard_bom_fn ON BOM_HEADER (nvl(UPDATE_DT, INSERT_DT))  TABLESPACE AUDIT_INDEX;
CREATE INDEX XPCMRRC_ITEMCATKEY_I1 ON PCM_REBATE_RULE_CATEGORY(ITEM_CATEGORY_KEY ) tablespace audit_index;
CREATE INDEX XPCMRRP_ITEMPLATKEY_I1 ON PCM_REBATE_RULE_PLATFORM (ITEM_PLATFORM_KEY ) tablespace audit_index;


-- TAM FG Indexes

CREATE INDEX XE2OPEN_TAMSUPALLOC_N1 ON TAM_SUPPLIER_ALLOCATION (TAM_ALLOCATION_ID, START_DATE) tablespace audit_index;
CREATE INDEX XE2OPEN_TAM_AL_N1 ON TAM_ALLOCATION (FUNCTIONAL_GROUP_ID, SITE_KEY, TAM_ALLOCATION_ID) tablespace audit_index;
CREATE INDEX XE2OPEN_FG_N1 ON FUNCTIONAL_GROUP (lower(NAME), FUNCTIONAL_GROUP_ID) tablespace audit_index;
CREATE INDEX XTAMSUPPALL_SD_ED on TAM_SUPPLIER_ALLOCATION (START_DATE,END_DATE) tablespace audit_index;
CREATE INDEX XTTAMITEMALL_TSAI_IK on TAM_ITEM_ALLOCATION (TAM_SUPPLIER_ALLOCATION_ID, ITEM_KEY)  tablespace audit_index;


-- Dashboard performance indexes

CREATE INDEX dashboard_cr ON PCM_COST_RECORD (SOURCING_LANE_KEY)  TABLESPACE AUDIT_INDEX;
CREATE INDEX dashboard_cr_fn ON PCM_COST_RECORD (nvl(UPDATE_DT, INSERT_DT))  TABLESPACE AUDIT_INDEX;
 
CREATE INDEX dashboard_sl_fn ON PCM_SOURCING_LANE (nvl(UPDATE_DT, INSERT_DT))  TABLESPACE AUDIT_INDEX;
 
CREATE INDEX dashboard_rp ON PCM_REBATE_PROGRAM (STATUS)  TABLESPACE AUDIT_INDEX;
CREATE INDEX dashboard_rp_fn ON PCM_REBATE_PROGRAM (nvl(UPDATE_DT, INSERT_DT))  TABLESPACE AUDIT_INDEX;
 
CREATE INDEX dashboard_fo ON PCM_FORECAST (FORECAST_TYPE,FORECAST_MODEL)  TABLESPACE AUDIT_INDEX;
CREATE INDEX dashboard_fo_st ON PCM_FORECAST (STATUS)  TABLESPACE AUDIT_INDEX;
CREATE INDEX dashboard_fo_fn ON PCM_FORECAST (nvl(UPDATE_DT, INSERT_DT))  TABLESPACE AUDIT_INDEX;

-- 1st STG Table to extract all TAM details --
CREATE TABLE TAM_ALLOC_CASCADE_PROC_STG1 
  ( 
     TAM_ALLOCATION_ID          NUMBER(19, 0), 
     FUNCTIONAL_GROUP_ID        NUMBER(19, 0), 
     FG_NAME                    VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            TIMESTAMP (6), 
     ALLOW_HEDGING              VARCHAR2(1 BYTE), 
     CREATED_BY                 VARCHAR2(255 BYTE), 
     CREATED_ON                 TIMESTAMP (6), 
     DISCP_EXTRACT_FLAG         VARCHAR2(1 BYTE), 
     SITE_KEY                   NUMBER(19, 0), 
     SITE_IDENTIFIER            VARCHAR2(255 BYTE), 
     SITE_DESCRIPTION           VARCHAR2(1024 BYTE), 
     SITE_TYPE                  VARCHAR2(128 BYTE), 
     PARENT_SITE_KEY            NUMBER(19, 0), 
     SUPPLIER_IDENTIFIER        VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              VARCHAR2(255 BYTE), 
     START_DATE                 TIMESTAMP (6), 
     END_DATE                   TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID NUMBER(19, 0), 
     SUPPLIER_ALLOCATION        NUMBER(10, 5), 
     TAM_ITEM_ALLOCATION_ID     NUMBER(19, 0), 
     ITEM_ALLOCATION            NUMBER(10, 5), 
     ITEM_IDENTIFIER            VARCHAR2(255 BYTE),
     CHILD_PARENT_SITE_ID 		NUMBER(19,0),
     CHILD_IS_DELTA 			NUMBER(19,0),
     DATASOURCE            		VARCHAR2(255 BYTE)
  ); 


-- 2nd STG Table to apply the Cascading Logic --
CREATE TABLE TAM_ALLOC_CASCADE_PROC_STG2 
  ( 
     TAM_ALLOCATION_ID          NUMBER(19, 0), 
     FUNCTIONAL_GROUP_ID        NUMBER(19, 0), 
     FG_NAME                    VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            TIMESTAMP (6), 
     ALLOW_HEDGING              VARCHAR2(1 BYTE), 
     CREATED_BY                 VARCHAR2(255 BYTE), 
     CREATED_ON                 TIMESTAMP (6), 
     DISCP_EXTRACT_FLAG         VARCHAR2(1 BYTE), 
     SITE_KEY                   NUMBER(19, 0), 
     SITE_IDENTIFIER            VARCHAR2(255 BYTE), 
     SITE_DESCRIPTION           VARCHAR2(1024 BYTE), 
     SITE_TYPE                  VARCHAR2(128 BYTE), 
     PARENT_SITE_KEY            NUMBER(19, 0), 
     SUPPLIER_IDENTIFIER        VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              VARCHAR2(255 BYTE), 
     START_DATE                 TIMESTAMP (6), 
     END_DATE                   TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID NUMBER(19, 0), 
     SUPPLIER_ALLOCATION        NUMBER, 
     OLD_SUPPLIER_ALLOCATION    NUMBER, 
     TOT_SUPP_ALOC              NUMBER, 
     TAM_ITEM_ALLOCATION_ID     NUMBER(19, 0), 
     ITEM_ALLOCATION            NUMBER(10, 5), 
     ITEM_IDENTIFIER            VARCHAR2(255 BYTE), 
     BUCK_ALOC                  NUMBER, 
     ALLOC_GLOBAL               NUMBER, 
     ALLOC_REGION               NUMBER, 
     REGION_PARENT_EXISTS       NUMBER, 
     DEFAULT_ITEM_IDENTIFIER    VARCHAR2(255 BYTE) 
  ); 

CREATE INDEX TAM_ALLOC_CASCADE_PROC_STG2_IDX1
  ON TAM_ALLOC_CASCADE_PROC_STG2 (FUNCTIONAL_GROUP_ID,SITE_KEY); 
  
CREATE INDEX TAM_ALLOC_CASCADE_PROC_STG2_IDX2
  ON TAM_ALLOC_CASCADE_PROC_STG2 (FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE);
  
 CREATE TABLE TAM_SITE_DETAIL_PROCESSING
  (
    SITE_KEY            NUMBER(19,0) NOT NULL ENABLE,
    SITE_IDENTIFIER     VARCHAR2(255 BYTE) NOT NULL ENABLE,
    SITE_DESCRIPTION    VARCHAR2(1024 BYTE),
    SITE_TYPE           VARCHAR2(128 BYTE),
    PARENT_SITE_KEY     NUMBER(19,0),
    BUSINESS_ENTITY_KEY NUMBER(19,0),
    SITE_DETAIL_ID      NUMBER(19,0),
    TAM_PROCESSING_FLAG VARCHAR2(1 BYTE)
  );
  
  CREATE UNIQUE INDEX XTAM_SITE_DETAIL_IDENT_I1 ON TAM_SITE_DETAIL_PROCESSING ("SITE_KEY");
  CREATE UNIQUE INDEX XTAM_SITE_DETAIL_U1 ON TAM_SITE_DETAIL_PROCESSING ("BUSINESS_ENTITY_KEY", "SITE_IDENTIFIER", "TAM_PROCESSING_FLAG");

CREATE TABLE SITE_CHANGE_DATA (
	SITE_KEY NUMBER(19,0), 
	SITE_TYPE VARCHAR2(20 BYTE), 
	CREATED_ON TIMESTAMP (6)
);

CREATE TABLE SITE_CHANGE_TAM_CASCADE 
  ( 
     TAM_ALLOCATION_ID          VARCHAR2(255 BYTE), 
     FUNCTIONAL_GROUP_ID        NUMBER(19, 0), 
     FG_NAME                    VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            TIMESTAMP (6),
     CREATED_BY                 VARCHAR2(255 BYTE), 
     CREATED_ON                 TIMESTAMP (6), 
     SITE_KEY                   NUMBER(19, 0),
     SITE_IDENTIFIER			VARCHAR2(1024 BYTE), 
     SITE_DESCRIPTION           VARCHAR2(1024 BYTE), 
     SITE_TYPE                  VARCHAR2(128 BYTE),
     SUPPLIER_KEY               NUMBER(19, 0),
     SUPPLIER_IDENTIFIER        VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              VARCHAR2(255 BYTE), 
     START_DATE                 TIMESTAMP (6), 
     END_DATE                   TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID VARCHAR2(255 BYTE), 
     SUPPLIER_ALLOCATION        NUMBER, 
     TOT_SUPP_ALOC              NUMBER, 
     TAM_ITEM_ALLOCATION_ID    	VARCHAR2(255 BYTE),
     ITEM_ALLOCATION            NUMBER(10, 5), 
     ITEM_IDENTIFIER            VARCHAR2(255 BYTE)
  );

--------------------------------------------------------
--  File created - Wednesday-April-01-2020   
--------------------------------------------------------
--------------------------------------------------------

/* This table will be created as part of story SCPlatform-3924 Auto Expire Simple Forecast of EOL CFG/Item story */
CREATE TABLE FORECASTS_TO_CLOSE(STAT_DATE DATE, FORECAST_KEY VARCHAR2(2000 BYTE),RTYPE VARCHAR2(20 BYTE));
CREATE TABLE LOGGER(LOG_DATE DATE,MSG VARCHAR2(400 BYTE));


CREATE INDEX ITEM_FG_MAP_ITEM ON ITEM_FG_MAP (ITEM_KEY) TABLESPACE AUDIT_DATA;
CREATE INDEX ITEM_FG_MAP_FG ON ITEM_FG_MAP (FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;
CREATE INDEX ITEM_ITEM_CATEGORY_ITEM ON ITEM_ITEM_CATEGORY (ITEM_KEY) TABLESPACE AUDIT_DATA;
CREATE INDEX FG_PFG_MAP_FG ON FG_PFG_MAP (FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;
CREATE INDEX FG_PFG_MAP_PFG ON FG_PFG_MAP (PARENT_FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;

--- TAM ROLLOVER CASCADE OPERATION--------
CREATE TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1
  ( 
     TAM_ALLOCATION_ID          	NUMBER(19, 0), 
     FUNCTIONAL_GROUP_ID       		NUMBER(19, 0), 
     FG_NAME                    	VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            	VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            	TIMESTAMP (6), 
     ALLOW_HEDGING              	VARCHAR2(1 BYTE), 
     CREATED_BY                 	VARCHAR2(255 BYTE), 
     CREATED_ON                 	TIMESTAMP (6), 
     DISCP_ROLLOVER_EXTRACT_FLAG    VARCHAR2(1 BYTE), 
     SITE_KEY                   	NUMBER(19, 0), 
     SITE_IDENTIFIER            	VARCHAR2(255 BYTE), 
     SITE_DESCRIPTION           	VARCHAR2(1024 BYTE), 
     SITE_TYPE                  	VARCHAR2(128 BYTE), 
     PARENT_SITE_KEY            	NUMBER(19, 0), 
     SUPPLIER_IDENTIFIER        	VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              	VARCHAR2(255 BYTE), 
     START_DATE                 	TIMESTAMP (6), 
     END_DATE                   	TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID		NUMBER(19, 0), 
     SUPPLIER_ALLOCATION        	NUMBER(10, 5), 
     TAM_ITEM_ALLOCATION_ID     	NUMBER(19, 0), 
     ITEM_ALLOCATION            	NUMBER(10, 5), 
     ITEM_IDENTIFIER            	VARCHAR2(255 BYTE),
     CHILD_PARENT_SITE_ID 			NUMBER(19,0),
     CHILD_IS_DELTA 				NUMBER(19,0),
     DATASOURCE						VARCHAR2(255 BYTE)
  ); 
  
CREATE TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 
  ( 
     TAM_ALLOCATION_ID          	NUMBER(19, 0), 
     FUNCTIONAL_GROUP_ID        	NUMBER(19, 0), 
     FG_NAME                    	VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            	VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            	TIMESTAMP (6), 
     ALLOW_HEDGING              	VARCHAR2(1 BYTE), 
     CREATED_BY                 	VARCHAR2(255 BYTE), 
     CREATED_ON                 	TIMESTAMP (6), 
     DISCP_ROLLOVER_EXTRACT_FLAG    VARCHAR2(1 BYTE), 
     SITE_KEY                   	NUMBER(19, 0), 
     SITE_IDENTIFIER            	VARCHAR2(255 BYTE), 
     SITE_DESCRIPTION           	VARCHAR2(1024 BYTE), 
     SITE_TYPE                  	VARCHAR2(128 BYTE), 
     PARENT_SITE_KEY            	NUMBER(19, 0), 
     SUPPLIER_IDENTIFIER        	VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              	VARCHAR2(255 BYTE), 
     START_DATE                 	TIMESTAMP (6), 
     END_DATE                   	TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID 	NUMBER(19, 0), 
     SUPPLIER_ALLOCATION        	NUMBER, 
     OLD_SUPPLIER_ALLOCATION    	NUMBER, 
     TOT_SUPP_ALOC              	NUMBER, 
     TAM_ITEM_ALLOCATION_ID     	NUMBER(19, 0), 
     ITEM_ALLOCATION            	NUMBER(10, 5), 
     ITEM_IDENTIFIER            	VARCHAR2(255 BYTE), 
     BUCK_ALOC                  	NUMBER, 
     ALLOC_GLOBAL               	NUMBER, 
     ALLOC_REGION               	NUMBER, 
     REGION_PARENT_EXISTS       	NUMBER, 
     DEFAULT_ITEM_IDENTIFIER    	VARCHAR2(255 BYTE) 
  ); 

CREATE INDEX TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2_IDX1
  ON TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 (FUNCTIONAL_GROUP_ID,SITE_KEY); 
  
CREATE INDEX TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2_IDX2
  ON TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 (FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE);
  
  CREATE TABLE TAM_ROLLOVER_SITE_DETAIL_PROCESSING
  (
    SITE_KEY            NUMBER(19,0) NOT NULL ENABLE,
    SITE_IDENTIFIER     VARCHAR2(255 BYTE) NOT NULL ENABLE,
    SITE_DESCRIPTION    VARCHAR2(1024 BYTE),
    SITE_TYPE           VARCHAR2(128 BYTE),
    PARENT_SITE_KEY     NUMBER(19,0),
    BUSINESS_ENTITY_KEY NUMBER(19,0),
    SITE_DETAIL_ID      NUMBER(19,0),
    TAM_PROCESSING_FLAG VARCHAR2(1 BYTE)
  );
  
  CREATE UNIQUE INDEX XTAM_ROLLOVER_SITE_DETAIL_IDENT_I1 ON TAM_ROLLOVER_SITE_DETAIL_PROCESSING ("SITE_KEY");
  CREATE UNIQUE INDEX XTAM_ROLLOVER_SITE_DETAIL_U1 ON TAM_ROLLOVER_SITE_DETAIL_PROCESSING ("BUSINESS_ENTITY_KEY", "SITE_IDENTIFIER", "TAM_PROCESSING_FLAG");

CREATE INDEX ITEM_EXTRACT_KEY ON ITEM_MASTER_EXTRACT(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_ATTR_KEY ON ITEM_ADD_ATTRIBUTE(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_PLATFORM_KEY ON ITEM_ITEM_PLATFORM(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_ITEM_PLATFORM_KEY ON ITEM_ITEM_PLATFORM(ITEM_PLATFORM_KEY) TABLESPACE AUDIT_INDEX;
-- delete edit profile workflow
DELETE FROM pcm_workflow where workflow_key = 'EDIT_PROFILE';

--cost exception model start
CREATE SEQUENCE PCM_SOURCING_LANE_EXCEPTION_SEQ
		INCREMENT BY 1
		START WITH 1
		NOMAXVALUE
		NOMINVALUE
		CACHE 20
		NOCYCLE ORDER;
		
CREATE SEQUENCE COST_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE COST_EXCEPTION_ODM_CM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_LOB_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_INFO_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_PRICING_SEQ
		INCREMENT BY 1
		START WITH 1
		NOMAXVALUE
		NOMINVALUE
		CACHE 20
		NOCYCLE ORDER;
		

CREATE SEQUENCE PCM_COST_RECORD_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
 CREATE SEQUENCE PCM_COST_RECORD_RANGE_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_RECORD_VALUE_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_COST_RECORD_VALUE_DETAIL_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE COST_EXCEPTION_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE COST_EXCEPTION(
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	EXCEPTION_ID VARCHAR2(255) NOT NULL,
	EXCEPTION_NAME VARCHAR2(255) NOT NULL,
	EXCEPTION_REQUESTOR VARCHAR2(255),
	EXCEPTION_OWNER VARCHAR2(255),
	EXCEPTION_APPROVER VARCHAR2(255),
	COST_TYPE_KEY VARCHAR2(32) NOT NULL,
	REQUEST_TYPE VARCHAR2(255),
	COMMODITY VARCHAR2(255),
	SUBTIER VARCHAR2(1),
	PLATFORM_NAME VARCHAR2(255),
	ODM_ACKNOWLEDGEMENT VARCHAR2(255),
	PREVIOUS_STATE VARCHAR2(255),
	STATE VARCHAR2(255),
	APPROVED_ON TIMESTAMP(6),
	APPROVED_BY VARCHAR2(255),
	REJECTED_ON TIMESTAMP(6),
	REJECTED_BY VARCHAR2(255),
	CLOSED_ON TIMESTAMP(6),
	CLOSED_BY VARCHAR2(255),
	REQUESTED_ON TIMESTAMP(6),
	CREATED_ON TIMESTAMP(6) NOT NULL,
	CREATED_BY VARCHAR2(255) NOT NULL,
	LAST_CHANGED_ON TIMESTAMP(6),
	LAST_CHANGED_BY VARCHAR2(255),
	RE_REQUESTED_ON TIMESTAMP(6),
	RE_REQUESTED_BY VARCHAR2(255),
	UPLOAD_TYPE VARCHAR2(32) NOT NULL,
	CONSTRAINT CEXP_CTK_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT CEXP_PK PRIMARY KEY(EXCEPTION_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_ODM_CM(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	APPLICABLE_ODM_CM VARCHAR2(255),
	CONSTRAINT CEXPOC_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPOC_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_LOB(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	LINE_OF_BUSINESS VARCHAR2(255),
    CONSTRAINT CEXPL_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPL_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_INFO(
	ID NUMBER(19) NOT NULL,
	EXCEPTION_KEY NUMBER(19) NOT NULL,
	STATE VARCHAR2(255),
	STATE_CHANGE_BY VARCHAR2(255),
	STATE_CHANGE_ON TIMESTAMP(6),
	EXCEPTION_COMMENT VARCHAR2(1024),
	CONSTRAINT CEXPI_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPI_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;

CREATE TABLE COST_EXCEPTION_PRICING(
	ID NUMBER(19) NOT NULL,
	EXCEPTION_KEY NUMBER(19) NOT NULL,
	FILE_NAME VARCHAR2(255),
    COST_RECORD_COUNT NUMBER(19),
	UPLOADED_BY VARCHAR2(255),
	UPLOADED_ON TIMESTAMP(6),
	CONSTRAINT CEXPP_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPP_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_SOURCING_LANE_EXCEPTION
(
    SOURCING_LANE_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_NAME VARCHAR2(512) NOT NULL,
    SOURCING_LANE_EXTERNAL_ID VARCHAR2(255) NULL,
    ITEM_KEY NUMBER(19) NOT NULL,
    SUPPLIER_KEY NUMBER(19),
    BOM_KEY NUMBER(19),
    FROM_SITE_KEY NUMBER(19),
    TO_SITE_KEY NUMBER(19),
    OWNER_KEY NUMBER(19),
    DATE_OFFSET NUMBER(10),
    PRODUCT_STATE VARCHAR2(32),
    CURRENCY_CODE VARCHAR2(3),
    SYSTEM_DERIVED VARCHAR2(1) DEFAULT 'N' NOT NULL,    
    ENDDATE_REQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DESCRIPTION VARCHAR2(1024),
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    COLLABORATION VARCHAR2(1),
    COST_PROV_BUSINESS_ENTITY VARCHAR2(255),
	IS_AVL_EXISTS VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PCMSLE_SITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,
    CONSTRAINT PCMSLE_SBE_FK FOREIGN KEY(SUPPLIER_KEY)
        REFERENCES BUSINESS_ENTITY,         
    CONSTRAINT PCMSLE_BOM_FK FOREIGN KEY(BOM_KEY)
        REFERENCES BOM_HEADER,          
    CONSTRAINT PCMSLE_USER_FK FOREIGN KEY (OWNER_KEY) 
        REFERENCES PCM_USER,
    CONSTRAINT PCMSLE_FS_SITE_FK FOREIGN KEY (FROM_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSLE_TS_SITE_FK FOREIGN KEY (TO_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSLE_PK PRIMARY KEY(SOURCING_LANE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;

-- Natural Key
CREATE UNIQUE INDEX XSLE_NK ON PCM_SOURCING_LANE_EXCEPTION(ITEM_KEY,SUPPLIER_KEY,
    BOM_KEY,FROM_SITE_KEY,TO_SITE_KEY,CURRENCY_CODE)
    TABLESPACE AUDIT_INDEX;
    
CREATE INDEX XSLE_ITEM_N1 ON PCM_SOURCING_LANE_EXCEPTION(ITEM_KEY) 
    TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_COST_RECORD_EXCEPTION
(
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_KEY NUMBER(19) NULL,
    SOURCING_LANE_EXCEPTION_KEY NUMBER(19),
    EXCEPTION_KEY NUMBER(19) NOT NULL,
    COST_RECORD_EXTERNAL_ID VARCHAR2(255) NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_PROVIDER_KEY NUMBER(19) NULL,  
    DESCRIPTION VARCHAR2(1024) NULL,
    REASON_CODE VARCHAR2(128) NULL,
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),  
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP, 
    SYSTEM_ACTION VARCHAR2(1024),
    PRICING_SCENARIO_KEY NUMBER(19) NULL,
    PROJECT_NAME VARCHAR2(255), 
    STRING_ATTRIBUTE1 VARCHAR2(1024),
    STRING_ATTRIBUTE2 VARCHAR2(1024),
    STRING_ATTRIBUTE3 VARCHAR2(1024),
    STRING_ATTRIBUTE4 VARCHAR2(1024),
    STRING_ATTRIBUTE5 VARCHAR2(1024),
    STRING_ATTRIBUTE6 VARCHAR2(1024),
    STRING_ATTRIBUTE7 VARCHAR2(1024),
    STRING_ATTRIBUTE8 VARCHAR2(1024),
    STRING_ATTRIBUTE9 VARCHAR2(1024),
    STRING_ATTRIBUTE10 VARCHAR2(1024),
    NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE,
    CONSTRAINT PCMCRE_SLANE_FK FOREIGN KEY(SOURCING_LANE_KEY)
        REFERENCES PCM_SOURCING_LANE ON DELETE CASCADE,
    CONSTRAINT PCMCRE_CTYPE_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT PCMCRE_CPROV_BE_FK FOREIGN KEY(COST_PROVIDER_KEY)
        REFERENCES BUSINESS_ENTITY ON DELETE SET NULL,
    CONSTRAINT PCMCRE_PS_FK FOREIGN KEY(PRICING_SCENARIO_KEY)
        REFERENCES PCM_PRICING_SCENARIO,
    CONSTRAINT PCMCRE_EK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT PCMCRE_SLANEEXC_FK FOREIGN KEY(SOURCING_LANE_EXCEPTION_KEY)
		REFERENCES PCM_SOURCING_LANE_EXCEPTION,
    CONSTRAINT PCMCRE_PK PRIMARY KEY(COST_RECORD_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;  
    
CREATE TABLE PCM_COST_RECORD_RANGE_EXCEPTION
(
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    FROM_RANGE DECIMAL(19,4) NOT NULL,
    TO_RANGE DECIMAL(19,4),
    IS_ACTIVE NUMBER(1),
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    CONSTRAINT PCMCRRNGE_ACTIVE_BOOL CHECK (IS_ACTIVE in (0,1)),
    CONSTRAINT PCMCRRNGE_FRM_LT_TO CHECK (FROM_RANGE < TO_RANGE),
    CONSTRAINT PCMCRRNGE_CR_FK FOREIGN KEY(COST_RECORD_KEY)
        REFERENCES PCM_COST_RECORD_EXCEPTION(COST_RECORD_KEY) ON DELETE CASCADE,
    CONSTRAINT PCMCRRNGE_PK PRIMARY KEY(COST_RECORD_RANGE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;


CREATE TABLE PCM_COST_RECORD_VALUE_EXCEPTION
(
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_ELEMENT_KEY VARCHAR2(32) NOT NULL,
    COST_VALUE DECIMAL(19,6) NOT NULL,
    COST_UOM VARCHAR2(6) NOT NULL,
    COST_VALUE_TYPE VARCHAR2(2) DEFAULT 'S' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,                 
    CONSTRAINT PCMCRVE_CRRNG_FK FOREIGN KEY(COST_RECORD_RANGE_KEY)
        REFERENCES PCM_COST_RECORD_RANGE_EXCEPTION(COST_RECORD_RANGE_KEY) ON DELETE CASCADE,        
    CONSTRAINT PCMCRVE_CELEMENT_FK FOREIGN KEY(COST_TYPE_KEY,COST_ELEMENT_KEY)
        REFERENCES PCM_COST_ELEMENT(COST_TYPE_KEY,COST_ELEMENT_KEY),        
    CONSTRAINT PCMCRVE_PK PRIMARY KEY(COST_RECORD_VALUE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                              
)  TABLESPACE AUDIT_DATA;
   
CREATE TABLE PCM_COST_VALUE_DETAIL_EXCEPTION
(
    COST_VALUE_DETAIL_KEY NUMBER(19) NOT NULL,
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_VALUE_NAME VARCHAR2(32) NOT NULL,
    COST_VALUE_VALUE DECIMAL(19,6) NOT NULL,
    COST_VALUE_BLEND DECIMAL(6,3) NOT NULL,
    CONSTRAINT PCMCVDE_CRV_FK FOREIGN KEY(COST_RECORD_VALUE_KEY)
        REFERENCES PCM_COST_RECORD_VALUE_EXCEPTION ON DELETE CASCADE,
    CONSTRAINT PCMCVDE_PK PRIMARY KEY(COST_VALUE_DETAIL_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                               
)  TABLESPACE AUDIT_DATA;

CREATE INDEX X_FISCAL_PERIOD_DATE ON FISCAL_PERIOD(FISCAL_PERIOD_START_DATE,FISCAL_PERIOD_END_DATE)TABLESPACE audit_index;
CREATE INDEX X_PCM_COT_PROJECT_NAME ON PCM_COST_RECORD(LOWER(PROJECT_NAME))TABLESPACE audit_index;
CREATE INDEX X_CP_COST_TYPE_PROFILE_ID ON COMMODITY_PROFILE_COST_TYPE(PROFILE_ID) TABLESPACE audit_index;
CREATE INDEX X_SL_SUPPLIER ON PCM_SOURCING_LANE(SUPPLIER_KEY)TABLESPACE audit_index;
CREATE INDEX X_XLOB_ITEM_ALLOCATION ON XLOB_ITEM_ALLOCATION(START_DATE,END_DATE)TABLESPACE audit_index;
CREATE INDEX X_FG_ID_TYPE ON FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID,TYPE)TABLESPACE audit_index;
CREATE INDEX X_XLOB_ALLOCATION_SITE_KEY ON XLOB_ALLOCATION(SITE_KEY)TABLESPACE audit_index;
CREATE INDEX LOAD_EVENT_JOB_KEY ON LOAD_EVENT(LOAD_JOB_KEY)TABLESPACE audit_index;

--User connection info
CREATE TABLE PCM_USER_CONNECTION_INFO(
 	 user_Id VARCHAR2(255) NOT NULL ,
	 session_Id VARCHAR2(255),
	 LAST_UPDATE_ON TIMESTAMP(6) NOT NULL,
	  PRIMARY KEY (user_Id)
);


 CREATE TABLE FG_LOB_VALUES
   (	ID NUMBER(19) NOT NULL, 
	    FUNCTIONAL_GROUP_ID NUMBER(19) NOT NULL, 
	    VALUE VARCHAR2(255 BYTE), 
	    CONSTRAINT LOB_PK PRIMARY KEY (ID) USING INDEX TABLESPACE AUDIT_INDEX,
	    CONSTRAINT FG_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID)
			REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID)
   )TABLESPACE AUDIT_DATA ;

CREATE UNIQUE INDEX FG_LOB_FGID
   ON FG_LOB_VALUES(FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_INDEX;
   
 
CREATE INDEX TSA_SUPPLIER_DATE_ID ON TAM_SUPPLIER_ALLOCATION(BUSINESS_ENTITY_KEY,START_DATE,TAM_SUPPLIER_ALLOCATION_ID) TABLESPACE AUDIT_INDEX;
CREATE INDEX TIA_ITEM_ID ON TAM_ITEM_ALLOCATION(ITEM_KEY,TAM_SUPPLIER_ALLOCATION_ID) TABLESPACE AUDIT_INDEX;

CREATE SEQUENCE COST_EXCEPTION_APPROVER_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE COST_EXCEPTION_APPROVER(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	APPROVER_ROLE VARCHAR2(255),
	APPROVER VARCHAR2(255),
	STATE VARCHAR2(255),
	PROXY_APPROVER VARCHAR2(255),
	PROXY_APPROVER_ROLE VARCHAR2(255),
	ACTION_DATE  TIMESTAMP(6),
	ACTUAL_USER VARCHAR2(255),
    CONSTRAINT CEXPL_CEA_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEAXPL_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA;

--Archive purge log table
CREATE TABLE MTCM_PURGE_LOG
   ( LOG_ID NUMBER(10,0), 
	APP_ID VARCHAR2(50 BYTE), 
	TABLE_NAME VARCHAR2(50 BYTE), 
	KEY_COLUMN VARCHAR2(80 BYTE), 
	PROGRAM_NAME VARCHAR2(32 BYTE), 
	STATUS VARCHAR2(15 BYTE), 
	START_DATE DATE, 
	END_DATE DATE, 
	LAST_UPDATED DATE, 
	ROWS_PROCESSED NUMBER(10,0), 
	MESSAGE VARCHAR2(3000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE AUDIT_DATA ;
   
CREATE SEQUENCE MTCM_PURGE_LOG_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ;

CREATE TABLE COST_ROLLUP_CHANGE (
    BOM_KEY        NUMBER NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    USER_KEY       NUMBER,
    CREATE_DATE    TIMESTAMP DEFAULT SYSTIMESTAMP
);

create table ROLE_COMMODITY_PROFILE_MAPPING
(
	ROLE_KEY Number(19,0) NOT NULL,
	PROFILE_ID Number(19,0) NOT NULL,
    BUSINESS_ENTITY_KEY NUMBER(19),
	CONSTRAINT ROLE_PROFILE_PK PRIMARY KEY (ROLE_KEY, PROFILE_ID, BUSINESS_ENTITY_KEY),
	CONSTRAINT role_profile_fk FOREIGN KEY (ROLE_KEY) REFERENCES PCM_ROLE(ROLE_KEY),
    CONSTRAINT business_entity_mapping_key_fk FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY),
    CONSTRAINT profile_role_fk FOREIGN KEY (PROFILE_ID) REFERENCES COMMODITY_PROFILE(PROFILE_ID)
);
CREATE SEQUENCE CURRENCY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE currency (
    id                    NUMBER(19),
    start_date            TIMESTAMP,
    end_date              TIMESTAMP,
    business_entity_key   NUMBER(19),
    from_currency         VARCHAR2(255),
    to_currency           VARCHAR2(255),
    conversion_rate       NUMBER(18,10),
    CONSTRAINT pk_currency  PRIMARY KEY (id),
    CONSTRAINT uq_currency_business
        UNIQUE ( start_date, end_date,business_entity_key,from_currency,to_currency)
);

CREATE TABLE AVL_SITE_MAPPING (
    ID NUMBER(19,0) PRIMARY KEY,
    AVL_KEY NUMBER(19,0),
    SOURCE_SITE_KEY NUMBER(19,0),
    DESTINATION_SITE_KEY NUMBER(19,0),
    CONSTRAINT fk_site_avl FOREIGN KEY (AVL_KEY) REFERENCES ITEM_AVL(AVL_KEY),
    CONSTRAINT fk_source_site FOREIGN KEY (SOURCE_SITE_KEY) REFERENCES SITE(SITE_KEY),
    CONSTRAINT fk_dest_site FOREIGN KEY (DESTINATION_SITE_KEY) REFERENCES SITE(SITE_KEY)
);

CREATE SEQUENCE AVL_SITE_MAPPING_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
CACHE 20
NOCYCLE ORDER;