-- Model to support the Best BOM Report
DROP TRIGGER T_CLEAR_BEST_BOM_ITEM_CACHE;
DROP TABLE BEST_BOM_EXTRACT;
DROP TABLE BEST_BOM_RELATED_ITEM;
DROP TABLE BEST_BOM_RELATED_ITEM_SETS;
DROP TABLE INTERCHANGEABLE_ITEMS_SET;
DROP VIEW IV_BEST_BOM_EXTRACT;
DROP VIEW IV_BEST_BOM_RELATED_ITEM;
DROP PACKAGE BestBomExtract;
/*
 * Performace Monitoring 
*/
DROP TABLE PERF_MON;
DROP PACKAGE pkg_log;
DROP TABLE BEST_BOM_TIME_LOG;