DROP TABLE PCM_LOAD_Item;
DROP TABLE PCM_LOAD_ItemFlexAttribute;
DROP TABLE PCM_LOAD_AdditionalAttribute;
DROP TABLE PCM_LOAD_AVL;
DROP TABLE PCM_LOAD_Bom;
DROP TABLE PCM_LOAD_BomLine;
DROP PACKAGE LoadItemMessage;
