DROP TRIGGER T_COLLAB_SOURCING_LANE;
DROP TRIGGER T_COLLAB_COST_RECORD;
DROP TRIGGER T_COLLAB_BOM_LINE_ITEM;
DROP TRIGGER T_COLLAB_SUPPLIER_ALLOCATION;
DROP TRIGGER T_COLLAB_ITEM_MASTER;
DROP TABLE PCM_COLLAB_EXTRACT;
DROP TABLE PCM_COLLAB_EXTRACT_ITEM_CACHE;
DROP PACKAGE CollabExtract;
