DROP SEQUENCE PCM_USER_SEQ;
DROP SEQUENCE PCM_ROLE_SEQ;
DROP SEQUENCE PCM_ACL_SEQ;
DROP SEQUENCE PCM_SEARCH_FILTER_SEQ;
DROP SEQUENCE PCM_USER_ALERTS_SEQ;
DROP SEQUENCE PCM_SOURCING_LANE_SEQ;
DROP SEQUENCE PCM_COST_RECORD_SEQ;
DROP SEQUENCE PCM_COST_RECORD_RANGE_SEQ;
DROP SEQUENCE PCM_COST_RECORD_VALUE_SEQ;
DROP SEQUENCE PCM_COST_VALUE_DETAIL_SEQ;
DROP SEQUENCE PCM_REBATE_PROGRAM_SEQ;
DROP SEQUENCE PCM_REBATE_ITEM_SEQ;
DROP SEQUENCE PCM_REBATE_RULE_SEQ;
DROP SEQUENCE PCM_ASSIGNMENT_SEQ;
DROP SEQUENCE PCM_SUPPLIER_ALLOCATION_SEQ;
DROP SEQUENCE PCM_FORECAST_SEQ;
DROP SEQUENCE PCM_FORECAST_VALUE_SEQ;
DROP SEQUENCE PCM_AUDIT_HISTORY_SEQ;
DROP SEQUENCE PCM_ALERT_SUBSCRIPTION_SEQ;
DROP SEQUENCE PCM_ALERT_SUBSCRIPTION_OPT_SEQ;
DROP SEQUENCE PCM_ITEM_CATEGORY_CR_SEQ;
DROP SEQUENCE PCM_ITEM_CATEGORY_CRV_SEQ;
DROP SEQUENCE PCM_DEFECT_TYPE_SEQ;
DROP SEQUENCE PCM_EARULE_SEQ;
DROP SEQUENCE PCM_ANALYTICS_RUN_SEQ;
DROP SEQUENCE PCM_ANALYTICS_RESULT_SEQ;
DROP SEQUENCE REGION_ID_SEQ;
DROP SEQUENCE ATTRIBUTE_GROUP_SEQ;
DROP SEQUENCE CT_PROFILE_ID_SEQ;
DROP SEQUENCE PROFILE_ID_SEQ;
DROP SEQUENCE USER_PROFILE_KEY_SEQ;
DROP SEQUENCE SC_ALERT_SEQ;
DROP SEQUENCE PARENT_FUNCTIONAL_GROUP_ID_SEQ;
DROP SEQUENCE FUNCTIONAL_GROUP_ID_SEQ;
DROP SEQUENCE TAM_ALLOCATION_KEY_SEQ;
DROP SEQUENCE TAM_SUPPLIER_ALLOCATION_KEY_SEQ;
DROP SEQUENCE TAM_ITEM_ALLOCATION_KEY_SEQ;
DROP SEQUENCE FG_AUDIT_KEY_SEQ;
DROP SEQUENCE SITE_DETAILS_KEY_SEQ;
DROP SEQUENCE SITE_CCN_KEY_SEQ;
DROP SEQUENCE SITE_FACILITIES_KEY_SEQ;
DROP SEQUENCE TAM_MRP_VOLUME_SEQ;
DROP SEQUENCE XLOB_ALLOCATION_SEQ;
DROP SEQUENCE XLOB_ITEM_ALLOCATION_SEQ;
DROP SEQUENCE PCM_DB_CONFIGURATION_KEY_SEQ;
DROP SEQUENCE MULTI_PURPOSE_USES_KEY_SEQ;
DROP SEQUENCE FG_LOB_SEQUENCE;

DROP TRIGGER T_PCM_AUDIT_HISTORY_ORDER;
DROP TRIGGER T_DELTA_ITEM_CHANGE;

DROP TABLE PCM_APPLICATION_SETTINGS CASCADE CONSTRAINT;
DROP TABLE PCM_ROLE CASCADE CONSTRAINT;
DROP TABLE PCM_ROLE_PREFS CASCADE CONSTRAINT;
DROP TABLE PCM_USER CASCADE CONSTRAINT;
DROP TABLE PCM_USER_PREFS CASCADE CONSTRAINT;
DROP TABLE PCM_USER_DELEGATE CASCADE CONSTRAINT;
DROP TABLE PCM_WORKFLOW CASCADE CONSTRAINT;
DROP TABLE PCM_ACCESS_CONTROL CASCADE CONSTRAINT;
DROP TABLE PCM_SEARCH_FILTER CASCADE CONSTRAINT;
DROP TABLE PCM_SEARCH_FILTER_VALUE CASCADE CONSTRAINT;
DROP TABLE PCM_USER_ALERTS CASCADE CONSTRAINT;
DROP TABLE PCM_SOURCING_LANE CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_TYPE CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_ELEMENT CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_RECORD CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_RECORD_RANGE CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_RECORD_VALUE CASCADE CONSTRAINTS;
DROP TABLE PCM_COST_VALUE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE PCM_PRICING_SCENARIO CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_PROGRAM CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_ITEM CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_RULE CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_RULE_ITEM CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_RULE_PLATFORM CASCADE CONSTRAINTS;
DROP TABLE PCM_REBATE_RULE_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PCM_ASSIGNMENT CASCADE CONSTRAINT;
DROP TABLE PCM_RESPONSIBILITY CASCADE CONSTRAINT;
DROP TABLE PCM_ROLE_RESPONSIBILITY CASCADE CONSTRAINT;
DROP TABLE PCM_ENTITY_ACTION_RULE CASCADE CONSTRAINTS ;
DROP TABLE PCM_SUPPLIER_ALLOCATION CASCADE CONSTRAINT;
DROP TABLE PCM_FORECAST CASCADE CONSTRAINT;
DROP TABLE PCM_FORECAST_VALUE CASCADE CONSTRAINT;
DROP TABLE PCM_FORECAST_VALUE_ADJUSTMENT CASCADE CONSTRAINT;
DROP TABLE PCM_FORECAST_AUTO_APPROVE_CAT CASCADE CONSTRAINT;
DROP TABLE PCM_AUDIT_HISTORY_TARGETS;
DROP TABLE PCM_AUDIT_HISTORY CASCADE CONSTRAINT;
DROP TABLE PCM_EXTRACT_KEY;
DROP TABLE PCM_ALERT_SUBSCRIPTION CASCADE CONSTRAINT;
DROP TABLE PCM_ALERT_SUBSCRIPTION_OPTIONS CASCADE CONSTRAINT;
DROP TABLE PCM_FORECAST_VALUE_ARCHIVE CASCADE CONSTRAINT;
DROP TABLE PCM_ITEM_CATEGORY_COST_RECORD CASCADE CONSTRAINTS;
DROP TABLE PCM_ITEM_CATEGORY_CRV CASCADE CONSTRAINTS;
DROP TABLE PCM_DEFECT_TYPE CASCADE CONSTRAINTS;
DROP TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT CASCADE CONSTRAINTS;
DROP TABLE PCM_JOB_STATUS_CONTROL CASCADE CONSTRAINTS;
DROP TABLE PCM_ANALYTICS_RESULT CASCADE CONSTRAINTS;
DROP TABLE PCM_ANALYTICS_RUN CASCADE CONSTRAINTS;
DROP TABLE COMMODITY_PROFILE_COST_TYPE CASCADE CONSTRAINTS;
DROP TABLE USER_COMMODITYPROFILE_MAPPING CASCADE CONSTRAINTS;
DROP TABLE COMMODITY_PROFILE CASCADE CONSTRAINTS;
DROP TABLE PCM_REGIONAL_REGION_MAP CASCADE CONSTRAINTS;
DROP TABLE SC_ALERT_DETAIL CASCADE CONSTRAINTS;
DROP TABLE FG_PFG_MAP CASCADE CONSTRAINTS;
DROP TABLE ITEM_FG_MAP CASCADE CONSTRAINTS;
DROP TABLE PARENT_FUNCTIONAL_GROUP CASCADE CONSTRAINTS;
DROP TABLE FUNCTIONAL_GROUP CASCADE CONSTRAINTS;
DROP TABLE TAM_ALLOCATION CASCADE CONSTRAINTS;
DROP TABLE TAM_SUPPLIER_ALLOCATION CASCADE CONSTRAINTS;
DROP TABLE TAM_ITEM_ALLOCATION CASCADE CONSTRAINTS;
DROP TABLE FG_AUDIT_HISTORY;
DROP TABLE TAM_MRP_VOLUME;
DROP TABLE SITE_DETAILS CASCADE CONSTRAINTS;
DROP TABLE CCN_SITE CASCADE CONSTRAINTS;
DROP TABLE SITE_FACILITIES CASCADE CONSTRAINTS;
DROP TABLE ITEM_MASTER_EXTRACT;
DROP TABLE PCM_DB_CONFIGURATION;
DROP TABLE MULTI_PURPOSE_USES;

DROP FUNCTION calculateExpression;
DROP FUNCTION concatValues;

-- Model to support the TAM Cascade Extract
DROP TABLE TAM_ALLOC_CASCADE_PROC_STG1;
DROP TABLE TAM_ALLOC_CASCADE_PROC_STG2;
DROP TABLE TAM_SITE_DETAIL_PROCESSING;


-- Drop TAM Rollover Extract
DROP TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1;
DROP TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2;
DROP TABLE TAM_ROLLOVER_SITE_DETAIL_PROCESSING;

-- Drop Site Change TAM Extract
DROP TABLE SITE_CHANGE_TAM_CASCADE;
DROP TABLE SITE_CHANGE_DATA;

-- Drop XLOB Allocation
DROP TABLE XLOB_ITEM_ALLOCATION;
DROP TABLE XLOB_ALLOCATION;

/* part of story SCPlatform-3924 Auto Expire Simple Forecast of EOL CFG/Item story */
DROP TABLE FORECASTS_TO_CLOSE;
DROP TABLE LOGGER;

--drop cost exception model
DROP TABLE PCM_COST_VALUE_DETAIL_EXCEPTION;
DROP TABLE PCM_COST_RECORD_VALUE_EXCEPTION;
DROP TABLE PCM_COST_RECORD_RANGE_EXCEPTION;
DROP TABLE PCM_COST_RECORD_EXCEPTION;
DROP TABLE COST_EXCEPTION_PRICING;
DROP TABLE PCM_SOURCING_LANE_EXCEPTION;
DROP TABLE COST_EXCEPTION_INFO;
DROP TABLE COST_EXCEPTION_ODM_CM;
DROP TABLE COST_EXCEPTION_LOB;
DROP TABLE COST_EXCEPTION;
DROP TABLE COST_EXCEPTION_APPROVER;
DROP SEQUENCE PCM_COST_RECORD_VALUE_DETAIL_EXCEPTION_SEQ;
DROP SEQUENCE PCM_COST_RECORD_VALUE_EXCEPTION_SEQ;
DROP SEQUENCE PCM_COST_RECORD_RANGE_EXCEPTION_SEQ;
DROP SEQUENCE PCM_COST_RECORD_EXCEPTION_SEQ;
DROP SEQUENCE COST_EXCEPTION_PRICING_SEQ;
DROP SEQUENCE COST_EXCEPTION_INFO_SEQ;
DROP SEQUENCE COST_EXCEPTION_ODM_CM_SEQ;
DROP SEQUENCE COST_EXCEPTION_LOB_SEQ;
DROP SEQUENCE COST_EXCEPTION_SEQ;
DROP SEQUENCE COST_EXCEPTION_APPROVER_SEQ;
DROP SEQUENCE PCM_SOURCING_LANE_EXCEPTION_SEQ;
DROP SEQUENCE COST_EXCEPTION_ID_SEQ;
DROP SEQUENCE BUSINESS_ENTITY_ATTRIBUTE_SEQ;

--Drop PCM_USER_CONNECTION_INFO Table
DROP TABLE PCM_USER_CONNECTION_INFO;

--Drop purge table and sequence
DROP TABLE MTCM_PURGE_LOG;
DROP SEQUENCE MTCM_PURGE_LOG_SEQ;
DROP TABLE COST_EXCEPTION;
DROP TABLE FG_LOB_VALUES;
DROP TABLE HT_PCM_FORECAST_VALUE;
DROP TABLE JOB_STATUS_CONTROL;
DROP TABLE PCM_SL_DEBUG_AUDIT;
DROP TABLE PROD_CR;

DROP INDEX XSA_U1;
DROP TABLE AVL_SITE_MAPPING;
DROP SEQUENCE AVL_SITE_MAPPING_SEQ;