DROP TRIGGER T_BE_SOURCING_LANE;
DROP TRIGGER T_BE_COST_RECORD;
DROP TRIGGER T_BE_BOM_LINE_ITEM;
DROP TRIGGER T_BE_SUPPLIER_ALLOCATION;
DROP TRIGGER T_BE_ITEM_MASTER;
DROP TABLE PCM_BOM_EXTRACT;
DROP PACKAGE BomExtract;
