SET DEFINE OFF;

--From 3.2 to 3.3
ALTER TABLE PCM_ROLE_RESPONSIBILITY DROP CONSTRAINT PCM_ROLE_RESP_RESP_FK;

DROP TABLE PCM_RESPONSIBILITY;

CREATE TABLE PCM_RESPONSIBILITY
(
   RESPONSIBILITY_KEY VARCHAR2(32) NOT NULL,
   RESPONSIBILITY_NAME VARCHAR2(64) NOT NULL,
   RESPONSIBILITY_ORDER NUMBER(4),
   RESPONSIBILITY_TYPE VARCHAR2(2) NOT NULL,
   CONSTRAINT PCMR_PK PRIMARY KEY(RESPONSIBILITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                       
)  TABLESPACE AUDIT_DATA;

INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('PRODUCTION', 'Production', 1, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('SERVICE', 'Service', 2, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('REGIONAL', 'Regional', 3, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('FINANCE', 'Finance', 4, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('THIRD_PARTY', 'Third Party', 5, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('SCM', 'Supply Chain Manager', 6, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE)
	values ('VIEWER', 'Viewer', 7, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE) 
	values ('BUYER', 'Buyer', 8, 'I');
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER, RESPONSIBILITY_TYPE) 
	values ('OWNER', 'Owner', 0, 'IC');

ALTER TABLE PCM_ASSIGNMENT
    ADD (CONSTRAINT PCM_ASSIGNMENT_RESP_FK
        FOREIGN KEY (RESPONSIBILITY)
        REFERENCES PCM_RESPONSIBILITY (RESPONSIBILITY_KEY)
    )
;

ALTER TABLE PCM_ROLE_RESPONSIBILITY
    ADD (CONSTRAINT PCM_ROLE_RESP_RESP_FK
        FOREIGN KEY (RESPONSIBILITY_KEY)
        REFERENCES PCM_RESPONSIBILITY
    )
;

INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (10,'BUYER');
