SET DEFINE OFF;

--From 2.1 to 3.0

DROP TRIGGER T_ITEM_OWNER;
DROP VIEW IV_ITEM_OWNER_EXTRACT;

CREATE TABLE PCM_RESPONSIBILITY
(
   RESPONSIBILITY_KEY VARCHAR2(32) NOT NULL,
   RESPONSIBILITY_NAME VARCHAR2(64) NOT NULL,
   RESPONSIBILITY_ORDER NUMBER(4),
   CONSTRAINT PCMR_PK PRIMARY KEY(RESPONSIBILITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                       
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ROLE_RESPONSIBILITY
(
   ROLE_KEY NUMBER(19) NOT NULL,
   RESPONSIBILITY_KEY VARCHAR2(32) NOT NULL,
   CONSTRAINT PCMROLERRESP_PK PRIMARY KEY(ROLE_KEY,RESPONSIBILITY_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX, 
   CONSTRAINT PCM_ROLE_RESP_ROLE_FK FOREIGN KEY(ROLE_KEY)
       REFERENCES PCM_ROLE ON DELETE CASCADE,
   CONSTRAINT PCM_ROLE_RESP_RESP_FK FOREIGN KEY(RESPONSIBILITY_KEY)
       REFERENCES PCM_RESPONSIBILITY ON DELETE CASCADE
)  TABLESPACE AUDIT_DATA;

DELETE FROM PCM_RESPONSIBILITY;
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('PRODUCTION', 'Production', 1);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('SERVICE', 'Service', 2);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('REGIONAL', 'Regional', 3);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('THIRD_PARTY', 'Third Party', 4);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('SCM', 'Supply Chain Manager', 5);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('VIEWER', 'Viewer', 6);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER)
	values ('FINANCE', 'Finance', 7);
INSERT INTO PCM_RESPONSIBILITY (RESPONSIBILITY_KEY, RESPONSIBILITY_NAME, RESPONSIBILITY_ORDER) 
	values ('BUYER', 'Buyer', 8);
	
DELETE FROM PCM_ROLE_RESPONSIBILITY;
-- GCM Role
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (50,'PRODUCTION');
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (50,'SERVICE');
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (50,'REGIONAL');
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (50,'THIRD_PARTY');
-- SCM Role
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (90,'SCM');
-- Finance Role
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
	values (40,'FINANCE');
-- Administrator Role
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
SELECT 1,RESPONSIBILITY_KEY
FROM PCM_RESPONSIBILITY
WHERE RESPONSIBILITY_KEY != 'VIEWER'
AND RESPONSIBILITY_KEY != 'BUYER';
-- Business Administrator Role
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
SELECT 2,RESPONSIBILITY_KEY
FROM PCM_RESPONSIBILITY
WHERE RESPONSIBILITY_KEY != 'VIEWER'
AND RESPONSIBILITY_KEY != 'BUYER';
-- All Roles
INSERT INTO PCM_ROLE_RESPONSIBILITY (ROLE_KEY, RESPONSIBILITY_KEY)
SELECT ROLE_KEY,'VIEWER'
FROM PCM_ROLE;

-- Alert Subscription
CREATE SEQUENCE PCM_ALERT_SUBSCRIPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_ALERT_SUBSCRIPTION_OPT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE PCM_ALERT_SUBSCRIPTION
(
	SUBSCRIPTION_KEY NUMBER(19) NOT NULL,
	ALERT_TYPE VARCHAR2(255) NOT NULL,
	USER_KEY NUMBER(19) NOT NULL,
	SUBSCRIBE_FLAG NUMBER(1),
	CONSTRAINT PCMAS_U_FK FOREIGN KEY(USER_KEY)
       REFERENCES PCM_USER ON DELETE CASCADE,
    CONSTRAINT PCMAS_PK PRIMARY KEY(SUBSCRIPTION_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPAS_U1 
  ON PCM_ALERT_SUBSCRIPTION(ALERT_TYPE, USER_KEY)
  TABLESPACE AUDIT_INDEX;
  
CREATE TABLE PCM_ALERT_SUBSCRIPTION_OPTIONS
(
	OPTION_KEY NUMBER(19) NOT NULL,
	SUBSCRIPTION_KEY NUMBER(19) NOT NULL,
	OPTION_ID VARCHAR2(255) NOT NULL,
	OPTION_VALUE VARCHAR2(1024),
	CONSTRAINT PCMASO_AS_FK FOREIGN KEY(SUBSCRIPTION_KEY)
       REFERENCES PCM_ALERT_SUBSCRIPTION ON DELETE CASCADE,
	CONSTRAINT PCMASO_PK PRIMARY KEY(OPTION_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPASO_U1 
  ON PCM_ALERT_SUBSCRIPTION_OPTIONS(SUBSCRIPTION_KEY, OPTION_ID, OPTION_VALUE)
  TABLESPACE AUDIT_INDEX;

--INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
--values ('MAIN_ALERTS', 'Review Alerts', 'MCM', 'MAIN', '@e2.hub.portal.url@/auth/portal/default/alerts', 4, '_top');

--workflow url does not match
INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('MAIN_ALERTS', 'Review Alerts', 'MCM', 'MAIN', 'AlertSearch.do', 4, '_top');
 

UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 4 WHERE WORKFLOW_KEY = 'EDIT_ITEM';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 5 WHERE WORKFLOW_KEY = 'EDIT_ROLE';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 6 WHERE WORKFLOW_KEY = 'EDIT_CONTACT';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 7 WHERE WORKFLOW_KEY = 'EDIT_BE';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 8 WHERE WORKFLOW_KEY = 'EDIT_USER';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 9 WHERE WORKFLOW_KEY = 'VIEW_AUDIT';
UPDATE PCM_WORKFLOW SET DISPLAY_ORDER = 10 WHERE WORKFLOW_KEY = 'ADMIN_UPLOAD';
INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('EDIT_ALERT_SUB', 'Manage Alerts', 'MCM', 'ADMIN', 'editAlertSubscription.do', 3, NULL);

INSERT INTO PCM_ACCESS_CONTROL (access_control_key, entity_type, role_key, user_key, target_entity_key, acl) 
SELECT pcm_acl_seq.nextval, 'WORKFLOW', role_key, null, 'EDIT_ALERT_SUB', 'Execute'
FROM PCM_ROLE WHERE role_id NOT IN ('ADMIN','BUS_ADMIN','GUEST');

-- Recreate all views, packages, and triggers
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_mcm_views.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_mcm_views.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_margin_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_margin_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_best_bom_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_best_bom_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_audit_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_audit_model.sql;
