-- 1.0 OR 1.1 TO 1.2 MIGRATION SCRIPT

CREATE SEQUENCE PCM_FORECAST_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_FORECAST_VALUE_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE PCM_FORECAST
(
   FORECAST_KEY NUMBER(19) NOT NULL,
   FORECAST_EXTERNAL_ID VARCHAR2(64) NULL,
   DESCRIPTION VARCHAR2(1024) NULL,
   ITEM_KEY NUMBER(19) NOT NULL,
   SITE_KEY NUMBER(19) NULL,
   FORECAST_TYPE VARCHAR2(64) NOT NULL,
   PERIOD_TYPE VARCHAR2(32) NOT NULL,
   CALENDAR_NAME VARCHAR2(32) NOT NULL,
   PERIODIC_ADJUST_TYPE VARCHAR2(32) NULL,   
   PERIODIC_ADJUST_AMOUNT NUMBER(19,6) NULL,
   CONFIDENCE_FACTOR NUMBER(6,3) NULL,
   REMAINING_ROLLOVERS NUMBER(2,0) DEFAULT 0 NOT NULL,
   STATUS VARCHAR2(40) NOT NULL,
   STATUS_CHANGE_DATE TIMESTAMP,    
   STATUS_LAST_CHANGE_BY VARCHAR2(64),     
   INSERT_DT DATE DEFAULT SYSDATE NOT NULL,
   UPDATE_DT DATE NULL,
   EFFECTIVE_FROM_DT DATE NULL,
   EFFECTIVE_TO_DT DATE NULL,
   DELETE_FLAG VARCHAR2(1) NULL,
   CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,          
   CONSTRAINT PCMF_ITEM_FK FOREIGN KEY(ITEM_KEY)
       REFERENCES ITEM_MASTER,
   CONSTRAINT PCMF_SITE_FK FOREIGN KEY (SITE_KEY)
        REFERENCES SITE,
   CONSTRAINT PCMF_PK PRIMARY KEY(FORECAST_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XFOR_U1 
	ON PCM_FORECAST(FORECAST_EXTERNAL_ID)
  TABLESPACE AUDIT_INDEX;

CREATE INDEX XFOR_I1
	ON PCM_FORECAST(ITEM_KEY,FORECAST_TYPE)
	TABLESPACE AUDIT_INDEX;

CREATE TABLE PCM_FORECAST_VALUE
(
   FORECAST_VALUE_KEY NUMBER(19) NOT NULL,
   FORECAST_KEY NUMBER(19) NOT NULL,   
   FORECAST_VALUE DECIMAL(19,6) NULL,
   FORECAST_UOM VARCHAR2(6) NULL,
   FORECAST_MEASURE_KEY VARCHAR2(64) NOT NULL,
   EFFECTIVE_FROM_DT DATE NOT NULL,
   EFFECTIVE_TO_DT DATE NULL,   
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,                 
   CONSTRAINT PCMFV_F_FK FOREIGN KEY(FORECAST_KEY)
       REFERENCES PCM_FORECAST ON DELETE CASCADE,   
   CONSTRAINT PCMFV_PK PRIMARY KEY(FORECAST_VALUE_KEY)       
) TABLESPACE AUDIT_DATA;    

CREATE UNIQUE INDEX XFORVAL_U1 
  ON PCM_FORECAST_VALUE(FORECAST_KEY, FORECAST_MEASURE_KEY, EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;

CREATE TABLE CURRENCY_RATE
(
    FROM_CURRENCY_CODE VARCHAR2(3) NOT NULL,
    TO_CURRENCY_CODE VARCHAR2(3) NOT NULL,
    EXCHANGE_RATE NUMBER(19,6) NOT NULL,
    CONSTRAINT CUR_RATE_FCUR_FK FOREIGN KEY(FROM_CURRENCY_CODE) 
    	REFERENCES CURRENCY_CODE ON DELETE CASCADE,
    CONSTRAINT CUR_RATE_TCUR_FK FOREIGN KEY(TO_CURRENCY_CODE) 
    	REFERENCES CURRENCY_CODE ON DELETE CASCADE,    	
    CONSTRAINT CUR_RATE_PK PRIMARY KEY(FROM_CURRENCY_CODE,TO_CURRENCY_CODE)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;


ALTER TABLE PCM_AUDIT_HISTORY 
	ADD (PCM_SUB_TARGET_KEY VARCHAR2(36) NULL,   
        PCM_SUB_TARGET_TYPE VARCHAR2(255) NULL);
