SET DEFINE OFF;

--Change all the insert/updates to be timestamp
ALTER TABLE PCM_SOURCING_LANE MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE PCM_COST_RECORD MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE PCM_SUPPLIER_ALLOCATION MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE PCM_REBATE_PROGRAM MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE PCM_FORECAST MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE BUSINESS_ENTITY MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE BUSINESS_ENTITY_ALT MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DROP INDEX XITM_MSTR_OWNER;
DROP INDEX XITM_MSTR_OWNER_CI; 
ALTER TABLE ITEM_MASTER MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX XITM_MSTR_OWNER 
	ON ITEM_MASTER(OWNER_NAME,INSERT_DT)
		TABLESPACE AUDIT_INDEX;
CREATE INDEX XITM_MSTR_OWNER_CI 
	ON ITEM_MASTER(LOWER(OWNER_NAME),INSERT_DT)
		TABLESPACE AUDIT_INDEX;

ALTER TABLE ITEM_AML MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE ITEM_AVL MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE BOM_HEADER MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE BOM_LINE_ITEM MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE BOM_GROUP MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE CONTACT MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE SITE MODIFY (UPDATE_DT TIMESTAMP, INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- BOM Subkey
CREATE INDEX XBMLI_BOM_SUBKEY_I2
	ON BOM_LINE_ITEM(SUB_BOM_KEY) 
		TABLESPACE AUDIT_INDEX;

-- Performance fixes
CREATE INDEX XBSENT_TYPE 
	ON BUSINESS_ENTITY (BUSINESS_ENTITY_TYPE_KEY) 
	TABLESPACE AUDIT_INDEX;    

CREATE INDEX XITM_MSTR_ITYPE 
	ON ITEM_MASTER(ITEM_TYPE)
		TABLESPACE AUDIT_INDEX;

-- Forecast related stuff
ALTER TABLE PCM_FORECAST MODIFY (REMAINING_ROLLOVERS NUMBER(2,0) NULL);
ALTER TABLE PCM_FORECAST MODIFY (EFFECTIVE_FROM_DT NULL);

CREATE UNIQUE INDEX XFOR_U2
	ON PCM_FORECAST(ITEM_KEY,SITE_KEY, FORECAST_TYPE)
	TABLESPACE AUDIT_INDEX;

insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('FC', 'Forecast', 'MCM', NULL, NULL, 5, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('NEW_FC', 'New Forecast', 'MCM', 'FC', 'newForecast.do', 1, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('SEARCH_FC', 'Search Forecast', 'MCM', 'FC', 'searchForecast.do', 2, NULL);

-- Report
UPDATE PCM_WORKFLOW SET WORKFLOW_URL = 'initFilter.do?filterName=CostRecordReport&reportName=CostRecordReport'
   WHERE WORKFLOW_KEY = 'RPT_COST';

-- remove unused views
DROP VIEW IV_BUSINESS_TYPE;
DROP VIEW IV_SUPPLIER_ALLOCATION;
DROP VIEW IV_SOURCING_LANE;
DROP VIEW IV_COST_RECORD;
DROP VIEW IV_SOURCING_LANES;
DROP VIEW IV_ITEM_CATEGORY;

-- add the last period date to prevent rollovers
-- from reoccurring during the same period
ALTER TABLE PCM_FORECAST ADD (LAST_ROLLOVER_START_DATE DATE);

-- create the forecast value archive table
CREATE TABLE PCM_FORECAST_VALUE_ARCHIVE
(
   FORECAST_VALUE_KEY NUMBER(19) NOT NULL,
   FORECAST_KEY NUMBER(19) NOT NULL,
   FORECAST_VALUE DECIMAL(19,6) NULL,
   FORECAST_UOM VARCHAR2(6) NULL,
   FORECAST_MEASURE_KEY VARCHAR2(64) NOT NULL,
   EFFECTIVE_FROM_DT DATE NOT NULL,
   EFFECTIVE_TO_DT DATE NULL,
   AUDIT_REV NUMBER(10),
   LAST_REV_CHANGE_DATE TIMESTAMP,
   CONSTRAINT PCMFVA_F_FK FOREIGN KEY(FORECAST_KEY)
       REFERENCES PCM_FORECAST ON DELETE CASCADE,
   CONSTRAINT PCMFVA_PK PRIMARY KEY(FORECAST_VALUE_KEY)
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XFORVALAR_U1 
  ON PCM_FORECAST_VALUE_ARCHIVE(FORECAST_KEY, FORECAST_MEASURE_KEY, EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;


@ /scplatform/app/scplatform/deploy/schema/oracle/drop_mcm_views.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_mcm_views.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_margin_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_margin_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/drop_best_bom_model.sql;
@ /scplatform/app/scplatform/deploy/schema/oracle/create_best_bom_model.sql;
