# default properties not found in /scplatform/config/system.properties
# format: abc.xzy=somevalue
#Defaults
app.name=scplatform
app.jndi.name=${app.name}
scplatform.test.email=${e2.bootstrap.user.0.email}
scplatform.home.dir = ${e2.deploy.dir}/app/scplatform
scplatform.log.dir = ${e2.deploy.dir}/var/log/scplatform
scplatform.tests.dir = ${scplatform.home.dir}/tests


