/**
 * Copyright (c) 2026 Kumara Swamy — github.com/bkumars22
 * Supply Chain Intelligence Platform
 * Licensed under MIT License — see LICENSE file for details
 */
package com.scplatform.pcm.ms3supplier;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for CSV parsing and row-level validation.
 * No Spring context — the service is instantiated directly because parseCsv()
 * does no DB access.
 */
class SupplierCsvImportServiceTest {

    private SupplierCsvImportService svc;

    private static final String HEADER =
        "supplier_id,supplier_name,country,po_number,item_code,promised_date,actual_date,qty_ordered,qty_received,quality_score";

    @BeforeEach
    void setUp() {
        svc = new SupplierCsvImportService();
    }

    // ── Empty / blank input ───────────────────────────────────────────────────

    @Test
    void emptyString_returnsEmptyList() {
        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv("");
        assertTrue(rows.isEmpty(), "Empty input should return no rows");
    }

    @Test
    void nullInput_returnsEmptyList() {
        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(null);
        assertTrue(rows.isEmpty(), "Null input should return no rows");
    }

    @Test
    void headerOnlyFile_returnsEmptyList() {
        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(HEADER);
        assertTrue(rows.isEmpty(), "Header-only file should produce no data rows");
    }

    @Test
    void blankBodyAfterHeader_returnsEmptyList() {
        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(HEADER + "\n\n\n");
        assertTrue(rows.isEmpty(), "Blank rows after header should produce no data rows");
    }

    // ── Happy path ────────────────────────────────────────────────────────────

    @Test
    void validRow_parsesAllFields() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme Supplies,USA,PO-001,WIDGET,2024-01-15,2024-01-17,100,100,5";

        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(csv);

        assertEquals(1, rows.size());
        SupplierCsvImportService.ParsedRow r = rows.get(0);
        assertTrue(r.valid, "Row should be valid");
        assertEquals("SUPP-001",      r.supplierId);
        assertEquals("Acme Supplies", r.supplierName);
        assertEquals("USA",           r.country);
        assertEquals("PO-001",        r.poNumber);
        assertEquals("WIDGET",        r.itemCode);
        assertEquals(100,             r.qtyOrdered);
        assertEquals(100,             r.qtyReceived);
        assertEquals(5.0,             r.qualityScore);
        assertNotNull(r.promisedDate);
        assertNotNull(r.actualDate);
        assertEquals(2, r.rowNumber);
    }

    @Test
    void multipleRows_allParsed() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme Supplies,USA,,, 2024-01-10,2024-01-12,50,50,\n"
            + "SUPP-001,Acme Supplies,USA,,,2024-02-01,2024-02-05,80,75,";

        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(csv);
        assertEquals(2, rows.size());
        assertTrue(rows.get(0).valid);
        assertTrue(rows.get(1).valid);
        assertEquals(2, rows.get(0).rowNumber);
        assertEquals(3, rows.get(1).rowNumber);
    }

    // ── Forgiving defaults ────────────────────────────────────────────────────

    @Test
    void missingPoNumber_getsAutoGeneratedDefault() {
        String csv = HEADER + "\n"
            + "SUPP-002,Beta Corp,UK,,ITEM-X,2024-03-01,2024-03-03,10,10,";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals("CSV-2", row.poNumber, "Missing po_number should default to CSV-{rowNumber}");
    }

    @Test
    void missingItemCode_getsImportedDefault() {
        String csv = HEADER + "\n"
            + "SUPP-003,Gamma Ltd,DE,PO-X,,2024-04-01,2024-04-01,5,5,";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals("IMPORTED", row.itemCode);
    }

    @Test
    void missingQtyOrdered_defaultsToOne() {
        String csv = HEADER + "\n"
            + "SUPP-004,Delta Inc,CN,PO-1,PART-A,2024-05-01,2024-05-02,,,";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals(1, row.qtyOrdered);
        assertEquals(1, row.qtyReceived);
    }

    @Test
    void missingQtyReceived_defaultsToQtyOrdered() {
        String csv = HEADER + "\n"
            + "SUPP-005,Echo Co,JP,PO-2,PART-B,2024-06-01,2024-06-03,20,,";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals(20, row.qtyOrdered);
        assertEquals(20, row.qtyReceived);
    }

    @Test
    void missingQualityScore_defaultsToNull() {
        String csv = HEADER + "\n"
            + "SUPP-006,Foxtrot SA,FR,PO-3,PART-C,2024-07-01,2024-07-01,5,5,";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertNull(row.qualityScore, "Missing quality_score should be null (service uses 75.0 default)");
    }

    @Test
    void missingCountry_allowedBlank() {
        String csv = HEADER + "\n"
            + "SUPP-007,Gamma Co,,PO-4,PART-D,2024-08-01,2024-08-01,1,1,0";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals("", row.country);
    }

    // ── Required field missing → row-level error, not crash ──────────────────

    @Test
    void missingSupplierId_rowIsInvalid() {
        String csv = HEADER + "\n"
            + ",Acme Supplies,USA,PO-1,ITEM,2024-01-01,2024-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("supplier_id"));
    }

    @Test
    void missingSupplierName_rowIsInvalid() {
        String csv = HEADER + "\n"
            + "SUPP-001,,USA,PO-1,ITEM,2024-01-01,2024-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("supplier_name"));
    }

    @Test
    void missingPromisedDate_rowIsInvalid() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,,2024-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("promised_date"));
    }

    @Test
    void missingActualDate_rowIsInvalid() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,2024-01-01,,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("actual_date"));
    }

    // ── Malformed dates ───────────────────────────────────────────────────────

    @Test
    void malformedPromisedDate_rowIsInvalidWithClearMessage() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,not-a-date,2024-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("promised_date"),
            "Error should name the offending field");
        assertTrue(row.errorMessage.contains("not-a-date"),
            "Error should echo the bad value for the user to find it");
    }

    @Test
    void malformedActualDate_rowIsInvalidWithClearMessage() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,2024-01-01,32/99/9999,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertFalse(row.valid);
        assertTrue(row.errorMessage.contains("actual_date"));
        assertTrue(row.errorMessage.contains("32/99/9999"));
    }

    @Test
    void alternativeDateFormat_mmDdYyyy_isAccepted() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,01/15/2024,01/17/2024,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid, "MM/DD/YYYY date format should be accepted");
        assertEquals(2024, row.promisedDate.getYear());
        assertEquals(1,    row.promisedDate.getMonthValue());
        assertEquals(15,   row.promisedDate.getDayOfMonth());
    }

    // ── One bad row doesn't kill the rest ─────────────────────────────────────

    @Test
    void mixedValidAndInvalidRows_allReturned() {
        String csv = HEADER + "\n"
            + "SUPP-001,Acme,USA,PO-1,ITEM,2024-01-01,2024-01-03,10,10,5\n"  // valid
            + "SUPP-002,,UK,PO-2,ITEM,2024-02-01,2024-02-05,5,5,0\n"          // invalid: no name
            + "SUPP-003,Gamma,DE,PO-3,ITEM,bad-date,2024-03-02,8,8,2\n"       // invalid: bad date
            + "SUPP-004,Delta,JP,PO-4,ITEM,2024-04-01,2024-04-01,20,20,1";    // valid

        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(csv);
        assertEquals(4, rows.size());
        assertTrue(rows.get(0).valid);
        assertFalse(rows.get(1).valid);
        assertFalse(rows.get(2).valid);
        assertTrue(rows.get(3).valid);
    }

    // ── Quoted fields with commas ─────────────────────────────────────────────

    @Test
    void quotedFieldWithComma_parsedCorrectly() {
        String csv = HEADER + "\n"
            + "SUPP-001,\"Acme, Inc.\",USA,PO-1,ITEM,2024-01-01,2024-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid);
        assertEquals("Acme, Inc.", row.supplierName);
    }

    // ── parseLine unit tests (static helper) ──────────────────────────────────

    @Test
    void parseLine_simpleFields() {
        List<String> fields = SupplierCsvImportService.parseLine("a,b,c");
        assertEquals(List.of("a", "b", "c"), fields);
    }

    @Test
    void parseLine_emptyField() {
        List<String> fields = SupplierCsvImportService.parseLine("a,,c");
        assertEquals(3, fields.size());
        assertEquals("", fields.get(1));
    }

    @Test
    void parseLine_escapedQuote() {
        List<String> fields = SupplierCsvImportService.parseLine("\"say \"\"hello\"\"\",b");
        assertEquals("say \"hello\"", fields.get(0));
    }

    // ── parseDate unit tests ──────────────────────────────────────────────────

    @Test
    void parseDate_isoFormat() {
        assertNotNull(SupplierCsvImportService.parseDate("2024-06-15"));
    }

    @Test
    void parseDate_usFormat() {
        assertNotNull(SupplierCsvImportService.parseDate("06/15/2024"));
    }

    @Test
    void parseDate_invalidReturnsNull() {
        assertNull(SupplierCsvImportService.parseDate("not-a-date"));
    }

    @Test
    void parseDate_nullReturnsNull() {
        assertNull(SupplierCsvImportService.parseDate(null));
    }

    // ── UTF-8 BOM (Excel "CSV UTF-8" export) ──────────────────────────────────
    // Excel prepends a BOM to this export format. Left unhandled, it attaches
    // to the first header cell ("\uFEFFsupplier_id" != "supplier_id"), which
    // fails EVERY row with "missing supplier_id" -- not just the header.

    @Test
    void bomPrefixedHeader_stillParsesFirstColumnCorrectly() {
        String csv = "\uFEFF" + HEADER + "\n"
            + "SUP-1,Acme Corp,USA,PO-1,ITEM,2026-01-01,2026-01-02,10,10,5";

        SupplierCsvImportService.ParsedRow row = svc.parseCsv(csv).get(0);
        assertTrue(row.valid, "BOM must not make the first row's supplier_id look missing");
        assertEquals("SUP-1", row.supplierId);
    }

    // ── Real messy Excel-style export, end to end ─────────────────────────────
    // Per the source plan's own verification checklist: "import a real, messy,
    // realistic supplier CSV (not a clean synthetic one)". This fixture has a
    // UTF-8 BOM, mixed-case/spaced headers, a quoted comma, mixed date formats
    // in the same file, blank optional columns, padded whitespace, a blank
    // line, a malformed date, a missing supplier_id, and an unexpected extra
    // trailing column -- see the file itself for the exact layout.

    @Test
    void realMessyExcelExport_parsesValidRowsAndReportsCleanErrorsForTheRest() throws Exception {
        String csv = new String(
            java.nio.file.Files.readAllBytes(
                java.nio.file.Paths.get(getClass().getClassLoader()
                    .getResource("ms3supplier/messy_supplier_import.csv").toURI())),
            java.nio.charset.StandardCharsets.UTF_8);

        List<SupplierCsvImportService.ParsedRow> rows = svc.parseCsv(csv);

        List<SupplierCsvImportService.ParsedRow> valid = rows.stream().filter(r -> r.valid).toList();
        List<SupplierCsvImportService.ParsedRow> invalid = rows.stream().filter(r -> !r.valid).toList();

        // 7 valid delivery rows across 5 distinct suppliers; the blank line is
        // silently skipped (not an error -- real exports commonly trail one).
        assertEquals(7, valid.size());
        assertEquals(2, invalid.size());
        assertEquals(Set.of("SUP-900", "SUP-901", "SUP-902", "SUP-903", "SUP-905"),
            valid.stream().map(r -> r.supplierId).collect(java.util.stream.Collectors.toSet()));

        // BOM didn't break the first data row's supplier_id.
        assertEquals("SUP-900", rows.get(0).supplierId);

        // Quoted comma in the supplier name survived intact.
        SupplierCsvImportService.ParsedRow meridian = valid.stream()
            .filter(r -> r.supplierId.equals("SUP-901")).findFirst().orElseThrow();
        assertEquals("Meridian, Rossi & Co.", meridian.supplierName);

        // Leading/trailing whitespace around every field was trimmed.
        SupplierCsvImportService.ParsedRow nordholm = valid.stream()
            .filter(r -> r.supplierId.equals("SUP-903")).findFirst().orElseThrow();
        assertEquals("Nordholm AB", nordholm.supplierName);
        assertEquals("Sweden", nordholm.country);

        // Both the mixed US-format date row and the ISO-format row for the
        // same supplier parsed correctly.
        long sup900Rows = valid.stream().filter(r -> r.supplierId.equals("SUP-900")).count();
        assertEquals(2, sup900Rows);

        // The malformed date and the missing-supplier_id row both produced
        // clear, specific error messages rather than a generic failure.
        assertTrue(invalid.stream().anyMatch(r -> r.errorMessage.contains("Invalid promised_date")));
        assertTrue(invalid.stream().anyMatch(r -> r.errorMessage.contains("Missing required field: supplier_id")));
    }
}
