/**
 * Copyright (c) 2026 Kumara Swamy — github.com/bkumars22
 * Supply Chain Intelligence Platform
 * Licensed under MIT License — see LICENSE file for details
 */
// Auto-generated by agent25_playwright_generator.py
import { Page } from "@playwright/test";

export const APP_URL  = "http://localhost:3000";
export const API_URL  = "http://localhost:8089/supchain";
export const USERNAME = "kumar";
export const PASSWORD = "Kumar@2026";

export async function loginViaUI(page: Page) {
  await page.goto(APP_URL + "/login");
  await page.waitForLoadState("networkidle");
  const user = page.locator('input[type="text"], input[name="username"], input[placeholder*="user" i]').first();
  const pass = page.locator('input[type="password"]').first();
  await user.fill(USERNAME);
  await pass.fill(PASSWORD);
  await page.locator('button[type="submit"], button:has-text("Sign"), button:has-text("Login")').first().click();
  await page.waitForURL((url) => !url.toString().includes("/login"), { timeout: 15000 });
}

export async function getJwtToken(): Promise<string> {
  const res = await fetch(API_URL + "/api/auth/login", {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify({ username: USERNAME, password: PASSWORD })
  });
  const data = await res.json();
  return data.token || "";
}
