WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE PCM_AUDIT_HISTORY ADD CONSTRAINT PCMAH_PK PRIMARY KEY (AUDIT_RECORD_KEY);

CREATE TABLE PCM_AUDIT_HISTORY_TARGETS
(
   AUDIT_RECORD_KEY VARCHAR2(32) NOT NULL,
   PCM_TARGET_KEY VARCHAR2(36) NOT NULL,
   CONSTRAINT PCMAHT_PCMAHT_FK FOREIGN KEY(AUDIT_RECORD_KEY)
       REFERENCES PCM_AUDIT_HISTORY ON DELETE CASCADE
) TABLESPACE AUDIT_DATA;

INSERT INTO PCM_AUDIT_HISTORY_TARGETS
SELECT AUDIT_RECORD_KEY,PCM_TARGET_KEY
FROM PCM_AUDIT_HISTORY;

ALTER TABLE PCM_AUDIT_HISTORY DROP COLUMN PCM_TARGET_KEY;

ALTER TABLE PCM_AUDIT_HISTORY ADD ROLE_ID VARCHAR2(50);

CREATE INDEX XPAH_I1 
  ON PCM_AUDIT_HISTORY(PCM_TARGET_TYPE)
  TABLESPACE AUDIT_INDEX;
  
CREATE UNIQUE INDEX XPAHT_U1 
  ON PCM_AUDIT_HISTORY_TARGETS(AUDIT_RECORD_KEY,PCM_TARGET_KEY)
  TABLESPACE AUDIT_INDEX;
