INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) VALUES 
('XLOB_DELETE_TEMPLATE', 'XLOB Delete Template', 'MCM', 'FUNCTIONAL_GROUP', 'downloadXLOBDelete.do', 10, NULL);

INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1, NULL, 'XLOB_DELETE_TEMPLATE', 'Execute');