CREATE TABLE ITEM_MASTER_EXTRACT (
ITEM_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGE_DT TIMESTAMP
);

ALTER TABLE FUNCTIONAL_GROUP add FG_PLATFORM VARCHAR2(255);


CREATE OR REPLACE PROCEDURE ITEM_CHANGE_INSERT_PROC (ITEM_KEY_PARAM IN NUMBER)
AS
PRAGMA AUTONOMOUS_TRANSACTION;

BEGIN
   INSERT INTO ITEM_MASTER_EXTRACT (ITEM_KEY,LAST_CHANGE_DT) SELECT ITEM_KEY_PARAM,SYSDATE from dual
    where not exists(SELECT 1 FROM ITEM_MASTER_EXTRACT WHERE ITEM_KEY = ITEM_KEY_PARAM);
COMMIT;
END;
/


create or replace TRIGGER T_DELTA_ITEM_CHANGE
	AFTER INSERT OR UPDATE ON ITEM_MASTER
	FOR EACH ROW
DECLARE
	v_item_key item_master.item_key%TYPE;
BEGIN
	v_item_key := :new.item_key; 
	ITEM_CHANGE_INSERT_PROC(v_item_key);	
END DELTA_ITEM_CHANGE;
/

CREATE OR REPLACE VIEW IV_ITEM_EXTRACT AS 
  SELECT
  IM.ITEM_KEY AS ITEM_KEY ,
  /* ITEM ATTRIBUTES */
  IM.ITEM_UNIQUE_IDENTIFIER AS ITEM_UNIQUE_IDENTIFIER,  
  IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,
  IM.ITEM_EXTERNAL_ID AS ITEM_EXTERNAL_ID,
  IM.ITEM_TYPE AS ITEM_TYPE,
  IM.GBL_UOM_CODE AS PRODUCT_UOM_CODE,
  IM.GBL_LFCYCL_PH_CODE AS LIFE_CYCLE_TYPE_CODE,
  IM.GBL_PROD_LFCYCL_CODE_OTHER AS LIFE_CYCLE_TYPE_CODE_OTHER,
  IM.ITEM_CLASSIFICATION AS ITEM_CLASSIFICATION,
  IM.PRODUCT_FAMILY AS PRODUCT_FAMILY,
  IM.MAKE_BUY AS MAKE_BUY,
  IM.MAKE_BUY_OTHER AS MAKE_BUY_OTHER,
  IM.SERIALNUMBER_REQUIRED AS SERIALNUMBER_REQUIRED,
  IM.CERTIFICATION_REQUIRED AS CERTIFICATION_REQUIRED,
  IM.OWNER_NAME AS OWNER_NAME,
  IM.ITEM_DESCRIPTION AS ITEM_DESCRIPTION,
  IM.IS_TOP_LEVEL AS IS_TOP_LEVEL,
  IM.COLLABORATION AS COLLABORATION,
  IM.ITEM_PART_TYPE AS ITEM_PART_TYPE,
  IM.INVENTORY AS INVENTORY,
  IM.EOL AS EOL,
  IM.EOL_LAST_CHANGED_ON AS EOL_LAST_CHANGED_ON,
  IM.EOL_TYPE AS EOL_TYPE,
  IM.UPDATE_DT AS UPDATE_DT,
  IM.DATA_SOURCE AS DATA_SOURCE,
  /* Version details from Item table */
  IM.VERSION AS VERSION,
  IM.REVISION AS REVISION,
  IM.VERSION_DATE AS VERSION_DATE,
  IM.REVISION_DATE AS REVISION_DATE, 
  /* Attribute Details */
  attr.ATTRIBUTE_KEY AS ATTRIBUTE_KEY,
  attr.ATTRIBUTE_NAME AS ATTRIBUTE_NAME,
  attr.ATTRIBUTE_VALUE AS ATTRIBUTE_VALUE,
  attr.ATTRIBUTE_TYPE AS ATTRIBUTE_TYPE,  
  /* Platform details */
  pf.ITEM_PLATFORM_KEY AS ITEM_PLATFORM_KEY,
  pf.ITEM_PLATFORM_NAME AS ITEM_PLATFORM_NAME,
  pf.ITEM_PLATFORM_TYPE AS ITEM_PLATFORM_TYPE,
  pf.ITEM_PLATFORM_DESC AS ITEM_PLATFORM_DESC,
  /* Category details */  
  ic.ITEM_CATEGORY_NAME   AS ITEM_CATEGORY_NAME,  
   /* BUSINESS_ENTITY Details */
  be.BUSINESS_ENTITY_NAME AS BUSINESS_ENTITY_NAME,
  be.BUSINESS_ENTITY_TYPE_KEY AS BUSINESS_ENTITY_TYPE_KEY,   
  /* Contact Details */
  VC.CONTACT_NAME AS CONTACT_NAME,
  VC.CONTACT_UNIQUE_ID AS CONTACT_UNIQUE_ID
FROM
ITEM_MASTER IM
LEFT OUTER JOIN ITEM_ADD_ATTRIBUTE attr ON attr.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_ITEM_PLATFORM rpf ON rpf.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM pf ON pf.ITEM_PLATFORM_KEY = rpf.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_ITEM_CATEGORY ric ON ric.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_CATEGORY ic ON ic.ITEM_CATEGORY_KEY = ric.ITEM_CATEGORY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = IM.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN CONTACT VC ON IM.CONTACT_KEY = VC.CONTACT_KEY


CREATE TABLE SITE_CHANGE_DATA (
	SITE_KEY NUMBER(19,0), 
	SITE_TYPE VARCHAR2(20 BYTE), 
	CREATED_ON TIMESTAMP (6)
);

CREATE TABLE SITE_CHANGE_TAM_CASCADE 
  ( 
     TAM_ALLOCATION_ID          VARCHAR2(255 BYTE), 
     FUNCTIONAL_GROUP_ID        NUMBER(19, 0), 
     FG_NAME                    VARCHAR2(255 BYTE), 
     LAST_CHANGED_BY            VARCHAR2(255 BYTE), 
     LAST_CHANGED_ON            TIMESTAMP (6),
     CREATED_BY                 VARCHAR2(255 BYTE), 
     CREATED_ON                 TIMESTAMP (6), 
     SITE_KEY                   NUMBER(19, 0),
     SITE_IDENTIFIER			VARCHAR2(1024 BYTE), 
     SITE_DESCRIPTION           VARCHAR2(1024 BYTE), 
     SITE_TYPE                  VARCHAR2(128 BYTE), 
     SUPPLIER_IDENTIFIER        VARCHAR2(255 BYTE), 
     SUPPLIER_NAME              VARCHAR2(255 BYTE), 
     START_DATE                 TIMESTAMP (6), 
     END_DATE                   TIMESTAMP (6), 
     TAM_SUPPLIER_ALLOCATION_ID VARCHAR2(255 BYTE), 
     SUPPLIER_ALLOCATION        NUMBER, 
     TOT_SUPP_ALOC              NUMBER, 
     TAM_ITEM_ALLOCATION_ID    	VARCHAR2(255 BYTE),
     ITEM_ALLOCATION            NUMBER(10, 5), 
     ITEM_IDENTIFIER            VARCHAR2(255 BYTE)
  );
  
CREATE OR REPLACE PROCEDURE SITE_CHANGE_INSERT_PROC (NEW_SITE_KEY IN NUMBER,NEW_SITE_DETAIL_ID IN NUMBER,OLD_SITE_DETAIL_ID IN NUMBER,NEW_SITE_TYPE IN VARCHAR2,OLD_TAM_PROCESSING_FLAG IN VARCHAR2,
  NEW_TAM_PROCESSING_FLAG IN VARCHAR2,OPERATION_TYPE IN VARCHAR2,TARGET IN VARCHAR2)
AS
PRAGMA AUTONOMOUS_TRANSACTION;

v_SITE_TYPE VARCHAR2(255);
v_SITE_KEY NUMBER;

BEGIN
  IF (TARGET = 'SITE') THEN
    IF (OPERATION_TYPE = 'INSERT') THEN
      IF (NEW_SITE_TYPE = 'REGION') THEN
        INSERT INTO SITE_CHANGE_DATA
        (SITE_KEY,SITE_TYPE,CREATED_ON)
        SELECT s.SITE_KEY,s.SITE_KEY,SYSTIMESTAMP FROM SITE s WHERE s.PARENT_SITE_KEY = NEW_SITE_KEY;
      ELSIF (NEW_SITE_TYPE = 'SITE') THEN
        INSERT INTO SITE_CHANGE_DATA
        (SITE_KEY,SITE_TYPE,CREATED_ON) VALUES (NEW_SITE_KEY,NEW_SITE_TYPE,SYSTIMESTAMP);
      END IF;
    ELSIF (OPERATION_TYPE = 'UPDATE') THEN
      IF (OLD_SITE_DETAIL_ID IS NULL AND NEW_SITE_DETAIL_ID IS NOT NULL) THEN
        IF (NEW_SITE_TYPE = 'REGION') THEN
          INSERT INTO SITE_CHANGE_DATA
          (SITE_KEY,SITE_TYPE,CREATED_ON)
          SELECT s.SITE_KEY,s.SITE_TYPE,SYSTIMESTAMP FROM SITE s WHERE s.PARENT_SITE_KEY = NEW_SITE_KEY;
        ELSIF (NEW_SITE_TYPE = 'SITE') THEN
          INSERT INTO SITE_CHANGE_DATA (SITE_KEY,SITE_TYPE,CREATED_ON) VALUES (NEW_SITE_KEY,NEW_SITE_TYPE,SYSTIMESTAMP);
        END IF;
      END IF;
    END IF;
  ELSIF (TARGET = 'SITE_DETAILS') THEN
    IF ((OLD_TAM_PROCESSING_FLAG IS NULL OR OLD_TAM_PROCESSING_FLAG = '0' ) AND NEW_TAM_PROCESSING_FLAG = '1') THEN
    
    SELECT s.SITE_TYPE,s.SITE_KEY INTO v_SITE_TYPE,v_SITE_KEY FROM SITE s WHERE s.SITE_DETAIL_ID = NEW_SITE_DETAIL_ID AND ROWNUM = 1;
  
      IF (v_SITE_TYPE = 'REGION') THEN
        INSERT INTO SITE_CHANGE_DATA
          (SITE_KEY,SITE_TYPE,CREATED_ON)
          SELECT s.SITE_KEY,s.SITE_KEY,SYSTIMESTAMP FROM SITE s WHERE s.PARENT_SITE_KEY = v_SITE_KEY;
      ELSIF (v_SITE_TYPE = 'SITE') THEN
        INSERT INTO SITE_CHANGE_DATA (SITE_KEY,SITE_TYPE,CREATED_ON) VALUES (v_SITE_KEY,v_SITE_TYPE,SYSTIMESTAMP);
      END IF;
    END IF;
  END IF;
COMMIT;
END;
/  
create or replace TRIGGER T_TAM_EXTRACT_SITE_CHANGE
	AFTER INSERT OR UPDATE ON SITE
	FOR EACH ROW

DECLARE
      v_newSiteKey          SITE.SITE_KEY%TYPE;
      v_newSiteDetailId     SITE.SITE_DETAIL_ID%TYPE;
      v_oldSiteDetailId     SITE.SITE_DETAIL_ID%TYPE;
      v_newSiteType         SITE.SITE_TYPE%TYPE;
BEGIN
   v_newSiteKey        := :new.SITE_KEY;
   v_newSiteDetailId   := :new.SITE_DETAIL_ID;
   v_oldSiteDetailId   := :old.SITE_DETAIL_ID;
   v_newSiteType       := :new.SITE_TYPE;

	IF INSERTING THEN
    SITE_CHANGE_INSERT_PROC(v_newSiteKey,v_newSiteDetailId,v_oldSiteDetailId,v_newSiteType,null,null,'INSERT','SITE');
  END IF;
  
  IF UPDATING THEN 
    SITE_CHANGE_INSERT_PROC(v_newSiteKey,v_newSiteDetailId,v_oldSiteDetailId,v_newSiteType,null,null,'UPDATE','SITE');
  END IF;
END;
/

create or replace TRIGGER T_TAM_EXTRACT_SITE_DETAILS_CHANGE
	AFTER UPDATE ON SITE_DETAILS
	FOR EACH ROW

DECLARE
      v_newSiteDetailId       SITE_DETAILS.ID%TYPE;
      v_oldSiteDetailId       SITE_DETAILS.ID%TYPE;
      v_newTAMProcessingFlag  SITE_DETAILS.TAM_PROCESSING_FLAG%TYPE;
      v_oldTAMProcessingFlag  SITE_DETAILS.TAM_PROCESSING_FLAG%TYPE;
BEGIN
   v_newSiteDetailId      := :new.ID;
   v_oldSiteDetailId      := :old.ID;
   v_newTAMProcessingFlag := :new.TAM_PROCESSING_FLAG;
   v_oldTAMProcessingFlag := :old.TAM_PROCESSING_FLAG;
  
  SITE_CHANGE_INSERT_PROC(null,v_newSiteDetailId,v_oldSiteDetailId,'',v_oldTAMProcessingFlag,v_newTAMProcessingFlag,'','SITE_DETAILS');
END;
/

create or replace PROCEDURE SITE_CHANGE_TAM_CASCADE_EXTRACT_PROC (vOUT_RESULT out SYS_REFCURSOR,V_START_DATE DATE)
AS
  CURSOR cur_FgSite
  IS
  WITH a1 AS
    (SELECT tam.FUNCTIONAL_GROUP_ID,site.SITE_KEY,site.SITE_DESCRIPTION,
    CASE site.SITE_TYPE WHEN 'GLOBAL'  THEN 1
                        WHEN 'REGION' THEN 2
                        END AS SITE_TYPE
    FROM TAM_ALLOCATION tam LEFT JOIN SITE site
    ON site.SITE_KEY = tam.SITE_KEY AND site.SITE_TYPE IN('REGION','GLOBAL') WHERE site.SITE_KEY is not null),a2 AS(SELECT FUNCTIONAL_GROUP_ID,SITE_KEY,MAX(SITE_TYPE) over (partition BY FUNCTIONAL_GROUP_ID) max_site FROM a1),a3 AS
    (SELECT FUNCTIONAL_GROUP_ID,MAX(SITE_KEY) AS SITE_KEY,max_site FROM a2 GROUP BY FUNCTIONAL_GROUP_ID,max_site) 
    SELECT a3.FUNCTIONAL_GROUP_ID,CASE WHEN exists (select 1 from tam_allocation where FUNCTIONAL_GROUP_ID=a3.FUNCTIONAL_GROUP_ID and site_key = site.PARENT_SITE_KEY) THEN site.PARENT_SITE_KEY ELSE 1 END AS SITE_KEY,CASE max_site WHEN 1 THEN 'GLOBAL' WHEN 2 THEN 'REGION' END AS SITE_TYPE,sc.SITE_KEY AS NEW_SITE_KEY,site.SITE_DESCRIPTION AS NEW_SITE_DESCRIPTION,
    site.SITE_TYPE AS NEW_SITE_TYPE FROM a3,SITE_CHANGE_DATA sc 
    LEFT JOIN SITE site ON site.SITE_KEY = sc.SITE_KEY
    LEFT JOIN SITE_DETAILS sideDetails ON sideDetails.ID = site.SITE_DETAIL_ID
    LEFT JOIN BUSINESS_ENTITY be ON site.BUSINESS_ENTITY_KEY = be.BUSINESS_ENTITY_KEY
    LEFT JOIN BUSINESS_ENTITY_TYPE bet ON be.BUSINESS_ENTITY_TYPE_KEY        = bet.BUSINESS_ENTITY_TYPE_KEY
    WHERE sideDetails.TAM_PROCESSING_FLAG =1
    AND bet.BUSINESS_ENTITY_TYPE_NAME     = 'ENTERPRISE';

rec_FgSite cur_FgSite%ROWTYPE;

V_ActualTamExists NUMBER(1);

BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE SITE_CHANGE_TAM_CASCADE';
DELETE FROM SITE_CHANGE_DATA WHERE RowID NOT IN (SELECT MIN(RowID) FROM SITE_CHANGE_DATA GROUP BY SITE_KEY,SITE_TYPE);
  OPEN cur_FgSite;
  LOOP
    FETCH cur_FgSite INTO rec_FgSite;
    EXIT
  WHEN cur_FgSite%NOTFOUND;
    BEGIN
      SELECT 1
      INTO V_ActualTamExists
      FROM DUAL
      WHERE EXISTS
        (SELECT 1
        FROM TAM_ALLOCATION tam
        WHERE tam.FUNCTIONAL_GROUP_ID = rec_FgSite.FUNCTIONAL_GROUP_ID
        AND tam.SITE_KEY              = rec_FgSite.NEW_SITE_KEY
        );
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      V_ActualTamExists := 0;
    END;
  IF (V_ActualTamExists = 1) THEN
    
    INSERT INTO SITE_CHANGE_TAM_CASCADE (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SITE_DESCRIPTION,SITE_TYPE,SUPPLIER_IDENTIFIER, 
    SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER)
      SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,rec_FgSite.NEW_SITE_DESCRIPTION,rec_FgSite.NEW_SITE_TYPE,SUPPLIER_IDENTIFIER,
      SUPPLIER,START_DATE,END_DATE,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER,SUPPLIER_ALLOCATION,TOTAL_SUPPLIER_ALLOCATION,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER||'-'||ITEM_IDENTIFIER,ITEM_ALLOCATION,ITEM_IDENTIFIER 
      FROM (
      SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,SITE_KEY,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,SUPPLIER_ALLOCATION,
         SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOTAL_SUPPLIER_ALLOCATION,
        SUM(SUPPLIER_ALLOCATION) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER) AS SUPPLIER_SUM_ALLOCATION,ITEM_IDENTIFIER,
		CASE WHEN ITEM_ALLOCATION IS NULL THEN
            CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
                CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100
                ELSE 0 END
            ELSE 0 END
        ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION
        FROM(
          SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,
          	ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM,
            CASE WHEN PERIOD_SUM_ALOC IS NULL THEN
            CASE WHEN REGION_PERIOD_SUM IS NULL THEN GLOBAL_ALLOCATION ELSE REGION_ALLOCATION END
            ELSE SUPPLIER_ALLOCATION
            END AS SUPPLIER_ALLOCATION,ITEM_IDENTIFIER,
 			CASE WHEN PERIOD_ITEM_ALLOCATION IS NULL THEN
            CASE WHEN REGION_PERIOD_ITEM_SUM IS NULL THEN GLOBAL_ITEM_ALLOCATION ELSE REGION_ITEM_ALLOCATION END
            ELSE ITEM_ALLOCATION
            END AS ITEM_ALLOCATION,
            CASE  WHEN (COUNT(CASE WHEN DATA_SOURCE = 'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0
            THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
            ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
            END AS DEFAULT_ITEM_IDENTIFIER,TAM_SUPPLIER_ALLOCATION_ID 
            FROM (
              SELECT x1.*,
                CASE WHEN x1.REGION_TAM IS NULL THEN NULL ELSE (SELECT tsa2.ALLOCATION FROM TAM_SUPPLIER_ALLOCATION tsa2 WHERE tsa2.TAM_ALLOCATION_ID = x1.REGION_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER) END AS REGION_ALLOCATION,
                CASE WHEN x1.REGION_TAM IS NULL THEN NULL ELSE (SELECT tia2.ALLOCATION FROM TAM_ITEM_ALLOCATION tia2 INNER JOIN TAM_SUPPLIER_ALLOCATION tsa2 ON tsa2.TAM_SUPPLIER_ALLOCATION_ID = tia2.TAM_SUPPLIER_ALLOCATION_ID WHERE tsa2.TAM_ALLOCATION_ID = x1.REGION_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER AND tia2.ITEM_KEY = x1.ITEM_KEY) END AS REGION_ITEM_ALLOCATION,
                CASE WHEN x1.REGION_TAM IS NULL THEN NULL ELSE (SELECT SUM(tsa2.ALLOCATION) FROM TAM_SUPPLIER_ALLOCATION tsa2 WHERE tsa2.TAM_ALLOCATION_ID = x1.REGION_TAM AND tsa2.START_DATE = x1.START_DATE) END AS REGION_PERIOD_SUM,
                CASE WHEN x1.REGION_TAM IS NULL THEN NULL ELSE (SELECT SUM(tia2.ALLOCATION) FROM TAM_ITEM_ALLOCATION tia2 INNER JOIN TAM_SUPPLIER_ALLOCATION tsa2 ON tsa2.TAM_SUPPLIER_ALLOCATION_ID = tia2.TAM_SUPPLIER_ALLOCATION_ID WHERE tsa2.TAM_ALLOCATION_ID = x1.REGION_TAM AND tsa2.START_DATE = x1.START_DATE) END AS REGION_PERIOD_ITEM_SUM,
                CASE WHEN x1.GLOBAL_TAM IS NULL THEN NULL ELSE (SELECT tsa2.ALLOCATION FROM TAM_SUPPLIER_ALLOCATION tsa2 WHERE tsa2.TAM_ALLOCATION_ID = x1.GLOBAL_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER) END AS GLOBAL_ALLOCATION,
                CASE WHEN x1.GLOBAL_TAM IS NULL THEN NULL ELSE (SELECT tia2.ALLOCATION FROM TAM_ITEM_ALLOCATION tia2 INNER JOIN TAM_SUPPLIER_ALLOCATION tsa2 ON tsa2.TAM_SUPPLIER_ALLOCATION_ID = tia2.TAM_SUPPLIER_ALLOCATION_ID WHERE tsa2.TAM_ALLOCATION_ID = x1.GLOBAL_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER AND tia2.ITEM_KEY = x1.ITEM_KEY) END AS GLOBAL_ITEM_ALLOCATION
                FROM(
                  SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,
                  SUPPLIER_ALLOCATION,ITEM_IDENTIFIER,ITEM_ALLOCATION,SUM(ITEM_ALLOCATION) OVER (PARTITION BY TAM_ALLOCATION_ID,START_DATE) PERIOD_ITEM_ALLOCATION,SUM(SUPPLIER_ALLOCATION) OVER (PARTITION BY TAM_ALLOCATION_ID,START_DATE) PERIOD_SUM_ALOC,ITEM_KEY,TAM_SUPPLIER_ALLOCATION_ID,
                  (SELECT tam1.TAM_ALLOCATION_ID FROM TAM_ALLOCATION tam1 WHERE tam1.FUNCTIONAL_GROUP_ID = x.FUNCTIONAL_GROUP_ID AND tam1.SITE_KEY = (SELECT PARENT_SITE_KEY FROM SITE WHERE SITE_KEY = x.SITE_KEY)) AS REGION_TAM,
                  (SELECT tam1.TAM_ALLOCATION_ID FROM TAM_ALLOCATION tam1 WHERE tam1.FUNCTIONAL_GROUP_ID = x.FUNCTIONAL_GROUP_ID AND tam1.SITE_KEY = 1) AS GLOBAL_TAM,DATA_SOURCE
                  FROM (
                    SELECT ta.TAM_ALLOCATION_ID,ta.FUNCTIONAL_GROUP_ID,fg.NAME AS FG_NAME,ta.LAST_CHANGED_BY,ta.LAST_CHANGED_ON,ta.CREATED_BY,ta.CREATED_ON,ta.SITE_KEY,tsa.BUSINESS_ENTITY_KEY AS SUPPLIER_IDENTIFIER,
                    be.BUSINESS_ENTITY_NAME AS SUPPLIER,tsa.START_DATE,tsa.END_DATE,tsa.ALLOCATION AS SUPPLIER_ALLOCATION,im.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,tia.ALLOCATION AS ITEM_ALLOCATION,tsa.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,tia.ITEM_KEY AS ITEM_KEY,im.DATA_SOURCE AS DATA_SOURCE FROM TAM_ALLOCATION ta
                    LEFT JOIN TAM_SUPPLIER_ALLOCATION tsa  ON tsa.TAM_ALLOCATION_ID = ta.TAM_ALLOCATION_ID
                    LEFT JOIN TAM_ITEM_ALLOCATION tia ON tsa.TAM_SUPPLIER_ALLOCATION_ID = tia.TAM_SUPPLIER_ALLOCATION_ID
                    LEFT JOIN FUNCTIONAL_GROUP fg ON fg.FUNCTIONAL_GROUP_ID = ta.FUNCTIONAL_GROUP_ID
                    LEFT JOIN ITEM_MASTER im on tia.ITEM_KEY = im.ITEM_KEY
                    INNER JOIN SITE s ON ta.SITE_KEY = s.SITE_KEY
                    INNER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
                    WHERE tsa.START_DATE >= V_START_DATE
                    AND ta.FUNCTIONAL_GROUP_ID = rec_FgSite.FUNCTIONAL_GROUP_ID  AND s.SITE_KEY = rec_FgSite.NEW_SITE_KEY)x 
                  ) x1 
                ) x2
              ) x3
          ) x4  WHERE x4.SUPPLIER_SUM_ALLOCATION > 0 AND x4.ITEM_ALLOCATION > 0;

  ELSIF (V_ActualTamExists = 0 AND rec_FgSite.SITE_TYPE = 'REGION') THEN
    
    INSERT INTO SITE_CHANGE_TAM_CASCADE (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SITE_DESCRIPTION,SITE_TYPE,SUPPLIER_IDENTIFIER, 
    SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER)
    SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,rec_FgSite.NEW_SITE_KEY,rec_FgSite.NEW_SITE_DESCRIPTION,rec_FgSite.NEW_SITE_TYPE,SUPPLIER_IDENTIFIER,
    SUPPLIER,START_DATE,END_DATE,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER,SUPPLIER_ALLOCATION,TOTAL_SUPPLIER_ALLOCATION,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER||'-'||ITEM_IDENTIFIER,ITEM_ALLOCATION,ITEM_IDENTIFIER
	FROM (
    SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,rec_FgSite.NEW_SITE_KEY,rec_FgSite.NEW_SITE_DESCRIPTION,rec_FgSite.NEW_SITE_TYPE,SUPPLIER_IDENTIFIER,
    SUPPLIER,START_DATE,END_DATE,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER,SUPPLIER_ALLOCATION,TOTAL_SUPPLIER_ALLOCATION,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER||'-'||ITEM_IDENTIFIER,
    CASE WHEN ITEM_ALLOCATION IS NULL THEN
        CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
            CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100
            ELSE 0 END
        ELSE 0 END
    ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION,ITEM_IDENTIFIER,SUPPLIER_SUM_ALLOCATION,SITE_KEY
    FROM (
      SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,SITE_KEY,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,SUPPLIER_ALLOCATION,
      SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOTAL_SUPPLIER_ALLOCATION,
      SUM(SUPPLIER_ALLOCATION) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER) AS SUPPLIER_SUM_ALLOCATION,ITEM_IDENTIFIER,ITEM_ALLOCATION,
      CASE  WHEN (COUNT(CASE WHEN DATA_SOURCE = 'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0
      THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
      ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
      END AS DEFAULT_ITEM_IDENTIFIER,TAM_SUPPLIER_ALLOCATION_ID
      FROM(
        SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,
        ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM,
        CASE WHEN PERIOD_SUM_ALOC IS NULL THEN GLOBAL_ALLOCATION
        ELSE SUPPLIER_ALLOCATION
        END AS SUPPLIER_ALLOCATION,ITEM_IDENTIFIER,DATA_SOURCE,TAM_SUPPLIER_ALLOCATION_ID,
        CASE WHEN PERIOD_ITEM_ALLOCATION IS NULL THEN GLOBAL_ITEM_ALLOCATION
        ELSE ITEM_ALLOCATION
        END AS ITEM_ALLOCATION FROM (
          SELECT x1.*,
          CASE WHEN x1.GLOBAL_TAM IS NULL THEN NULL ELSE (SELECT tsa2.ALLOCATION FROM TAM_SUPPLIER_ALLOCATION tsa2 WHERE tsa2.TAM_ALLOCATION_ID = x1.GLOBAL_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER) END AS GLOBAL_ALLOCATION,
          CASE WHEN x1.GLOBAL_TAM IS NULL THEN NULL ELSE (SELECT tia2.ALLOCATION FROM TAM_ITEM_ALLOCATION tia2 INNER JOIN TAM_SUPPLIER_ALLOCATION tsa2 ON tsa2.TAM_SUPPLIER_ALLOCATION_ID = tia2.TAM_SUPPLIER_ALLOCATION_ID WHERE tsa2.TAM_ALLOCATION_ID = x1.GLOBAL_TAM AND tsa2.START_DATE = x1.START_DATE AND tsa2.BUSINESS_ENTITY_KEY = x1.SUPPLIER_IDENTIFIER AND tia2.ITEM_KEY = x1.ITEM_KEY) END AS GLOBAL_ITEM_ALLOCATION
          FROM(
            SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,
            SUPPLIER_ALLOCATION,ITEM_IDENTIFIER,DATA_SOURCE,ITEM_ALLOCATION,SUM(ITEM_ALLOCATION) OVER (PARTITION BY TAM_ALLOCATION_ID,START_DATE) PERIOD_ITEM_ALLOCATION,SUM(SUPPLIER_ALLOCATION) OVER (PARTITION BY TAM_ALLOCATION_ID,START_DATE) PERIOD_SUM_ALOC,ITEM_KEY,TAM_SUPPLIER_ALLOCATION_ID,
            (SELECT tam1.TAM_ALLOCATION_ID FROM TAM_ALLOCATION tam1 WHERE tam1.FUNCTIONAL_GROUP_ID = x.FUNCTIONAL_GROUP_ID AND tam1.SITE_KEY = 1) AS GLOBAL_TAM
            FROM (
              SELECT ta.TAM_ALLOCATION_ID,ta.FUNCTIONAL_GROUP_ID,fg.NAME AS FG_NAME,ta.LAST_CHANGED_BY,ta.LAST_CHANGED_ON,ta.CREATED_BY,ta.CREATED_ON,ta.SITE_KEY,tsa.BUSINESS_ENTITY_KEY AS SUPPLIER_IDENTIFIER,
              be.BUSINESS_ENTITY_NAME AS SUPPLIER,tsa.START_DATE,tsa.END_DATE,tsa.ALLOCATION AS SUPPLIER_ALLOCATION,im.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,im.DATA_SOURCE AS DATA_SOURCE,tia.ITEM_KEY AS ITEM_KEY,tia.ALLOCATION AS ITEM_ALLOCATION,tsa.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID FROM TAM_ALLOCATION ta
              LEFT JOIN TAM_SUPPLIER_ALLOCATION tsa  ON tsa.TAM_ALLOCATION_ID = ta.TAM_ALLOCATION_ID
              LEFT JOIN TAM_ITEM_ALLOCATION tia ON tsa.TAM_SUPPLIER_ALLOCATION_ID = tia.TAM_SUPPLIER_ALLOCATION_ID
              LEFT JOIN FUNCTIONAL_GROUP fg ON fg.FUNCTIONAL_GROUP_ID = ta.FUNCTIONAL_GROUP_ID
              INNER JOIN ITEM_FG_MAP ifm ON ifm.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID AND ifm.ITEM_KEY = tia.ITEM_KEY
              INNER JOIN ITEM_MASTER im ON im.ITEM_KEY = ifm.ITEM_KEY
              INNER JOIN ITEM_AVL avl ON avl.ITEM_KEY = im.ITEM_KEY AND avl.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
              INNER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
              INNER JOIN SITE s ON ta.SITE_KEY = s.SITE_KEY
              WHERE tsa.START_DATE >= V_START_DATE
              AND ta.FUNCTIONAL_GROUP_ID = rec_FgSite.FUNCTIONAL_GROUP_ID AND s.SITE_KEY = rec_FgSite.SITE_KEY)x 
              ) x1 
            ) x2 
          ) x3 
        ) x4 
      ) x5 WHERE x5.SUPPLIER_SUM_ALLOCATION > 0 AND x5.ITEM_ALLOCATION > 0;

  ELSIF (V_ActualTamExists = 0 AND rec_FgSite.SITE_TYPE = 'GLOBAL') THEN
   INSERT INTO SITE_CHANGE_TAM_CASCADE (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SITE_DESCRIPTION,SITE_TYPE,SUPPLIER_IDENTIFIER, 
    SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER)
    SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,rec_FgSite.NEW_SITE_KEY,rec_FgSite.NEW_SITE_DESCRIPTION,rec_FgSite.NEW_SITE_TYPE,SUPPLIER_IDENTIFIER,
    SUPPLIER,START_DATE,END_DATE,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER,SUPPLIER_ALLOCATION,TOTAL_SUPPLIER_ALLOCATION,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER||'-'||ITEM_IDENTIFIER,ITEM_ALLOCATION,ITEM_IDENTIFIER
	FROM (
    SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,rec_FgSite.NEW_SITE_KEY,rec_FgSite.NEW_SITE_DESCRIPTION,rec_FgSite.NEW_SITE_TYPE,SUPPLIER_IDENTIFIER,
    SUPPLIER,START_DATE,END_DATE,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER,SUPPLIER_ALLOCATION,TOTAL_SUPPLIER_ALLOCATION,FUNCTIONAL_GROUP_ID||'-'||SITE_KEY||'-'||SUPPLIER_IDENTIFIER||'-'||ITEM_IDENTIFIER,
    CASE WHEN ITEM_ALLOCATION IS NULL THEN
        CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
            CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100 
            ELSE 0 END
        ELSE 0 END
    ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION,ITEM_IDENTIFIER,SUPPLIER_SUM_ALLOCATION,SITE_KEY
    FROM (
      SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,SITE_KEY,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SUPPLIER_IDENTIFIER,SUPPLIER,START_DATE,END_DATE,SUPPLIER_ALLOCATION,
      SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOTAL_SUPPLIER_ALLOCATION,
      SUM(SUPPLIER_ALLOCATION) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER) AS SUPPLIER_SUM_ALLOCATION,ITEM_IDENTIFIER,ITEM_ALLOCATION,TAM_SUPPLIER_ALLOCATION_ID,
      CASE  WHEN (COUNT(CASE WHEN DATA_SOURCE = 'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0
      THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
      ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
      END AS DEFAULT_ITEM_IDENTIFIER
      FROM(
        SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,CREATED_BY,CREATED_ON,SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER,SUPPLIER_ALLOCATION,START_DATE,END_DATE,ITEM_IDENTIFIER,DATA_SOURCE,ITEM_ALLOCATION,TAM_SUPPLIER_ALLOCATION_ID,
        ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM
        FROM (
          SELECT ta.TAM_ALLOCATION_ID,ta.FUNCTIONAL_GROUP_ID,fg.NAME AS FG_NAME,ta.LAST_CHANGED_BY,ta.LAST_CHANGED_ON,ta.CREATED_BY,ta.CREATED_ON,ta.SITE_KEY,tsa.BUSINESS_ENTITY_KEY AS SUPPLIER_IDENTIFIER,
          be.BUSINESS_ENTITY_NAME AS SUPPLIER,tsa.START_DATE,tsa.END_DATE,tsa.ALLOCATION AS SUPPLIER_ALLOCATION,im.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,im.DATA_SOURCE AS DATA_SOURCE,tia.ALLOCATION AS ITEM_ALLOCATION,tsa.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID FROM TAM_ALLOCATION ta
          LEFT JOIN TAM_SUPPLIER_ALLOCATION tsa  ON tsa.TAM_ALLOCATION_ID = ta.TAM_ALLOCATION_ID
          LEFT JOIN TAM_ITEM_ALLOCATION tia ON tsa.TAM_SUPPLIER_ALLOCATION_ID = tia.TAM_SUPPLIER_ALLOCATION_ID
          LEFT JOIN FUNCTIONAL_GROUP fg ON fg.FUNCTIONAL_GROUP_ID = ta.FUNCTIONAL_GROUP_ID
          INNER JOIN ITEM_FG_MAP ifm ON ifm.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID AND ifm.ITEM_KEY = tia.ITEM_KEY
          INNER JOIN ITEM_MASTER im ON im.ITEM_KEY = ifm.ITEM_KEY
          INNER JOIN ITEM_AVL avl ON avl.ITEM_KEY = im.ITEM_KEY AND avl.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
          INNER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
          INNER JOIN SITE s ON ta.SITE_KEY = s.SITE_KEY
          WHERE tsa.START_DATE >= V_START_DATE
          AND ta.FUNCTIONAL_GROUP_ID = rec_FgSite.FUNCTIONAL_GROUP_ID  AND s.SITE_KEY = 1)x 
          ) x1 
        ) x2 
      ) x3 WHERE x3.SUPPLIER_SUM_ALLOCATION > 0 AND x3.ITEM_ALLOCATION > 0;
  END IF;
  COMMIT;
  END LOOP;
  CLOSE cur_FgSite;
   OPEN VOUT_RESULT FOR
  SELECT 1 AS COUNT FROM DUAL;
END;
/

CREATE OR REPLACE VIEW IV_BOM_EXTRACT AS
SELECT B.BOM_KEY,
I.ITEM_IDENTIFIER B_ITEM_IDENTIFIER,
I.ITEM_UNIQUE_IDENTIFIER B_ITEM_UNIQUE_IDENTIFIER,
I.VERSION B_VERSION,
I.REVISION B_REVISION,
I.BUSINESS_ENTITY_IDENTIFIER B_BUSINESS_ENTITY_IDENTIFIER,
I.BUSINESS_ENTITY_TYPE_NAME B_BUSINESS_ENTITY_TYPE_NAME,
I.DATA_SOURCE B_DATA_SOURCE,
COALESCE(B.UPDATE_DT,B.INSERT_DT) UPDATE_DT,
BLI.BOM_LINE_ITEM_KEY BLI_KEY,
II.ITEM_IDENTIFIER BLI_ITEM_IDENTIFIER,
II.ITEM_UNIQUE_IDENTIFIER BLI_ITEM_UNIQUE_IDENTIFIER,
II.VERSION BLI_VERSION,
II.REVISION BLI_REVISION,
II.BUSINESS_ENTITY_IDENTIFIER BLI_BUSINESS_ENTITY_IDENTIFIER,
II.BUSINESS_ENTITY_TYPE_NAME BLI_BUSINESS_ENTITY_TYPE_NAME,
BLI.MANAGED_FLAG,
BLI.ITEM_QUANTITY,
B.CURRENT_FLAG,
B.STATUS,
B.STATUS_CHANGE_DATE,
B.STATUS_LAST_CHANGE_BY,
B.CONTEXT_OBJECT_TYPE,
B.CONTEXT_OBJECT_ID,
B.STRING_ATTRIBUTE1 AS BOM_STRING_ATTRIBUTE1,
B.STRING_ATTRIBUTE2 AS BOM_STRING_ATTRIBUTE2,
B.STRING_ATTRIBUTE3 AS BOM_STRING_ATTRIBUTE3,
B.STRING_ATTRIBUTE4 AS BOM_STRING_ATTRIBUTE4,
B.STRING_ATTRIBUTE5 AS BOM_STRING_ATTRIBUTE5,
B.STRING_ATTRIBUTE6 AS BOM_STRING_ATTRIBUTE6,
B.STRING_ATTRIBUTE7 AS BOM_STRING_ATTRIBUTE7,
B.STRING_ATTRIBUTE8 AS BOM_STRING_ATTRIBUTE8,
B.STRING_ATTRIBUTE9 AS BOM_STRING_ATTRIBUTE9,
B.STRING_ATTRIBUTE10 AS BOM_STRING_ATTRIBUTE10,
B.NUMBER_ATTRIBUTE1 AS BOM_NUMBER_ATTRIBUTE1,
B.NUMBER_ATTRIBUTE2 AS BOM_NUMBER_ATTRIBUTE2,
B.NUMBER_ATTRIBUTE3 AS BOM_NUMBER_ATTRIBUTE3,
B.NUMBER_ATTRIBUTE4 AS BOM_NUMBER_ATTRIBUTE4,
B.NUMBER_ATTRIBUTE5 AS BOM_NUMBER_ATTRIBUTE5,
B.NUMBER_ATTRIBUTE6 AS BOM_NUMBER_ATTRIBUTE6,
B.NUMBER_ATTRIBUTE7 AS BOM_NUMBER_ATTRIBUTE7,
B.NUMBER_ATTRIBUTE8 AS BOM_NUMBER_ATTRIBUTE8,
B.NUMBER_ATTRIBUTE9 AS BOM_NUMBER_ATTRIBUTE9,
B.NUMBER_ATTRIBUTE10 AS BOM_NUMBER_ATTRIBUTE10,
B.FLOAT_ATTRIBUTE1 AS BOM_FLOAT_ATTRIBUTE1,
B.FLOAT_ATTRIBUTE2 AS BOM_FLOAT_ATTRIBUTE2,
B.FLOAT_ATTRIBUTE3 AS BOM_FLOAT_ATTRIBUTE3,
B.FLOAT_ATTRIBUTE4 AS BOM_FLOAT_ATTRIBUTE4,
B.FLOAT_ATTRIBUTE5 AS BOM_FLOAT_ATTRIBUTE5,
B.FLOAT_ATTRIBUTE6 AS BOM_FLOAT_ATTRIBUTE6,
B.FLOAT_ATTRIBUTE7 AS BOM_FLOAT_ATTRIBUTE7,
B.FLOAT_ATTRIBUTE8 AS BOM_FLOAT_ATTRIBUTE8,
B.FLOAT_ATTRIBUTE9 AS BOM_FLOAT_ATTRIBUTE9,
B.FLOAT_ATTRIBUTE10 AS BOM_FLOAT_ATTRIBUTE10,
B.DATE_ATTRIBUTE1 AS BOM_DATE_ATTRIBUTE1,
B.DATE_ATTRIBUTE2 AS BOM_DATE_ATTRIBUTE2,
B.DATE_ATTRIBUTE3 AS BOM_DATE_ATTRIBUTE3,
B.DATE_ATTRIBUTE4 AS BOM_DATE_ATTRIBUTE4,
B.DATE_ATTRIBUTE5 AS BOM_DATE_ATTRIBUTE5,
B.DATE_ATTRIBUTE6 AS BOM_DATE_ATTRIBUTE6,
B.DATE_ATTRIBUTE7 AS BOM_DATE_ATTRIBUTE7,
B.DATE_ATTRIBUTE8 AS BOM_DATE_ATTRIBUTE8,
B.DATE_ATTRIBUTE9 AS BOM_DATE_ATTRIBUTE9,
B.DATE_ATTRIBUTE10 AS BOM_DATE_ATTRIBUTE10,
BLI.STRING_ATTRIBUTE1 AS BOM_LINE_STRING_ATTRIBUTE1,
BLI.STRING_ATTRIBUTE2 AS BOM_LINE_STRING_ATTRIBUTE2,
BLI.STRING_ATTRIBUTE3 AS BOM_LINE_STRING_ATTRIBUTE3,
BLI.STRING_ATTRIBUTE4 AS BOM_LINE_STRING_ATTRIBUTE4,
BLI.STRING_ATTRIBUTE5 AS BOM_LINE_STRING_ATTRIBUTE5,
BLI.STRING_ATTRIBUTE6 AS BOM_LINE_STRING_ATTRIBUTE6,
BLI.STRING_ATTRIBUTE7 AS BOM_LINE_STRING_ATTRIBUTE7,
BLI.STRING_ATTRIBUTE8 AS BOM_LINE_STRING_ATTRIBUTE8,
BLI.STRING_ATTRIBUTE9 AS BOM_LINE_STRING_ATTRIBUTE9,
BLI.STRING_ATTRIBUTE10 AS BOM_LINE_STRING_ATTRIBUTE10,
BLI.NUMBER_ATTRIBUTE1 AS BOM_LINE_NUMBER_ATTRIBUTE1,
BLI.NUMBER_ATTRIBUTE2 AS BOM_LINE_NUMBER_ATTRIBUTE2,
BLI.NUMBER_ATTRIBUTE3 AS BOM_LINE_NUMBER_ATTRIBUTE3,
BLI.NUMBER_ATTRIBUTE4 AS BOM_LINE_NUMBER_ATTRIBUTE4,
BLI.NUMBER_ATTRIBUTE5 AS BOM_LINE_NUMBER_ATTRIBUTE5,
BLI.NUMBER_ATTRIBUTE6 AS BOM_LINE_NUMBER_ATTRIBUTE6,
BLI.NUMBER_ATTRIBUTE7 AS BOM_LINE_NUMBER_ATTRIBUTE7,
BLI.NUMBER_ATTRIBUTE8 AS BOM_LINE_NUMBER_ATTRIBUTE8,
BLI.NUMBER_ATTRIBUTE9 AS BOM_LINE_NUMBER_ATTRIBUTE9,
BLI.NUMBER_ATTRIBUTE10 AS BOM_LINE_NUMBER_ATTRIBUTE10,
BLI.FLOAT_ATTRIBUTE1 AS BOM_LINE_FLOAT_ATTRIBUTE1,
BLI.FLOAT_ATTRIBUTE2 AS BOM_LINE_FLOAT_ATTRIBUTE2,
BLI.FLOAT_ATTRIBUTE3 AS BOM_LINE_FLOAT_ATTRIBUTE3,
BLI.FLOAT_ATTRIBUTE4 AS BOM_LINE_FLOAT_ATTRIBUTE4,
BLI.FLOAT_ATTRIBUTE5 AS BOM_LINE_FLOAT_ATTRIBUTE5,
BLI.FLOAT_ATTRIBUTE6 AS BOM_LINE_FLOAT_ATTRIBUTE6,
BLI.FLOAT_ATTRIBUTE7 AS BOM_LINE_FLOAT_ATTRIBUTE7,
BLI.FLOAT_ATTRIBUTE8 AS BOM_LINE_FLOAT_ATTRIBUTE8,
BLI.FLOAT_ATTRIBUTE9 AS BOM_LINE_FLOAT_ATTRIBUTE9,
BLI.FLOAT_ATTRIBUTE10 AS BOM_LINE_FLOAT_ATTRIBUTE10,
BLI.DATE_ATTRIBUTE1 AS BOM_LINE_DATE_ATTRIBUTE1,
BLI.DATE_ATTRIBUTE2 AS BOM_LINE_DATE_ATTRIBUTE2,
BLI.DATE_ATTRIBUTE3 AS BOM_LINE_DATE_ATTRIBUTE3,
BLI.DATE_ATTRIBUTE4 AS BOM_LINE_DATE_ATTRIBUTE4,
BLI.DATE_ATTRIBUTE5 AS BOM_LINE_DATE_ATTRIBUTE5,
BLI.DATE_ATTRIBUTE6 AS BOM_LINE_DATE_ATTRIBUTE6,
BLI.DATE_ATTRIBUTE7 AS BOM_LINE_DATE_ATTRIBUTE7,
BLI.DATE_ATTRIBUTE8 AS BOM_LINE_DATE_ATTRIBUTE8,
BLI.DATE_ATTRIBUTE9 AS BOM_LINE_DATE_ATTRIBUTE9,
BLI.DATE_ATTRIBUTE10 AS BOM_LINE_DATE_ATTRIBUTE10
FROM BOM_HEADER B
JOIN IV_ITEM_BUSINESS I ON
I.ITEM_KEY = B.ITEM_KEY
JOIN BOM_LINE_ITEM BLI ON
BLI.BOM_KEY = B.BOM_KEY
JOIN IV_ITEM_BUSINESS II ON
II.ITEM_KEY = BLI.ITEM_KEY;



CREATE INDEX ITEM_FG_MAP_ITEM ON ITEM_FG_MAP (ITEM_KEY) TABLESPACE AUDIT_DATA;
CREATE INDEX ITEM_FG_MAP_FG ON ITEM_FG_MAP (FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;
CREATE INDEX ITEM_ITEM_CATEGORY_ITEM ON ITEM_ITEM_CATEGORY (ITEM_KEY) TABLESPACE AUDIT_DATA;
CREATE INDEX FG_PFG_MAP_FG ON FG_PFG_MAP (FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;
CREATE INDEX FG_PFG_MAP_PFG ON FG_PFG_MAP (PARENT_FUNCTIONAL_GROUP_ID) TABLESPACE AUDIT_DATA;


CREATE OR REPLACE PROCEDURE TAM_DELETE_CASCADE_INSERT(
    vOUT_RESULT OUT SYS_REFCURSOR )
AS
BEGIN
  INSERT
  INTO TAM_ALLOC_CASCADE_PROC_STG2
    (
      TAM_ALLOCATION_ID,
      FUNCTIONAL_GROUP_ID,
      FG_NAME,
      LAST_CHANGED_BY,
      LAST_CHANGED_ON,
      ALLOW_HEDGING,
      CREATED_BY,
      CREATED_ON,
      DISCP_EXTRACT_FLAG,
      SITE_KEY,
      SITE_IDENTIFIER,
      SITE_DESCRIPTION,
      SITE_TYPE,
      PARENT_SITE_KEY,
      REGION_PARENT_EXISTS
    )
  SELECT t.TAM_ALLOCATION_ID,
    t.FUNCTIONAL_GROUP_ID,
    fg.NAME,
    t.LAST_CHANGED_BY,
    t.LAST_CHANGED_ON,
    t.ALLOW_HEDGING,
    t.CREATED_BY,
    t.CREATED_ON,
    t.DISCP_EXTRACT_FLAG,
    t.SITE_KEY,
    s.SITE_IDENTIFIER,
    s.SITE_DESCRIPTION,
    s.SITE_TYPE,
    s.PARENT_SITE_KEY,
    1
  FROM TAM_ALLOCATION t
  INNER JOIN FUNCTIONAL_GROUP fg
  ON t.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID
  INNER JOIN site s
  ON s.SITE_KEY                = t.SITE_KEY
  WHERE t.CURRENT_DATA_DELETED = 'Y'
  AND t.DISCP_EXTRACT_FLAG     = 'P';
  COMMIT;
  OPEN VOUT_RESULT FOR SELECT 1
AS
  COUNT FROM DUAL;
EXCEPTION
WHEN OTHERS THEN
  RAISE;
END TAM_DELETE_CASCADE_INSERT;
/

CREATE INDEX ITEM_EXTRACT_KEY ON ITEM_MASTER_EXTRACT(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_ATTR_KEY ON ITEM_ADD_ATTRIBUTE(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_PLATFORM_KEY ON ITEM_ITEM_PLATFORM(ITEM_KEY) TABLESPACE AUDIT_INDEX;
CREATE INDEX ITEM_ITEM_PLATFORM_KEY ON ITEM_ITEM_PLATFORM(ITEM_PLATFORM_KEY) TABLESPACE AUDIT_INDEX;

ALTER TABLE SITE_CHANGE_TAM_CASCADE ADD (SITE_IDENTIFIER VARCHAR2(255 BYTE));
ALTER TABLE SITE_CHANGE_TAM_CASCADE ADD (SUPPLIER_KEY NUMBER(19));