CREATE OR REPLACE FORCE EDITIONABLE VIEW IV_BOM_EXTRACT AS 
  SELECT B.BOM_KEY,
I.ITEM_IDENTIFIER B_ITEM_IDENTIFIER,
I.ITEM_UNIQUE_IDENTIFIER B_ITEM_UNIQUE_IDENTIFIER,
I.VERSION B_VERSION,
I.REVISION B_REVISION,
I.BUSINESS_ENTITY_IDENTIFIER B_BUSINESS_ENTITY_IDENTIFIER,
I.BUSINESS_ENTITY_TYPE_NAME B_BUSINESS_ENTITY_TYPE_NAME,
I.DATA_SOURCE B_DATA_SOURCE,
B.EFFECTIVE_FROM_DT B_EFFECTIVE_FROM_DT,
B.EFFECTIVE_TO_DT B_EFFECTIVE_TO_DT,
COALESCE(B.UPDATE_DT,B.INSERT_DT) UPDATE_DT,
BLI.BOM_LINE_ITEM_KEY BLI_KEY,
II.ITEM_IDENTIFIER BLI_ITEM_IDENTIFIER,
II.ITEM_UNIQUE_IDENTIFIER BLI_ITEM_UNIQUE_IDENTIFIER,
II.VERSION BLI_VERSION,
II.REVISION BLI_REVISION,
II.BUSINESS_ENTITY_IDENTIFIER BLI_BUSINESS_ENTITY_IDENTIFIER,
II.BUSINESS_ENTITY_TYPE_NAME BLI_BUSINESS_ENTITY_TYPE_NAME,
BLI.EFFECTIVE_FROM_DT BLI_EFFECTIVE_FROM_DT,
BLI.EFFECTIVE_TO_DT BLI_EFFECTIVE_TO_DT,
BLI.MANAGED_FLAG,
BLI.ITEM_QUANTITY,
B.CURRENT_FLAG,
B.STATUS,
B.STATUS_CHANGE_DATE,
B.STATUS_LAST_CHANGE_BY,
B.CONTEXT_OBJECT_TYPE,
B.CONTEXT_OBJECT_ID,
B.STRING_ATTRIBUTE1 AS BOM_STRING_ATTRIBUTE1,
B.STRING_ATTRIBUTE2 AS BOM_STRING_ATTRIBUTE2,
B.STRING_ATTRIBUTE3 AS BOM_STRING_ATTRIBUTE3,
B.STRING_ATTRIBUTE4 AS BOM_STRING_ATTRIBUTE4,
B.STRING_ATTRIBUTE5 AS BOM_STRING_ATTRIBUTE5,
B.STRING_ATTRIBUTE6 AS BOM_STRING_ATTRIBUTE6,
B.STRING_ATTRIBUTE7 AS BOM_STRING_ATTRIBUTE7,
B.STRING_ATTRIBUTE8 AS BOM_STRING_ATTRIBUTE8,
B.STRING_ATTRIBUTE9 AS BOM_STRING_ATTRIBUTE9,
B.STRING_ATTRIBUTE10 AS BOM_STRING_ATTRIBUTE10,
B.NUMBER_ATTRIBUTE1 AS BOM_NUMBER_ATTRIBUTE1,
B.NUMBER_ATTRIBUTE2 AS BOM_NUMBER_ATTRIBUTE2,
B.NUMBER_ATTRIBUTE3 AS BOM_NUMBER_ATTRIBUTE3,
B.NUMBER_ATTRIBUTE4 AS BOM_NUMBER_ATTRIBUTE4,
B.NUMBER_ATTRIBUTE5 AS BOM_NUMBER_ATTRIBUTE5,
B.NUMBER_ATTRIBUTE6 AS BOM_NUMBER_ATTRIBUTE6,
B.NUMBER_ATTRIBUTE7 AS BOM_NUMBER_ATTRIBUTE7,
B.NUMBER_ATTRIBUTE8 AS BOM_NUMBER_ATTRIBUTE8,
B.NUMBER_ATTRIBUTE9 AS BOM_NUMBER_ATTRIBUTE9,
B.NUMBER_ATTRIBUTE10 AS BOM_NUMBER_ATTRIBUTE10,
B.FLOAT_ATTRIBUTE1 AS BOM_FLOAT_ATTRIBUTE1,
B.FLOAT_ATTRIBUTE2 AS BOM_FLOAT_ATTRIBUTE2,
B.FLOAT_ATTRIBUTE3 AS BOM_FLOAT_ATTRIBUTE3,
B.FLOAT_ATTRIBUTE4 AS BOM_FLOAT_ATTRIBUTE4,
B.FLOAT_ATTRIBUTE5 AS BOM_FLOAT_ATTRIBUTE5,
B.FLOAT_ATTRIBUTE6 AS BOM_FLOAT_ATTRIBUTE6,
B.FLOAT_ATTRIBUTE7 AS BOM_FLOAT_ATTRIBUTE7,
B.FLOAT_ATTRIBUTE8 AS BOM_FLOAT_ATTRIBUTE8,
B.FLOAT_ATTRIBUTE9 AS BOM_FLOAT_ATTRIBUTE9,
B.FLOAT_ATTRIBUTE10 AS BOM_FLOAT_ATTRIBUTE10,
B.DATE_ATTRIBUTE1 AS BOM_DATE_ATTRIBUTE1,
B.DATE_ATTRIBUTE2 AS BOM_DATE_ATTRIBUTE2,
B.DATE_ATTRIBUTE3 AS BOM_DATE_ATTRIBUTE3,
B.DATE_ATTRIBUTE4 AS BOM_DATE_ATTRIBUTE4,
B.DATE_ATTRIBUTE5 AS BOM_DATE_ATTRIBUTE5,
B.DATE_ATTRIBUTE6 AS BOM_DATE_ATTRIBUTE6,
B.DATE_ATTRIBUTE7 AS BOM_DATE_ATTRIBUTE7,
B.DATE_ATTRIBUTE8 AS BOM_DATE_ATTRIBUTE8,
B.DATE_ATTRIBUTE9 AS BOM_DATE_ATTRIBUTE9,
B.DATE_ATTRIBUTE10 AS BOM_DATE_ATTRIBUTE10,
BLI.STRING_ATTRIBUTE1 AS BOM_LINE_STRING_ATTRIBUTE1,
BLI.STRING_ATTRIBUTE2 AS BOM_LINE_STRING_ATTRIBUTE2,
BLI.STRING_ATTRIBUTE3 AS BOM_LINE_STRING_ATTRIBUTE3,
BLI.STRING_ATTRIBUTE4 AS BOM_LINE_STRING_ATTRIBUTE4,
BLI.STRING_ATTRIBUTE5 AS BOM_LINE_STRING_ATTRIBUTE5,
BLI.STRING_ATTRIBUTE6 AS BOM_LINE_STRING_ATTRIBUTE6,
BLI.STRING_ATTRIBUTE7 AS BOM_LINE_STRING_ATTRIBUTE7,
BLI.STRING_ATTRIBUTE8 AS BOM_LINE_STRING_ATTRIBUTE8,
BLI.STRING_ATTRIBUTE9 AS BOM_LINE_STRING_ATTRIBUTE9,
BLI.STRING_ATTRIBUTE10 AS BOM_LINE_STRING_ATTRIBUTE10,
BLI.NUMBER_ATTRIBUTE1 AS BOM_LINE_NUMBER_ATTRIBUTE1,
BLI.NUMBER_ATTRIBUTE2 AS BOM_LINE_NUMBER_ATTRIBUTE2,
BLI.NUMBER_ATTRIBUTE3 AS BOM_LINE_NUMBER_ATTRIBUTE3,
BLI.NUMBER_ATTRIBUTE4 AS BOM_LINE_NUMBER_ATTRIBUTE4,
BLI.NUMBER_ATTRIBUTE5 AS BOM_LINE_NUMBER_ATTRIBUTE5,
BLI.NUMBER_ATTRIBUTE6 AS BOM_LINE_NUMBER_ATTRIBUTE6,
BLI.NUMBER_ATTRIBUTE7 AS BOM_LINE_NUMBER_ATTRIBUTE7,
BLI.NUMBER_ATTRIBUTE8 AS BOM_LINE_NUMBER_ATTRIBUTE8,
BLI.NUMBER_ATTRIBUTE9 AS BOM_LINE_NUMBER_ATTRIBUTE9,
BLI.NUMBER_ATTRIBUTE10 AS BOM_LINE_NUMBER_ATTRIBUTE10,
BLI.FLOAT_ATTRIBUTE1 AS BOM_LINE_FLOAT_ATTRIBUTE1,
BLI.FLOAT_ATTRIBUTE2 AS BOM_LINE_FLOAT_ATTRIBUTE2,
BLI.FLOAT_ATTRIBUTE3 AS BOM_LINE_FLOAT_ATTRIBUTE3,
BLI.FLOAT_ATTRIBUTE4 AS BOM_LINE_FLOAT_ATTRIBUTE4,
BLI.FLOAT_ATTRIBUTE5 AS BOM_LINE_FLOAT_ATTRIBUTE5,
BLI.FLOAT_ATTRIBUTE6 AS BOM_LINE_FLOAT_ATTRIBUTE6,
BLI.FLOAT_ATTRIBUTE7 AS BOM_LINE_FLOAT_ATTRIBUTE7,
BLI.FLOAT_ATTRIBUTE8 AS BOM_LINE_FLOAT_ATTRIBUTE8,
BLI.FLOAT_ATTRIBUTE9 AS BOM_LINE_FLOAT_ATTRIBUTE9,
BLI.FLOAT_ATTRIBUTE10 AS BOM_LINE_FLOAT_ATTRIBUTE10,
BLI.DATE_ATTRIBUTE1 AS BOM_LINE_DATE_ATTRIBUTE1,
BLI.DATE_ATTRIBUTE2 AS BOM_LINE_DATE_ATTRIBUTE2,
BLI.DATE_ATTRIBUTE3 AS BOM_LINE_DATE_ATTRIBUTE3,
BLI.DATE_ATTRIBUTE4 AS BOM_LINE_DATE_ATTRIBUTE4,
BLI.DATE_ATTRIBUTE5 AS BOM_LINE_DATE_ATTRIBUTE5,
BLI.DATE_ATTRIBUTE6 AS BOM_LINE_DATE_ATTRIBUTE6,
BLI.DATE_ATTRIBUTE7 AS BOM_LINE_DATE_ATTRIBUTE7,
BLI.DATE_ATTRIBUTE8 AS BOM_LINE_DATE_ATTRIBUTE8,
BLI.DATE_ATTRIBUTE9 AS BOM_LINE_DATE_ATTRIBUTE9,
BLI.DATE_ATTRIBUTE10 AS BOM_LINE_DATE_ATTRIBUTE10
FROM BOM_HEADER B
JOIN IV_ITEM_BUSINESS I ON
I.ITEM_KEY = B.ITEM_KEY
JOIN BOM_LINE_ITEM BLI ON
BLI.BOM_KEY = B.BOM_KEY
JOIN IV_ITEM_BUSINESS II ON
II.ITEM_KEY = BLI.ITEM_KEY;
ALTER TABLE BOM_LINE_ITEM MODIFY ITEM_QUANTITY NUMBER(19,6);



CREATE OR REPLACE PROCEDURE check_child_rows (
    p_parent_table   IN VARCHAR2,
    p_parent_column  IN VARCHAR2,
    p_parent_value   IN VARCHAR2,
    p_result         OUT VARCHAR2
)
AS
    v_parent_owner    VARCHAR2(50);
    v_child_owner     VARCHAR2(50);
    v_child_table     VARCHAR2(50);
    v_child_column    VARCHAR2(50);
    v_sql             VARCHAR2(1000);
    v_count           NUMBER;
    v_msg             VARCHAR2(4000) := '';
    v_has_child_rows  BOOLEAN := FALSE;

    CURSOR fk_cursor IS
        SELECT
            c.owner AS child_owner,
            c.table_name AS child_table,
            cc.column_name AS child_column
        FROM all_constraints c
        JOIN all_cons_columns cc
            ON c.owner = cc.owner AND c.constraint_name = cc.constraint_name
        WHERE c.constraint_type = 'R'
          AND c.table_name NOT IN ('ITEM_ITEM_CATEGORY', 'ITEM_ADD_ATTRIBUTE') -- Exclude specific tables
          AND c.r_constraint_name = (
                SELECT constraint_name
                FROM all_constraints
                WHERE table_name = UPPER(p_parent_table)
                  AND constraint_type = 'P'
                  AND ROWNUM = 1
            );
BEGIN
    -- Get parent table owner
    SELECT owner INTO v_parent_owner
    FROM all_tables
    WHERE table_name = UPPER(p_parent_table)
      AND ROWNUM = 1;

    -- Loop through referencing child tables (excluding ITEM_ITEM_CATEGORY)
    FOR fk IN fk_cursor LOOP
        v_child_owner := fk.child_owner;
        v_child_table := fk.child_table;
        v_child_column := fk.child_column;

        v_sql := 'SELECT COUNT(*) FROM "' || v_child_owner || '"."' || v_child_table ||
                 '" WHERE "' || v_child_column || '" = :1';

        EXECUTE IMMEDIATE v_sql INTO v_count USING p_parent_value;

        IF v_count > 0 THEN
            IF NOT v_has_child_rows THEN
                v_msg := 'Child rows found in: ';
                v_has_child_rows := TRUE;
            END IF;

            v_msg := v_msg || v_child_owner || '.' || v_child_table ||
                     ' (' || v_count || ' rows); ';
        END IF;
    END LOOP;

    IF v_has_child_rows THEN
        p_result := v_msg;
    ELSE
        p_result := 'No child rows found.';
    END IF;
END;
/