WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE ITEM_ADD_ATTRIBUTE ADD ATTRIBUTE_VALUE_NUM NUMBER (19, 4) NULL;
ALTER TABLE ITEM_ADD_ATTRIBUTE ADD ATTRIBUTE_VALUE_DT  TIMESTAMP (6) NULL;

-- Add Item only search workflow
update PCM_WORKFLOW set DISPLAY_ORDER=3 where WORKFLOW_KEY = 'SEARCH_BOM';
update PCM_WORKFLOW set WORKFLOW_NAME='Item AVL',DISPLAY_ORDER=2 where WORKFLOW_KEY = 'SEARCH_ITEM';
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('SEARCH_ITEM_ONLY', 'Items', 'MCM', 'SEARCH', 'itemOnlySearch.do', 1, NULL);
 
DECLARE
	v_role_key PCM_ACCESS_CONTROL.ROLE_KEY%TYPE;
	v_user_key PCM_ACCESS_CONTROL.USER_KEY%TYPE;
	v_acl PCM_ACCESS_CONTROL.ACL%TYPE;
	Cursor c_acl IS select ROLE_KEY,USER_KEY,ACL 
				  from PCM_ACCESS_CONTROL 
				  where ENTITY_TYPE = 'WORKFLOW' and TARGET_ENTITY_KEY='SEARCH_ITEM'; 
BEGIN
 OPEN c_acl;
 LOOP
 	FETCH c_acl into v_role_key,v_user_key,v_acl;
 	EXIT WHEN c_acl%NOTFOUND;
	INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.NEXTVAL, 'WORKFLOW', v_role_key, v_user_key, 'SEARCH_ITEM_ONLY', v_acl);
 END LOOP;
 CLOSE c_acl;
END;
/
 
 
 
 
 
 
 
 
 
