WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK
        
CREATE SEQUENCE PCM_EARULE_SEQ 
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        


CREATE TABLE PCM_ENTITY_ACTION_RULE 
    ( 
     RULE_KEY NUMBER (19)  NOT NULL , 
     RULE_TYPE VARCHAR2 (50 BYTE)  NOT NULL , 
     ENTITY_TYPE VARCHAR2 (40 BYTE)  NOT NULL , 
     TARGET_ENTITY_KEY VARCHAR2 (32) , 
     ACTN VARCHAR2 (50 BYTE)  NOT NULL , 
     ACTIVE NUMBER (1)  NOT NULL , 
     ITEM_CATEGORY_KEY NUMBER (19) , 
     NUM_DAYS NUMBER (5) , 
     RESPONSIBILITY_KEY VARCHAR2 (32) , 
     ROLE_KEY NUMBER (19),
     STATE VARCHAR2 (50),
     ALLOW NUMBER(1)
    ) 
    TABLESPACE AUDIT_DATA;


COMMENT ON COLUMN PCM_ENTITY_ACTION_RULE.ACTN IS 'Action' 
;

ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_PK PRIMARY KEY ( RULE_KEY ) ;

ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_ITM_CAT_FK FOREIGN KEY 
    ( 
     ITEM_CATEGORY_KEY
    ) 
    REFERENCES ITEM_CATEGORY 
    ( 
     ITEM_CATEGORY_KEY
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE PCM_ENTITY_ACTION_RULE 
    ADD CONSTRAINT PCM_EARULE_PCM_RESP_FK FOREIGN KEY 
    ( 
     RESPONSIBILITY_KEY
    ) 
    REFERENCES PCM_RESPONSIBILITY 
    ( 
     RESPONSIBILITY_KEY
    ) 
    ON DELETE CASCADE
    NOT DEFERRABLE 
;

ALTER TABLE BOM_HEADER
ADD LOAD_SOURCE VARCHAR2(255);
