WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE PCM_SUPPLIER_ALLOCATION
ADD CONTEXT_OBJECT_TYPE VARCHAR2(50);
ALTER TABLE PCM_SUPPLIER_ALLOCATION
ADD CONTEXT_OBJECT_ID   NUMBER(19,0);

DROP INDEX XSA_U1;
CREATE UNIQUE INDEX XSA_U1
    ON PCM_SUPPLIER_ALLOCATION(CUSTOMER_ITEM_GROUP_ITEM_KEY ASC,
    CUSTOMER_ITEM_KEY ASC,SUPPLIER_ITEM_KEY ASC,
    SUPPLIER_BUSINESS_ENTITY_KEY ASC,CUSTOMER_SITE_KEY ASC,SUPPLIER_SITE_KEY ASC,
    EFFECTIVE_FROM_DT ASC,EFFECTIVE_TO_DT ASC,CONTEXT_OBJECT_TYPE ASC,CONTEXT_OBJECT_ID ASC)
 TABLESPACE AUDIT_INDEX;
 
 -- added for SCPlatform-974 to fix the collab extract performance issue
DECLARE
BEGIN
     EXECUTE IMMEDIATE 'CREATE INDEX XBMLI_ITEM_I3
		ON BOM_LINE_ITEM(ITEM_KEY) 
		TABLESPACE AUDIT_INDEX';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
