ALTER TABLE PCM_SUPPLIER_ALLOCATION
ADD (DESTINATION_SITE_KEY NUMBER(19));

ALTER TABLE PCM_SUPPLIER_ALLOCATION
ADD CONSTRAINT PCMSA_DSITE_FK
FOREIGN KEY (DESTINATION_SITE_KEY)
REFERENCES SITE (SITE_KEY);

DROP INDEX XSA_U1;

CREATE UNIQUE INDEX XSA_U1
ON PCM_SUPPLIER_ALLOCATION (CUSTOMER_ITEM_GROUP_ITEM_KEY ASC, CUSTOMER_ITEM_KEY ASC, SUPPLIER_ITEM_KEY ASC,
SUPPLIER_BUSINESS_ENTITY_KEY ASC,CUSTOMER_SITE_KEY ASC,SUPPLIER_SITE_KEY ASC,DESTINATION_SITE_KEY ASC,EFFECTIVE_FROM_DT ASC,
EFFECTIVE_TO_DT ASC,CONTEXT_OBJECT_TYPE ASC,CONTEXT_OBJECT_ID ASC)
TABLESPACE AUDIT_INDEX;

CREATE TABLE AVL_SITE_MAPPING (
    ID NUMBER(19,0) PRIMARY KEY,
    AVL_KEY NUMBER(19,0),
    SOURCE_SITE_KEY NUMBER(19,0),
    DESTINATION_SITE_KEY NUMBER(19,0),
    CONSTRAINT fk_site_avl FOREIGN KEY (AVL_KEY) REFERENCES ITEM_AVL(AVL_KEY),
    CONSTRAINT fk_source_site FOREIGN KEY (SOURCE_SITE_KEY) REFERENCES SITE(SITE_KEY),
    CONSTRAINT fk_dest_site FOREIGN KEY (DESTINATION_SITE_KEY) REFERENCES SITE(SITE_KEY)
);

CREATE SEQUENCE AVL_SITE_MAPPING_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
CACHE 20
NOCYCLE ORDER;
