WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE BOM_LINE_ITEM ADD
(
	STRING_ATTRIBUTE1 VARCHAR2(1024),
	STRING_ATTRIBUTE2 VARCHAR2(1024),
	STRING_ATTRIBUTE3 VARCHAR2(1024),
	STRING_ATTRIBUTE4 VARCHAR2(1024),
	STRING_ATTRIBUTE5 VARCHAR2(1024),
	STRING_ATTRIBUTE6 VARCHAR2(1024),
	STRING_ATTRIBUTE7 VARCHAR2(1024),
	STRING_ATTRIBUTE8 VARCHAR2(1024),
	STRING_ATTRIBUTE9 VARCHAR2(1024),
	STRING_ATTRIBUTE10 VARCHAR2(1024),
	NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE
);

ALTER TABLE BOM_HEADER ADD
(
	CONTEXT_OBJECT_TYPE VARCHAR2(50),
   	CONTEXT_OBJECT_ID NUMBER(19,0),
	STRING_ATTRIBUTE1 VARCHAR2(1024),
	STRING_ATTRIBUTE2 VARCHAR2(1024),
	STRING_ATTRIBUTE3 VARCHAR2(1024),
	STRING_ATTRIBUTE4 VARCHAR2(1024),
	STRING_ATTRIBUTE5 VARCHAR2(1024),
	STRING_ATTRIBUTE6 VARCHAR2(1024),
	STRING_ATTRIBUTE7 VARCHAR2(1024),
	STRING_ATTRIBUTE8 VARCHAR2(1024),
	STRING_ATTRIBUTE9 VARCHAR2(1024),
	STRING_ATTRIBUTE10 VARCHAR2(1024),
	NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE
);

DROP INDEX XBMHDR_U1;
CREATE UNIQUE INDEX XBMHDR_U1
    ON BOM_HEADER(        
		ITEM_KEY ASC
		,VERSION ASC
		,REVISION ASC
		,DATA_SOURCE ASC
		,BUSINESS_ENTITY_KEY ASC
		,CONTEXT_OBJECT_TYPE
		,CONTEXT_OBJECT_ID
    ) TABLESPACE AUDIT_INDEX;
    
ALTER TABLE BOM_VERSION ADD
(
	CONTEXT_OBJECT_TYPE VARCHAR2(50),
   	CONTEXT_OBJECT_ID NUMBER(19,0)
);

CREATE UNIQUE INDEX XPCMRB_U1 ON PCM_REBATE_PROGRAM(
   REBATE_NAME)
   TABLESPACE AUDIT_INDEX;