create or replace PROCEDURE TAM_ROLLOVER (CURRENT_MONTH_START DATE,SPLIT_MONTH_START DATE, SPLIT_MONTH_END DATE,  ADD_MONTH_START DATE, ADD_MONTH_END DATE,
               COPY_MONTH_START DATE, COPY_MONTH_END DATE, MAX_ROLLOVER_COUNT NUMBER) AS
CURSOR cur_tam IS
SELECT t.*,fg.status, sd.*, fg.rollover_count
FROM tam_allocation t, functional_group fg,
     site s
     left join site_details sd on sd.ID = s.SITE_DETAIL_ID
WHERE t.functional_group_id = fg.functional_group_id
AND ( s.site_detail_id IN (SELECT sd.id FROM site_details sd
                   WHERE sd.site_state = '0' AND sd.TAM_PROCESSING_FLAG='1')
    OR NOT EXISTS (SELECT 'x' FROM site_details sd1
               WHERE s.site_detail_id = sd1.id)
               )
AND t.site_key = s.site_key
AND NVL(t.ROLL_OVER_COUNT, 0) <= MAX_ROLLOVER_COUNT
AND (t.NEXT_ROLLOVER_DATE < SPLIT_MONTH_START OR (t.NEXT_ROLLOVER_DATE is null AND t.CREATED_ON < CURRENT_MONTH_START));

rec_tam cur_tam%ROWTYPE;

v_rollover_count NUMBER(6,0);

BEGIN
  OPEN cur_tam;
  LOOP
     FETCH cur_tam INTO rec_tam;
     EXIT WHEN cur_tam%NOTFOUND;

         -- Break into Weekly for TAM_SUPPLIER_ALLOCATION

         INSERT INTO tam_supplier_allocation (TAM_SUPPLIER_ALLOCATION_ID, TAM_ALLOCATION_ID, BUSINESS_ENTITY_KEY, START_DATE, END_DATE, ALLOCATION)
               SELECT TAM_SUPPLIER_ALLOCATION_KEY_SEQ.NEXTVAL, tsa.TAM_ALLOCATION_ID, tsa.BUSINESS_ENTITY_KEY, cal.w_start, cal.w_end, tsa.allocation
               FROM tam_allocation tam, tam_supplier_allocation tsa,
                    (SELECT m.FISCAL_PERIOD_START_DATE, m.FISCAL_PERIOD_END_DATE, w.FISCAL_PERIOD_START_DATE w_start, W.FISCAL_PERIOD_END_DATE w_end
                     FROM fiscal_period m, fiscal_period w
                     WHERE m.FISCAL_PERIOD_TYPE = 'M'
                     AND w.FISCAL_PERIOD_TYPE = 'W'
                     AND m.FISCAL_PERIOD_START_DATE <= w.FISCAL_PERIOD_START_DATE
                     AND m.FISCAL_PERIOD_END_DATE >= w.FISCAL_PERIOD_END_DATE
                     AND m.FISCAL_PERIOD_START_DATE >= SPLIT_MONTH_START
                     and m.FISCAL_PERIOD_END_DATE <= SPLIT_MONTH_END ) cal
               WHERE tam.tam_allocation_id = tsa.tam_allocation_id
               AND cal.FISCAL_PERIOD_START_DATE = tsa.start_date
               AND cal.FISCAL_PERIOD_END_DATE = tsa.end_date
               AND tam.tam_allocation_id = rec_tam.tam_allocation_id
               AND NOT EXISTS (SELECT 'x' FROM tam_supplier_allocation tsa1
                                WHERE tsa1.TAM_ALLOCATION_ID = tsa.TAM_ALLOCATION_ID
                                AND tsa1.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
                                AND tsa1.start_date = cal.w_start
                                AND tsa1.end_date = cal.w_end);

               -- Break into Weekly for TAM_ITEM_ALLOCATION

               INSERT INTO tam_item_allocation (tam_item_allocation_id, tam_supplier_allocation_id, item_key, allocation)
               SELECT TAM_ITEM_ALLOCATION_KEY_SEQ.NEXTVAL, wtsa.tam_supplier_allocation_id, mtia.item_key, mtia.allocation
               FROM tam_allocation tam, tam_supplier_allocation mtsa, tam_item_allocation mtia,  tam_supplier_allocation wtsa,
                    (SELECT m.FISCAL_PERIOD_START_DATE, m.FISCAL_PERIOD_END_DATE, w.FISCAL_PERIOD_START_DATE w_start, W.FISCAL_PERIOD_END_DATE w_end
                     FROM fiscal_period m, fiscal_period w
                     WHERE m.FISCAL_PERIOD_TYPE = 'M'
                     AND w.FISCAL_PERIOD_TYPE = 'W'
                     AND m.FISCAL_PERIOD_START_DATE <= w.FISCAL_PERIOD_START_DATE
                     AND m.FISCAL_PERIOD_END_DATE >= w.FISCAL_PERIOD_END_DATE
                     AND m.FISCAL_PERIOD_START_DATE >= SPLIT_MONTH_START
                     and m.FISCAL_PERIOD_END_DATE <= SPLIT_MONTH_END ) cal
               WHERE tam.tam_allocation_id = mtsa.tam_allocation_id
               AND mtsa.tam_supplier_allocation_id = mtia.tam_supplier_allocation_id
               AND mtsa.start_date = SPLIT_MONTH_START
               AND mtsa.end_date = SPLIT_MONTH_END
               AND tam.tam_allocation_id = wtsa.tam_allocation_id
               AND mtsa.BUSINESS_ENTITY_KEY = wtsa.BUSINESS_ENTITY_KEY
               AND cal.w_start = wtsa.start_date
               AND cal.w_end = wtsa.end_date
               AND tam.tam_allocation_id = rec_tam.tam_allocation_id
               AND NOT EXISTS (SELECT 'x' FROM tam_item_allocation tia1
                                WHERE tia1.tam_supplier_allocation_id = wtsa.tam_supplier_allocation_id
                                AND tia1.item_key = mtia.item_key);

         -- delete monthly

        DELETE FROM tam_item_allocation
        WHERE TAM_ITEM_ALLOCATION_ID IN (SELECT mtia.TAM_ITEM_ALLOCATION_ID
                                 FROM tam_allocation tam, tam_supplier_allocation mtsa, tam_item_allocation mtia
                                 WHERE tam.tam_allocation_id = mtsa.tam_allocation_id
                                 AND mtsa.tam_supplier_allocation_id = mtia.tam_supplier_allocation_id
                                 AND mtsa.start_date = SPLIT_MONTH_START
                                 AND mtsa.end_date = SPLIT_MONTH_END
                                 AND tam.tam_allocation_id = rec_tam.tam_allocation_id
                                 );

        -- delete monthly

               DELETE FROM tam_supplier_allocation
               WHERE TAM_SUPPLIER_ALLOCATION_ID IN (SELECT mtsa.TAM_SUPPLIER_ALLOCATION_ID
                                                FROM tam_allocation tam, tam_supplier_allocation mtsa
                                                WHERE tam.tam_allocation_id = mtsa.tam_allocation_id
                                                AND mtsa.start_date = SPLIT_MONTH_START
                                                AND mtsa.end_date = SPLIT_MONTH_END
                                                AND tam.tam_allocation_id = rec_tam.tam_allocation_id
                                               );

        --DELLOCOS-4965: once reach max skip update TAM_rollover_count
        CASE
          WHEN rec_tam.rollover_count IS NULL THEN
            v_rollover_count := MAX_ROLLOVER_COUNT;
          ELSE
          v_rollover_count := rec_tam.rollover_count;
        END CASE;

        -- Add 12th month

        INSERT INTO tam_supplier_allocation (TAM_SUPPLIER_ALLOCATION_ID, TAM_ALLOCATION_ID, BUSINESS_ENTITY_KEY, START_DATE, END_DATE, ALLOCATION)
	SELECT TAM_SUPPLIER_ALLOCATION_KEY_SEQ.NEXTVAL, tsa.TAM_ALLOCATION_ID, tsa.BUSINESS_ENTITY_KEY, cal.FISCAL_PERIOD_START_DATE, cal.FISCAL_PERIOD_END_DATE,
	(CASE
        WHEN (rec_tam.STATUS IN('ACTIVE','PENDING REVIEW') and rec_tam.tam_visible_flag = '1' and NVL(rec_tam.ROLL_OVER_COUNT, 0) < v_rollover_count) THEN tsa.allocation
        WHEN (rec_tam.STATUS IN('ACTIVE','PENDING REVIEW') and rec_tam.tam_visible_flag = '1' and NVL(rec_tam.ROLL_OVER_COUNT, 0) >= v_rollover_count) THEN NULL
        WHEN (rec_tam.STATUS = 'INACTIVE') THEN NULL
        ELSE NULL
    END)
	FROM tam_allocation tam, tam_supplier_allocation tsa,
	    (SELECT m.FISCAL_PERIOD_START_DATE, m.FISCAL_PERIOD_END_DATE
	     FROM fiscal_period m
	     WHERE m.FISCAL_PERIOD_TYPE = 'M'
	     AND m.FISCAL_PERIOD_START_DATE >= ADD_MONTH_START  -- future month start
	     and m.FISCAL_PERIOD_END_DATE <= ADD_MONTH_END   -- future month end
	     ) cal
	WHERE tam.tam_allocation_id = tsa.tam_allocation_id
	AND tsa.start_date = COPY_MONTH_START -- last month start
	AND tsa.end_date = COPY_MONTH_END -- last month end
	AND tam.tam_allocation_id = rec_tam.tam_allocation_id
	AND NOT EXISTS (SELECT 'x' FROM tam_supplier_allocation tsa1
	                WHERE tsa1.TAM_ALLOCATION_ID = tsa.TAM_ALLOCATION_ID
	                AND tsa1.BUSINESS_ENTITY_KEY = tsa.BUSINESS_ENTITY_KEY
	                AND tsa1.start_date = cal.FISCAL_PERIOD_START_DATE
	                AND tsa1.end_date = cal.FISCAL_PERIOD_END_DATE);


       -- Add 12th month

       INSERT INTO tam_item_allocation (tam_item_allocation_id, tam_supplier_allocation_id, item_key, allocation)
       SELECT TAM_ITEM_ALLOCATION_KEY_SEQ.NEXTVAL, wtsa.tam_supplier_allocation_id, mtia.item_key,
       (CASE
        WHEN (rec_tam.STATUS IN('ACTIVE','PENDING REVIEW') and rec_tam.tam_visible_flag = '1' and NVL(rec_tam.ROLL_OVER_COUNT, 0) < v_rollover_count) THEN mtia.allocation
        WHEN (rec_tam.STATUS IN('ACTIVE','PENDING REVIEW') and rec_tam.tam_visible_flag = '1' and NVL(rec_tam.ROLL_OVER_COUNT, 0) >= v_rollover_count) THEN NULL
        WHEN (rec_tam.STATUS = 'INACTIVE') THEN NULL
        ELSE NULL
        END)
       FROM tam_allocation tam, tam_supplier_allocation mtsa, tam_item_allocation mtia,  tam_supplier_allocation wtsa,
           (SELECT m.FISCAL_PERIOD_START_DATE, m.FISCAL_PERIOD_END_DATE
                FROM fiscal_period m
                WHERE m.FISCAL_PERIOD_TYPE = 'M'
                AND m.FISCAL_PERIOD_START_DATE >= ADD_MONTH_START  -- future month start
                and m.FISCAL_PERIOD_END_DATE <= ADD_MONTH_END   -- future month end
            ) cal
       WHERE tam.tam_allocation_id = mtsa.tam_allocation_id
       AND mtsa.tam_supplier_allocation_id = mtia.tam_supplier_allocation_id
       AND mtsa.start_date = COPY_MONTH_START
       AND mtsa.end_date = COPY_MONTH_END
       AND tam.tam_allocation_id = wtsa.tam_allocation_id
       AND mtsa.BUSINESS_ENTITY_KEY = wtsa.BUSINESS_ENTITY_KEY
       AND wtsa.start_date = cal.FISCAL_PERIOD_START_DATE
       AND wtsa.end_date =  cal.FISCAL_PERIOD_END_DATE
       AND tam.tam_allocation_id = rec_tam.tam_allocation_id
       AND NOT EXISTS (SELECT 'x' FROM tam_item_allocation tia1
                       WHERE tia1.tam_supplier_allocation_id = wtsa.tam_supplier_allocation_id
                       AND tia1.item_key = mtia.item_key);

       IF (rec_tam.tam_visible_flag = '1' and rec_tam.STATUS IN('ACTIVE','PENDING REVIEW')) THEN
            IF (NVL(rec_tam.ROLL_OVER_COUNT, 0) < v_rollover_count) THEN
              UPDATE TAM_ALLOCATION
               SET NEXT_ROLLOVER_DATE = SPLIT_MONTH_START,
                   LAST_CHANGED_BY = 'BATCH',
                   LAST_CHANGED_ON= CURRENT_TIMESTAMP,
                   ROLL_OVER_COUNT = NVL(ROLL_OVER_COUNT,0) + 1,
                   EXTRACT_FLAG = 'P',
                   DISCP_ROLLOVER_EXTRACT_FLAG = 'P'
               WHERE TAM_ALLOCATION_ID = rec_tam.tam_allocation_id;
           ELSE
           --DELLOCOS-4965: once reach max skip update TAM_rollover_count
               UPDATE TAM_ALLOCATION
               SET NEXT_ROLLOVER_DATE = SPLIT_MONTH_START,
                   LAST_CHANGED_BY = 'BATCH',
                   LAST_CHANGED_ON= CURRENT_TIMESTAMP,
                   EXTRACT_FLAG = 'P',
                   DISCP_ROLLOVER_EXTRACT_FLAG = 'P'
               WHERE TAM_ALLOCATION_ID = rec_tam.tam_allocation_id;

               IF (rec_tam.LAST_ROLLOVER_DATE is null) THEN
               UPDATE TAM_ALLOCATION SET
                   LAST_ROLLOVER_DATE = SPLIT_MONTH_START
               WHERE TAM_ALLOCATION_ID = rec_tam.tam_allocation_id;
               END IF;

           END IF;
       ELSE
       UPDATE TAM_ALLOCATION
       SET NEXT_ROLLOVER_DATE = SPLIT_MONTH_START,
           ROLL_OVER_COUNT = NVL(ROLL_OVER_COUNT,0) + 1,
           EXTRACT_FLAG = 'P',
           DISCP_ROLLOVER_EXTRACT_FLAG = 'P'
       WHERE TAM_ALLOCATION_ID = rec_tam.tam_allocation_id;
       END IF;
       INSERT INTO FG_AUDIT_HISTORY (AUDIT_KEY, DATE_PERFORMED, USER_ID, USER_ROLE, ACTION, OPERATION_CODE, COMMENTS, AUDIT_SOURCE, TAM_KEY, SITE, FG_KEY)
        SELECT FG_AUDIT_KEY_SEQ.NEXTVAL, CURRENT_TIMESTAMP, 'BATCH','ADMIN','BATCH','TAM ROLLOVER','TAM Rolloved Over for FunctionalGroup: ' || fg.name || ' and Site: ' || s.site_description,
              'TAM', tam.tam_allocation_id, s.site_key,tam.functional_group_id
       FROM tam_allocation tam, functional_group fg,
            site s
       WHERE tam.functional_group_id = fg.functional_group_id
       AND fg.status in('ACTIVE','PENDING REVIEW')
       AND ( s.site_detail_id IN (SELECT sd.id FROM site_details sd
                          WHERE sd.site_state = '0')
           OR NOT EXISTS (SELECT 'x' FROM site_details sd1
                      WHERE s.site_detail_id = sd1.id)
                      )
       AND tam.site_key = s.site_key
       AND tam.ROLL_OVER_COUNT <= MAX_ROLLOVER_COUNT
       AND tam.tam_allocation_id = rec_tam.tam_allocation_id;

       COMMIT;

  END LOOP;
  CLOSE cur_tam;
  COMMIT;
END;

-- Add the new column
ALTER TABLE FUNCTIONAL_GROUP
ADD (FUNCTIONAL_GROUP_EXTERNAL_ID VARCHAR2(255));

-- Add UNIQUE constraint
ALTER TABLE FUNCTIONAL_GROUP
ADD CONSTRAINT UK_FUNCTIONAL_GROUP_EXTID UNIQUE (FUNCTIONAL_GROUP_EXTERNAL_ID);

--Create index on the new column
CREATE INDEX IDX_FG_EXTID
ON FUNCTIONAL_GROUP (FUNCTIONAL_GROUP_EXTERNAL_ID);

-- Copy existing FUNCTIONAL_ID values
UPDATE FUNCTIONAL_GROUP
SET FUNCTIONAL_GROUP_EXTERNAL_ID = FUNCTIONAL_GROUP_ID;

CREATE OR REPLACE VIEW IV_FUNCTIONAL_GROUP AS
SELECT
FG.FUNCTIONAL_GROUP_ID,
FG.FUNCTIONAL_GROUP_EXTERNAL_ID AS FUNCTIONAL_GROUP_EXTERNAL_ID,
FG.NAME AS FG_NAME,
FG.DESCRIPTION AS FG_DESCRIPTION,
FG.TYPE AS FG_TYPE,
FG.STATUS AS FG_STATUS,
FG.STATUS_CHANGED_BY,
FG.LAST_CHANGED_ON AS FG_LAST_CHAGNED_ON,
FG.LAST_CHANGED_BY AS FG_LAST_CHANGED_BY,
FG.EXTRACT_FLAG,
FG.CREATED_ON,
FG.CREATED_BY,
FGLOB.VALUE AS FG_LOB,
FG.FG_PLATFORM,
PFG.PARENT_FUNCTIONAL_GROUP_ID,
PFG.NAME AS PG_NAME,
PFG.DESCRIPTION AS PG_DESCRIPTION,
PFG.TYPE AS PG_TYPE,
PFG.PURPOSE,
PFG.LAST_CHANGED_ON AS PG_LAST_CHANGED_ON,
PFG.LAST_CHANGED_BY AS PG_LAST_CHANGED_BY,
PFG.CREATED_ON AS PFG_CREATED_ON,
PFG.CREATED_BY AS PFG_CREATED_BY,
IM.ITEM_IDENTIFIER,
PI.ITEM_IDENTIFIER AS PARENT_ITEM_IDENTIFIER,
ODM.ITEM_IDENTIFIER AS ODM_PART_IDENTIFIER,
PIB.BUSINESS_ENTITY_NAME AS PARENT_ITEM_BUSINESS_NAME,
ODMB.BUSINESS_ENTITY_NAME AS ODM_PART_BUSINESS_NAME
FROM FUNCTIONAL_GROUP FG
LEFT OUTER JOIN FG_LOB_VALUES FGLOB ON FGLOB.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN FG_PFG_MAP FGMAP ON FGMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN PARENT_FUNCTIONAL_GROUP PFG ON PFG.PARENT_FUNCTIONAL_GROUP_ID = FGMAP.PARENT_FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_FG_MAP IMAP ON IMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = IMAP.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM IP ON IP.ITEM_PLATFORM_KEY = FG.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_MASTER PI ON PI.ITEM_KEY = FG.PARENT_ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY PIB ON PIB.BUSINESS_ENTITY_KEY = PI.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN ITEM_MASTER ODM ON ODM.ITEM_KEY = FG.ODM_PART_KEY
LEFT OUTER JOIN BUSINESS_ENTITY ODMB ON ODMB.BUSINESS_ENTITY_KEY = ODM.BUSINESS_ENTITY_KEY
ORDER BY FUNCTIONAL_GROUP_ID ASC;
--End of View

create or replace PACKAGE BODY TamCascadeOperation AS

	PROCEDURE TAM_ALLOC_CASCADE_PROC_SP (
		vOUT_RESULT out SYS_REFCURSOR,
		vEXTRACT_FLAG  in  VARCHAR2
	) AS
	vMONTH_START_DATE DATE;
	vWEEK_START_DATE DATE;
	BEGIN

	SELECT TO_DATE(NEXT_DAY(SYSDATE,'SATURDAY') - 7) INTO vWEEK_START_DATE FROM DUAL;

	SELECT MIN(FISCAL_PERIOD_START_DATE)  INTO vMONTH_START_DATE
	FROM fiscal_period
	WHERE FISCAL_PERIOD_TYPE IN ('M','W')
	AND FISCAL_PERIOD_START_DATE >= trunc(vWEEK_START_DATE);

  -- Capture the SITE with TAM_PROCESSING_FLAG Info --
  EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_SITE_DETAIL_PROCESSING REUSE STORAGE');
  INSERT /*+ APPEND PARALLEL */ INTO TAM_SITE_DETAIL_PROCESSING (SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION, SITE_TYPE,PARENT_SITE_KEY,BUSINESS_ENTITY_KEY,SITE_DETAIL_ID,TAM_PROCESSING_FLAG)
  SELECT SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,BUSINESS_ENTITY_KEY,SITE_DETAIL_ID,
         CASE WHEN SITE_TYPE = 'GLOBAL' OR SITE_TYPE = 'REGION' THEN '1'
              ELSE TAM_PROCESSING_FLAG END AS TAM_PROCESSING_FLAG
  FROM SITE ST,SITE_DETAILS SD
      WHERE ST.SITE_DETAIL_ID = SD.ID;
  COMMIT;

  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_SITE_DETAIL_PROCESSING',CASCADE => TRUE, DEGREE=>16);


	-- 1st STG to extract all TAM details --
  EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ALLOC_CASCADE_PROC_STG1 REUSE STORAGE');
  INSERT /*+ APPEND PARALLEL */ INTO TAM_ALLOC_CASCADE_PROC_STG1 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,CHILD_IS_DELTA,DATASOURCE)
select
     X.TAM_ALLOCATION_ID,X.FUNCTIONAL_GROUP_ID,X.FG_NAME,X.LAST_CHANGED_BY,X.LAST_CHANGED_ON,X.ALLOW_HEDGING,X.CREATED_BY,X.CREATED_ON,X.DISCP_EXTRACT_FLAG,X.SITE_KEY,X.SITE_IDENTIFIER,X.SITE_DESCRIPTION,X.SITE_TYPE,X.PARENT_SITE_KEY,
      BE.BUSINESS_ENTITY_IDENTIFIER  AS SUPPLIER_IDENTIFIER,
      BE.BUSINESS_ENTITY_NAME        AS SUPPLIER_NAME,
      TSA.START_DATE                 AS START_DATE,
      TSA.END_DATE                   AS END_DATE,
      TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
      TSA.ALLOCATION                 AS SUPPLIER_ALLOCATION,
      TIA.TAM_ITEM_ALLOCATION_ID     AS TAM_ITEM_ALLOCATION_ID,
      TIA.ALLOCATION                 AS ITEM_ALLOCATION,
      IM.ITEM_IDENTIFIER             AS ITEM_IDENTIFIER,
      CHILD_PARENT_SITE_ID,
      CHILD_IS_DELTA,
      IM.DATA_SOURCE             	 AS DATASOURCE
FROM
(
SELECT * FROM
(
  SELECT X.*,
  CASE WHEN SITE_TYPE = 'GLOBAL' AND (MAX(CASE WHEN DISCP_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID)) = 1 THEN 1
       WHEN SITE_TYPE = 'REGION' AND MAX(CASE WHEN DISCP_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,CHILD_PARENT_SITE_ID) = 1 THEN 1
       ELSE 0 END AS CHILD_IS_DELTA
  FROM
  (
    SELECT
          TA.TAM_ALLOCATION_ID,
          FG.FUNCTIONAL_GROUP_ID,
          FG.NAME             AS FG_NAME,
          TA.LAST_CHANGED_BY AS LAST_CHANGED_BY,
          TA.LAST_CHANGED_ON AS LAST_CHANGED_ON,
          TA.ALLOW_HEDGING   AS ALLOW_HEDGING,
          TA.CREATED_BY      AS CREATED_BY,
          TA.CREATED_ON      AS CREATED_ON,
          TA.DISCP_EXTRACT_FLAG AS DISCP_EXTRACT_FLAG,
          TA.SITE_KEY                   AS SITE_KEY,
          SI.SITE_IDENTIFIER             AS SITE_IDENTIFIER,
          SI.SITE_DESCRIPTION            AS SITE_DESCRIPTION,
          SI.SITE_TYPE                   AS SITE_TYPE,
          SI.PARENT_SITE_KEY             AS PARENT_SITE_KEY,
          CASE WHEN SI.SITE_TYPE = 'SITE' THEN PARENT_SITE_KEY
             ELSE SI.SITE_KEY END AS CHILD_PARENT_SITE_ID
        FROM TAM_ALLOCATION TA
          INNER JOIN FUNCTIONAL_GROUP FG
                ON FG.FUNCTIONAL_GROUP_ID = TA.FUNCTIONAL_GROUP_ID
          INNER JOIN TAM_SITE_DETAIL_PROCESSING SI
	        ON SI.SITE_KEY = TA.SITE_KEY --AND SI.SITE_DESCRIPTION NOT LIKE '%DONOTUSE'
	        AND SI.TAM_PROCESSING_FLAG = '1'
	        AND FG.STATUS IN ('ACTIVE','PENDING REVIEW')
	        AND SI.BUSINESS_ENTITY_KEY IN (SELECT BE.BUSINESS_ENTITY_KEY
	                       	                FROM BUSINESS_ENTITY BE, BUSINESS_ENTITY_TYPE BET
	                                        WHERE BE.BUSINESS_ENTITY_TYPE_KEY  = BET.BUSINESS_ENTITY_TYPE_KEY
                                                AND BET.BUSINESS_ENTITY_TYPE_NAME = 'ENTERPRISE')
        WHERE EXISTS
                (
	                 select 'x' from tam_supplier_allocation tsa1
	                 where tsa1.TAM_ALLOCATION_ID = TA.TAM_ALLOCATION_ID
	                 AND START_DATE >= vMONTH_START_DATE
	                 AND (SI.SITE_TYPE <> 'GLOBAL' OR ( SI.SITE_TYPE = 'GLOBAL' AND tsa1.allocation > 0 ) )
                 )
    ) X
  ) WHERE (DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
) X
    INNER JOIN TAM_SUPPLIER_ALLOCATION TSA
    ON TSA.TAM_ALLOCATION_ID = X.TAM_ALLOCATION_ID AND TSA.START_DATE >= vMONTH_START_DATE
    INNER JOIN BUSINESS_ENTITY BE
    ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
    INNER JOIN IV_TAM_ITEM_ALLOCATION TIA
    ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
    INNER JOIN ITEM_MASTER IM
    ON IM.ITEM_KEY = TIA.ITEM_KEY;
COMMIT;

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ALLOC_CASCADE_PROC_STG1',CASCADE => TRUE, DEGREE=>16);

-- 2nd STG Process to apply the Cascading Logic --
	EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ALLOC_CASCADE_PROC_STG2 REUSE STORAGE');
	INSERT /*+ APPEND PARALLEL */ INTO TAM_ALLOC_CASCADE_PROC_STG2 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER)
  SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
  FROM
  (
  select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOT_SUPP_ALOC,
           TAM_ITEM_ALLOCATION_ID, ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
           MAX(CASE WHEN NVL(SUPPLIER_ALLOCATION,0) = 0 THEN 0 ELSE 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER) SUPP_ALLOC_NOT_NULL,
            MAX(
               CASE WHEN ((NVL(ITEM_ALLOCATION,0) = 0 AND SITE_TYPE = 'SITE') OR (NVL(ITEM_ALLOCATION,0) = 0 AND ITEM_IDENTIFIER <> DEFAULT_ITEM_IDENTIFIER)) THEN 0
               ELSE 1 END
              ) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER,ITEM_IDENTIFIER) ITEM_ALLOC_NOT_NULL
	  FROM
	  (
  		   select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOT_SUPP_ALOC,
           TAM_ITEM_ALLOCATION_ID,
           CASE WHEN ITEM_ALLOCATION IS NULL THEN
                CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
                 CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100
                 ELSE 0 END
                ELSE 0 END
                ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,SUPP_ROW_NUM
	  FROM
	  (
	    select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_region
	                  when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_global
	                  else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID,
                 case when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_item_region
	                  when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_item_global
	             else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,BUCK_ALOC,BUCK_ITEM_ALOC,alloc_region,alloc_item_region,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
	             ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_NAME,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM
	      FROM
	      (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,
	             max(case when site_type =  'REGION' then  SUPPLIER_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,start_date,FG_NAME) alloc_region,
                 SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
                 TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,
                 max(case when site_type =  'REGION' then  ITEM_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_region,
	             ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
                 ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	      FROM
	      (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'REGION' then alloc_global
                 else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID,
                 case when BUCK_ITEM_ALOC is null AND site_type = 'REGION' then alloc_item_global
	             else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	        from
	        (
	            select x.*,
	            SUM(SUPPLIER_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ALOC,
                SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ITEM_ALOC,
	            max(case when site_type =  'GLOBAL' and site_identifier = 1 then  SUPPLIER_ALLOCATION end) over (partition by supplier_identifier,start_date,FG_NAME) alloc_global,
                max(case when site_type =  'GLOBAL' and site_identifier = 1 then  ITEM_ALLOCATION end) over (partition by supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_global,
	            CASE WHEN (count(CASE WHEN site_type =  'REGION' THEN 1 END) OVER (PARTITION BY FG_NAME,CHILD_PARENT_SITE_ID)) > 0 THEN 1
	                 ELSE 0 END AS REGION_PARENT_EXISTS,
	            CASE WHEN (count(CASE WHEN DATASOURCE =  'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0
	            	 THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 END AS DEFAULT_ITEM_IDENTIFIER
	            from
	            (
	             select * from TAM_ALLOC_CASCADE_PROC_STG1-- where (DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
	            ) x
	         )x
	       )
	      )
	    )
	  ) WHERE DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG)
    ) WHERE SUPP_ALLOC_NOT_NULL > 0 AND ITEM_ALLOC_NOT_NULL > 0;
  COMMIT;

	DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ALLOC_CASCADE_PROC_STG2',CASCADE => TRUE, DEGREE=>16);

	OPEN VOUT_RESULT FOR
		SELECT 1 AS COUNT FROM DUAL;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE;
	END TAM_ALLOC_CASCADE_PROC_SP;

	PROCEDURE TAM_ALLOC_CASCADE_DELTA_UPDATE (
		vOUT_RESULT out SYS_REFCURSOR
	) AS
	vMONTH_START_DATE DATE;
	vWEEK_START_DATE DATE;
	BEGIN

	SELECT TO_DATE(NEXT_DAY(SYSDATE,'SATURDAY') - 7) INTO vWEEK_START_DATE FROM DUAL;

	SELECT MIN(FISCAL_PERIOD_START_DATE)  INTO vMONTH_START_DATE
	 FROM fiscal_period
	WHERE FISCAL_PERIOD_TYPE IN ('M','W')
	AND FISCAL_PERIOD_START_DATE >= trunc(vWEEK_START_DATE);

	-- Insert records in FG Audit

	insert into FG_AUDIT_HISTORY(audit_key,tam_key,user_id,user_role,audit_source,site,fg_key,action,operation_code,comments)
 	SELECT FG_AUDIT_KEY_SEQ.NEXTVAL,TA.TAM_ALLOCATION_ID,'ADMIN' ,'ADMIN','TAM',ta.site_key,ta.functional_group_id,'TAM_CASCADE_EXTRACT','TAM CASCADE EXTRACT CREATED', CONCAT(CONCAT('New TAM Created For FunctionalGroup: ' ,fg.NAME),concat(' and Site:  ', site.SITE_DESCRIPTION))
	from tam_allocation TA
    inner join functional_group fg on fg.functional_group_id=ta.functional_group_id
    inner join site site on site.site_key=ta.site_key
                WHERE TA.DISCP_EXTRACT_FLAG = 'P'
	      AND TA.TAM_ALLOCATION_ID IN
	      (
	        SELECT  TAM_ALLOCATION_ID FROM TAM_ALLOC_CASCADE_PROC_STG2 TAS WHERE DISCP_EXTRACT_FLAG = 'P'
	      );

	      COMMIT;

	    -- Update TAM_ALLOCATION to set the DISP_EXTRACT_FLAG to Y for DELTA Extractions --
	 UPDATE TAM_ALLOCATION TA SET DISCP_EXTRACT_FLAG = 'Y'
	      WHERE DISCP_EXTRACT_FLAG = 'P'
	      AND TAM_ALLOCATION_ID IN
	      (
	        SELECT  TAM_ALLOCATION_ID FROM TAM_ALLOC_CASCADE_PROC_STG2 TAS WHERE DISCP_EXTRACT_FLAG = 'P' AND TAS.LAST_CHANGED_ON = TA.LAST_CHANGED_ON
	      );

	      COMMIT;

	  OPEN VOUT_RESULT FOR
			SELECT 1 AS COUNT FROM DUAL;

		EXCEPTION
			WHEN OTHERS THEN
				RAISE;
	END TAM_ALLOC_CASCADE_DELTA_UPDATE;

END TamCascadeOperation;

create or replace PACKAGE BODY TamRolloverCascadeOperation AS

	PROCEDURE TAM_ALLOC_ROLLOVER_CASCADE_PROC_SP (
		vOUT_RESULT out SYS_REFCURSOR,
		vEXTRACT_FLAG  in  VARCHAR2
	) AS
	vMONTH_START_DATE DATE;
	BEGIN

	SELECT FISCAL_PERIOD_START_DATE INTO vMONTH_START_DATE FROM (
  		SELECT FISCAL_PERIOD_TYPE,FISCAL_PERIOD_NAME,FISCAL_PERIOD,FISCAL_PERIOD_START_DATE,FISCAL_PERIOD_END_DATE,ROWNUM AS ROWCOUNT FROM (
  			SELECT FISCAL_PERIOD_TYPE,FISCAL_PERIOD_NAME,FISCAL_PERIOD,FISCAL_PERIOD_START_DATE,FISCAL_PERIOD_END_DATE FROM FISCAL_PERIOD WHERE FISCAL_PERIOD_TYPE = 'M' ORDER BY  FISCAL_PERIOD_START_DATE)
  	WHERE FISCAL_PERIOD_END_DATE > (SELECT SYSDATE FROM DUAL) AND ROWNUM < 13 ) WHERE ROWCOUNT = 12;


  EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ROLLOVER_SITE_DETAIL_PROCESSING REUSE STORAGE');
  INSERT /*+ APPEND PARALLEL */ INTO TAM_ROLLOVER_SITE_DETAIL_PROCESSING (SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION, SITE_TYPE,PARENT_SITE_KEY,BUSINESS_ENTITY_KEY,SITE_DETAIL_ID,TAM_PROCESSING_FLAG)
  SELECT SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,BUSINESS_ENTITY_KEY,SITE_DETAIL_ID,
         CASE WHEN SITE_TYPE = 'GLOBAL' OR SITE_TYPE = 'REGION' THEN '1'
              ELSE TAM_PROCESSING_FLAG END AS TAM_PROCESSING_FLAG
  FROM SITE ST,SITE_DETAILS SD
      WHERE ST.SITE_DETAIL_ID = SD.ID;
  COMMIT;

  DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ROLLOVER_SITE_DETAIL_PROCESSING',CASCADE => TRUE, DEGREE=>16);


	-- 1st STG to extract all TAM details --
  EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1 REUSE STORAGE');
  INSERT /*+ APPEND PARALLEL */ INTO TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_ROLLOVER_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,CHILD_IS_DELTA,DATASOURCE)
select
     X.TAM_ALLOCATION_ID,X.FUNCTIONAL_GROUP_ID,X.FG_NAME,X.LAST_CHANGED_BY,X.LAST_CHANGED_ON,X.ALLOW_HEDGING,X.CREATED_BY,X.CREATED_ON,X.DISCP_ROLLOVER_EXTRACT_FLAG,X.SITE_KEY,X.SITE_IDENTIFIER,X.SITE_DESCRIPTION,X.SITE_TYPE,X.PARENT_SITE_KEY,
      BE.BUSINESS_ENTITY_IDENTIFIER  AS SUPPLIER_IDENTIFIER,
      BE.BUSINESS_ENTITY_NAME        AS SUPPLIER_NAME,
      TSA.START_DATE                 AS START_DATE,
      TSA.END_DATE                   AS END_DATE,
      TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
      TSA.ALLOCATION                 AS SUPPLIER_ALLOCATION,
      TIA.TAM_ITEM_ALLOCATION_ID     AS TAM_ITEM_ALLOCATION_ID,
      TIA.ALLOCATION                 AS ITEM_ALLOCATION,
      IM.ITEM_IDENTIFIER             AS ITEM_IDENTIFIER,
      CHILD_PARENT_SITE_ID,
      CHILD_IS_DELTA,
      IM.DATA_SOURCE             	 AS DATASOURCE
FROM
(
SELECT * FROM
(
  SELECT X.*,
  CASE WHEN SITE_TYPE = 'GLOBAL' AND (MAX(CASE WHEN DISCP_ROLLOVER_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID)) = 1 THEN 1
       WHEN SITE_TYPE = 'REGION' AND MAX(CASE WHEN DISCP_ROLLOVER_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,CHILD_PARENT_SITE_ID) = 1 THEN 1
       ELSE 0 END AS CHILD_IS_DELTA
  FROM
  (
    SELECT
          TA.TAM_ALLOCATION_ID,
          FG.FUNCTIONAL_GROUP_ID,
          FG.NAME             AS FG_NAME,
          TA.LAST_CHANGED_BY AS LAST_CHANGED_BY,
          TA.LAST_CHANGED_ON AS LAST_CHANGED_ON,
          TA.ALLOW_HEDGING   AS ALLOW_HEDGING,
          TA.CREATED_BY      AS CREATED_BY,
          TA.CREATED_ON      AS CREATED_ON,
          TA.DISCP_ROLLOVER_EXTRACT_FLAG AS DISCP_ROLLOVER_EXTRACT_FLAG,
          TA.SITE_KEY                   AS SITE_KEY,
          SI.SITE_IDENTIFIER             AS SITE_IDENTIFIER,
          SI.SITE_DESCRIPTION            AS SITE_DESCRIPTION,
          SI.SITE_TYPE                   AS SITE_TYPE,
          SI.PARENT_SITE_KEY             AS PARENT_SITE_KEY,
          CASE WHEN SI.SITE_TYPE = 'SITE' THEN PARENT_SITE_KEY
             ELSE SI.SITE_KEY END AS CHILD_PARENT_SITE_ID
        FROM TAM_ALLOCATION TA
          INNER JOIN FUNCTIONAL_GROUP FG
                ON FG.FUNCTIONAL_GROUP_ID = TA.FUNCTIONAL_GROUP_ID
          INNER JOIN TAM_ROLLOVER_SITE_DETAIL_PROCESSING SI
	        ON SI.SITE_KEY = TA.SITE_KEY --AND SI.SITE_DESCRIPTION NOT LIKE '%DONOTUSE'
	        AND SI.TAM_PROCESSING_FLAG = '1'
			AND FG.STATUS IN('ACTIVE','PENDING REVIEW')
	        AND SI.BUSINESS_ENTITY_KEY IN (SELECT BE.BUSINESS_ENTITY_KEY
	                       	                FROM BUSINESS_ENTITY BE, BUSINESS_ENTITY_TYPE BET
	                                        WHERE BE.BUSINESS_ENTITY_TYPE_KEY  = BET.BUSINESS_ENTITY_TYPE_KEY
                                                AND BET.BUSINESS_ENTITY_TYPE_NAME = 'ENTERPRISE')
        WHERE EXISTS
                (
                 select 'x' from tam_supplier_allocation tsa1
	                 where tsa1.TAM_ALLOCATION_ID = TA.TAM_ALLOCATION_ID
	                 AND START_DATE >= vMONTH_START_DATE
	                 AND (SI.SITE_TYPE <> 'GLOBAL' OR ( SI.SITE_TYPE = 'GLOBAL' AND tsa1.allocation > 0 ) )
                 )
    ) X
  ) WHERE (DISCP_ROLLOVER_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_ROLLOVER_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
) X
    INNER JOIN TAM_SUPPLIER_ALLOCATION TSA
    ON TSA.TAM_ALLOCATION_ID = X.TAM_ALLOCATION_ID AND TSA.START_DATE >= vMONTH_START_DATE
    INNER JOIN BUSINESS_ENTITY BE
    ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
    INNER JOIN IV_TAM_ROLLOVER_ITEM_ALLOCATION TIA
    ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
    INNER JOIN ITEM_MASTER IM
    ON IM.ITEM_KEY = TIA.ITEM_KEY;
COMMIT;

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1',CASCADE => TRUE, DEGREE=>16);

-- 2nd STG Process to apply the Cascading Logic --
	EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 REUSE STORAGE');
	INSERT /*+ APPEND PARALLEL */ INTO TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_ROLLOVER_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER)
  SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_ROLLOVER_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
  FROM
  (
  select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_ROLLOVER_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOT_SUPP_ALOC,
           TAM_ITEM_ALLOCATION_ID, ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
           MAX(CASE WHEN SUPPLIER_ALLOCATION IS NULL THEN 0 ELSE 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER) SUPP_ALLOC_NOT_NULL,
            MAX(
               CASE WHEN ((NVL(ITEM_ALLOCATION,0) = 0 AND SITE_TYPE = 'SITE') OR (NVL(ITEM_ALLOCATION,0) = 0 AND ITEM_IDENTIFIER <> DEFAULT_ITEM_IDENTIFIER)) THEN 0
               ELSE 1 END
              ) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER,ITEM_IDENTIFIER) ITEM_ALLOC_NOT_NULL
	  FROM
	  (
	  select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_ROLLOVER_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           TAM_ITEM_ALLOCATION_ID,
           CASE WHEN ITEM_ALLOCATION IS NULL THEN
                CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
                CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100
                ELSE 0 END
                ELSE 0 END
                ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,SUPP_ROW_NUM
	  FROM
	  (
	    select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_ROLLOVER_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_region
	                  when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_global
	                  else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID,
                 case when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_item_region
	                  when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_item_global
	                  else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,BUCK_ALOC,BUCK_ITEM_ALOC,alloc_region,alloc_item_region,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
	             ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_NAME,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM
	      FROM
	      (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_ROLLOVER_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,
	             max(case when site_type =  'REGION' then  SUPPLIER_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,start_date,FG_NAME) alloc_region,
                 SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
                 TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,
                 max(case when site_type =  'REGION' then  ITEM_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_region,
	             ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
                 ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	        FROM
	        (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_ROLLOVER_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'REGION' then alloc_global
                 else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID,
                 case when BUCK_ITEM_ALOC is null AND site_type = 'REGION' then alloc_item_global
	             else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	        from
	        (
	            select x.*,
	            SUM(SUPPLIER_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ALOC,
	            SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ITEM_ALOC,
	            max(case when site_type =  'GLOBAL' and site_identifier = 1 then  SUPPLIER_ALLOCATION end) over (partition by supplier_identifier,start_date,FG_NAME) alloc_global,
	            max(case when site_type =  'GLOBAL' and site_identifier = 1 then  ITEM_ALLOCATION end) over (partition by supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_global,
	            CASE WHEN (count(CASE WHEN site_type =  'REGION' THEN 1 END) OVER (PARTITION BY FG_NAME,CHILD_PARENT_SITE_ID)) > 0 THEN 1
	                 ELSE 0 END AS REGION_PARENT_EXISTS,
	            CASE WHEN (count(CASE WHEN DATASOURCE =  'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0
	            	 THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 END AS DEFAULT_ITEM_IDENTIFIER
	            from
	            (
	             select * from TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG1-- where (DISCP_ROLLOVER_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_ROLLOVER_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
	            ) x
	         )x
	       )
	     )
	    )
	  ) WHERE DISCP_ROLLOVER_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_ROLLOVER_EXTRACT_FLAG)
    ) WHERE SUPP_ALLOC_NOT_NULL > 0 AND ITEM_ALLOC_NOT_NULL > 0;
  COMMIT;

	DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2',CASCADE => TRUE, DEGREE=>16);

	OPEN VOUT_RESULT FOR
		SELECT 1 AS COUNT FROM DUAL;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE;
	END TAM_ALLOC_ROLLOVER_CASCADE_PROC_SP;

	PROCEDURE TAM_ALLOC_ROLLOVER_CASCADE_DELTA_UPDATE (
		vOUT_RESULT out SYS_REFCURSOR
	) AS
	vMONTH_START_DATE DATE;
	vWEEK_START_DATE DATE;
	BEGIN

	SELECT TO_DATE(NEXT_DAY(SYSDATE,'SATURDAY') - 7) INTO vWEEK_START_DATE FROM DUAL;

	SELECT MIN(FISCAL_PERIOD_START_DATE)  INTO vMONTH_START_DATE
	 FROM fiscal_period
	WHERE FISCAL_PERIOD_TYPE IN ('M','W')
	AND FISCAL_PERIOD_START_DATE >= trunc(vWEEK_START_DATE);

	    -- Update TAM_ALLOCATION to set the DISCP_ROLLOVER_EXTRACT_FLAG to Y for DELTA Extractions --
	  UPDATE TAM_ALLOCATION TA SET DISCP_ROLLOVER_EXTRACT_FLAG = 'Y'
	      WHERE DISCP_ROLLOVER_EXTRACT_FLAG = 'P'
	      AND TAM_ALLOCATION_ID IN
	      (
	        SELECT  TAM_ALLOCATION_ID FROM TAM_ROLLOVER_ALLOC_CASCADE_PROC_STG2 TAS WHERE DISCP_ROLLOVER_EXTRACT_FLAG = 'P'
	      );

	      COMMIT;

	  OPEN VOUT_RESULT FOR
			SELECT 1 AS COUNT FROM DUAL;

		EXCEPTION
			WHEN OTHERS THEN
				RAISE;
	END TAM_ALLOC_ROLLOVER_CASCADE_DELTA_UPDATE;

END TamRolloverCascadeOperation;

/*TAM Allocation extract, DELLOCOS-5390*/
CREATE OR REPLACE VIEW IV_TAM_ALLOCATION AS
SELECT
TAM.TAM_ALLOCATION_ID,
FG.FUNCTIONAL_GROUP_ID,
FG.NAME AS FG_NAME,
TAM.LAST_CHANGED_BY AS LAST_CHANGED_BY,
TAM.LAST_CHANGED_ON AS LAST_CHANGED_ON,
TAM.ALLOW_HEDGING AS ALLOW_HEDGING,
TAM.CREATED_BY AS CREATED_BY,
TAM.CREATED_ON AS CREATED_ON,
TAM.EXTRACT_FLAG,
SI.SITE_IDENTIFIER AS SITE_IDENTIFIER,
SI.SITE_DESCRIPTION AS SITE_DESCRIPTION,
SI.SITE_TYPE AS SITE_TYPE,
BE.BUSINESS_ENTITY_IDENTIFIER AS SUPPLIER_IDENTIFIER,
BE.BUSINESS_ENTITY_NAME AS SUPPLIER_NAME,
TSA.START_DATE AS START_DATE,
TSA.END_DATE AS END_DATE,
TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
TSA.ALLOCATION AS SUPPLIER_ALLOCATION,
TIA.TAM_ITEM_ALLOCATION_ID AS TAM_ITEM_ALLOCATION_ID,
TIA.ALLOCATION AS ITEM_ALLOCATION,
IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,
IM.STRING_ATTRIBUTE5 AS USER_ITEM_TYPE
FROM TAM_ALLOCATION TAM
LEFT OUTER JOIN FUNCTIONAL_GROUP FG ON FG.FUNCTIONAL_GROUP_ID = TAM.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN SITE SI ON SI.SITE_KEY = TAM.SITE_KEY
LEFT OUTER JOIN SITE_DETAILS SD ON SD.ID=SI.SITE_DETAIL_ID
LEFT OUTER JOIN TAM_SUPPLIER_ALLOCATION TSA ON TSA.TAM_ALLOCATION_ID = TAM.TAM_ALLOCATION_ID
LEFT OUTER JOIN TAM_ITEM_ALLOCATION TIA ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = TIA.ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY BE ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
WHERE FG.STATUS IN('ACTIVE','PENDING REVIEW') AND SD.TAM_PROCESSING_FLAG='1'
ORDER BY TAM_ALLOCATION_ID ASC, SUPPLIER_NAME ASC, START_DATE ASC;

ALTER TABLE FUNCTIONAL_GROUP DROP COLUMN FG_STATUS;

create table ROLE_COMMODITY_PROFILE_MAPPING
(
	ROLE_KEY Number(19,0) NOT NULL,
	PROFILE_ID Number(19,0) NOT NULL,
    BUSINESS_ENTITY_KEY NUMBER(19),
	CONSTRAINT ROLE_PROFILE_PK PRIMARY KEY (ROLE_KEY, PROFILE_ID, BUSINESS_ENTITY_KEY),
	CONSTRAINT role_profile_fk FOREIGN KEY (ROLE_KEY) REFERENCES PCM_ROLE(ROLE_KEY),
    CONSTRAINT business_entity_mapping_key_fk FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY),
    CONSTRAINT profile_role_fk FOREIGN KEY (PROFILE_ID) REFERENCES COMMODITY_PROFILE(PROFILE_ID)
);

CREATE OR REPLACE PROCEDURE check_child_rows (
    p_parent_table   IN VARCHAR2,
    p_parent_column  IN VARCHAR2,
    p_parent_value   IN VARCHAR2,
    p_result         OUT VARCHAR2
)
AS
    v_parent_owner    VARCHAR2(50);
    v_child_owner     VARCHAR2(50);
    v_child_table     VARCHAR2(50);
    v_child_column    VARCHAR2(50);
    v_sql             VARCHAR2(1000);
    v_count           NUMBER;
    v_msg             VARCHAR2(4000) := '';
    v_has_child_rows  BOOLEAN := FALSE;

    CURSOR fk_cursor IS
        SELECT
            c.owner AS child_owner,
            c.table_name AS child_table,
            cc.column_name AS child_column
        FROM all_constraints c
        JOIN all_cons_columns cc
            ON c.owner = cc.owner AND c.constraint_name = cc.constraint_name
        WHERE c.constraint_type = 'R'
          AND (
                       -- Exclude tables
                       c.table_name <> 'ITEM_ADD_ATTRIBUTE'
                       -- Exclude ITEM_ITEM_CATEGORY only when parent table is ITEM_ITEM_CATEGORY
                       AND (UPPER(p_parent_table) <> 'ITEM_ITEM_CATEGORY' OR c.table_name <> 'ITEM_ITEM_CATEGORY')
               )
          AND c.r_constraint_name = (
                SELECT constraint_name
                FROM all_constraints
                WHERE table_name = UPPER(p_parent_table)
                  AND constraint_type = 'P'
                  AND ROWNUM = 1
            );
BEGIN
    -- Get parent table owner
    SELECT owner INTO v_parent_owner
    FROM all_tables
    WHERE table_name = UPPER(p_parent_table)
      AND ROWNUM = 1;

    -- Loop through referencing child tables (excluding ITEM_ITEM_CATEGORY)
    FOR fk IN fk_cursor LOOP
        v_child_owner := fk.child_owner;
        v_child_table := fk.child_table;
        v_child_column := fk.child_column;

        v_sql := 'SELECT COUNT(*) FROM "' || v_child_owner || '"."' || v_child_table ||
                 '" WHERE "' || v_child_column || '" = :1';

        EXECUTE IMMEDIATE v_sql INTO v_count USING p_parent_value;

        IF v_count > 0 THEN
            IF NOT v_has_child_rows THEN
                v_msg := 'Child rows found in: ';
                v_has_child_rows := TRUE;
            END IF;

            v_msg := v_msg || v_child_owner || '.' || v_child_table ||
                     ' (' || v_count || ' rows); ';
        END IF;
    END LOOP;

    IF v_has_child_rows THEN
        p_result := v_msg;
    ELSE
        p_result := 'No child rows found.';
    END IF;
END;


--
--Below procedure will updates all the child boms data in BOM_HEADER,BOM_LINE_ITEM based on BOM_KEY supplied.
--Dynamically generate the update queries and updates the data. If any input parameter is NULL then it will 
--not include in the UPDATE Query
--
CREATE OR REPLACE PROCEDURE updateChildBomsData ( p_bom_key IN BOM_HEADER.BOM_KEY%TYPE,
p_effective_from_date IN BOM_HEADER.EFFECTIVE_FROM_DT%TYPE,
p_effective_to_date IN BOM_HEADER.EFFECTIVE_TO_DT%TYPE,
p_status IN BOM_HEADER.STATUS%TYPE ) AS

  v_last_bomkey  BOM_HEADER.BOM_KEY%TYPE;
  v_sql       VARCHAR2(4000);
  v_set       VARCHAR2(4000) := NULL;
  v_rows      PLS_INTEGER;
  cur INTEGER;

 CURSOR cur_childBoms IS
    WITH BOM_HIERARCHY (
      LEVEL_NO,
      PARENT_BOM_KEY,
      BOM_KEY,
      SUB_BOM_KEY,
      ITEM_KEY,
      ITEM_QUANTITY,
      EFFECTIVE_FROM_DT,
      EFFECTIVE_TO_DT,
      VERSION,
      BOM_PATH
    ) AS (
      SELECT
        1 AS LEVEL_NO,
        NULL AS PARENT_BOM_KEY,
        bh.BOM_KEY,
        bli.SUB_BOM_KEY,
        bli.ITEM_KEY,
        bli.ITEM_QUANTITY,
        bli.EFFECTIVE_FROM_DT,
        bli.EFFECTIVE_TO_DT,
        bh.VERSION,
        TO_CHAR(bh.BOM_KEY) AS BOM_PATH
      FROM BOM_HEADER bh
      LEFT JOIN BOM_LINE_ITEM bli ON bh.BOM_KEY = bli.BOM_KEY
      WHERE bh.BOM_KEY = p_bom_key
      UNION ALL
      SELECT
        bh.LEVEL_NO + 1,
        bh.BOM_KEY AS PARENT_BOM_KEY,
        bli.BOM_KEY,
        bli.SUB_BOM_KEY,
        bli.ITEM_KEY,
        bli.ITEM_QUANTITY,
        bli.EFFECTIVE_FROM_DT,
        bli.EFFECTIVE_TO_DT,
        bh.VERSION,
        bh.BOM_PATH || '>' || TO_CHAR(bli.BOM_KEY)
      FROM BOM_LINE_ITEM bli
      JOIN BOM_HIERARCHY bh ON bli.BOM_KEY = bh.SUB_BOM_KEY
    )
    SELECT BOM_KEY
    FROM   BOM_HIERARCHY
    ORDER BY LEVEL_NO;

   v_curr_bom_key BOM_HEADER.BOM_KEY%TYPE;
BEGIN

  OPEN cur_childBoms;
  LOOP
    FETCH cur_childBoms INTO v_curr_bom_key;
    EXIT WHEN cur_childBoms%NOTFOUND;

    IF v_last_bomkey IS NULL OR v_last_bomkey <> v_curr_bom_key THEN
        v_sql := 'UPDATE BOM_HEADER SET UPDATE_DT= :p1 ';
        v_sql := v_sql || CASE WHEN p_effective_from_date IS NOT NULL THEN ' ,EFFECTIVE_FROM_DT = :p2 ' END;
        v_sql := v_sql || CASE WHEN p_effective_to_date IS NOT NULL THEN ' ,EFFECTIVE_TO_DT = :p3 ' END;
        v_sql := v_sql || CASE WHEN p_status IS NOT NULL THEN ' ,STATUS = :p4 ' END;
        v_sql := v_sql || ' WHERE BOM_KEY = :p5 ';

        cur := DBMS_SQL.OPEN_CURSOR;
        DBMS_SQL.PARSE(cur, v_sql, DBMS_SQL.NATIVE);

        DBMS_SQL.BIND_VARIABLE(cur, ':p1',      SYSDATE);
        IF p_effective_from_date IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(cur, ':p2',    p_effective_from_date);
        END IF;
        IF p_effective_to_date IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(cur, ':p3',    p_effective_to_date);
        END IF;
        IF p_status IS NOT NULL THEN
            DBMS_SQL.BIND_VARIABLE(cur, ':p4',    p_status);
        END IF;
        DBMS_SQL.BIND_VARIABLE(cur, ':p5', v_curr_bom_key);

        v_rows := DBMS_SQL.EXECUTE(cur);
        DBMS_SQL.CLOSE_CURSOR(cur);

        v_sql := 'UPDATE BOM_LINE_ITEM SET UPDATE_DT= :p1 ';
        v_sql := v_sql || CASE WHEN p_effective_from_date IS NOT NULL THEN ' ,EFFECTIVE_FROM_DT = :p2 ' END;
        v_sql := v_sql || CASE WHEN p_effective_to_date IS NOT NULL THEN ' ,EFFECTIVE_TO_DT = :p3 ' END;
        v_sql := v_sql || ' WHERE BOM_KEY = :p4 ';

        cur := DBMS_SQL.OPEN_CURSOR;
        DBMS_SQL.PARSE(cur, v_sql, DBMS_SQL.NATIVE);

        DBMS_SQL.BIND_VARIABLE(cur, ':p1',      SYSDATE);
        IF p_effective_from_date IS NOT NULL THEN
        DBMS_SQL.BIND_VARIABLE(cur, ':p2',    p_effective_from_date);
        END IF;
        IF p_effective_to_date IS NOT NULL THEN
        DBMS_SQL.BIND_VARIABLE(cur, ':p3',    p_effective_to_date);
        END IF;
        DBMS_SQL.BIND_VARIABLE(cur, ':p4', v_curr_bom_key);

        v_rows := v_rows + DBMS_SQL.EXECUTE(cur);
        DBMS_SQL.CLOSE_CURSOR(cur);

        --DBMS_OUTPUT.PUT_LINE('Rows updated: ' || v_rows);
        v_last_bomkey := v_curr_bom_key;

    END IF;
  END LOOP;
  COMMIT;
  CLOSE cur_childBoms;

EXCEPTION
  WHEN OTHERS THEN
    IF cur_childBoms%ISOPEN THEN
      CLOSE cur_childBoms;
    END IF;
    -- DBMS_OUTPUT.PUT_LINE('Error: ' || SQLCODE || ' - ' || SQLERRM);
    RAISE;
END updateChildBomsData;

CREATE OR REPLACE PROCEDURE TamSchedulerForSingleSupplier(p_fg_ids SYS.ODCINUMBERLIST DEFAULT NULL) IS
     v_tam_allocation_id          NUMBER;
     v_tam_supplier_allocation_id NUMBER;
     v_supplier_key               NUMBER;
 BEGIN
     FOR fg_rec IN (
         SELECT fg.functional_group_id,
                MAX(b.business_entity_key) AS business_entity_key
         FROM functional_group fg
         JOIN item_fg_map m ON m.functional_group_id = fg.functional_group_id
         JOIN item_avl it   ON it.item_key = m.item_key
         JOIN business_entity b ON b.business_entity_key = it.business_entity_key
         JOIN item_master im ON im.item_key = m.item_key
         LEFT JOIN tam_allocation tam
           ON tam.functional_group_id = fg.functional_group_id
          AND tam.site_key = 1
         WHERE tam.tam_allocation_id IS NULL
           AND fg.status = 'ACTIVE'
           AND NOT EXISTS (
               SELECT 1
               FROM item_fg_map m2
               JOIN item_master im2 ON im2.item_key = m2.item_key
               WHERE m2.functional_group_id = fg.functional_group_id
                 AND im2.string_attribute5 = 'Vendor Agnostic Item'
           )
           AND (p_fg_ids IS NULL OR fg.functional_group_id IN (SELECT COLUMN_VALUE FROM TABLE(p_fg_ids)))
         GROUP BY fg.functional_group_id
         HAVING COUNT(DISTINCT b.business_entity_key) = 1
     ) LOOP
         BEGIN
             v_supplier_key := fg_rec.business_entity_key;

             -- Insert into TAM_ALLOCATION
             INSERT INTO TAM_ALLOCATION (
                 TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, SITE_KEY,
                 LAST_CHANGED_ON, LAST_CHANGED_BY, ALLOW_HEDGING,
                 CREATED_ON, CREATED_BY, EXTRACT_FLAG, ROLL_OVER_COUNT,
                 CURRENT_DATA_DELETED, NEXT_ROLLOVER_DATE,
                 DISCP_EXTRACT_FLAG, DISCP_ROLLOVER_EXTRACT_FLAG,
                 LAST_ROLLOVER_DATE, SOURCE_LAST_CHANGED_BY
             )
             VALUES (
                 TAM_ALLOCATION_KEY_SEQ.NEXTVAL,
                 fg_rec.functional_group_id,
                 1, SYSDATE, 'System', 'N',
                 SYSDATE, 'ADMIN', 'P', 0,
                 NULL, NULL, 'P', 'Y', NULL, 'System'
             )
             RETURNING TAM_ALLOCATION_ID INTO v_tam_allocation_id;

             -- Insert into TAM_SUPPLIER_ALLOCATION for fiscal periods
             FOR rec IN (
                 WITH current_month AS (
                     SELECT FISCAL_PERIOD_START_DATE AS start_date,
                            FISCAL_PERIOD_END_DATE   AS end_date
                     FROM fiscal_period
                     WHERE FISCAL_PERIOD_TYPE = 'M'
                       AND TRUNC(SYSDATE) BETWEEN FISCAL_PERIOD_START_DATE AND FISCAL_PERIOD_END_DATE
                 ),
                 next_month AS (
                     SELECT FISCAL_PERIOD_START_DATE AS start_date,
                            FISCAL_PERIOD_END_DATE   AS end_date
                     FROM (
                         SELECT fp.*,
                                ROW_NUMBER() OVER (ORDER BY fp.FISCAL_PERIOD_START_DATE ASC) rn
                         FROM fiscal_period fp
                         WHERE fp.FISCAL_PERIOD_TYPE = 'M'
                           AND fp.FISCAL_PERIOD_START_DATE > TRUNC(SYSDATE)
                     )
                     WHERE rn = 1
                 ),
                 weeks_in_two_months AS (
                     SELECT w.FISCAL_PERIOD_START_DATE AS start_date,
                            w.FISCAL_PERIOD_END_DATE   AS end_date,
                            CASE
                                WHEN w.FISCAL_PERIOD_END_DATE < TRUNC(SYSDATE)
                                     AND w.FISCAL_PERIOD_END_DATE >= TRUNC(SYSDATE) - 14
                                THEN 0 ELSE 100
                            END AS allocation
                     FROM fiscal_period w
                     WHERE w.FISCAL_PERIOD_TYPE = 'W'
                       AND EXISTS (
                           SELECT 1 FROM current_month m
                           WHERE w.FISCAL_PERIOD_START_DATE <= m.end_date
                             AND w.FISCAL_PERIOD_END_DATE   >= m.start_date
                       )
                     UNION ALL
                     SELECT w.FISCAL_PERIOD_START_DATE,
                            w.FISCAL_PERIOD_END_DATE,
                            100
                     FROM fiscal_period w
                     WHERE w.FISCAL_PERIOD_TYPE = 'W'
                       AND EXISTS (
                           SELECT 1 FROM next_month m
                           WHERE w.FISCAL_PERIOD_START_DATE <= m.end_date
                             AND w.FISCAL_PERIOD_END_DATE   >= m.start_date
                       )
                 ),
                 months_after_two AS (
                     SELECT FISCAL_PERIOD_START_DATE AS start_date,
                            FISCAL_PERIOD_END_DATE   AS end_date,
                            100 AS allocation
                     FROM (
                         SELECT fp.*,
                                ROW_NUMBER() OVER (ORDER BY fp.FISCAL_PERIOD_START_DATE ASC) rn
                         FROM fiscal_period fp
                         WHERE fp.FISCAL_PERIOD_TYPE = 'M'
                           AND fp.FISCAL_PERIOD_START_DATE >= TRUNC(SYSDATE)
                     )
                     WHERE rn > 1 AND rn < 12
                 ),
                 fiscal_periods AS (
                     SELECT * FROM weeks_in_two_months
                     UNION ALL
                     SELECT * FROM months_after_two
                 )
                 SELECT v_supplier_key AS business_entity_key,
                        fp.start_date, fp.end_date, fp.allocation
                 FROM fiscal_periods fp
                 ORDER BY fp.start_date
             ) LOOP
                 INSERT INTO TAM_SUPPLIER_ALLOCATION (
                     TAM_SUPPLIER_ALLOCATION_ID, TAM_ALLOCATION_ID,
                     BUSINESS_ENTITY_KEY, START_DATE, END_DATE, ALLOCATION
                 )
                 VALUES (
                     TAM_SUPPLIER_ALLOCATION_KEY_SEQ.NEXTVAL,
                     v_tam_allocation_id,
                     rec.business_entity_key,
                     rec.start_date,
                     rec.end_date,
                     rec.allocation
                 )
                 RETURNING TAM_SUPPLIER_ALLOCATION_ID INTO v_tam_supplier_allocation_id;

                 -- Insert into TAM_ITEM_ALLOCATION
                 FOR item_rec IN (
                     SELECT im.item_key
                     FROM item_fg_map m
                     JOIN item_master im ON im.item_key = m.item_key
                     WHERE m.functional_group_id = fg_rec.functional_group_id
                       AND (im.string_attribute5 IS NULL OR im.string_attribute5 <> 'Vendor Agnostic Item')
                 ) LOOP
                     INSERT INTO TAM_ITEM_ALLOCATION (
                         TAM_ITEM_ALLOCATION_ID, TAM_SUPPLIER_ALLOCATION_ID,
                         ITEM_KEY, ALLOCATION
                     )
                     VALUES (
                         TAM_ITEM_ALLOCATION_KEY_SEQ.NEXTVAL,
                         v_tam_supplier_allocation_id,
                         item_rec.item_key,
                         0
                     );
                 END LOOP;
             END LOOP;

         EXCEPTION
             WHEN NO_DATA_FOUND THEN
                 DBMS_OUTPUT.PUT_LINE('Condition not satisfied for FG ' || fg_rec.functional_group_id);
             WHEN OTHERS THEN
                 ROLLBACK;
                 DBMS_OUTPUT.PUT_LINE('Error processing FG ' || fg_rec.functional_group_id || ': ' || SQLERRM);
         END;
     END LOOP;

     COMMIT;
 EXCEPTION
     WHEN OTHERS THEN
         ROLLBACK;
         DBMS_OUTPUT.PUT_LINE('Fatal error in procedure: ' || SQLERRM);
 END;
 /

--Run the Quartz table script for Oracle
@./deploy/schema/oracle/quartz_tables_oracle.sql

 --Corn Job for TamSchedulerSingleSupplierCFG at 12 AM
 INSERT INTO APP_JOB_CONFIG VALUES (
   JOB_CONFIG_SEQ.NEXTVAL,
   'TAM_SCHEDULER_SINGLE_SUPPLIER_CFG_JOB',
   'TAM_SCHEDULER_CFG_GROUP',
   'com.scplatform.jobs.TamSchedulerSingleSupplierFGJob',
   '0 0 0 * * ?',  -- run daily at 12 AM
   'CRON',
   NULL,
   1,
   'TamScheduler job at 12 AM',
   SYSDATE,
   SYSDATE
 );


