WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

-- Add Cost Element Type to Cost Elements
ALTER TABLE PCM_COST_ELEMENT ADD COST_ELEMENT_TYPE VARCHAR2(32);
UPDATE PCM_COST_ELEMENT SET COST_ELEMENT_TYPE = 'MATERIAL';
COMMIT;
ALTER TABLE PCM_COST_ELEMENT MODIFY (COST_ELEMENT_TYPE NOT NULL);
ALTER TABLE PCM_COST_ELEMENT ADD CONSTRAINT PCMCE_CETYPE CHECK (COST_ELEMENT_TYPE in ('MATERIAL','TRANSFORMATION', 'FIXED'));


-- Cost Record Ranges
CREATE SEQUENCE PCM_COST_RECORD_RANGE_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE PCM_COST_RECORD_RANGE
(
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    FROM_RANGE DECIMAL(19,4) NOT NULL,
    TO_RANGE DECIMAL(19,4),
    IS_ACTIVE NUMBER(1),
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    CONSTRAINT PCMCRRNG_ACTIVE_BOOL CHECK (IS_ACTIVE in (0,1)),
    CONSTRAINT PCMCRRNG_FRM_LT_TO CHECK (FROM_RANGE < TO_RANGE),
    CONSTRAINT PCMCRRNG_CR_FK FOREIGN KEY(COST_RECORD_KEY)
        REFERENCES PCM_COST_RECORD(COST_RECORD_KEY) ON DELETE CASCADE,
    CONSTRAINT PCMCRRNG_PK PRIMARY KEY(COST_RECORD_RANGE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;

DECLARE
	v_max pcm_cost_record.cost_record_key%TYPE;
	l_min_record_key pcm_cost_record.cost_record_key%TYPE;
	l_max_record_key pcm_cost_record.cost_record_key%TYPE;
	l_increment NUMBER := 10000;
BEGIN
	SELECT MIN(cost_record_key), MAX(cost_record_key)
	INTO l_min_record_key, l_max_record_key
	FROM pcm_cost_record;
	 
	WHILE l_min_record_key <= l_max_record_key LOOP
	 
		INSERT INTO pcm_cost_record_range (cost_record_range_key, cost_record_key, from_range, is_active, audit_rev)
		SELECT cost_record_key, cost_record_key, 0,1,0
		FROM pcm_cost_record 
		WHERE cost_record_key BETWEEN l_min_record_key AND (l_min_record_key + l_increment);	    
		COMMIT;
		l_min_record_key := l_min_record_key + l_increment + 1;
	 
	END LOOP;
	COMMIT;
	
	v_max := l_max_record_key + 1000;
		
	EXECUTE IMMEDIATE 'ALTER SEQUENCE PCM_COST_RECORD_RANGE_SEQ INCREMENT BY ' || v_max;
	
	SELECT PCM_COST_RECORD_RANGE_SEQ.NEXTVAL INTO v_max FROM DUAL;
	
	EXECUTE IMMEDIATE 'ALTER SEQUENCE PCM_COST_RECORD_RANGE_SEQ INCREMENT BY 1';
END;
/
	
ALTER TABLE PCM_COST_RECORD_VALUE DROP CONSTRAINT PCMCRV_CR_FK;

DROP INDEX XCRVALUE_VALUE;

ALTER TABLE PCM_COST_RECORD_VALUE
	RENAME COLUMN COST_RECORD_KEY TO COST_RECORD_RANGE_KEY;
		
ALTER TABLE PCM_COST_RECORD_VALUE ADD CONSTRAINT PCMCRV_CRRNG_FK 
	FOREIGN KEY(COST_RECORD_RANGE_KEY)
    REFERENCES PCM_COST_RECORD_RANGE(COST_RECORD_RANGE_KEY);
    
CREATE UNIQUE INDEX PCMCRV_CRRNG_UIDX on PCM_COST_RECORD_VALUE(
	COST_RECORD_RANGE_KEY,COST_ELEMENT_KEY)
	TABLESPACE AUDIT_INDEX;

CREATE INDEX XCRVALUE_RANGE ON PCM_COST_RECORD_VALUE(
   COST_RECORD_RANGE_KEY,COST_VALUE)
   TABLESPACE AUDIT_INDEX;
   

	

-- Pricing Scenario
CREATE TABLE PCM_PRICING_SCENARIO
(
    PRICING_SCENARIO_KEY NUMBER(19) NOT NULL,
    PRICING_SCENARIO_NAME VARCHAR2(64) NOT NULL,    
    IS_RANGE_BASED NUMBER(1) DEFAULT 0 NOT NULL,    
    CONSTRAINT PCMPS_ISRANGE_BOOL CHECK (IS_RANGE_BASED in (0,1)),    
    CONSTRAINT PCMPS_PK PRIMARY KEY(PRICING_SCENARIO_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;  

ALTER TABLE PCM_COST_RECORD ADD(PRICING_SCENARIO_KEY NUMBER(19));
ALTER TABLE PCM_COST_RECORD
       ADD  ( CONSTRAINT PCMCR_PS_FK 
              FOREIGN KEY (PRICING_SCENARIO_KEY)
                             REFERENCES PCM_PRICING_SCENARIO) ;

--to include new column as primary key in ITEM_AVL---
-- create sequence for Item_AVL table
CREATE  SEQUENCE ITEM_AVL_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
---create new mapping table -----
CREATE TABLE PCM_ITEM_AVL_SITE
(
   AVL_KEY NUMBER(19) NOT NULL,
   SITE_KEY NUMBER(19) NOT NULL
)TABLESPACE AUDIT_DATA;    

ALTER TABLE PCM_ITEM_AVL_SITE
       ADD  ( CONSTRAINT ITEMAVLST_PK PRIMARY KEY (AVL_KEY,SITE_KEY)
       USING INDEX TABLESPACE AUDIT_INDEX ) ;

ALTER TRIGGER T_ITEM_AVL DISABLE;

ALTER TABLE ITEM_AVL DROP CONSTRAINT XITMAVL_PK;
ALTER TABLE ITEM_AVL ADD AVL_KEY NUMBER(19);

DECLARE
l_cnt NUMBER := 1;
BEGIN
 WHILE l_cnt <> 0 LOOP
   UPDATE item_avl
   SET avl_key = ITEM_AVL_SEQ.NEXTVAL
   WHERE avl_key IS NULL
    AND ROWNUM < 1001;

   l_cnt := SQL%ROWCOUNT;
   COMMIT;
 END LOOP;
END;
/

ALTER TABLE ITEM_AVL MODIFY AVL_KEY NOT NULL;
ALTER TABLE ITEM_AVL ADD CONSTRAINT XITMAVL_PK PRIMARY KEY (AVL_KEY) USING INDEX TABLESPACE AUDIT_INDEX;

--making coulmns as unique index after removing them as primary key

CREATE UNIQUE INDEX XIAVL_U1
       ON ITEM_AVL(ITEM_KEY, BUSINESS_ENTITY_KEY,
       SUPPLIER_PART_KEY) 
       TABLESPACE AUDIT_INDEX;
       
ALTER TRIGGER T_ITEM_AVL ENABLE;

INSERT INTO PCM_ITEM_AVL_SITE (AVL_KEY, SITE_KEY)
SELECT avl_key, site_key
FROM item_avl where site_key IS NOT NULL;
COMMIT;

ALTER TABLE PCM_ITEM_AVL_SITE
       ADD  ( CONSTRAINT ITEMAVLST_R01_XITMAVL
              FOREIGN KEY (AVL_KEY)
                             REFERENCES ITEM_AVL ON DELETE CASCADE ) ;
                             
ALTER TABLE PCM_ITEM_AVL_SITE
       ADD  ( CONSTRAINT ITEMAVLST_R02_SITE
              FOREIGN KEY (SITE_KEY)
                             REFERENCES SITE ) ;
                             
ALTER TABLE ITEM_AVL DROP CONSTRAINT ITMAVL_R04_SITE;
ALTER TABLE ITEM_AVL DROP COLUMN SITE_KEY;

       
----Changing the Index for PCM_SUPPLIER_ALLOCATION---

DROP INDEX XSA_SUPPSITEKEY_I2;

DROP INDEX XSA_U1;

CREATE UNIQUE INDEX XSA_U1
    ON PCM_SUPPLIER_ALLOCATION(CUSTOMER_ITEM_GROUP_ITEM_KEY ASC,
    CUSTOMER_ITEM_KEY ASC,SUPPLIER_ITEM_KEY ASC,
    SUPPLIER_BUSINESS_ENTITY_KEY ASC,CUSTOMER_SITE_KEY ASC,SUPPLIER_SITE_KEY ASC,
    EFFECTIVE_FROM_DT ASC,EFFECTIVE_TO_DT ASC)
    TABLESPACE AUDIT_INDEX;



-- Repains BOM
ALTER TABLE BOM_HEADER ADD (IS_REPAIRS NUMBER(1) NULL);


-- Attrition Rate to BOM
ALTER TABLE BOM_LINE_ITEM ADD (ATTRITION_RATE NUMBER(19, 4) NULL);

-- Item Category Cost Record
CREATE  SEQUENCE PCM_ITEM_CATEGORY_CR_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE PCM_ITEM_CATEGORY_COST_RECORD
(
	ITEM_CATEGORY_COST_RECORD_KEY NUMBER(19) NOT NULL,
	ITEM_CATEGORY_KEY NUMBER(19) NOT NULL,
	ITEM_KEY NUMBER(19),
	INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
	CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT PCMICCR_IC_FK FOREIGN KEY(ITEM_CATEGORY_KEY)
        REFERENCES ITEM_CATEGORY,
    CONSTRAINT PCMICCR_ITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,
    CONSTRAINT PCMICCR_PK PRIMARY KEY(ITEM_CATEGORY_COST_RECORD_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE UNIQUE INDEX XPCMICCR_U1
    ON PCM_ITEM_CATEGORY_COST_RECORD(ITEM_CATEGORY_KEY, ITEM_KEY)
    TABLESPACE AUDIT_INDEX;
    
CREATE TABLE PCM_ITEM_CATEGORY_CRV
(
	ITEM_CATEGORY_COST_RECORD_KEY NUMBER(19) NOT NULL,
	COST_TYPE_KEY VARCHAR(32) NOT NULL,
	COST_VALUE DECIMAL(19,6) NOT NULL,
	CONSTRAINT PCMICCRV_ICCR_FK FOREIGN KEY(ITEM_CATEGORY_COST_RECORD_KEY)
        REFERENCES PCM_ITEM_CATEGORY_COST_RECORD,
    CONSTRAINT PCMICCRV_CTYPE_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT PCMICCRV_PK PRIMARY KEY(ITEM_CATEGORY_COST_RECORD_KEY,COST_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

--insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
-- values ('NEW_ICCR', 'New Commodity Code Cost Record', 'MCM', 'SL', 'newItemCategoryCostRecord.do', 4, NULL);

--insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
-- values ('SEARCH_ICCR', 'Search Commodity Code Cost Records', 'MCM', 'SL', 'searchItemCategoryCostRecord.do', 5, NULL);

ALTER TABLE PCM_COST_TYPE ADD USE_IN_ITEM_CATEGORY_COST VARCHAR2(1) DEFAULT 'N' NOT NULL;

-- Defect Type and Bom Line Attrition Rate
CREATE SEQUENCE PCM_DEFECT_TYPE_SEQ
		INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE PCM_DEFECT_TYPE
(
	DEFECT_TYPE_KEY NUMBER(19) NOT NULL,
	DEFECT_NAME VARCHAR2(64) NOT NULL
) TABLESPACE AUDIT_DATA;

ALTER TABLE PCM_DEFECT_TYPE
	ADD CONSTRAINT PCMDT_PK PRIMARY KEY(DEFECT_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX;

CREATE UNIQUE INDEX PCMDT_NAME_UIDX on PCM_DEFECT_TYPE(DEFECT_NAME)
    TABLESPACE AUDIT_INDEX;
        
CREATE TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
(
	BOM_LINE_ITEM_KEY NUMBER(19) NOT NULL,
	ITEM_KEY NUMBER(19) NOT NULL,
	DEFECT_TYPE_KEY NUMBER(19) NOT NULL,
	ATTRITION_RATE NUMBER(19,4)
) TABLESPACE AUDIT_DATA;

ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_PK PRIMARY KEY(BOM_LINE_ITEM_KEY,ITEM_KEY,DEFECT_TYPE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX;

ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_BLI_FK FOREIGN KEY(BOM_LINE_ITEM_KEY)
        REFERENCES BOM_LINE_ITEM;
        
ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_ITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER;
        
ALTER TABLE PCM_BOM_LINE_ITEM_ATTRITION_RT
	ADD CONSTRAINT PCMBLIAR_PCMDT_FK FOREIGN KEY(DEFECT_TYPE_KEY)
        REFERENCES PCM_DEFECT_TYPE;
        
-- add BOM Replace if the role has BOM Save
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY,ENTITY_TYPE,ROLE_KEY,ACL)
SELECT PCM_ACL_SEQ.NEXTVAL,'BOM',ROLE_KEY,'Replace'
FROM PCM_ACCESS_CONTROL WHERE ENTITY_TYPE = 'BOM' AND ACL = 'Save';
