WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE ITEM_MASTER ADD INVENTORY DECIMAL(19,6);

DECLARE
BEGIN
     EXECUTE IMMEDIATE 'CREATE INDEX XPAHT_I1 ON PCM_AUDIT_HISTORY_TARGETS(PCM_TARGET_KEY) TABLESPACE AUDIT_INDEX';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/

ALTER TABLE PCM_COST_TYPE ADD USE_SUPPLIER_IN_ROLLUP VARCHAR2(1) DEFAULT 'N' NOT NULL;

ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE1 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE2 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE3 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE4 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE5 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE6 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE7 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE8 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE9 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD STRING_ATTRIBUTE10 VARCHAR2(1024);
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE1 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE2 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE3 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE4 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE5 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE6 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE7 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE8 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE9 NUMBER; 
ALTER TABLE PCM_COST_RECORD ADD NUMBER_ATTRIBUTE10 NUMBER;
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE1 NUMBER(19,6);
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE2 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE3 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE4 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE5 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE6 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE7 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE8 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE9 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD FLOAT_ATTRIBUTE10 NUMBER(19,6); 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE1 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE2 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE3 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE4 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE5 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE6 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE7 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE8 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE9 DATE; 
ALTER TABLE PCM_COST_RECORD ADD DATE_ATTRIBUTE10 DATE;
