-- SCPlatform-8441: New column LAST_LOADED_BY_USER added in 3 table PCM_FORECAST, PCM_COST_RECORD, PCM_AUDIT_HISTORY --
ALTER TABLE PCM_FORECAST
    ADD LAST_LOADED_BY_USER VARCHAR2(64);
    
ALTER TABLE PCM_COST_RECORD
    ADD LAST_LOADED_BY_USER VARCHAR2(64);
    
ALTER TABLE PCM_AUDIT_HISTORY
    ADD LAST_LOADED_BY_USER VARCHAR2(64);