

ALTER TABLE FUNCTIONAL_GROUP add (
PARENT_ITEM_KEY NUMBER(19,0),
ODM_PART_KEY NUMBER(19,0),
CONSTRAINT FG_PARENT_ITEM_FK FOREIGN KEY (PARENT_ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT FG_ODM_PART_FK FOREIGN KEY (ODM_PART_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)	
);


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IV_FUNCTIONAL_GROUP" ("FUNCTIONAL_GROUP_ID", "FG_NAME", "FG_DESCRIPTION", "FG_TYPE", "FG_STATUS", "STATUS_CHANGED_BY", "FG_LAST_CHAGNED_ON", "FG_LAST_CHANGED_BY", "EXTRACT_FLAG", "CREATED_ON", "CREATED_BY", "FG_LOB","FG_PLATFORM", "PARENT_FUNCTIONAL_GROUP_ID", "PG_NAME", "PG_DESCRIPTION", "PG_TYPE", "PURPOSE", "PG_LAST_CHANGED_ON", "PG_LAST_CHANGED_BY", "PFG_CREATED_ON", "PFG_CREATED_BY", "ITEM_IDENTIFIER","PARENT_ITEM_IDENTIFIER", "ODM_PART_IDENTIFIER", "PARENT_ITEM_BUSINESS_NAME", "ODM_PART_BUSINESS_NAME") AS 
  SELECT
FG.FUNCTIONAL_GROUP_ID,
FG.NAME AS FG_NAME,
FG.DESCRIPTION AS FG_DESCRIPTION,
FG.TYPE AS FG_TYPE,
FG.STATUS AS FG_STATUS,
FG.STATUS_CHANGED_BY,
FG.LAST_CHANGED_ON AS FG_LAST_CHAGNED_ON,
FG.LAST_CHANGED_BY AS FG_LAST_CHANGED_BY,
FG.EXTRACT_FLAG,
FG.CREATED_ON,
FG.CREATED_BY,
FGLOB.VALUE AS FG_LOB,
FG.FG_PLATFORM,
PFG.PARENT_FUNCTIONAL_GROUP_ID,
PFG.NAME AS PG_NAME,
PFG.DESCRIPTION AS PG_DESCRIPTION,
PFG.TYPE AS PG_TYPE,
PFG.PURPOSE,
PFG.LAST_CHANGED_ON AS PG_LAST_CHANGED_ON,
PFG.LAST_CHANGED_BY AS PG_LAST_CHANGED_BY,
PFG.CREATED_ON AS PFG_CREATED_ON,
PFG.CREATED_BY AS PFG_CREATED_BY,
IM.ITEM_IDENTIFIER,
PI.ITEM_IDENTIFIER AS PARENT_ITEM_IDENTIFIER,
ODM.ITEM_IDENTIFIER AS ODM_PART_IDENTIFIER,
PIB.BUSINESS_ENTITY_NAME AS PARENT_ITEM_BUSINESS_NAME,
ODMB.BUSINESS_ENTITY_NAME AS ODM_PART_BUSINESS_NAME
FROM FUNCTIONAL_GROUP FG
LEFT OUTER JOIN FG_LOB_VALUES FGLOB ON FGLOB.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN FG_PFG_MAP FGMAP ON FGMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN PARENT_FUNCTIONAL_GROUP PFG ON PFG.PARENT_FUNCTIONAL_GROUP_ID = FGMAP.PARENT_FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_FG_MAP IMAP ON IMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = IMAP.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM IP ON IP.ITEM_PLATFORM_KEY = FG.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_MASTER PI ON PI.ITEM_KEY = FG.PARENT_ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY PIB ON PIB.BUSINESS_ENTITY_KEY = PI.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN ITEM_MASTER ODM ON ODM.ITEM_KEY = FG.ODM_PART_KEY
LEFT OUTER JOIN BUSINESS_ENTITY ODMB ON ODMB.BUSINESS_ENTITY_KEY = ODM.BUSINESS_ENTITY_KEY
ORDER BY FUNCTIONAL_GROUP_ID ASC;

