ALTER TABLE COMMODITY_PROFILE ADD INCLUDE_EXCLUDE_TAM VARCHAR2(255);


insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('TAM_DOWNLOAD', 'Download', 'MCM', 'TAM', 'searchTAMDownload.do', 3, NULL);

CREATE TABLE SITE_DETAILS (
ID NUMBER(19,0) NOT NULL,
MRP_SITE VARCHAR2(255),
INTERFACE_SITE VARCHAR2(255),
COST_NEGOTIATION_FLAG VARCHAR2(1),
DEMAND_FORECAST_FLAG VARCHAR2(1),
TAM_VISIBLE_FLAG VARCHAR2(1),
TAM_PROCESSING_FLAG VARCHAR2(1),
SITE_STATE VARCHAR2(1),
SITE_OWNER VARCHAR2(255),
ODM_SUPPLIER VARCHAR2(255),
EOL_LAST_UPDATE_ON TIMESTAMP,
CONSTRAINT SITE_DETAILS_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

ALTER TABLE SITE ADD SITE_DETAIL_ID NUMBER(19,0);
ALTER TABLE SITE
ADD CONSTRAINT SITE_DETAILS_FG FOREIGN KEY (SITE_DETAIL_ID) REFERENCES SITE_DETAILS(ID);


CREATE SEQUENCE SITE_DETAILS_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE CCN_SITE (
ID NUMBER(19,0) NOT NULL,
CCN VARCHAR2(255),
GLOBAL_REGION VARCHAR2(255),
INTERFACE_REGION VARCHAR2(255),
SITE_KEY NUMBER(19,0) NOT NULL,
CONSTRAINT SITE_KEY_CCN_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT SITE_CCN_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE SITE_CCN_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE SITE_FACILITIES (
ID NUMBER(19,0) NOT NULL,
FACILITY VARCHAR2(255),
DEFAULT_FACILITY_FLAG VARCHAR2(1),
SITE_KEY NUMBER(19,0) NOT NULL,
CONSTRAINT SITE_KEY_FACILITIES_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT SITE_FACILITIES_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE SITE_FACILITIES_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE OR REPLACE VIEW IV_TAM_ALLOCATION AS
SELECT
TAM.TAM_ALLOCATION_ID,
FG.FUNCTIONAL_GROUP_ID,
FG.NAME AS FG_NAME,
TAM.LAST_CHANGED_BY AS LAST_CHANGED_BY,
TAM.LAST_CHANGED_ON AS LAST_CHANGED_ON,
TAM.ALLOW_HEDGING AS ALLOW_HEDGING,
TAM.CREATED_BY AS CREATED_BY,
TAM.CREATED_ON AS CREATED_ON,
TAM.EXTRACT_FLAG,
SI.SITE_IDENTIFIER AS SITE_IDENTIFIER,
SI.SITE_DESCRIPTION AS SITE_DESCRIPTION,
SI.SITE_TYPE AS SITE_TYPE,
BE.BUSINESS_ENTITY_IDENTIFIER AS SUPPLIER_IDENTIFIER,
BE.BUSINESS_ENTITY_NAME AS SUPPLIER_NAME,
TSA.START_DATE AS START_DATE,
TSA.END_DATE AS END_DATE,
TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
TSA.ALLOCATION AS SUPPLIER_ALLOCATION,
TIA.TAM_ITEM_ALLOCATION_ID AS TAM_ITEM_ALLOCATION_ID,
TIA.ALLOCATION AS ITEM_ALLOCATION,
IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER
FROM TAM_ALLOCATION TAM
LEFT OUTER JOIN FUNCTIONAL_GROUP FG ON FG.FUNCTIONAL_GROUP_ID = TAM.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN SITE SI ON SI.SITE_KEY = TAM.SITE_KEY
LEFT OUTER JOIN TAM_SUPPLIER_ALLOCATION TSA ON TSA.TAM_ALLOCATION_ID = TAM.TAM_ALLOCATION_ID
LEFT OUTER JOIN TAM_ITEM_ALLOCATION TIA ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = TIA.ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY BE ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
ORDER BY TAM_ALLOCATION_ID ASC, SUPPLIER_NAME ASC, START_DATE ASC;

ALTER TABLE item_master ADD EOL varchar2(1);

ALTER TABLE item_master ADD EOL_LAST_CHANGED_ON TIMESTAMP;

ALTER TABLE item_master ADD EOL_TYPE varchar2(255);

ALTER TABLE TAM_ALLOCATION ADD NEXT_ROLLOVER_DATE TIMESTAMP(6);

ALTER TABLE FG_AUDIT_HISTORY MODIFY DATE_PERFORMED TIMESTAMP(6);

ALTER TABLE TAM_ALLOCATION ADD CURRENT_DATA_DELETED VARCHAR2(1);

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Supply Allocation' WHERE WORKFLOW_KEY = 'FUNCTIONAL_GROUP';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Audit History (Allocation)' WHERE WORKFLOW_KEY = 'TAM_HISTORY';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Audit History (Functional Group)' WHERE WORKFLOW_KEY = 'HISTORY';

UPDATE PCM_WORKFLOW set WORKFLOW_PARENT_KEY = 'FUNCTIONAL_GROUP' WHERE WORKFLOW_KEY IN  ('ALLOCATION','TAM_HISTORY','TAM_DOWNLOAD');

DELETE PCM_WORKFLOW WHERE WORKFLOW_KEY = 'TAM';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Supply Allocation (Sub-Tier)' WHERE WORKFLOW_KEY = 'SA';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Manage Allocation' WHERE WORKFLOW_KEY = 'ALLOCATION';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Download Allocation' WHERE WORKFLOW_KEY = 'TAM_DOWNLOAD';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Manage Parent Group' WHERE WORKFLOW_KEY = 'MANAGE_PARENT';

UPDATE PCM_WORKFLOW set WORKFLOW_NAME = 'Audit History (Allocation)' WHERE WORKFLOW_KEY = 'TAM_HISTORY';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 1 WHERE WORKFLOW_KEY = 'MANAGE_PARENT';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 2 WHERE WORKFLOW_KEY = 'MANAGE_GROUP';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 3 WHERE WORKFLOW_KEY = 'ALLOCATION';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 4 WHERE WORKFLOW_KEY = 'TAM_DOWNLOAD';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 5 WHERE WORKFLOW_KEY = 'HISTORY';

UPDATE PCM_WORKFLOW set DISPLAY_ORDER = 6 WHERE WORKFLOW_KEY = 'TAM_HISTORY';