WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

DECLARE
BEGIN
     EXECUTE IMMEDIATE 'ALTER TABLE PCM_ITEM_CATEGORY_CRV DROP CONSTRAINT PCMICCRV_PK';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
DECLARE
BEGIN
     EXECUTE IMMEDIATE 'DROP INDEX PCMICCRV_PK';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/

-- Analytics
CREATE SEQUENCE PCM_ANALYTICS_RUN_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_ANALYTICS_RESULT_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE PCM_ANALYTICS_RUN
  (
    RUN_ID NUMBER(19,0) NOT NULL,
    STARTED_AT TIMESTAMP (6) NOT NULL,
    ENDED_AT TIMESTAMP (6),
    ANALYTICS_TYPE VARCHAR2(50) NOT NULL,
    CONSTRAINT XANARUN_PK PRIMARY KEY (RUN_ID) USING INDEX TABLESPACE AUDIT_INDEX
  ) TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_ANALYTICS_RESULT
  (
    RESULT_ID        NUMBER(19,0) NOT NULL,
    ANALYTICS_RUN_ID NUMBER(19,0) NOT NULL,
    ANALYTICS_RESULT_TYPE VARCHAR2(50) NOT NULL,
    STRINGCOL1       VARCHAR2(255),
    STRINGCOL2       VARCHAR2(255),
    STRINGCOL3       VARCHAR2(255),
    STRINGCOL4       VARCHAR2(255),
    NUMCOL1          NUMBER(19,6),
    NUMCOL2          NUMBER(19,6),
    NUMCOL3          NUMBER(19,6),
    NUMCOL4          NUMBER(19,6),
    DATECOL1 TIMESTAMP (6),
    DATECOL2 TIMESTAMP (6),
    DATECOL3 TIMESTAMP (6),
    DATECOL4 TIMESTAMP (6),
    SERIALIZATION_TYPE VARCHAR2(50),
    SERIALIZED_RESULT BLOB,
    CONSTRAINT XANARES_PK PRIMARY KEY (RESULT_ID) USING INDEX TABLESPACE AUDIT_INDEX
  ) TABLESPACE AUDIT_DATA;

ALTER TABLE PCM_ANALYTICS_RESULT
  ADD CONSTRAINT ANARES_ANARUN_FK FOREIGN KEY(ANALYTICS_RUN_ID) 
  	REFERENCES PCM_ANALYTICS_RUN ON DELETE CASCADE;

ALTER TABLE PCM_ITEM_CATEGORY_COST_RECORD ADD DELETE_FLAG VARCHAR2(1);
ALTER TABLE PCM_ITEM_CATEGORY_COST_RECORD ADD DESCRIPTION VARCHAR2(1024);
ALTER TABLE PCM_ITEM_CATEGORY_COST_RECORD ADD CONTEXT_OBJECT_TYPE VARCHAR2(50);
ALTER TABLE PCM_ITEM_CATEGORY_COST_RECORD ADD CONTEXT_OBJECT_ID NUMBER(19,0);
UPDATE PCM_ITEM_CATEGORY_COST_RECORD SET CONTEXT_OBJECT_TYPE='ITEM',CONTEXT_OBJECT_ID=ITEM_KEY;
DROP INDEX XPCMICCR_U1;
ALTER TABLE PCM_ITEM_CATEGORY_COST_RECORD DROP COLUMN ITEM_KEY;
CREATE UNIQUE INDEX XPCMICCR_U1
    ON PCM_ITEM_CATEGORY_COST_RECORD(ITEM_CATEGORY_KEY, CONTEXT_OBJECT_TYPE, CONTEXT_OBJECT_ID)
    TABLESPACE AUDIT_INDEX;

CREATE  SEQUENCE PCM_ITEM_CATEGORY_CRV_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
ALTER TABLE PCM_ITEM_CATEGORY_CRV ADD ITEM_CATEGORY_CRV_KEY NUMBER(19);
UPDATE PCM_ITEM_CATEGORY_CRV SET ITEM_CATEGORY_CRV_KEY = PCM_ITEM_CATEGORY_CRV_SEQ.NEXTVAL;
ALTER TABLE PCM_ITEM_CATEGORY_CRV MODIFY ITEM_CATEGORY_CRV_KEY NUMBER(19) NOT NULL;
ALTER TABLE PCM_ITEM_CATEGORY_CRV
ADD CONSTRAINT PCMICCRV_PK PRIMARY KEY (ITEM_CATEGORY_CRV_KEY) USING INDEX TABLESPACE AUDIT_INDEX;

ALTER TABLE PCM_ITEM_CATEGORY_CRV ADD EFFECTIVE_FROM_DT DATE;
ALTER TABLE PCM_ITEM_CATEGORY_CRV ADD EFFECTIVE_TO_DT DATE;
DECLARE
	from_dt pcm_item_category_crv.effective_from_dt%TYPE;
	to_dt pcm_item_category_crv.effective_to_dt%TYPE;
BEGIN
	SELECT fiscal_period_start_date,fiscal_period_end_date
	INTO from_dt,to_dt
	FROM fiscal_period
	WHERE fiscal_period_start_date <= trunc(sysdate)
	AND fiscal_period_end_date >= trunc(sysdate)
	AND fiscal_period_type = 'M';
	
	UPDATE pcm_item_category_crv
	SET effective_from_dt = from_dt, effective_to_dt = to_dt;
	
	EXCEPTION
	  WHEN NO_DATA_FOUND THEN NULL;
END;
/
ALTER TABLE PCM_ITEM_CATEGORY_CRV MODIFY EFFECTIVE_FROM_DT DATE NOT NULL;

CREATE UNIQUE INDEX XPCMICCRV_U1 
  ON PCM_ITEM_CATEGORY_CRV(ITEM_CATEGORY_COST_RECORD_KEY,COST_TYPE_KEY,EFFECTIVE_FROM_DT)
  TABLESPACE AUDIT_INDEX;
-- END Analytics