ALTER TABLE commodity_profile
ADD INCLUDE_EXCLUDE_PRICE_TAM VARCHAR2(255);

--cost exception model start
CREATE SEQUENCE COST_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE COST_EXCEPTION_ODM_CM_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_LOB_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_INFO_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE COST_EXCEPTION_PRICING_SEQ
		INCREMENT BY 1
		START WITH 1
		NOMAXVALUE
		NOMINVALUE
		CACHE 20
		NOCYCLE ORDER;
		

CREATE SEQUENCE PCM_COST_RECORD_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
 CREATE SEQUENCE PCM_COST_RECORD_RANGE_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PCM_COST_RECORD_VALUE_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE PCM_COST_RECORD_VALUE_DETAIL_EXCEPTION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE SEQUENCE COST_EXCEPTION_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
CREATE TABLE COST_EXCEPTION(
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	EXCEPTION_ID VARCHAR2(255) NOT NULL,
	EXCEPTION_NAME VARCHAR2(255) NOT NULL,
	EXCEPTION_REQUESTOR VARCHAR2(255),
	EXCEPTION_OWNER VARCHAR2(255),
	EXCEPTION_APPROVER VARCHAR2(255),
	COST_TYPE_KEY VARCHAR2(32) NOT NULL,
	REQUEST_TYPE VARCHAR2(255),
	COMMODITY VARCHAR2(255),
	SUBTIER VARCHAR2(1),
	PLATFORM_NAME VARCHAR2(255),
	ODM_ACKNOWLEDGEMENT VARCHAR2(255),
	PREVIOUS_STATE VARCHAR2(255),
	STATE VARCHAR2(255),
	APPROVED_ON TIMESTAMP(6),
	APPROVED_BY VARCHAR2(255),
	REJECTED_ON TIMESTAMP(6),
	REJECTED_BY VARCHAR2(255),
	CLOSED_ON TIMESTAMP(6),
	CLOSED_BY VARCHAR2(255),
	REQUESTED_ON TIMESTAMP(6),
	CREATED_ON TIMESTAMP(6) NOT NULL,
	CREATED_BY VARCHAR2(255) NOT NULL,
	LAST_CHANGED_ON TIMESTAMP(6),
	LAST_CHANGED_BY VARCHAR2(255),
	CONSTRAINT CEXP_CTK_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT CEXP_PK PRIMARY KEY(EXCEPTION_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_ODM_CM(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	APPLICABLE_ODM_CM VARCHAR2(255),
	CONSTRAINT CEXPOC_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPOC_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_LOB(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	LINE_OF_BUSINESS VARCHAR2(255),
    CONSTRAINT CEXPL_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPL_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA; 

CREATE TABLE COST_EXCEPTION_INFO(
	ID NUMBER(19) NOT NULL,
	EXCEPTION_KEY NUMBER(19) NOT NULL,
	STATE VARCHAR2(255),
	STATE_CHANGE_BY VARCHAR2(255),
	STATE_CHANGE_ON TIMESTAMP(6),
	EXCEPTION_COMMENT VARCHAR2(1024),
	CONSTRAINT CEXPI_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPI_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;

CREATE TABLE COST_EXCEPTION_PRICING(
	ID NUMBER(19) NOT NULL,
	EXCEPTION_KEY NUMBER(19) NOT NULL,
	FILE_NAME VARCHAR2(255),
    COST_RECORD_COUNT NUMBER(19),
	UPLOADED_BY VARCHAR2(255),
	UPLOADED_ON TIMESTAMP(6),
	CONSTRAINT CEXPP_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEXPP_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;

CREATE TABLE PCM_COST_RECORD_EXCEPTION
(
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_KEY NUMBER(19) NOT NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
    COST_RECORD_EXTERNAL_ID VARCHAR2(255) NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_PROVIDER_KEY NUMBER(19) NULL,  
    DESCRIPTION VARCHAR2(1024) NULL,
    REASON_CODE VARCHAR2(128) NULL,
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),  
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    EFFECTIVE_FROM_DT DATE NULL,
    EFFECTIVE_TO_DT DATE NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP, 
    SYSTEM_ACTION VARCHAR2(1024),
    PRICING_SCENARIO_KEY NUMBER(19) NULL,
    PROJECT_NAME VARCHAR2(255), 
    STRING_ATTRIBUTE1 VARCHAR2(1024),
    STRING_ATTRIBUTE2 VARCHAR2(1024),
    STRING_ATTRIBUTE3 VARCHAR2(1024),
    STRING_ATTRIBUTE4 VARCHAR2(1024),
    STRING_ATTRIBUTE5 VARCHAR2(1024),
    STRING_ATTRIBUTE6 VARCHAR2(1024),
    STRING_ATTRIBUTE7 VARCHAR2(1024),
    STRING_ATTRIBUTE8 VARCHAR2(1024),
    STRING_ATTRIBUTE9 VARCHAR2(1024),
    STRING_ATTRIBUTE10 VARCHAR2(1024),
    NUMBER_ATTRIBUTE1 NUMBER, 
	NUMBER_ATTRIBUTE2 NUMBER, 
	NUMBER_ATTRIBUTE3 NUMBER, 
	NUMBER_ATTRIBUTE4 NUMBER, 
	NUMBER_ATTRIBUTE5 NUMBER, 
	NUMBER_ATTRIBUTE6 NUMBER, 
	NUMBER_ATTRIBUTE7 NUMBER, 
	NUMBER_ATTRIBUTE8 NUMBER, 
	NUMBER_ATTRIBUTE9 NUMBER, 
	NUMBER_ATTRIBUTE10 NUMBER,
	FLOAT_ATTRIBUTE1 NUMBER(19,6),
	FLOAT_ATTRIBUTE2 NUMBER(19,6), 
	FLOAT_ATTRIBUTE3 NUMBER(19,6), 
	FLOAT_ATTRIBUTE4 NUMBER(19,6), 
	FLOAT_ATTRIBUTE5 NUMBER(19,6), 
	FLOAT_ATTRIBUTE6 NUMBER(19,6), 
	FLOAT_ATTRIBUTE7 NUMBER(19,6), 
	FLOAT_ATTRIBUTE8 NUMBER(19,6), 
	FLOAT_ATTRIBUTE9 NUMBER(19,6), 
	FLOAT_ATTRIBUTE10 NUMBER(19,6), 
	DATE_ATTRIBUTE1 DATE, 
	DATE_ATTRIBUTE2 DATE, 
	DATE_ATTRIBUTE3 DATE, 
	DATE_ATTRIBUTE4 DATE, 
	DATE_ATTRIBUTE5 DATE, 
	DATE_ATTRIBUTE6 DATE, 
	DATE_ATTRIBUTE7 DATE, 
	DATE_ATTRIBUTE8 DATE, 
	DATE_ATTRIBUTE9 DATE, 
	DATE_ATTRIBUTE10 DATE,
    CONSTRAINT PCMCRE_SLANE_FK FOREIGN KEY(SOURCING_LANE_KEY)
        REFERENCES PCM_SOURCING_LANE ON DELETE CASCADE,
    CONSTRAINT PCMCRE_CTYPE_FK FOREIGN KEY(COST_TYPE_KEY)
        REFERENCES PCM_COST_TYPE,
    CONSTRAINT PCMCRE_CPROV_BE_FK FOREIGN KEY(COST_PROVIDER_KEY)
        REFERENCES BUSINESS_ENTITY ON DELETE SET NULL,
    CONSTRAINT PCMCRE_PS_FK FOREIGN KEY(PRICING_SCENARIO_KEY)
        REFERENCES PCM_PRICING_SCENARIO,
    CONSTRAINT PCMCRE_EK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT PCMCRE_PK PRIMARY KEY(COST_RECORD_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;  
    
CREATE TABLE PCM_COST_RECORD_RANGE_EXCEPTION
(
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_KEY NUMBER(19) NOT NULL,
    FROM_RANGE DECIMAL(19,4) NOT NULL,
    TO_RANGE DECIMAL(19,4),
    IS_ACTIVE NUMBER(1),
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    CONSTRAINT PCMCRRNGE_ACTIVE_BOOL CHECK (IS_ACTIVE in (0,1)),
    CONSTRAINT PCMCRRNGE_FRM_LT_TO CHECK (FROM_RANGE < TO_RANGE),
    CONSTRAINT PCMCRRNGE_CR_FK FOREIGN KEY(COST_RECORD_KEY)
        REFERENCES PCM_COST_RECORD_EXCEPTION(COST_RECORD_KEY) ON DELETE CASCADE,
    CONSTRAINT PCMCRRNGE_PK PRIMARY KEY(COST_RECORD_RANGE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)  TABLESPACE AUDIT_DATA;


CREATE TABLE PCM_COST_RECORD_VALUE_EXCEPTION
(
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_RECORD_RANGE_KEY NUMBER(19) NOT NULL,
    COST_TYPE_KEY VARCHAR2(32) NOT NULL,
    COST_ELEMENT_KEY VARCHAR2(32) NOT NULL,
    COST_VALUE DECIMAL(19,6) NOT NULL,
    COST_UOM VARCHAR2(6) NOT NULL,
    COST_VALUE_TYPE VARCHAR2(2) DEFAULT 'S' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,                 
    CONSTRAINT PCMCRVE_CRRNG_FK FOREIGN KEY(COST_RECORD_RANGE_KEY)
        REFERENCES PCM_COST_RECORD_RANGE_EXCEPTION(COST_RECORD_RANGE_KEY) ON DELETE CASCADE,        
    CONSTRAINT PCMCRVE_CELEMENT_FK FOREIGN KEY(COST_TYPE_KEY,COST_ELEMENT_KEY)
        REFERENCES PCM_COST_ELEMENT(COST_TYPE_KEY,COST_ELEMENT_KEY),        
    CONSTRAINT PCMCRVE_PK PRIMARY KEY(COST_RECORD_VALUE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                              
)  TABLESPACE AUDIT_DATA;
   
CREATE TABLE PCM_COST_VALUE_DETAIL_EXCEPTION
(
    COST_VALUE_DETAIL_KEY NUMBER(19) NOT NULL,
    COST_RECORD_VALUE_KEY NUMBER(19) NOT NULL,
    COST_VALUE_NAME VARCHAR2(32) NOT NULL,
    COST_VALUE_VALUE DECIMAL(19,6) NOT NULL,
    COST_VALUE_BLEND DECIMAL(6,3) NOT NULL,
    CONSTRAINT PCMCVDE_CRV_FK FOREIGN KEY(COST_RECORD_VALUE_KEY)
        REFERENCES PCM_COST_RECORD_VALUE_EXCEPTION ON DELETE CASCADE,
    CONSTRAINT PCMCVDE_PK PRIMARY KEY(COST_VALUE_DETAIL_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                               
)  TABLESPACE AUDIT_DATA;

-- This view is used by the cost exception data filters to help with access control
CREATE OR REPLACE VIEW IV_SOURCING_BUSINESS_ENTITY_EXCEPTION AS
	SELECT SL.SOURCING_LANE_KEY SOURCING_LANE_KEY, CRE.COST_RECORD_KEY COST_RECORD_KEY, 
    	SL.ITEM_KEY ITEM_KEY, IM.BUSINESS_ENTITY_KEY BUSINESS_ENTITY_KEY, 
    	SL.SUPPLIER_KEY SUPPLIER_KEY, CRE.COST_PROVIDER_KEY COST_PROVIDER_KEY,
    	CRE.COST_TYPE_KEY COST_TYPE_KEY
	FROM PCM_SOURCING_LANE SL JOIN ITEM_MASTER IM ON IM.ITEM_KEY = SL.ITEM_KEY
	LEFT OUTER JOIN PCM_COST_RECORD_EXCEPTION CRE ON CRE.SOURCING_LANE_KEY = SL.SOURCING_LANE_KEY;

--cost exception model completes

/* Item Extract */
CREATE OR REPLACE VIEW IV_ITEM_EXTRACT AS 
  SELECT
  IM.ITEM_KEY AS ITEM_KEY ,
  IM.ITEM_UNIQUE_IDENTIFIER AS ITEM_UNIQUE_IDENTIFIER,  
  IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,
  IM.ITEM_EXTERNAL_ID AS ITEM_EXTERNAL_ID,
  IM.ITEM_TYPE AS ITEM_TYPE,
  IM.GBL_UOM_CODE AS PRODUCT_UOM_CODE,
  IM.GBL_LFCYCL_PH_CODE AS LIFE_CYCLE_TYPE_CODE,
  IM.GBL_PROD_LFCYCL_CODE_OTHER AS LIFE_CYCLE_TYPE_CODE_OTHER,
  IM.ITEM_CLASSIFICATION AS ITEM_CLASSIFICATION,
  IM.PRODUCT_FAMILY AS PRODUCT_FAMILY,
  IM.MAKE_BUY AS MAKE_BUY,
  IM.MAKE_BUY_OTHER AS MAKE_BUY_OTHER,
  IM.SERIALNUMBER_REQUIRED AS SERIALNUMBER_REQUIRED,
  IM.CERTIFICATION_REQUIRED AS CERTIFICATION_REQUIRED,
  IM.OWNER_NAME AS OWNER_NAME,
  IM.ITEM_DESCRIPTION AS ITEM_DESCRIPTION,
  IM.IS_TOP_LEVEL AS IS_TOP_LEVEL,
  IM.COLLABORATION AS COLLABORATION,
  IM.ITEM_PART_TYPE AS ITEM_PART_TYPE,
  IM.INVENTORY AS INVENTORY,
  IM.EOL AS EOL,
  IM.EOL_LAST_CHANGED_ON AS EOL_LAST_CHANGED_ON,
  IM.EOL_TYPE AS EOL_TYPE,
  IM.UPDATE_DT AS UPDATE_DT,
  IM.DATA_SOURCE AS DATA_SOURCE,
  IM.VERSION AS VERSION,
  IM.REVISION AS REVISION,
  IM.VERSION_DATE AS VERSION_DATE,
  IM.REVISION_DATE AS REVISION_DATE,
  IM.MANAGED_FLAG AS MANAGED_FLAG,
  IM.STRING_ATTRIBUTE1 AS IM_STRING_ATTRIBUTE1,
  IM.STRING_ATTRIBUTE2 AS IM_STRING_ATTRIBUTE2,
  IM.STRING_ATTRIBUTE3 AS IM_STRING_ATTRIBUTE3,
  IM.STRING_ATTRIBUTE4 AS IM_STRING_ATTRIBUTE4,
  IM.STRING_ATTRIBUTE5 AS IM_STRING_ATTRIBUTE5,
  IM.STRING_ATTRIBUTE6 AS IM_STRING_ATTRIBUTE6,
  IM.STRING_ATTRIBUTE7 AS IM_STRING_ATTRIBUTE7,
  IM.STRING_ATTRIBUTE8 AS IM_STRING_ATTRIBUTE8,
  IM.STRING_ATTRIBUTE9 AS IM_STRING_ATTRIBUTE9,
  IM.STRING_ATTRIBUTE10 AS IM_STRING_ATTRIBUTE10,
  IM.NUMBER_ATTRIBUTE1 AS IM_NUMBER_ATTRIBUTE1,
  IM.NUMBER_ATTRIBUTE2 AS IM_NUMBER_ATTRIBUTE2,
  IM.NUMBER_ATTRIBUTE3 AS IM_NUMBER_ATTRIBUTE3,
  IM.NUMBER_ATTRIBUTE4 AS IM_NUMBER_ATTRIBUTE4,
  IM.NUMBER_ATTRIBUTE5 AS IM_NUMBER_ATTRIBUTE5,
  IM.NUMBER_ATTRIBUTE6 AS IM_NUMBER_ATTRIBUTE6,
  IM.NUMBER_ATTRIBUTE7 AS IM_NUMBER_ATTRIBUTE7,
  IM.NUMBER_ATTRIBUTE8 AS IM_NUMBER_ATTRIBUTE8,
  IM.NUMBER_ATTRIBUTE9 AS IM_NUMBER_ATTRIBUTE9,
  IM.NUMBER_ATTRIBUTE10 AS IM_NUMBER_ATTRIBUTE10,
  IM.FLOAT_ATTRIBUTE1 AS IM_FLOAT_ATTRIBUTE1,
  IM.FLOAT_ATTRIBUTE2 AS IM_FLOAT_ATTRIBUTE2,
  IM.FLOAT_ATTRIBUTE3 AS IM_FLOAT_ATTRIBUTE3,
  IM.FLOAT_ATTRIBUTE4 AS IM_FLOAT_ATTRIBUTE4,
  IM.FLOAT_ATTRIBUTE5 AS IM_FLOAT_ATTRIBUTE5,
  IM.FLOAT_ATTRIBUTE6 AS IM_FLOAT_ATTRIBUTE6,
  IM.FLOAT_ATTRIBUTE7 AS IM_FLOAT_ATTRIBUTE7,
  IM.FLOAT_ATTRIBUTE8 AS IM_FLOAT_ATTRIBUTE8,
  IM.FLOAT_ATTRIBUTE9 AS IM_FLOAT_ATTRIBUTE9,
  IM.FLOAT_ATTRIBUTE10 AS IM_FLOAT_ATTRIBUTE10,
  IM.DATE_ATTRIBUTE1 AS IM_DATE_ATTRIBUTE1,
  IM.DATE_ATTRIBUTE2 AS IM_DATE_ATTRIBUTE2,
  IM.DATE_ATTRIBUTE3 AS IM_DATE_ATTRIBUTE3,
  IM.DATE_ATTRIBUTE4 AS IM_DATE_ATTRIBUTE4,
  IM.DATE_ATTRIBUTE5 AS IM_DATE_ATTRIBUTE5,
  IM.DATE_ATTRIBUTE6 AS IM_DATE_ATTRIBUTE6,
  IM.DATE_ATTRIBUTE7 AS IM_DATE_ATTRIBUTE7,
  IM.DATE_ATTRIBUTE8 AS IM_DATE_ATTRIBUTE8,
  IM.DATE_ATTRIBUTE9 AS IM_DATE_ATTRIBUTE9,
  IM.DATE_ATTRIBUTE10 AS IM_DATE_ATTRIBUTE10,
  attr.ATTRIBUTE_KEY AS ATTRIBUTE_KEY,
  attr.ATTRIBUTE_NAME AS ATTRIBUTE_NAME,
  attr.ATTRIBUTE_VALUE AS ATTRIBUTE_VALUE,
  attr.ATTRIBUTE_TYPE AS ATTRIBUTE_TYPE,  
  ag.ATTRIBUTE_GROUP_NAME AS ATTRIBUTE_GROUP_NAME,
  pf.ITEM_PLATFORM_KEY AS ITEM_PLATFORM_KEY,
  pf.ITEM_PLATFORM_NAME AS ITEM_PLATFORM_NAME,
  pf.ITEM_PLATFORM_TYPE AS ITEM_PLATFORM_TYPE,
  pf.ITEM_PLATFORM_DESC AS ITEM_PLATFORM_DESC,
  ic.ITEM_CATEGORY_NAME   AS ITEM_CATEGORY_NAME,  
  be.BUSINESS_ENTITY_NAME AS BUSINESS_ENTITY_NAME,
  be.BUSINESS_ENTITY_TYPE_KEY AS BUSINESS_ENTITY_TYPE_KEY,   
  be.BUSINESS_ENTITY_IDENTIFIER AS BUSINESS_ENTITY_IDENTIFIER, 
  bet.BUSINESS_ENTITY_TYPE_NAME AS BUSINESS_ENTITY_TYPE_NAME,
  VC.CONTACT_NAME AS CONTACT_NAME,
  VC.CONTACT_UNIQUE_ID AS CONTACT_UNIQUE_ID
FROM
ITEM_MASTER IM
LEFT OUTER JOIN ITEM_ADD_ATTRIBUTE attr ON attr.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ATTRIBUTE_GROUP ag ON ag.ATTRIBUTE_GROUP_KEY = attr.ATTRIBUTE_GROUP_KEY
LEFT OUTER JOIN ITEM_ITEM_PLATFORM rpf ON rpf.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM pf ON pf.ITEM_PLATFORM_KEY = rpf.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_ITEM_CATEGORY ric ON ric.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_CATEGORY ic ON ic.ITEM_CATEGORY_KEY = ric.ITEM_CATEGORY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = IM.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY_TYPE bet ON bet.BUSINESS_ENTITY_TYPE_KEY = be.BUSINESS_ENTITY_TYPE_KEY
LEFT OUTER JOIN CONTACT VC ON IM.CONTACT_KEY = VC.CONTACT_KEY;

INSERT INTO PCM_ROLE (ROLE_KEY, ROLE_ID, ROLE_NAME, PERM_ROLE, BUSINESS_ENTITY_KEY) values (1070, 'SUPER_SERVICE_GCM', 'Super Service GCM', 'N', NULL);

INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET) VALUES 
('EXCEPTION_REQUEST', 'New Exception Request', 'MCM', 'SL', 'createExceptionRequest.do', 6, NULL);

INSERT INTO PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET)
values ('SEARCH_EXCEPTION','Search Exception Request','MCM','SL','searchExceptionRequest.do',7,null);


CREATE INDEX LOAD_EVENT_JOB_KEY ON LOAD_EVENT(LOAD_JOB_KEY)TABLESPACE audit_index;


CREATE TABLE PCM_SOURCING_LANE_EXCEPTION
(
    SOURCING_LANE_KEY NUMBER(19) NOT NULL,
    SOURCING_LANE_NAME VARCHAR2(512) NOT NULL,
    SOURCING_LANE_EXTERNAL_ID VARCHAR2(255) NULL,
    ITEM_KEY NUMBER(19) NOT NULL,
    SUPPLIER_KEY NUMBER(19),
    BOM_KEY NUMBER(19),
    FROM_SITE_KEY NUMBER(19),
    TO_SITE_KEY NUMBER(19),
    OWNER_KEY NUMBER(19),
    DATE_OFFSET NUMBER(10),
    PRODUCT_STATE VARCHAR2(32),
    CURRENCY_CODE VARCHAR2(3),
    SYSTEM_DERIVED VARCHAR2(1) DEFAULT 'N' NOT NULL,    
    ENDDATE_REQUIRED VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    DESCRIPTION VARCHAR2(1024),
    STATUS VARCHAR2(40) NOT NULL,
    STATUS_CHANGE_DATE TIMESTAMP,    
    STATUS_LAST_CHANGE_BY VARCHAR2(64),
    INSERT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DT TIMESTAMP NULL,
    DELETE_FLAG VARCHAR2(1) NULL,
    CURRENT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    AUDIT_REV NUMBER(10),
    LAST_REV_CHANGE_DATE TIMESTAMP,
    COLLABORATION VARCHAR2(1),
    COST_PROV_BUSINESS_ENTITY VARCHAR2(255),
	IS_AVL_EXISTS VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PCMSLE_SITEM_FK FOREIGN KEY(ITEM_KEY)
        REFERENCES ITEM_MASTER,
    CONSTRAINT PCMSLE_SBE_FK FOREIGN KEY(SUPPLIER_KEY)
        REFERENCES BUSINESS_ENTITY,         
    CONSTRAINT PCMSLE_BOM_FK FOREIGN KEY(BOM_KEY)
        REFERENCES BOM_HEADER,          
    CONSTRAINT PCMSLE_USER_FK FOREIGN KEY (OWNER_KEY) 
        REFERENCES PCM_USER,
    CONSTRAINT PCMSLE_FS_SITE_FK FOREIGN KEY (FROM_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSLE_TS_SITE_FK FOREIGN KEY (TO_SITE_KEY) 
        REFERENCES SITE,
    CONSTRAINT PCMSLE_PK PRIMARY KEY(SOURCING_LANE_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX                           
)  TABLESPACE AUDIT_DATA;

-- Natural Key
CREATE UNIQUE INDEX XSLE_NK ON PCM_SOURCING_LANE_EXCEPTION(ITEM_KEY,SUPPLIER_KEY,
    BOM_KEY,FROM_SITE_KEY,TO_SITE_KEY,CURRENCY_CODE)
    TABLESPACE AUDIT_INDEX;
    
CREATE INDEX XSLE_ITEM_N1 ON PCM_SOURCING_LANE_EXCEPTION(ITEM_KEY) 
    TABLESPACE AUDIT_INDEX;
	
	
	
ALTER TABLE PCM_COST_RECORD_EXCEPTION
MODIFY SOURCING_LANE_KEY NUMBER(19) NULL;

ALTER TABLE PCM_COST_RECORD_EXCEPTION
ADD SOURCING_LANE_EXCEPTION_KEY NUMBER(19);

ALTER TABLE PCM_COST_RECORD_EXCEPTION
ADD CONSTRAINT PCMCRE_SLANEEXC_FK FOREIGN KEY(SOURCING_LANE_EXCEPTION_KEY)
REFERENCES PCM_SOURCING_LANE_EXCEPTION;

CREATE SEQUENCE PCM_SOURCING_LANE_EXCEPTION_SEQ
		INCREMENT BY 1
		START WITH 1
		NOMAXVALUE
		NOMINVALUE
		CACHE 20
		NOCYCLE ORDER;