INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER) 
values ('WAP','WAP',8,'Y','N');
INSERT INTO PCM_COST_TYPE (COST_TYPE_KEY, COST_TYPE_NAME, COST_TYPE_ORDER, USE_IN_ROLLUP, ALLOW_MULTI_PROVIDER) 
values ('XWAP','XWAP', 9,'Y','N');
	
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE, IS_REQUIRED) 
values ('MATERIAL','WAP','MATERIAL','S',1,'MATERIAL',1);
INSERT INTO PCM_COST_ELEMENT (COST_ELEMENT_KEY, COST_TYPE_KEY, COST_ELEMENT_NAME, COST_ELEMENT_VALUE_TYPE, COST_ELEMENT_ORDER,COST_ELEMENT_TYPE, IS_REQUIRED) 
values ('MATERIAL','XWAP','MATERIAL','S',1,'MATERIAL',1);

/* Item Extract */
CREATE OR REPLACE VIEW IV_ITEM_EXTRACT AS 
  SELECT
  IM.ITEM_KEY AS ITEM_KEY ,
  IM.ITEM_UNIQUE_IDENTIFIER AS ITEM_UNIQUE_IDENTIFIER,  
  IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,
  IM.ITEM_EXTERNAL_ID AS ITEM_EXTERNAL_ID,
  IM.ITEM_TYPE AS ITEM_TYPE,
  IM.GBL_UOM_CODE AS PRODUCT_UOM_CODE,
  IM.GBL_LFCYCL_PH_CODE AS LIFE_CYCLE_TYPE_CODE,
  IM.GBL_PROD_LFCYCL_CODE_OTHER AS LIFE_CYCLE_TYPE_CODE_OTHER,
  IM.ITEM_CLASSIFICATION AS ITEM_CLASSIFICATION,
  IM.PRODUCT_FAMILY AS PRODUCT_FAMILY,
  IM.MAKE_BUY AS MAKE_BUY,
  IM.MAKE_BUY_OTHER AS MAKE_BUY_OTHER,
  IM.SERIALNUMBER_REQUIRED AS SERIALNUMBER_REQUIRED,
  IM.CERTIFICATION_REQUIRED AS CERTIFICATION_REQUIRED,
  IM.OWNER_NAME AS OWNER_NAME,
  IM.ITEM_DESCRIPTION AS ITEM_DESCRIPTION,
  IM.IS_TOP_LEVEL AS IS_TOP_LEVEL,
  IM.COLLABORATION AS COLLABORATION,
  IM.ITEM_PART_TYPE AS ITEM_PART_TYPE,
  IM.INVENTORY AS INVENTORY,
  IM.EOL AS EOL,
  IM.EOL_LAST_CHANGED_ON AS EOL_LAST_CHANGED_ON,
  IM.EOL_TYPE AS EOL_TYPE,
  IM.UPDATE_DT AS UPDATE_DT,
  IM.DATA_SOURCE AS DATA_SOURCE,
  IM.VERSION AS VERSION,
  IM.REVISION AS REVISION,
  IM.VERSION_DATE AS VERSION_DATE,
  IM.REVISION_DATE AS REVISION_DATE,
  IM.MANAGED_FLAG AS MANAGED_FLAG,
  IM.STRING_ATTRIBUTE1 AS IM_STRING_ATTRIBUTE1,
  IM.STRING_ATTRIBUTE2 AS IM_STRING_ATTRIBUTE2,
  IM.STRING_ATTRIBUTE3 AS IM_STRING_ATTRIBUTE3,
  IM.STRING_ATTRIBUTE4 AS IM_STRING_ATTRIBUTE4,
  IM.STRING_ATTRIBUTE5 AS IM_STRING_ATTRIBUTE5,
  IM.STRING_ATTRIBUTE6 AS IM_STRING_ATTRIBUTE6,
  IM.STRING_ATTRIBUTE7 AS IM_STRING_ATTRIBUTE7,
  IM.STRING_ATTRIBUTE8 AS IM_STRING_ATTRIBUTE8,
  IM.STRING_ATTRIBUTE9 AS IM_STRING_ATTRIBUTE9,
  IM.STRING_ATTRIBUTE10 AS IM_STRING_ATTRIBUTE10,
  IM.NUMBER_ATTRIBUTE1 AS IM_NUMBER_ATTRIBUTE1,
  IM.NUMBER_ATTRIBUTE2 AS IM_NUMBER_ATTRIBUTE2,
  IM.NUMBER_ATTRIBUTE3 AS IM_NUMBER_ATTRIBUTE3,
  IM.NUMBER_ATTRIBUTE4 AS IM_NUMBER_ATTRIBUTE4,
  IM.NUMBER_ATTRIBUTE5 AS IM_NUMBER_ATTRIBUTE5,
  IM.NUMBER_ATTRIBUTE6 AS IM_NUMBER_ATTRIBUTE6,
  IM.NUMBER_ATTRIBUTE7 AS IM_NUMBER_ATTRIBUTE7,
  IM.NUMBER_ATTRIBUTE8 AS IM_NUMBER_ATTRIBUTE8,
  IM.NUMBER_ATTRIBUTE9 AS IM_NUMBER_ATTRIBUTE9,
  IM.NUMBER_ATTRIBUTE10 AS IM_NUMBER_ATTRIBUTE10,
  IM.FLOAT_ATTRIBUTE1 AS IM_FLOAT_ATTRIBUTE1,
  IM.FLOAT_ATTRIBUTE2 AS IM_FLOAT_ATTRIBUTE2,
  IM.FLOAT_ATTRIBUTE3 AS IM_FLOAT_ATTRIBUTE3,
  IM.FLOAT_ATTRIBUTE4 AS IM_FLOAT_ATTRIBUTE4,
  IM.FLOAT_ATTRIBUTE5 AS IM_FLOAT_ATTRIBUTE5,
  IM.FLOAT_ATTRIBUTE6 AS IM_FLOAT_ATTRIBUTE6,
  IM.FLOAT_ATTRIBUTE7 AS IM_FLOAT_ATTRIBUTE7,
  IM.FLOAT_ATTRIBUTE8 AS IM_FLOAT_ATTRIBUTE8,
  IM.FLOAT_ATTRIBUTE9 AS IM_FLOAT_ATTRIBUTE9,
  IM.FLOAT_ATTRIBUTE10 AS IM_FLOAT_ATTRIBUTE10,
  IM.DATE_ATTRIBUTE1 AS IM_DATE_ATTRIBUTE1,
  IM.DATE_ATTRIBUTE2 AS IM_DATE_ATTRIBUTE2,
  IM.DATE_ATTRIBUTE3 AS IM_DATE_ATTRIBUTE3,
  IM.DATE_ATTRIBUTE4 AS IM_DATE_ATTRIBUTE4,
  IM.DATE_ATTRIBUTE5 AS IM_DATE_ATTRIBUTE5,
  IM.DATE_ATTRIBUTE6 AS IM_DATE_ATTRIBUTE6,
  IM.DATE_ATTRIBUTE7 AS IM_DATE_ATTRIBUTE7,
  IM.DATE_ATTRIBUTE8 AS IM_DATE_ATTRIBUTE8,
  IM.DATE_ATTRIBUTE9 AS IM_DATE_ATTRIBUTE9,
  IM.DATE_ATTRIBUTE10 AS IM_DATE_ATTRIBUTE10,
  attr.ATTRIBUTE_KEY AS ATTRIBUTE_KEY,
  attr.ATTRIBUTE_NAME AS ATTRIBUTE_NAME,
  attr.ATTRIBUTE_VALUE AS ATTRIBUTE_VALUE,
  attr.ATTRIBUTE_TYPE AS ATTRIBUTE_TYPE,  
  ag.ATTRIBUTE_GROUP_NAME AS ATTRIBUTE_GROUP_NAME,
  pf.ITEM_PLATFORM_KEY AS ITEM_PLATFORM_KEY,
  pf.ITEM_PLATFORM_NAME AS ITEM_PLATFORM_NAME,
  pf.ITEM_PLATFORM_TYPE AS ITEM_PLATFORM_TYPE,
  pf.ITEM_PLATFORM_DESC AS ITEM_PLATFORM_DESC,
  ic.ITEM_CATEGORY_NAME   AS ITEM_CATEGORY_NAME,  
  be.BUSINESS_ENTITY_NAME AS BUSINESS_ENTITY_NAME,
  be.BUSINESS_ENTITY_TYPE_KEY AS BUSINESS_ENTITY_TYPE_KEY,   
  be.BUSINESS_ENTITY_IDENTIFIER AS BUSINESS_ENTITY_IDENTIFIER, 
  bet.BUSINESS_ENTITY_TYPE_NAME AS BUSINESS_ENTITY_TYPE_NAME,
  VC.CONTACT_NAME AS CONTACT_NAME,
  VC.CONTACT_UNIQUE_ID AS CONTACT_UNIQUE_ID
FROM
ITEM_MASTER IM
LEFT OUTER JOIN ITEM_ADD_ATTRIBUTE attr ON attr.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ATTRIBUTE_GROUP ag ON ag.ATTRIBUTE_GROUP_KEY = attr.ATTRIBUTE_GROUP_KEY
LEFT OUTER JOIN ITEM_ITEM_PLATFORM rpf ON rpf.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM pf ON pf.ITEM_PLATFORM_KEY = rpf.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_ITEM_CATEGORY ric ON ric.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_CATEGORY ic ON ic.ITEM_CATEGORY_KEY = ric.ITEM_CATEGORY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = IM.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY_TYPE bet ON bet.BUSINESS_ENTITY_TYPE_KEY = be.BUSINESS_ENTITY_TYPE_KEY
LEFT OUTER JOIN CONTACT VC ON IM.CONTACT_KEY = VC.CONTACT_KEY;

CREATE INDEX X_FISCAL_PERIOD_DATE ON FISCAL_PERIOD(FISCAL_PERIOD_START_DATE,FISCAL_PERIOD_END_DATE)TABLESPACE audit_index;
CREATE INDEX X_PCM_COT_PROJECT_NAME ON PCM_COST_RECORD(LOWER(PROJECT_NAME))TABLESPACE audit_index;
CREATE INDEX X_CP_COST_TYPE_PROFILE_ID ON COMMODITY_PROFILE_COST_TYPE(PROFILE_ID) TABLESPACE audit_index;
CREATE INDEX X_SL_SUPPLIER ON PCM_SOURCING_LANE(SUPPLIER_KEY)TABLESPACE audit_index;
CREATE INDEX X_XLOB_ITEM_ALLOCATION ON XLOB_ITEM_ALLOCATION(START_DATE,END_DATE)TABLESPACE audit_index;
CREATE INDEX X_FG_ID_TYPE ON FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID,TYPE)TABLESPACE audit_index;
CREATE INDEX X_XLOB_ALLOCATION_SITE_KEY ON XLOB_ALLOCATION(SITE_KEY)TABLESPACE audit_index;
CREATE INDEX LOAD_EVENT_JOB_KEY ON LOAD_EVENT(LOAD_JOB_KEY)TABLESPACE audit_index;