CREATE SEQUENCE COST_EXCEPTION_ODM_EMAIL_SEQ
		INCREMENT BY 1
		START WITH 1
		NOMAXVALUE
		NOMINVALUE
		CACHE 20
		NOCYCLE ORDER;

CREATE TABLE COST_EXCEPTION_ODM_EMAIL(
	ID NUMBER(19) NOT NULL,
	EXCEPTION_KEY NUMBER(19) NOT NULL,
	FILE_NAME VARCHAR2(255),
    FILE_CONTENT BLOB,
	UPLOADED_BY VARCHAR2(255),
	UPLOADED_ON TIMESTAMP(6),
	CONSTRAINT CEOE_CEK_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEOE_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX  
)  TABLESPACE AUDIT_DATA;
	
CREATE TABLE PCM_USER_CONNECTION_INFO(
 	 user_Id VARCHAR2(255) NOT NULL ,
	 session_Id VARCHAR2(255),
	 LAST_UPDATE_ON TIMESTAMP(6) NOT NULL,
	  PRIMARY KEY (user_Id)
);
