ALTER TABLE COST_EXCEPTION ADD
(
	RE_REQUESTED_ON TIMESTAMP(6),
	RE_REQUESTED_BY VARCHAR2(255)
);

CREATE SEQUENCE COST_EXCEPTION_APPROVER_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE TABLE COST_EXCEPTION_APPROVER(
	ID NUMBER(19) NOT  NULL,
    EXCEPTION_KEY NUMBER(19) NOT NULL,
	APPROVER_ROLE VARCHAR2(255),
	APPROVER VARCHAR2(255),
	STATE VARCHAR2(255),
	PROXY_APPROVER VARCHAR2(255),
	PROXY_APPROVER_ROLE VARCHAR2(255),
	ACTION_DATE  TIMESTAMP(6),
	ACTUAL_USER VARCHAR2(255),
    CONSTRAINT CEXPL_CEA_FK FOREIGN KEY(EXCEPTION_KEY)
        REFERENCES COST_EXCEPTION,
    CONSTRAINT CEAXPL_PK PRIMARY KEY(ID)
        USING INDEX TABLESPACE AUDIT_INDEX 
)TABLESPACE AUDIT_DATA;

insert into PCM_WORKFLOW
values('MAIN_UPLOAD_MANAGE', 'Upload/Manage Jobs', 'MCM', NULL, NULL, 9, NULL);

delete from PCM_WORKFLOW where workflow_key = 'MAIN_UPLOAD';

update PCM_WORKFLOW set WORKFLOW_PARENT_KEY = 'MAIN_UPLOAD_MANAGE' where workflow_key = 'MAIN_LOADJOB';


insert into PCM_WORKFLOW
values('UPLOAD_ADMIN', 'Admin', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=admin', 1, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_COST_FORECAST', 'Cost Forecast', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=cost_forecast', 4, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_XLOB', 'XLOB Price and Allocation', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=XLOB_Allocation', 5, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_MISCELLANEOUS', 'Miscellaneous', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=miscellaneous', 6, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_PRICING', 'Pricing', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=pricing', 2, NULL);

insert into PCM_WORKFLOW
values('UPLOAD_SA', 'Supply Allocation', 'MCM', 'MAIN_UPLOAD_MANAGE', 'uploadFile.do?uploadMenuType=supply_allocation', 3, NULL);



-- DELLOCOS-4810
INSERT INTO PCM_ROLE (ROLE_KEY, ROLE_ID, ROLE_NAME, PERM_ROLE, BUSINESS_ENTITY_KEY) values (1090, 'DGP_ACCOUNTING', 'DGP Accounting Approver', 'N', NULL);
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'ADMIN', 1090, NULL, NULL, 'ReadUser');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'SOURCING_LANE', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'COST_RECORD', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'COST_RECORD', 1090, NULL, NULL, 'ReadNote');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'COST_EXCEPTION', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'COST_EXCEPTION', 1090, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'COST_EXCEPTION', 1090, NULL, NULL, 'Correction');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REBATE', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REBATE', 1090, NULL, NULL, 'Validate');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'FUNCTIONAL_GROUP', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'PARENT_FUNCTIONAL_GROUP', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'TAM', 1090, NULL, NULL, 'Read-site');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'TAM', 1090, NULL, NULL, 'Read-region');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'TAM', 1090, NULL, NULL, 'Read-global');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'FORECAST', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'ITEM_ASSIGNMENT', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'ITEM_ASSIGNMENT', 1090, NULL, NULL, 'Save');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'ITEM_ASSIGNMENT', 1090, NULL, NULL, 'AssignSelf');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'ITEM_CATEGORY', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'BOM', 1090, NULL, NULL, 'Read');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'UPDOWN', 1090, NULL, NULL, 'DownloadFile');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'UPDOWN', 1090, NULL, NULL, 'ReadJob');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'UPDOWN', 1090, NULL, NULL, 'ReadAnyJob');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'ReadReport');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'SubmitReport');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'ReadSupplyAllocationException');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'SubmitSupplyAllocationException');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'ReadCostRecordPriceValidation');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'SubmitCostRecordPriceValidation');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'ReadCostForecastValidation');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'REPORTS', 1090, NULL, NULL, 'SubmitCostForecastValidation');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MAIN_DASHBOARD', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MAIN_ALERTS', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_SL', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_CR', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'CR_VARIANCE_REPORT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_EXCEPTION', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_RP', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MDM_ITEM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MDM_ICAT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MDM_BOM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_FC', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SF_VARIANCE_REPORT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MANAGE_PARENT', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MANAGE_GROUP', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'ALLOCATION', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'TAM_DOWNLOAD', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SA_MANAGEMENT_HSTORY', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SA_EXCEPTION', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SA_HISTORY', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'PriceTAM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'RPT_SUBMIT_JOB', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'MAIN_LOADJOB', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_ITEM_ONLY', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_ITEM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'SEARCH_BOM', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'EDIT_ALERT_SUB', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'EDIT_USER', 'Execute');
INSERT INTO PCM_ACCESS_CONTROL (ACCESS_CONTROL_KEY, ENTITY_TYPE, ROLE_KEY, USER_KEY, TARGET_ENTITY_KEY, ACL) VALUES (PCM_ACL_SEQ.nextval, 'WORKFLOW', 1090, NULL, 'VIEW_AUDIT', 'Execute');
COMMIT;

	-- 1st STG to extract all TAM details --
  EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ALLOC_CASCADE_PROC_STG1 REUSE STORAGE');
  INSERT /*+ APPEND PARALLEL */ INTO TAM_ALLOC_CASCADE_PROC_STG1 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,CHILD_IS_DELTA,DATASOURCE)
select
     X.TAM_ALLOCATION_ID,X.FUNCTIONAL_GROUP_ID,X.FG_NAME,X.LAST_CHANGED_BY,X.LAST_CHANGED_ON,X.ALLOW_HEDGING,X.CREATED_BY,X.CREATED_ON,X.DISCP_EXTRACT_FLAG,X.SITE_KEY,X.SITE_IDENTIFIER,X.SITE_DESCRIPTION,X.SITE_TYPE,X.PARENT_SITE_KEY,
      BE.BUSINESS_ENTITY_IDENTIFIER  AS SUPPLIER_IDENTIFIER,
      BE.BUSINESS_ENTITY_NAME        AS SUPPLIER_NAME,
      TSA.START_DATE                 AS START_DATE,
      TSA.END_DATE                   AS END_DATE,
      TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
      TSA.ALLOCATION                 AS SUPPLIER_ALLOCATION,
      TIA.TAM_ITEM_ALLOCATION_ID     AS TAM_ITEM_ALLOCATION_ID,
      TIA.ALLOCATION                 AS ITEM_ALLOCATION,
      IM.ITEM_IDENTIFIER             AS ITEM_IDENTIFIER,
      CHILD_PARENT_SITE_ID,
      CHILD_IS_DELTA,
      IM.DATA_SOURCE             	 AS DATASOURCE
FROM
(
SELECT * FROM
(
  SELECT X.*,
  CASE WHEN SITE_TYPE = 'GLOBAL' AND (MAX(CASE WHEN DISCP_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID)) = 1 THEN 1
       WHEN SITE_TYPE = 'REGION' AND MAX(CASE WHEN DISCP_EXTRACT_FLAG = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,CHILD_PARENT_SITE_ID) = 1 THEN 1
       ELSE 0 END AS CHILD_IS_DELTA
  FROM
  (
    SELECT
          TA.TAM_ALLOCATION_ID,
          FG.FUNCTIONAL_GROUP_ID,
          FG.NAME             AS FG_NAME,
          TA.LAST_CHANGED_BY AS LAST_CHANGED_BY,
          TA.LAST_CHANGED_ON AS LAST_CHANGED_ON,
          TA.ALLOW_HEDGING   AS ALLOW_HEDGING,
          TA.CREATED_BY      AS CREATED_BY,
          TA.CREATED_ON      AS CREATED_ON,
          TA.DISCP_EXTRACT_FLAG AS DISCP_EXTRACT_FLAG,
          TA.SITE_KEY                   AS SITE_KEY,
          SI.SITE_IDENTIFIER             AS SITE_IDENTIFIER,
          SI.SITE_DESCRIPTION            AS SITE_DESCRIPTION,
          SI.SITE_TYPE                   AS SITE_TYPE,
          SI.PARENT_SITE_KEY             AS PARENT_SITE_KEY,
          CASE WHEN SI.SITE_TYPE = 'SITE' THEN PARENT_SITE_KEY
             ELSE SI.SITE_KEY END AS CHILD_PARENT_SITE_ID
        FROM TAM_ALLOCATION TA
          INNER JOIN FUNCTIONAL_GROUP FG
                ON FG.FUNCTIONAL_GROUP_ID = TA.FUNCTIONAL_GROUP_ID
          INNER JOIN TAM_SITE_DETAIL_PROCESSING SI
	        ON SI.SITE_KEY = TA.SITE_KEY --AND SI.SITE_DESCRIPTION NOT LIKE '%DONOTUSE'
	        AND SI.TAM_PROCESSING_FLAG = '1'
	        AND FG.STATUS = 'ACTIVE'
	        AND SI.BUSINESS_ENTITY_KEY IN (SELECT BE.BUSINESS_ENTITY_KEY
	                       	                FROM BUSINESS_ENTITY BE, BUSINESS_ENTITY_TYPE BET
	                                        WHERE BE.BUSINESS_ENTITY_TYPE_KEY  = BET.BUSINESS_ENTITY_TYPE_KEY
                                                AND BET.BUSINESS_ENTITY_TYPE_NAME = 'ENTERPRISE')
        WHERE EXISTS
                (
	                 select 'x' from tam_supplier_allocation tsa1
	                 where tsa1.TAM_ALLOCATION_ID = TA.TAM_ALLOCATION_ID
	                 AND START_DATE >= vMONTH_START_DATE
	                 AND (SI.SITE_TYPE <> 'GLOBAL' OR ( SI.SITE_TYPE = 'GLOBAL' AND tsa1.allocation > 0 ) )
                 )
    ) X
  ) WHERE (DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
) X
    INNER JOIN TAM_SUPPLIER_ALLOCATION TSA
    ON TSA.TAM_ALLOCATION_ID = X.TAM_ALLOCATION_ID AND TSA.START_DATE >= vMONTH_START_DATE
    INNER JOIN BUSINESS_ENTITY BE
    ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
    INNER JOIN IV_TAM_ITEM_ALLOCATION TIA
    ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
    INNER JOIN ITEM_MASTER IM
    ON IM.ITEM_KEY = TIA.ITEM_KEY;
COMMIT;

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ALLOC_CASCADE_PROC_STG1',CASCADE => TRUE, DEGREE=>16);
	
-- 2nd STG Process to apply the Cascading Logic --
	EXECUTE IMMEDIATE ('TRUNCATE TABLE TAM_ALLOC_CASCADE_PROC_STG2 REUSE STORAGE');
	INSERT /*+ APPEND PARALLEL */ INTO TAM_ALLOC_CASCADE_PROC_STG2 (TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER)
  SELECT TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,FG_NAME,LAST_CHANGED_BY,LAST_CHANGED_ON,ALLOW_HEDGING,CREATED_BY,CREATED_ON,DISCP_EXTRACT_FLAG,SITE_KEY,SITE_IDENTIFIER,SITE_DESCRIPTION,SITE_TYPE,PARENT_SITE_KEY,SUPPLIER_IDENTIFIER,SUPPLIER_NAME,START_DATE,END_DATE,TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,TOT_SUPP_ALOC,TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,ITEM_IDENTIFIER,BUCK_ALOC,ALLOC_GLOBAL,ALLOC_REGION,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
  FROM
  (
  select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOT_SUPP_ALOC,
           TAM_ITEM_ALLOCATION_ID, ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
           MAX(CASE WHEN NVL(SUPPLIER_ALLOCATION,0) = 0 THEN 0 ELSE 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER) SUPP_ALLOC_NOT_NULL,
            MAX(
               CASE WHEN ((NVL(ITEM_ALLOCATION,0) = 0 AND SITE_TYPE = 'SITE') OR (NVL(ITEM_ALLOCATION,0) = 0 AND ITEM_IDENTIFIER <> DEFAULT_ITEM_IDENTIFIER)) THEN 0 
               ELSE 1 END
              ) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_IDENTIFIER,SUPPLIER_IDENTIFIER,ITEM_IDENTIFIER) ITEM_ALLOC_NOT_NULL
	  FROM
	  (	
  		   select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
           SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
           SUPPLIER_ALLOCATION,OLD_SUPPLIER_ALLOCATION,
           SUM(CASE WHEN SUPP_ROW_NUM = 1 THEN SUPPLIER_ALLOCATION ELSE NULL END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,START_DATE) AS TOT_SUPP_ALOC,
           TAM_ITEM_ALLOCATION_ID, 
           CASE WHEN ITEM_ALLOCATION IS NULL THEN
                CASE WHEN ITEM_IDENTIFIER = DEFAULT_ITEM_IDENTIFIER THEN
                 CASE WHEN SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,TAM_SUPPLIER_ALLOCATION_ID) is null THEN 100 
                 ELSE 0 END
                ELSE 0 END
                ELSE ITEM_ALLOCATION END AS ITEM_ALLOCATION,
           ITEM_IDENTIFIER,BUCK_ALOC,alloc_global,alloc_region,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,SUPP_ROW_NUM
	  FROM
	  (
	    select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_region
	                  when BUCK_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_global
	                  else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID, 
                 case when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 1 then alloc_item_region
	                  when BUCK_ITEM_ALOC is null AND site_type = 'SITE' AND REGION_PARENT_EXISTS = 0 then alloc_item_global
	             else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,BUCK_ALOC,BUCK_ITEM_ALOC,alloc_region,alloc_item_region,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER,
	             ROW_NUMBER() OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_NAME,START_DATE order by ITEM_IDENTIFIER ) AS SUPP_ROW_NUM
	      FROM
	      (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,SUPPLIER_ALLOCATION,
	             max(case when site_type =  'REGION' then  SUPPLIER_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,start_date,FG_NAME) alloc_region,
                 SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
                 TAM_ITEM_ALLOCATION_ID,ITEM_ALLOCATION,
                 max(case when site_type =  'REGION' then  ITEM_ALLOCATION end) over (partition by CHILD_PARENT_SITE_ID,supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_region,
	             ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
                 ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	      FROM
	      (
	        select TAM_ALLOCATION_ID, FUNCTIONAL_GROUP_ID, FG_NAME, LAST_CHANGED_BY, LAST_CHANGED_ON, ALLOW_HEDGING, CREATED_BY, CREATED_ON, DISCP_EXTRACT_FLAG, SITE_KEY, SITE_IDENTIFIER, SITE_DESCRIPTION,
	             SITE_TYPE, PARENT_SITE_KEY, SUPPLIER_IDENTIFIER, SUPPLIER_NAME, START_DATE, END_DATE, TAM_SUPPLIER_ALLOCATION_ID,
	             case when BUCK_ALOC is null AND site_type = 'REGION' then alloc_global
                 else SUPPLIER_ALLOCATION end as SUPPLIER_ALLOCATION,
	             SUPPLIER_ALLOCATION OLD_SUPPLIER_ALLOCATION,
	             TAM_ITEM_ALLOCATION_ID, 
                 case when BUCK_ITEM_ALOC is null AND site_type = 'REGION' then alloc_item_global
	             else ITEM_ALLOCATION end as ITEM_ALLOCATION,
                 ITEM_ALLOCATION OLD_ITEM_ALLOCATION,
	             ITEM_IDENTIFIER,CHILD_PARENT_SITE_ID,
	             BUCK_ALOC,BUCK_ITEM_ALOC,alloc_global,alloc_item_global,REGION_PARENT_EXISTS,DEFAULT_ITEM_IDENTIFIER
	        from
	        (
	            select x.*,
	            SUM(SUPPLIER_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ALOC,
                SUM(ITEM_ALLOCATION) over (PARTITION BY TAM_ALLOCATION_ID,FUNCTIONAL_GROUP_ID,START_DATE) BUCK_ITEM_ALOC,
	            max(case when site_type =  'GLOBAL' and site_identifier = 1 then  SUPPLIER_ALLOCATION end) over (partition by supplier_identifier,start_date,FG_NAME) alloc_global,
                max(case when site_type =  'GLOBAL' and site_identifier = 1 then  ITEM_ALLOCATION end) over (partition by supplier_identifier,item_identifier,start_date,FG_NAME) alloc_item_global,
	            CASE WHEN (count(CASE WHEN site_type =  'REGION' THEN 1 END) OVER (PARTITION BY FG_NAME,CHILD_PARENT_SITE_ID)) > 0 THEN 1
	                 ELSE 0 END AS REGION_PARENT_EXISTS,
	            CASE WHEN (count(CASE WHEN DATASOURCE =  'EMC' THEN 1 END) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)) > 0 
	            	 THEN MAX(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 ELSE MIN(ITEM_IDENTIFIER) OVER (PARTITION BY FUNCTIONAL_GROUP_ID,SITE_KEY,SUPPLIER_IDENTIFIER,START_DATE)
	            	 END AS DEFAULT_ITEM_IDENTIFIER
	            from
	            (
	             select * from TAM_ALLOC_CASCADE_PROC_STG1-- where (DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG) OR CHILD_IS_DELTA = 1)
	            ) x
	         )x
	       )
	      )
	    )
	  ) WHERE DISCP_EXTRACT_FLAG = NVL(vEXTRACT_FLAG,DISCP_EXTRACT_FLAG)
    ) WHERE SUPP_ALLOC_NOT_NULL > 0 AND ITEM_ALLOC_NOT_NULL > 0;
  COMMIT;

	DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'TAM_ALLOC_CASCADE_PROC_STG2',CASCADE => TRUE, DEGREE=>16);

	OPEN VOUT_RESULT FOR
		SELECT 1 AS COUNT FROM DUAL;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE;
	END TAM_ALLOC_CASCADE_PROC_SP;
	
	PROCEDURE TAM_ALLOC_CASCADE_DELTA_UPDATE (
		vOUT_RESULT out SYS_REFCURSOR
	) AS
	vMONTH_START_DATE DATE;
	vWEEK_START_DATE DATE;
	BEGIN
		
	SELECT TO_DATE(NEXT_DAY(SYSDATE,'SATURDAY') - 7) INTO vWEEK_START_DATE FROM DUAL;
	
	SELECT MIN(FISCAL_PERIOD_START_DATE)  INTO vMONTH_START_DATE
	 FROM fiscal_period
	WHERE FISCAL_PERIOD_TYPE IN ('M','W')
	AND FISCAL_PERIOD_START_DATE >= trunc(vWEEK_START_DATE);
	
	-- Insert records in FG Audit
	
	insert into FG_AUDIT_HISTORY(audit_key,user_id,user_role,audit_source,site,fg_key,action,operation_code,comments)
 	SELECT FG_AUDIT_KEY_SEQ.NEXTVAL,TA.CREATED_BY ,r.role_id,'TAM',ta.site_key,ta.functional_group_id,'TAM_CASCADE_EXTRACT','TAM CASCADE EXTRACT CREATED', CONCAT(CONCAT('New TAM Created For FunctionalGroup: ' ,fg.NAME),concat(' and Site:  ', site.SITE_DESCRIPTION))
	from tam_allocation TA
    inner join functional_group fg on fg.functional_group_id=ta.functional_group_id
    inner join site site on site.site_key=ta.site_key
    inner join pcm_user u on u.user_id=ta.CREATED_BY
    inner join pcm_role r on r.role_key=u.role_key
                WHERE TA.DISCP_EXTRACT_FLAG = 'P'
	      AND TA.TAM_ALLOCATION_ID IN
	      (
	        SELECT  TAM_ALLOCATION_ID FROM TAM_ALLOC_CASCADE_PROC_STG2 TAS WHERE DISCP_EXTRACT_FLAG = 'P' AND TAS.LAST_CHANGED_ON = TA.LAST_CHANGED_ON
	        UNION ALL
	        SELECT TAM_ALLOCATION_ID FROM tam_allocation  ta
	        where DISCP_EXTRACT_FLAG = 'P'
	        and not exists (select 'x' from tam_supplier_allocation tsa1 where tsa1.TAM_ALLOCATION_ID = TA.TAM_ALLOCATION_ID
	                        and tsa1.allocation > 0 and START_DATE >= vMONTH_START_DATE)
	      );		
	      
	      COMMIT;
	      
	    -- Update TAM_ALLOCATION to set the DISP_EXTRACT_FLAG to Y for DELTA Extractions --
	 UPDATE TAM_ALLOCATION TA SET DISCP_EXTRACT_FLAG = 'Y'
	      WHERE DISCP_EXTRACT_FLAG = 'P'
	      AND TAM_ALLOCATION_ID IN
	      (
	        SELECT  TAM_ALLOCATION_ID FROM TAM_ALLOC_CASCADE_PROC_STG2 TAS WHERE DISCP_EXTRACT_FLAG = 'P' AND TAS.LAST_CHANGED_ON = TA.LAST_CHANGED_ON
	        UNION ALL
	        SELECT TAM_ALLOCATION_ID FROM tam_allocation  ta
	        where DISCP_EXTRACT_FLAG = 'P'
	        and not exists (select 'x' from tam_supplier_allocation tsa1 where tsa1.TAM_ALLOCATION_ID = TA.TAM_ALLOCATION_ID
	                        and tsa1.allocation > 0 and START_DATE >= vMONTH_START_DATE)
	      );

	      COMMIT;
	      
  FROM SITE ST,SITE_DETAILS SD
      WHERE ST.SITE_DETAIL_ID = SD.ID;
	  OPEN VOUT_RESULT FOR
			SELECT 1 AS COUNT FROM DUAL;
	
		EXCEPTION
			WHEN OTHERS THEN
				RAISE;
	END TAM_ALLOC_CASCADE_DELTA_UPDATE;

END TamCascadeOperation;
/