
WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE PCM_COST_RECORD ADD SYSTEM_ACTION VARCHAR2(1024);

ALTER TABLE PCM_SOURCING_LANE ADD COST_PROV_BUSINESS_ENTITY VARCHAR2(255);
 
create table COMMODITY_PROFILE
(
	PROFILE_ID Number(19,0) NOT NULL,
	PROFILE_NAME varchar2(255) NOT NULL,
	COMPANY_ITEM_TYPE varchar2(255) NOT NULL,
	INCLUDE_EXCLUDE_COST_RECORD varchar2(255),
	INCLUDE_EXCLUDE_COST_FORECAST varchar2(255),
	INCLUDE_EXCLUDE_REBATE varchar2(255),
	INCLUDE_EXCLUDE_ITEM varchar2(255),
	INCLUDE_EXCLUDE_BOM varchar2(255),
	ITEM_CATEGORY_KEY Number(19,0),
	CONSTRAINT profileid_pk PRIMARY KEY (PROFILE_ID) USING INDEX TABLESPACE AUDIT_INDEX	,
	CONSTRAINT ITEM_CATEGORY_FK FOREIGN KEY (ITEM_CATEGORY_KEY) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_KEY)
);

create table USER_COMMODITYPROFILE_MAPPING
(
	USER_KEY Number(19,0) NOT NULL,
	PROFILE_ID Number(19,0) NOT NULL,
	CONSTRAINT USER_PROFILE_PK PRIMARY KEY (USER_KEY, PROFILE_ID),
	CONSTRAINT userid_fk FOREIGN KEY (USER_KEY) REFERENCES PCM_USER(USER_KEY),
	CONSTRAINT fk_comprofile FOREIGN KEY (PROFILE_ID) REFERENCES COMMODITY_PROFILE(PROFILE_ID)
);

create table COMMODITY_PROFILE_COST_TYPE
(
  ID Number(19,0) NOT NULL,
	PROFILE_ID Number(19,0),
	COST_TYPE varchar2(255),
	CONSTRAINT CPCT_ID_PK PRIMARY KEY (ID),
	CONSTRAINT CPCT_PROFILE_ID_FK FOREIGN KEY (PROFILE_ID) REFERENCES COMMODITY_PROFILE(PROFILE_ID) ON DELETE CASCADE ENABLE
); 

CREATE SEQUENCE PROFILE_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE USER_PROFILE_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
CREATE SEQUENCE CT_PROFILE_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('SEARCH_COMPROFILE', 'Commodity Profile', 'MCM', 'ADMIN', 'commodityProfileSearch.do', 11, NULL);

insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('USER_PROFILE_MAPPING', 'User Commodity Profile', 'MCM', 'ADMIN', 'userProfileMappingSearch.do', 12, NULL); 
