ALTER TABLE PARENT_FUNCTIONAL_GROUP ADD CREATED_ON TIMESTAMP(6) ADD CREATED_BY VARCHAR2(1024);

insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('FUNCTIONAL_GROUP', 'Functional Group', 'MCM', NULL, NULL, 6, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('MANAGE_GROUP', 'Manage Functional Group', 'MCM', 'FUNCTIONAL_GROUP', 'manageFunctionalGroup.do', 1, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('MANAGE_PARENT', 'Manage Parent', 'MCM', 'FUNCTIONAL_GROUP', 'manageParent.do', 2, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('HISTORY', 'History', 'MCM', 'FUNCTIONAL_GROUP', 'functionalGroupHistory.do', 3, NULL);
 
CREATE TABLE FG_AUDIT_HISTORY (
AUDIT_KEY NUMBER(19,0) NOT NULL,
DATE_PERFORMED TIMESTAMP(6),
USER_ID VARCHAR2(255) NOT NULL,
USER_ROLE VARCHAR2(255) NOT NULL,
ACTION VARCHAR2(255),
OPERATION_CODE VARCHAR2(255),
ITEM_NUMBER NUMBER(19,0),
COMMENTS VARCHAR2(1024),
AUDIT_SOURCE VARCHAR2(255),
OBJECT_KEY VARCHAR2(255 BYTE), 
CONSTRAINT FG_AUDIT_HISTORY_PK PRIMARY KEY(AUDIT_KEY)
        USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE FG_AUDIT_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        
CREATE OR REPLACE VIEW IV_FUNCTIONAL_GROUP AS
SELECT 
FG.FUNCTIONAL_GROUP_ID,
FG.NAME AS FG_NAME,
FG.DESCRIPTION AS FG_DESCRIPTION,
FG.TYPE AS FG_TYPE,
FG.STATUS AS FG_STATUS,
FG.STATUS_CHANGED_BY,
FG.LAST_CHANGED_ON AS FG_LAST_CHAGNED_ON,
FG.LAST_CHANGED_BY AS FG_LAST_CHANGED_BY,
FG.EXTRACT_FLAG,
FG.CREATED_ON,
FG.CREATED_BY,
PFG.PARENT_FUNCTIONAL_GROUP_ID,
PFG.NAME AS PG_NAME,
PFG.DESCRIPTION AS PG_DESCRIPTION,
PFG.TYPE AS PG_TYPE,
PFG.PURPOSE,
PFG.LAST_CHANGED_ON AS PG_LAST_CHANGED_ON,
PFG.LAST_CHANGED_BY AS PG_LAST_CHANGED_BY,
PFG.CREATED_ON AS PFG_CREATED_ON,
PFG.CREATED_BY AS PFG_CREATED_BY,
IM.ITEM_IDENTIFIER,
IP.ITEM_PLATFORM_NAME
FROM FUNCTIONAL_GROUP FG
LEFT OUTER JOIN FG_PFG_MAP FGMAP ON FGMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN PARENT_FUNCTIONAL_GROUP PFG ON PFG.PARENT_FUNCTIONAL_GROUP_ID = FGMAP.PARENT_FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_FG_MAP IMAP ON IMAP.FUNCTIONAL_GROUP_ID = FG.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = IMAP.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM IP ON IP.ITEM_PLATFORM_KEY = FG.ITEM_PLATFORM_KEY
ORDER BY FUNCTIONAL_GROUP_ID ASC;


CREATE TABLE TAM_ALLOCATION (
TAM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
ALLOW_HEDGING VARCHAR2(1),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
CONSTRAINT TAM_AL_PK PRIMARY KEY(TAM_ALLOCATION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT FUNCTIONAL_GROUP_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT SITE_KEY_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
)TABLESPACE AUDIT_DATA;
	
	
CREATE TABLE TAM_SUPPLIER_ALLOCATION (
TAM_SUPPLIER_ALLOCATION_ID NUMBER(19,0) NOT NULL,
TAM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
BUSINESS_ENTITY_KEY NUMBER(19,0) NOT NULL,
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
ALLOCATION NUMBER(10,5),
CONSTRAINT TAM_SUPP_AL_PK PRIMARY KEY(TAM_SUPPLIER_ALLOCATION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT TAM_ALL_KEY_FK FOREIGN KEY (TAM_ALLOCATION_ID) REFERENCES TAM_ALLOCATION(TAM_ALLOCATION_ID),
CONSTRAINT BUSINESS_ENTITY_KEY_FK FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY)
)TABLESPACE AUDIT_DATA;


CREATE TABLE TAM_ITEM_ALLOCATION (
TAM_ITEM_ALLOCATION_ID NUMBER(19,0) NOT NULL,
TAM_SUPPLIER_ALLOCATION_ID NUMBER(19,0) NOT NULL,
ITEM_KEY NUMBER(19,0) NOT NULL,
ALLOCATION NUMBER(10,5),
CONSTRAINT TAM_ITEM_AL_PK PRIMARY KEY(TAM_ITEM_ALLOCATION_ID)  USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT TAM_SUPP_ALL_KEY_FK FOREIGN KEY (TAM_SUPPLIER_ALLOCATION_ID) REFERENCES TAM_SUPPLIER_ALLOCATION(TAM_SUPPLIER_ALLOCATION_ID),
CONSTRAINT ITEM_ALL_KEY_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)
)TABLESPACE AUDIT_DATA;


CREATE SEQUENCE TAM_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE TAM_SUPPLIER_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE TAM_ITEM_ALLOCATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('TAM', 'Allocation Management', 'MCM', NULL, NULL, 7, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('ALLOCATION', 'Allocation', 'MCM', 'TAM', 'manageTAM.do', 1, NULL);
insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
 values ('TAM_HISTORY', 'History', 'MCM', 'TAM', 'tamHistory.do', 2, NULL);
 
CREATE OR REPLACE VIEW IV_TAM_ALLOCATION AS
SELECT
TAM.TAM_ALLOCATION_ID,
FG.FUNCTIONAL_GROUP_ID,
FG.NAME AS FG_NAME,
TAM.LAST_CHANGED_BY AS LAST_CHANGED_BY,
TAM.LAST_CHANGED_ON AS LAST_CHANGED_ON,
TAM.ALLOW_HEDGING AS ALLOW_HEDGING,
TAM.CREATED_BY AS CREATED_BY,
TAM.CREATED_ON AS CREATED_ON,
TAM.EXTRACT_FLAG,
SI.SITE_IDENTIFIER AS SITE_IDENTIFIER,
SI.SITE_DESCRIPTION AS SITE_DESCRIPTION,
SI.SITE_TYPE AS SITE_TYPE,
BE.BUSINESS_ENTITY_IDENTIFIER AS SUPPLIER_IDENTIFIER,
BE.BUSINESS_ENTITY_NAME AS SUPPLIER_NAME,
TSA.START_DATE AS START_DATE,
TSA.END_DATE AS END_DATE,
TSA.TAM_SUPPLIER_ALLOCATION_ID AS TAM_SUPPLIER_ALLOCATION_ID,
TSA.ALLOCATION AS SUPPLIER_ALLOCATION,
TIA.TAM_ITEM_ALLOCATION_ID AS TAM_ITEM_ALLOCATION_ID,
TIA.ALLOCATION AS ITEM_ALLOCATION,
IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER
FROM TAM_ALLOCATION TAM
LEFT OUTER JOIN FUNCTIONAL_GROUP FG ON FG.FUNCTIONAL_GROUP_ID = TAM.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN SITE SI ON SI.SITE_KEY = TAM.SITE_KEY
LEFT OUTER JOIN TAM_SUPPLIER_ALLOCATION TSA ON TSA.TAM_ALLOCATION_ID = TAM.TAM_ALLOCATION_ID
LEFT OUTER JOIN TAM_ITEM_ALLOCATION TIA ON TIA.TAM_SUPPLIER_ALLOCATION_ID = TSA.TAM_SUPPLIER_ALLOCATION_ID
LEFT OUTER JOIN ITEM_MASTER IM ON IM.ITEM_KEY = TIA.ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY BE ON TSA.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
ORDER BY TAM_ALLOCATION_ID,TAM_SUPPLIER_ALLOCATION_ID,START_DATE ASC;

ALTER TABLE TAM_ALLOCATION ADD ROLL_OVER_COUNT NUMBER(6);

ALTER TABLE FG_AUDIT_HISTORY ADD (SUPPLIER NUMBER(19,0), SITE NUMBER(19,0), BUCKET_START_DATE TIMESTAMP(6), BUCKET_END_DATE TIMESTAMP(6));