WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

DECLARE
BEGIN
     EXECUTE IMMEDIATE 'CREATE INDEX XFOR_I2 ON PCM_FORECAST(CURRENT_FLAG,FORECAST_MODEL,FORECAST_TYPE,STATUS) TABLESPACE AUDIT_INDEX';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
