WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

alter table item_change_audit modify op_code varchar2(255);

DECLARE
BEGIN
     EXECUTE IMMEDIATE 'DROP TRIGGER T_COLLAB_BOM_LINE_ITEM_INIT';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
DECLARE
BEGIN
     EXECUTE IMMEDIATE 'DROP TRIGGER T_COLLAB_BOM_LINE_ITEM_ROWIDS';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
DECLARE
BEGIN
     EXECUTE IMMEDIATE 'DROP PACKAGE collab_state_pkg';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
DECLARE
BEGIN
     EXECUTE IMMEDIATE 'CREATE INDEX XICA_I2 ON ITEM_CHANGE_AUDIT(OP_CODE) TABLESPACE AUDIT_INDEX';
EXCEPTION
     WHEN OTHERS THEN
          null;
END;
/
