ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE1 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE2 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE3 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE4 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE5 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE6 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE7 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE8 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE9 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD STRING_ATTRIBUTE10 VARCHAR2(1024);
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE1 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE2 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE3 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE4 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE5 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE6 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE7 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE8 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE9 NUMBER; 
ALTER TABLE PCM_FORECAST ADD NUMBER_ATTRIBUTE10 NUMBER;
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE1 NUMBER(19,6);
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE2 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE3 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE4 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE5 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE6 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE7 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE8 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE9 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD FLOAT_ATTRIBUTE10 NUMBER(19,6); 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE1 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE2 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE3 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE4 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE5 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE6 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE7 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE8 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE9 DATE; 
ALTER TABLE PCM_FORECAST ADD DATE_ATTRIBUTE10 DATE;




CREATE OR REPLACE VIEW IV_FORECAST_EXTRACT AS
 SELECT
    FC.FORECAST_KEY AS FORECAST_KEY,
    FC.FORECAST_EXTERNAL_ID AS FORECAST_EXTERNAL_ID,
    FC.DESCRIPTION AS DESCRIPTION,
    IM.ITEM_IDENTIFIER AS V_ITEM_IDENTIFIER,
    IM.ITEM_UNIQUE_IDENTIFIER AS V_ITEM_UNIQUE_IDENTIFIER,
    IM.REVISION AS V_ITEM_REVISION,
    IM.VERSION AS V_ITEM_VERSION,
    IM.ITEM_TYPE AS V_ITEM_TYPE,
    BE.BUSINESS_ENTITY_IDENTIFIER AS V_BUSINESS_ENTITY_IDENTIFIER,
    BE.BUSINESS_ENTITY_TYPE_KEY AS V_BUSINESS_ENTITY_TYPE_KEY,
    CAST(FC.EFFECTIVE_FROM_DT AS TIMESTAMP) AS EFFECTIVE_FROM_DT, 
    CAST(FC.EFFECTIVE_TO_DT AS TIMESTAMP) AS EFFECTIVE_TO_DT,
    DECODE(FC.SITE_KEY, NULL, NULL, S.SITE_IDENTIFIER) AS SITE,
    FC.FORECAST_TYPE AS FORECAST_TYPE,
    FC.FORECAST_MODEL AS FORECAST_MODEL,
    FC.PERIOD_TYPE AS PERIOD_TYPE,
    FC.CALENDAR_NAME AS CALENDAR_NAME,
    FC.PERIODIC_ADJUST_AMOUNT AS PERIODIC_ADJUST_AMOUNT,
    FC.PERIODIC_ADJUST_TYPE AS PERIODIC_ADJUST_TYPE,
    FC.CONFIDENCE_FACTOR AS CONFIDENCE_FACTOR,
    FC.REMAINING_ROLLOVERS AS REMAINING_ROLLOVERS,
    FC.STATUS AS STATUS,
    CAST(FC.STATUS_CHANGE_DATE AS TIMESTAMP) AS STATUS_CHANGE_DATE,
    FC.STATUS_LAST_CHANGE_BY AS STATUS_LAST_CHANGE_BY,
    CAST(FC.INSERT_DT AS TIMESTAMP) AS INSERT_DT,
    CAST(FC.UPDATE_DT AS TIMESTAMP) AS UPDATE_DT,
    FC.LAST_CHANGE_BY AS LAST_CHANGE_BY,
    FC.CURRENT_FLAG AS CURRENT_FLAG,
    FC.DELETE_FLAG AS DELETE_FLAG,
    FC.FORECAST_ORIGIN_EXTERNAL_ID AS ORIGIN_EXTERNAL_ID,
    FV.FORECAST_VALUE_KEY AS B_FORECAST_VALUE_KEY,
    CAST(FV.EFFECTIVE_FROM_DT AS TIMESTAMP) AS B_EFFECTIVE_FROM_DT,
    CAST(FV.EFFECTIVE_TO_DT AS TIMESTAMP) AS B_EFFECTIVE_TO_DT,
    FV.FORECAST_MEASURE_KEY AS B_TYPE,
    FV.FORECAST_UOM AS B_UOM,
    FV.FORECAST_VALUE AS B_VALUE,
    FV.SAVED_STATES AS B_LAST_APPROVED_INFORMATION,
    FC.STRING_ATTRIBUTE1 AS FC_STRING_ATTRIBUTE1,
    FC.STRING_ATTRIBUTE2 AS FC_STRING_ATTRIBUTE2,
    FC.STRING_ATTRIBUTE3 AS FC_STRING_ATTRIBUTE3,
    FC.STRING_ATTRIBUTE4 AS FC_STRING_ATTRIBUTE4,
    FC.STRING_ATTRIBUTE5 AS FC_STRING_ATTRIBUTE5,
    FC.STRING_ATTRIBUTE6 AS FC_STRING_ATTRIBUTE6,
    FC.STRING_ATTRIBUTE7 AS FC_STRING_ATTRIBUTE7,
    FC.STRING_ATTRIBUTE8 AS FC_STRING_ATTRIBUTE8,
    FC.STRING_ATTRIBUTE9 AS FC_STRING_ATTRIBUTE9,
    FC.STRING_ATTRIBUTE10 AS FC_STRING_ATTRIBUTE10,
    FC.NUMBER_ATTRIBUTE1 AS FC_NUMBER_ATTRIBUTE1,
    FC.NUMBER_ATTRIBUTE2 AS FC_NUMBER_ATTRIBUTE2,
    FC.NUMBER_ATTRIBUTE3 AS FC_NUMBER_ATTRIBUTE3,
    FC.NUMBER_ATTRIBUTE4 AS FC_NUMBER_ATTRIBUTE4,
    FC.NUMBER_ATTRIBUTE5 AS FC_NUMBER_ATTRIBUTE5,
    FC.NUMBER_ATTRIBUTE6 AS FC_NUMBER_ATTRIBUTE6,
    FC.NUMBER_ATTRIBUTE7 AS FC_NUMBER_ATTRIBUTE7,
    FC.NUMBER_ATTRIBUTE8 AS FC_NUMBER_ATTRIBUTE8,
    FC.NUMBER_ATTRIBUTE9 AS FC_NUMBER_ATTRIBUTE9,
    FC.NUMBER_ATTRIBUTE10 AS FC_NUMBER_ATTRIBUTE10,
    FC.FLOAT_ATTRIBUTE1 AS FC_FLOAT_ATTRIBUTE1,
    FC.FLOAT_ATTRIBUTE2 AS FC_FLOAT_ATTRIBUTE2,
    FC.FLOAT_ATTRIBUTE3 AS FC_FLOAT_ATTRIBUTE3,
    FC.FLOAT_ATTRIBUTE4 AS FC_FLOAT_ATTRIBUTE4,
    FC.FLOAT_ATTRIBUTE5 AS FC_FLOAT_ATTRIBUTE5,
    FC.FLOAT_ATTRIBUTE6 AS FC_FLOAT_ATTRIBUTE6,
    FC.FLOAT_ATTRIBUTE7 AS FC_FLOAT_ATTRIBUTE7,
    FC.FLOAT_ATTRIBUTE8 AS FC_FLOAT_ATTRIBUTE8,
    FC.FLOAT_ATTRIBUTE9 AS FC_FLOAT_ATTRIBUTE9,
    FC.FLOAT_ATTRIBUTE10 AS FC_FLOAT_ATTRIBUTE10,
    FC.DATE_ATTRIBUTE1 AS FC_DATE_ATTRIBUTE1,
    FC.DATE_ATTRIBUTE2 AS FC_DATE_ATTRIBUTE2,
    FC.DATE_ATTRIBUTE3 AS FC_DATE_ATTRIBUTE3,
    FC.DATE_ATTRIBUTE4 AS FC_DATE_ATTRIBUTE4,
    FC.DATE_ATTRIBUTE5 AS FC_DATE_ATTRIBUTE5,
    FC.DATE_ATTRIBUTE6 AS FC_DATE_ATTRIBUTE6,
    FC.DATE_ATTRIBUTE7 AS FC_DATE_ATTRIBUTE7,
    FC.DATE_ATTRIBUTE8 AS FC_DATE_ATTRIBUTE8,
    FC.DATE_ATTRIBUTE9 AS FC_DATE_ATTRIBUTE9,
    FC.DATE_ATTRIBUTE10 AS FC_DATE_ATTRIBUTE10
 FROM PCM_FORECAST FC 
 JOIN ITEM_MASTER IM ON FC.ITEM_KEY = IM.ITEM_KEY
 JOIN BUSINESS_ENTITY BE ON IM.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
 LEFT OUTER JOIN PCM_FORECAST_VALUE FV ON FC.FORECAST_KEY = FV.FORECAST_KEY 
 LEFT OUTER JOIN SITE S ON FC.SITE_KEY = S.SITE_KEY;


UPDATE PCM_WORKFLOW SET WORKFLOW_NAME = 'Data Management' WHERE WORKFLOW_NAME = 'Master Data Management';

INSERT INTO PCM_USER (USER_KEY, USER_ID, USER_NAME, BUSINESS_ENTITY_KEY, CONTACT_KEY, EMAIL_ADDRESS , FOREIGN_ID, ROLE_KEY, ENABLED_FLAG) 
VALUES (pcm_user_seq.nextval, 'SYSTEM','BATCH', 11, NULL, NULL, NULL, 1, 'Y');