CREATE SEQUENCE SC_ALERT_SEQ
        INCREMENT BY 1
        START WITH 1000
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
		
		
	CREATE TABLE SC_ALERT_DETAIL
   (	"ID" NUMBER(19,0), 
	"STATE" VARCHAR2(64 CHAR), 
	"DISMISED_BY" VARCHAR2(64 CHAR), 
	"USER_LOGIN_ID" VARCHAR2(64 CHAR), 
	"ALERT_LABEL" VARCHAR2(255 CHAR), 
	"ALERT_ID" VARCHAR2(512 CHAR), 
	"ALERT_TYPE" VARCHAR2(255 CHAR), 
	"CREATED" DATE, 
	"SHORT_SUMMARY" VARCHAR2(255 CHAR), 
	"LONG_SUMMARY" VARCHAR2(512 CHAR), 
	"EXPIRATION_DATE" DATE, 
	"PUNCHOUT_URL" VARCHAR2(1024 CHAR), 
	"STRING_ATTRIBUTE1" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE2" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE3" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE4" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE5" VARCHAR2(255 CHAR), 
	"STRING_ATTRIBUTE6" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE7" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE8" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE9" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE10" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE11" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE12" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE13" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE14" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE15" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE16" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE17" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE18" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE19" VARCHAR2(64 CHAR), 
	"STRING_ATTRIBUTE20" VARCHAR2(64 CHAR), 
	"DATE_ATTRIBUTE1" DATE, 
	"DATE_ATTRIBUTE2" DATE, 
	"DATE_ATTRIBUTE3" DATE, 
	"DATE_ATTRIBUTE4" DATE, 
	"DATE_ATTRIBUTE5" DATE, 
	"DATE_ATTRIBUTE6" DATE, 
	"DATE_ATTRIBUTE7" DATE, 
	"DATE_ATTRIBUTE8" DATE, 
	"DATE_ATTRIBUTE9" DATE, 
	"DATE_ATTRIBUTE10" DATE, 
	"NUMERIC_ATTRIBUTE1" FLOAT(126), 
	"NUMERIC_ATTRIBUTE2" FLOAT(126), 
	"NUMERIC_ATTRIBUTE3" FLOAT(126), 
	"NUMERIC_ATTRIBUTE4" FLOAT(126), 
	"NUMERIC_ATTRIBUTE5" FLOAT(126), 
	"NUMERIC_ATTRIBUTE6" FLOAT(126), 
	"NUMERIC_ATTRIBUTE7" FLOAT(126), 
	"NUMERIC_ATTRIBUTE8" FLOAT(126), 
	"NUMERIC_ATTRIBUTE9" FLOAT(126), 
	"NUMERIC_ATTRIBUTE10" FLOAT(126),
    CONSTRAINT alertid_pk PRIMARY KEY (ID) USING INDEX TABLESPACE AUDIT_INDEX
   );
   
   UPDATE PCM_WORKFLOW set WORKFLOW_URL='AlertSearch.do',WORKFLOW_URL_TARGET=null where WORKFLOW_KEY='MAIN_ALERTS';