CREATE TABLE FUNCTIONAL_GROUP (
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
NAME VARCHAR2(255) UNIQUE NOT NULL,
DESCRIPTION VARCHAR2(255),
TYPE VARCHAR2(255),
STATUS VARCHAR2(255),
ITEM_PLATFORM_KEY NUMBER(19,0),
STATUS_CHANGED_BY VARCHAR2(255),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
CONSTRAINT FG_PK PRIMARY KEY(FUNCTIONAL_GROUP_ID)
        USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT PLATFORM_FK FOREIGN KEY (ITEM_PLATFORM_KEY) REFERENCES ITEM_PLATFORM(ITEM_PLATFORM_KEY)		
)TABLESPACE AUDIT_DATA;

CREATE TABLE PARENT_FUNCTIONAL_GROUP (
PARENT_FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
NAME VARCHAR2(255) UNIQUE NOT NULL,
DESCRIPTION VARCHAR2(255),
TYPE VARCHAR2(255),
PURPOSE VARCHAR(255),
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
CONSTRAINT PFG_PK PRIMARY KEY(PARENT_FUNCTIONAL_GROUP_ID)
        USING INDEX TABLESPACE AUDIT_INDEX   
)TABLESPACE AUDIT_DATA;

CREATE TABLE ITEM_FG_MAP (
ITEM_KEY NUMBER(19,0) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
CONSTRAINT ITEM_IDENTIFIER_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT FUNCTIONAL_GROUP_ID_ITEM_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID)	
)TABLESPACE AUDIT_DATA;

CREATE TABLE FG_PFG_MAP (
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
PARENT_FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
CONSTRAINT FUNCTIONAL_GROUP_FG_ID_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT PARENT_FUNCTIONAL_GRP_ID FOREIGN KEY (PARENT_FUNCTIONAL_GROUP_ID) REFERENCES PARENT_FUNCTIONAL_GROUP(PARENT_FUNCTIONAL_GROUP_ID)
)TABLESPACE AUDIT_DATA;
                            
CREATE SEQUENCE FUNCTIONAL_GROUP_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE SEQUENCE PARENT_FUNCTIONAL_GROUP_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;