WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK

ALTER TABLE PCM_SOURCING_LANE
ADD COLLABORATION NUMBER(1);

CREATE INDEX XSL_COLLAB_I2 ON PCM_SOURCING_LANE(COLLABORATION) 
    TABLESPACE AUDIT_INDEX;
    
ALTER TABLE ITEM_MASTER 
ADD COLLABORATION NUMBER(1);

CREATE INDEX XITM_MSTR_ICOLLAB
	ON ITEM_MASTER (COLLABORATION)
		tablespace audit_index;

 
-- Collab Extract

CREATE TABLE PCM_JOB_STATUS_CONTROL
(
  JOB_ID VARCHAR2(32) NOT NULL,
  JOB_TYPE VARCHAR2(32),
  JOB_STATUS VARCHAR2(32) NOT NULL,
  JOB_START_DATE TIMESTAMP NOT NULL,
  JOB_END_DATE TIMESTAMP,
  CONSTRAINT XPJSC_PK PRIMARY KEY (JOB_ID)
	USING INDEX TABLESPACE AUDIT_INDEX
) TABLESPACE AUDIT_DATA;

CREATE  SEQUENCE ITEM_CHANGE_AUDIT_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
ALTER TABLE ITEM_CHANGE_AUDIT  ADD ITEM_CHANGE_AUDIT_KEY NUMBER(19);

UPDATE ITEM_CHANGE_AUDIT  set ITEM_CHANGE_AUDIT_KEY=ITEM_CHANGE_AUDIT_SEQ.NEXTVAL;

ALTER TABLE ITEM_CHANGE_AUDIT MODIFY ITEM_CHANGE_AUDIT_KEY NOT NULL;

ALTER TABLE ITEM_CHANGE_AUDIT ADD CONSTRAINT ITEM_CHANGE_AUDIT_PK PRIMARY KEY(ITEM_CHANGE_AUDIT_KEY);
