create table TAM_MRP_VOLUME
(
ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0),
ITEM_KEY NUMBER(19,0),
REGION_KEY NUMBER(19,2),
DATA_MEASURE VARCHAR2(255),
MRP_VALUE NUMBER(10,5),
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
FACILITY VARCHAR2(255),
CCN VARCHAR2(255),
SUB_LEVEL_DATA VARCHAR2(1),
CONSTRAINT SITE_KEY_TAM_MRP_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT REGION_KEY_TAM_MRP_FK FOREIGN KEY (REGION_KEY) REFERENCES SITE(SITE_KEY),
CONSTRAINT ITEM_KEY_TAM_MRP_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY),
CONSTRAINT TAM_MRP_VOLUME_PK PRIMARY KEY(ID,SITE_KEY,ITEM_KEY,START_DATE,END_DATE) USING INDEX TABLESPACE AUDIT_INDEX
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE TAM_MRP_VOLUME_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;