DELETE FROM PCM_WORKFLOW where WORKFLOW_KEY = 'EDIT_PROFILE';

CREATE TABLE XLOB_ALLOCATION (
ID NUMBER(19) NOT NULL,
FUNCTIONAL_GROUP_ID NUMBER(19,0) NOT NULL,
SITE_KEY NUMBER(19,0) NOT NULL,
LAST_CHANGED_ON TIMESTAMP(6),
LAST_CHANGED_BY VARCHAR2(255),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
LAST_SYSTEM_UPDATED_ON TIMESTAMP(6),
LAST_SYSTEM_UPDATED_BY VARCHAR2(255),
ROLL_OVER_COUNT NUMBER(6),
NEXT_ROLLOVER_DATE TIMESTAMP(6),
EXTRACT_FLAG VARCHAR2(1) DEFAULT 'Y' NOT NULL,
RECORD_SOURCE VARCHAR2(255),
CURRENT_DATA_DELETED VARCHAR2(1),
CONSTRAINT XLOB_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT XLOB_GROUP_FK FOREIGN KEY (FUNCTIONAL_GROUP_ID) REFERENCES FUNCTIONAL_GROUP(FUNCTIONAL_GROUP_ID),
CONSTRAINT SITE_KEY_XLOB_FK FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
)TABLESPACE AUDIT_DATA;


CREATE TABLE XLOB_ITEM_ALLOCATION (
ID NUMBER(19) NOT NULL,
XLOB_ALLOCATION_ID NUMBER(19,0) NOT NULL,
BUSINESS_ENTITY_KEY NUMBER(19,0) NOT NULL,
ITEM_KEY NUMBER(19,0) NOT NULL,
MANUFACTURER_PART VARCHAR2(255),
START_DATE TIMESTAMP(6),
END_DATE TIMESTAMP(6),
CREATED_ON TIMESTAMP(6),
CREATED_BY VARCHAR2(255),
ALLOCATION NUMBER(10,5),
CONSTRAINT XLOB_ITEM_PK PRIMARY KEY(ID) USING INDEX TABLESPACE AUDIT_INDEX,
CONSTRAINT XLOB_ALLOCATION_KEY_FK FOREIGN KEY (XLOB_ALLOCATION_ID) REFERENCES XLOB_ALLOCATION(ID),
CONSTRAINT XLOB_BUSINESS_ENTITY_FK FOREIGN KEY (BUSINESS_ENTITY_KEY) REFERENCES BUSINESS_ENTITY(BUSINESS_ENTITY_KEY),
CONSTRAINT XLOB_ITEM_KEY_FK FOREIGN KEY (ITEM_KEY) REFERENCES ITEM_MASTER(ITEM_KEY)
)TABLESPACE AUDIT_DATA;


CREATE SEQUENCE XLOB_ALLOCATION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        

CREATE SEQUENCE XLOB_ITEM_ALLOCATION_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
        
        
CREATE OR REPLACE PROCEDURE TAM_DELETE_CASCADE_INSERT(
    vOUT_RESULT OUT SYS_REFCURSOR )
AS
BEGIN
  INSERT
  INTO TAM_ALLOC_CASCADE_PROC_STG2
    (
      TAM_ALLOCATION_ID,
      FUNCTIONAL_GROUP_ID,
      FG_NAME,
      LAST_CHANGED_BY,
      LAST_CHANGED_ON,
      ALLOW_HEDGING,
      CREATED_BY,
      CREATED_ON,
      DISCP_EXTRACT_FLAG,
      SITE_KEY,
      SITE_IDENTIFIER,
      SITE_DESCRIPTION,
      SITE_TYPE,
      PARENT_SITE_KEY,
      REGION_PARENT_EXISTS
    )
  SELECT t.TAM_ALLOCATION_ID,
    t.FUNCTIONAL_GROUP_ID,
    fg.NAME,
    t.LAST_CHANGED_BY,
    t.LAST_CHANGED_ON,
    t.ALLOW_HEDGING,
    t.CREATED_BY,
    t.CREATED_ON,
    t.DISCP_EXTRACT_FLAG,
    t.SITE_KEY,
    s.SITE_IDENTIFIER,
    s.SITE_DESCRIPTION,
    s.SITE_TYPE,
    s.PARENT_SITE_KEY,
    1
  FROM TAM_ALLOCATION t
  INNER JOIN FUNCTIONAL_GROUP fg
  ON t.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID
  INNER JOIN site s
  ON s.SITE_KEY                = t.SITE_KEY
  WHERE t.CURRENT_DATA_DELETED = 'Y'
  AND t.DISCP_EXTRACT_FLAG     = 'P';
  COMMIT;
  OPEN VOUT_RESULT FOR SELECT 1
AS
  COUNT FROM DUAL;
EXCEPTION
WHEN OTHERS THEN
  RAISE;
END TAM_DELETE_CASCADE_INSERT;
/

insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
values ('CR_VARIANCE_REPORT', 'Price Variance Report', 'MCM', 'SL', 'costRecordPriceVariance.do', 4, NULL);

insert into PCM_WORKFLOW (WORKFLOW_KEY, WORKFLOW_NAME, WORKFLOW_GROUP, WORKFLOW_PARENT_KEY, WORKFLOW_URL, DISPLAY_ORDER, WORKFLOW_URL_TARGET)
values ('SF_VARIANCE_REPORT', 'Forecast Variance Report', 'MCM', 'FC', 'costForecastVariance.do', 3, NULL);


-- XLOB Rollover

create or replace PROCEDURE XLOB_ROLLOVER (CURRENT_MONTH_START DATE,NEXT_ROLLOVER DATE,ADD_MONTH_START DATE, ADD_MONTH_END DATE,
               COPY_MONTH_START DATE, COPY_MONTH_END DATE, MAX_ROLLOVER_COUNT NUMBER) AS
CURSOR cur_xlob_alloc IS
SELECT xa.ID as xlobID,fg.status, sd.*
FROM XLOB_ALLOCATION xa, functional_group fg,site s
LEFT JOIN SITE_DETAILS sd on sd.ID = s.SITE_DETAIL_ID
WHERE xa.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID
AND xa.site_key = s.site_key
AND xa.ROLL_OVER_COUNT < MAX_ROLLOVER_COUNT
AND (xa.NEXT_ROLLOVER_DATE < NEXT_ROLLOVER OR (xa.NEXT_ROLLOVER_DATE is null AND xa.CREATED_ON < CURRENT_MONTH_START));

rec_alloc cur_xlob_alloc%ROWTYPE;

BEGIN
  OPEN cur_xlob_alloc;
  LOOP
    FETCH cur_xlob_alloc INTO rec_alloc;
    EXIT WHEN cur_xlob_alloc%NOTFOUND;

    -- Add 12th month

    INSERT INTO XLOB_ITEM_ALLOCATION (ID, XLOB_ALLOCATION_ID, BUSINESS_ENTITY_KEY,ITEM_KEY,MANUFACTURER_PART,START_DATE, END_DATE,CREATED_ON,CREATED_BY,ALLOCATION)
	SELECT XLOB_ITEM_ALLOCATION_SEQ.NEXTVAL, xlobAlloc.ID, xlobPartAlloc.BUSINESS_ENTITY_KEY,xlobPartAlloc.ITEM_KEY,xlobPartAlloc.MANUFACTURER_PART,
	cal.FISCAL_PERIOD_START_DATE, cal.FISCAL_PERIOD_END_DATE,CURRENT_TIMESTAMP,'BATCH',
		(CASE  WHEN (rec_alloc.STATUS = 'ACTIVE' and rec_alloc.tam_visible_flag = '1') THEN xlobPartAlloc.allocation ELSE NULL END)
		FROM XLOB_ALLOCATION xlobAlloc, XLOB_ITEM_ALLOCATION xlobPartAlloc,
	    (SELECT m.FISCAL_PERIOD_START_DATE, m.FISCAL_PERIOD_END_DATE
	     FROM fiscal_period m
	     WHERE m.FISCAL_PERIOD_TYPE = 'M'
	     AND m.FISCAL_PERIOD_START_DATE >= ADD_MONTH_START  -- future month start
	     and m.FISCAL_PERIOD_END_DATE <= ADD_MONTH_END   -- future month end
	    ) cal
	WHERE xlobAlloc.ID = xlobPartAlloc.XLOB_ALLOCATION_ID
	AND xlobPartAlloc.START_DATE = COPY_MONTH_START -- last month start
	AND xlobPartAlloc.END_DATE = COPY_MONTH_END -- last month end
	AND xlobAlloc.ID = rec_alloc.xlobID
	AND NOT EXISTS (SELECT 'x' FROM XLOB_ITEM_ALLOCATION xlobPartAlloc1
	WHERE xlobPartAlloc1.XLOB_ALLOCATION_ID = xlobPartAlloc.XLOB_ALLOCATION_ID
	AND xlobPartAlloc1.BUSINESS_ENTITY_KEY = xlobPartAlloc.BUSINESS_ENTITY_KEY
	AND xlobPartAlloc1.START_DATE = cal.FISCAL_PERIOD_START_DATE
	AND xlobPartAlloc1.END_DATE = cal.FISCAL_PERIOD_END_DATE);

	--update allocation
	
	IF (rec_alloc.tam_visible_flag = '1' and rec_alloc.STATUS = 'ACTIVE') THEN
       UPDATE XLOB_ALLOCATION
       SET NEXT_ROLLOVER_DATE = NEXT_ROLLOVER,
           LAST_CHANGED_BY = 'BATCH',
           LAST_CHANGED_ON= CURRENT_TIMESTAMP,
           ROLL_OVER_COUNT = NVL(ROLL_OVER_COUNT,0) + 1,
           EXTRACT_FLAG = 'P'
       WHERE ID = rec_alloc.xlobID;
    ELSE
       UPDATE XLOB_ALLOCATION
       SET NEXT_ROLLOVER_DATE = NEXT_ROLLOVER
       WHERE ID = rec_alloc.xlobID;
    END IF;
    
	--update audit history
	
	INSERT INTO FG_AUDIT_HISTORY (AUDIT_KEY, DATE_PERFORMED, USER_ID, USER_ROLE, ACTION, OPERATION_CODE, COMMENTS, AUDIT_SOURCE, TAM_KEY, SITE, FG_KEY)
		SELECT FG_AUDIT_KEY_SEQ.NEXTVAL, CURRENT_TIMESTAMP, 'BATCH','ADMIN','BATCH','XLOB ROLLOVER',
		'XLOB Rolloved Over for FunctionalGroup: ' || fg.name || ' and Site: ' || s.site_description,'XLOB', xalloc.ID, s.site_key,xalloc.FUNCTIONAL_GROUP_ID
		FROM XLOB_ALLOCATION xalloc, FUNCTIONAL_GROUP fg,SITE s
		WHERE xalloc.FUNCTIONAL_GROUP_ID = fg.FUNCTIONAL_GROUP_ID
		AND fg.STATUS ='ACTIVE'
		AND xalloc.SITE_KEY = s.SITE_KEY
		AND xalloc.ROLL_OVER_COUNT < MAX_ROLLOVER_COUNT
		AND xalloc.ID = rec_alloc.xlobID;

    COMMIT;

  END LOOP;
  CLOSE cur_xlob_alloc;
  COMMIT;
END;
/

ALTER TABLE PCM_SEARCH_FILTER_VALUE MODIFY SEARCH_FILTER_FIELD_VALUE varchar2(4000 BYTE);

ALTER TABLE PCM_SEARCH_FILTER MODIFY SEARCH_FILTER_NAME varchar2(55 BYTE);

CREATE OR REPLACE VIEW IV_XLOB_TAM_EXTRACT AS 
SELECT
XA.LAST_CHANGED_ON AS LAST_CHANGED_ON ,
XA.CREATED_BY AS CREATED_BY ,
XA.CREATED_ON AS CREATED_ON ,
XA.LAST_CHANGED_BY AS LAST_CHANGED_BY ,
XA.RECORD_SOURCE AS RECORD_SOURCE ,
XA.LAST_SYSTEM_UPDATED_BY AS LAST_SYSTEM_UPDATED_BY ,
XA.ID AS ID ,
XA.EXTRACT_FLAG AS EXTRACT_FLAG ,
SI.SITE_IDENTIFIER AS SITE_IDENTIFIER ,
SI.SITE_DESCRIPTION AS SITE_DESCRIPTION ,
SI.SITE_TYPE AS SITE_TYPE ,
FG.NAME AS NAME ,
FG.TYPE AS FG_TYPE,
FG.FUNCTIONAL_GROUP_ID AS FUNCTIONAL_GROUP_ID , 
TA.ALLOW_HEDGING AS ALLOW_HEDGING ,  
BE.BUSINESS_ENTITY_NAME AS ITEM_BUSINESS_ENTITY_NAME ,
BE.BUSINESS_ENTITY_IDENTIFIER AS ITEM_BUSINESS_ENTITY_IDENTIFIER ,
SBE.BUSINESS_ENTITY_IDENTIFIER AS SUPPLIER_BUSINESS_ENTITY_IDENTIFIER,
SBE.BUSINESS_ENTITY_NAME AS SUPPLIER_BUSINESS_ENTITY_NAME ,
IMA.ITEM_IDENTIFIER AS ITEM_IDENTIFIER ,
XI.START_DATE AS START_DATE ,
XI.END_DATE AS END_DATE ,
XI.MANUFACTURER_PART AS MANUFACTURER_PART ,
XI.ITEM_KEY AS ITEM_KEY ,
XI.ALLOCATION AS ALLOCATION ,
XI.ID AS XLOB_ITEM_ID
FROM
XLOB_ALLOCATION XA
LEFT OUTER JOIN SITE SI ON SI.SITE_KEY = XA.SITE_KEY
LEFT OUTER JOIN FUNCTIONAL_GROUP FG ON FG.FUNCTIONAL_GROUP_ID = XA.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN TAM_ALLOCATION TA ON TA.FUNCTIONAL_GROUP_ID = XA.FUNCTIONAL_GROUP_ID
LEFT OUTER JOIN XLOB_ITEM_ALLOCATION XI ON XI.XLOB_ALLOCATION_ID = XA.ID
LEFT OUTER JOIN ITEM_MASTER IMA ON IMA.ITEM_KEY = XI.ITEM_KEY
LEFT OUTER JOIN BUSINESS_ENTITY SBE ON SBE.BUSINESS_ENTITY_KEY = XI.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY BE ON BE.BUSINESS_ENTITY_KEY = IMA.BUSINESS_ENTITY_KEY
ORDER BY XA.ID,XI.START_DATE;

ALTER TABLE PCM_COST_RECORD ADD (PROJECT_NAME VARCHAR2(255 BYTE));

/* Item Extract */
CREATE OR REPLACE VIEW IV_ITEM_EXTRACT AS 
  SELECT
  IM.ITEM_KEY AS ITEM_KEY ,
  IM.ITEM_UNIQUE_IDENTIFIER AS ITEM_UNIQUE_IDENTIFIER,  
  IM.ITEM_IDENTIFIER AS ITEM_IDENTIFIER,
  IM.ITEM_EXTERNAL_ID AS ITEM_EXTERNAL_ID,
  IM.ITEM_TYPE AS ITEM_TYPE,
  IM.GBL_UOM_CODE AS PRODUCT_UOM_CODE,
  IM.GBL_LFCYCL_PH_CODE AS LIFE_CYCLE_TYPE_CODE,
  IM.GBL_PROD_LFCYCL_CODE_OTHER AS LIFE_CYCLE_TYPE_CODE_OTHER,
  IM.ITEM_CLASSIFICATION AS ITEM_CLASSIFICATION,
  IM.PRODUCT_FAMILY AS PRODUCT_FAMILY,
  IM.MAKE_BUY AS MAKE_BUY,
  IM.MAKE_BUY_OTHER AS MAKE_BUY_OTHER,
  IM.SERIALNUMBER_REQUIRED AS SERIALNUMBER_REQUIRED,
  IM.CERTIFICATION_REQUIRED AS CERTIFICATION_REQUIRED,
  IM.OWNER_NAME AS OWNER_NAME,
  IM.ITEM_DESCRIPTION AS ITEM_DESCRIPTION,
  IM.IS_TOP_LEVEL AS IS_TOP_LEVEL,
  IM.COLLABORATION AS COLLABORATION,
  IM.ITEM_PART_TYPE AS ITEM_PART_TYPE,
  IM.INVENTORY AS INVENTORY,
  IM.EOL AS EOL,
  IM.EOL_LAST_CHANGED_ON AS EOL_LAST_CHANGED_ON,
  IM.EOL_TYPE AS EOL_TYPE,
  IM.UPDATE_DT AS UPDATE_DT,
  IM.DATA_SOURCE AS DATA_SOURCE,
  IM.VERSION AS VERSION,
  IM.REVISION AS REVISION,
  IM.VERSION_DATE AS VERSION_DATE,
  IM.REVISION_DATE AS REVISION_DATE,
  IM.MANAGED_FLAG AS MANAGED_FLAG,
  IM.STRING_ATTRIBUTE1 AS IM_STRING_ATTRIBUTE1,
  IM.STRING_ATTRIBUTE2 AS IM_STRING_ATTRIBUTE2,
  IM.STRING_ATTRIBUTE3 AS IM_STRING_ATTRIBUTE3,
  IM.STRING_ATTRIBUTE4 AS IM_STRING_ATTRIBUTE4,
  IM.STRING_ATTRIBUTE5 AS IM_STRING_ATTRIBUTE5,
  IM.STRING_ATTRIBUTE6 AS IM_STRING_ATTRIBUTE6,
  IM.STRING_ATTRIBUTE7 AS IM_STRING_ATTRIBUTE7,
  IM.STRING_ATTRIBUTE8 AS IM_STRING_ATTRIBUTE8,
  IM.STRING_ATTRIBUTE9 AS IM_STRING_ATTRIBUTE9,
  IM.STRING_ATTRIBUTE10 AS IM_STRING_ATTRIBUTE10,
  IM.NUMBER_ATTRIBUTE1 AS IM_NUMBER_ATTRIBUTE1,
  IM.NUMBER_ATTRIBUTE2 AS IM_NUMBER_ATTRIBUTE2,
  IM.NUMBER_ATTRIBUTE3 AS IM_NUMBER_ATTRIBUTE3,
  IM.NUMBER_ATTRIBUTE4 AS IM_NUMBER_ATTRIBUTE4,
  IM.NUMBER_ATTRIBUTE5 AS IM_NUMBER_ATTRIBUTE5,
  IM.NUMBER_ATTRIBUTE6 AS IM_NUMBER_ATTRIBUTE6,
  IM.NUMBER_ATTRIBUTE7 AS IM_NUMBER_ATTRIBUTE7,
  IM.NUMBER_ATTRIBUTE8 AS IM_NUMBER_ATTRIBUTE8,
  IM.NUMBER_ATTRIBUTE9 AS IM_NUMBER_ATTRIBUTE9,
  IM.NUMBER_ATTRIBUTE10 AS IM_NUMBER_ATTRIBUTE10,
  IM.FLOAT_ATTRIBUTE1 AS IM_FLOAT_ATTRIBUTE1,
  IM.FLOAT_ATTRIBUTE2 AS IM_FLOAT_ATTRIBUTE2,
  IM.FLOAT_ATTRIBUTE3 AS IM_FLOAT_ATTRIBUTE3,
  IM.FLOAT_ATTRIBUTE4 AS IM_FLOAT_ATTRIBUTE4,
  IM.FLOAT_ATTRIBUTE5 AS IM_FLOAT_ATTRIBUTE5,
  IM.FLOAT_ATTRIBUTE6 AS IM_FLOAT_ATTRIBUTE6,
  IM.FLOAT_ATTRIBUTE7 AS IM_FLOAT_ATTRIBUTE7,
  IM.FLOAT_ATTRIBUTE8 AS IM_FLOAT_ATTRIBUTE8,
  IM.FLOAT_ATTRIBUTE9 AS IM_FLOAT_ATTRIBUTE9,
  IM.FLOAT_ATTRIBUTE10 AS IM_FLOAT_ATTRIBUTE10,
  IM.DATE_ATTRIBUTE1 AS IM_DATE_ATTRIBUTE1,
  IM.DATE_ATTRIBUTE2 AS IM_DATE_ATTRIBUTE2,
  IM.DATE_ATTRIBUTE3 AS IM_DATE_ATTRIBUTE3,
  IM.DATE_ATTRIBUTE4 AS IM_DATE_ATTRIBUTE4,
  IM.DATE_ATTRIBUTE5 AS IM_DATE_ATTRIBUTE5,
  IM.DATE_ATTRIBUTE6 AS IM_DATE_ATTRIBUTE6,
  IM.DATE_ATTRIBUTE7 AS IM_DATE_ATTRIBUTE7,
  IM.DATE_ATTRIBUTE8 AS IM_DATE_ATTRIBUTE8,
  IM.DATE_ATTRIBUTE9 AS IM_DATE_ATTRIBUTE9,
  IM.DATE_ATTRIBUTE10 AS IM_DATE_ATTRIBUTE10,
  attr.ATTRIBUTE_KEY AS ATTRIBUTE_KEY,
  attr.ATTRIBUTE_NAME AS ATTRIBUTE_NAME,
  attr.ATTRIBUTE_VALUE AS ATTRIBUTE_VALUE,
  attr.ATTRIBUTE_TYPE AS ATTRIBUTE_TYPE,  
  ag.ATTRIBUTE_GROUP_NAME AS ATTRIBUTE_GROUP_NAME,
  pf.ITEM_PLATFORM_KEY AS ITEM_PLATFORM_KEY,
  pf.ITEM_PLATFORM_NAME AS ITEM_PLATFORM_NAME,
  pf.ITEM_PLATFORM_TYPE AS ITEM_PLATFORM_TYPE,
  pf.ITEM_PLATFORM_DESC AS ITEM_PLATFORM_DESC,
  ic.ITEM_CATEGORY_NAME   AS ITEM_CATEGORY_NAME,  
  be.BUSINESS_ENTITY_NAME AS BUSINESS_ENTITY_NAME,
  be.BUSINESS_ENTITY_TYPE_KEY AS BUSINESS_ENTITY_TYPE_KEY,   
  be.BUSINESS_ENTITY_IDENTIFIER AS BUSINESS_ENTITY_IDENTIFIER, 
  bet.BUSINESS_ENTITY_TYPE_NAME AS BUSINESS_ENTITY_TYPE_NAME,
  VC.CONTACT_NAME AS CONTACT_NAME,
  VC.CONTACT_UNIQUE_ID AS CONTACT_UNIQUE_ID
FROM
ITEM_MASTER IM
LEFT OUTER JOIN ITEM_ADD_ATTRIBUTE attr ON attr.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ATTRIBUTE_GROUP ag ON ag.ATTRIBUTE_GROUP_KEY = attr.ATTRIBUTE_GROUP_KEY
LEFT OUTER JOIN ITEM_ITEM_PLATFORM rpf ON rpf.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_PLATFORM pf ON pf.ITEM_PLATFORM_KEY = rpf.ITEM_PLATFORM_KEY
LEFT OUTER JOIN ITEM_ITEM_CATEGORY ric ON ric.ITEM_KEY = IM.ITEM_KEY
LEFT OUTER JOIN ITEM_CATEGORY ic ON ic.ITEM_CATEGORY_KEY = ric.ITEM_CATEGORY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY be ON be.BUSINESS_ENTITY_KEY = IM.BUSINESS_ENTITY_KEY
LEFT OUTER JOIN BUSINESS_ENTITY_TYPE bet ON bet.BUSINESS_ENTITY_TYPE_KEY = be.BUSINESS_ENTITY_TYPE_KEY
LEFT OUTER JOIN CONTACT VC ON IM.CONTACT_KEY = VC.CONTACT_KEY;

/* Cost Record Extract*/
CREATE OR REPLACE VIEW IV_COST_EXTRACT AS
 SELECT SL.SOURCING_LANE_KEY AS SL_KEY,
	SL.SOURCING_LANE_NAME AS SL_NAME,
	SL.SOURCING_LANE_EXTERNAL_ID AS SL_EXTERNAL_ID,
	SL.DESCRIPTION AS SL_DESCRIPTION,
	CPBE.BUSINESS_ENTITY_IDENTIFIER AS SL_COST_PROV_BUSINESS_ENTITY,
	SL.PRODUCT_STATE,
	IM.ITEM_IDENTIFIER AS SL_ITEM_IDENTIFIER,
	IM.ITEM_UNIQUE_IDENTIFIER AS SL_ITEM_UNIQUE_IDENTIFIER,
	IM.VERSION AS SL_ITEM_VERSION,
	IM.REVISION AS SL_ITEM_REVISION,
	BE.BUSINESS_ENTITY_IDENTIFIER AS SL_ITEM_BE_IDENTIFIER,
	BE.BUSINESS_ENTITY_TYPE_KEY  AS SL_ITEM_BE_TYPE_KEY,
	SBE.BUSINESS_ENTITY_IDENTIFIER AS SL_SUPPLIER_IDENTIFIER,
	SBE.BUSINESS_ENTITY_TYPE_KEY  AS SL_SUPPLIER_TYPE_KEY,
	TS.SITE_IDENTIFIER AS SL_TO_SITE,
    BTS.BUSINESS_ENTITY_IDENTIFIER AS SL_TO_SITE_BE_IDENTIFIER,
	BTS.BUSINESS_ENTITY_TYPE_KEY  AS SL_TO_SITE_BE_TYPE_KEY,
	FS.SITE_IDENTIFIER  AS SL_FROM_SITE,
	SL.DATE_OFFSET SL_OFFSET,
	SL.CURRENCY_CODE SL_CURRENCY,
	SL.CURRENT_FLAG AS SL_CURRENT_FLAG,
	SL.STATUS AS SL_STATUS,
    CAST(SL.STATUS_CHANGE_DATE AS TIMESTAMP) AS SL_STATUS_CHANGE_DT,    
    SL.STATUS_LAST_CHANGE_BY AS SL_STATUS_LAST_CHANGE_BY,
	CAST(COALESCE (SL.UPDATE_DT, SL.INSERT_DT) AS TIMESTAMP) AS SL_UPDATE_DT ,
	CR.COST_RECORD_KEY AS CR_KEY,
	CR.COST_RECORD_EXTERNAL_ID AS CR_EXTERNAL_ID,
	CR.COST_TYPE_KEY AS CR_TYPE_KEY,
	PSC.PRICING_SCENARIO_NAME AS CR_PRICING_SCENARIO,
	CRRNG.FROM_RANGE AS CRRNG_FROM_RANGE,
	CRRNG.TO_RANGE AS CRRNG_TO_RANGE,
	CRRNG.IS_ACTIVE AS CRRNG_IS_ACTIVE,
	CRV.COST_RECORD_VALUE_KEY AS CRV_KEY,
	CRV.COST_ELEMENT_KEY AS CRV_ELEMENT_KEY,
	CRV.COST_VALUE AS CRV_COST_VALUE,
	CRV.COST_UOM AS CRV_UOM,
	CPBE.BUSINESS_ENTITY_IDENTIFIER AS CR_PROVIDER_IDENTIFIER,
	CPBE.BUSINESS_ENTITY_TYPE_KEY AS CR_PROVIDER_TYPE_KEY,
	CAST(CR.EFFECTIVE_FROM_DT AS TIMESTAMP) AS CR_EFFECTIVE_FROM_DT,
	CAST(CR.EFFECTIVE_TO_DT AS TIMESTAMP) AS CR_EFFECTIVE_TO_DT,
	CR.CURRENT_FLAG AS CR_CURRENT_FLAG,
    CR.STATUS AS CR_STATUS,
    CAST(CR.STATUS_CHANGE_DATE AS TIMESTAMP) AS CR_STATUS_CHANGE_DATE,    
    CR.STATUS_LAST_CHANGE_BY AS CR_STATUS_LAST_CHANGED_BY,
	CAST(COALESCE(CR.UPDATE_DT, CR.INSERT_DT) AS TIMESTAMP) AS CR_UPDATE_DT,
	CR.DESCRIPTION AS CR_COMMENT,
    CR.REASON_CODE AS CR_REASON_CODE,
    CR.SYSTEM_ACTION AS CR_SYSTEM_ACTION,
    CR.PROJECT_NAME AS CR_PROJECT_NAME,
	IM.OWNER_NAME AS SL_OWNER_NAME,
	CRDV.COST_VALUE_DETAIL_KEY AS CRDV_KEY,
	CRDV.COST_VALUE_NAME AS CRDV_NAME, 
	CRDV.COST_VALUE_VALUE AS CRDV_VALUE, 
	CRDV.COST_VALUE_BLEND AS CRDV_BLEND,
	(SELECT SUM(COST_VALUE) FROM PCM_COST_RECORD_VALUE WHERE COST_RECORD_RANGE_KEY = CRRNG.COST_RECORD_RANGE_KEY) AS CR_TOTAL,
	BH.BOM_NAME,
	BH.VERSION AS BOM_VERSION,
	BH.REVISION AS BOM_REVISION,
	BBE.BUSINESS_ENTITY_IDENTIFIER AS BOM_BE_IDENTIFIER,
	BBE.BUSINESS_ENTITY_TYPE_KEY  AS BOM_BE_TYPE_KEY,
	SL.COLLABORATION,
	IM.DATA_SOURCE AS IM_DATASOURCE,
	CR.STRING_ATTRIBUTE1 AS CR_STRING_ATTRIBUTE1,
    CR.STRING_ATTRIBUTE2 AS CR_STRING_ATTRIBUTE2,
    CR.STRING_ATTRIBUTE3 AS CR_STRING_ATTRIBUTE3,
    CR.STRING_ATTRIBUTE4 AS CR_STRING_ATTRIBUTE4,
    CR.STRING_ATTRIBUTE5 AS CR_STRING_ATTRIBUTE5,
    CR.STRING_ATTRIBUTE6 AS CR_STRING_ATTRIBUTE6,
    CR.STRING_ATTRIBUTE7 AS CR_STRING_ATTRIBUTE7,
    CR.STRING_ATTRIBUTE8 AS CR_STRING_ATTRIBUTE8,
    CR.STRING_ATTRIBUTE9 AS CR_STRING_ATTRIBUTE9,
    CR.STRING_ATTRIBUTE10 AS CR_STRING_ATTRIBUTE10,
    CR.NUMBER_ATTRIBUTE1 AS CR_NUMBER_ATTRIBUTE1,
    CR.NUMBER_ATTRIBUTE2 AS CR_NUMBER_ATTRIBUTE2,
    CR.NUMBER_ATTRIBUTE3 AS CR_NUMBER_ATTRIBUTE3,
    CR.NUMBER_ATTRIBUTE4 AS CR_NUMBER_ATTRIBUTE4,
    CR.NUMBER_ATTRIBUTE5 AS CR_NUMBER_ATTRIBUTE5,
    CR.NUMBER_ATTRIBUTE6 AS CR_NUMBER_ATTRIBUTE6,
    CR.NUMBER_ATTRIBUTE7 AS CR_NUMBER_ATTRIBUTE7,
    CR.NUMBER_ATTRIBUTE8 AS CR_NUMBER_ATTRIBUTE8,
    CR.NUMBER_ATTRIBUTE9 AS CR_NUMBER_ATTRIBUTE9,
    CR.NUMBER_ATTRIBUTE10 AS CR_NUMBER_ATTRIBUTE10,
    CR.FLOAT_ATTRIBUTE1 AS CR_FLOAT_ATTRIBUTE1,
    CR.FLOAT_ATTRIBUTE2 AS CR_FLOAT_ATTRIBUTE2,
    CR.FLOAT_ATTRIBUTE3 AS CR_FLOAT_ATTRIBUTE3,
    CR.FLOAT_ATTRIBUTE4 AS CR_FLOAT_ATTRIBUTE4,
    CR.FLOAT_ATTRIBUTE5 AS CR_FLOAT_ATTRIBUTE5,
    CR.FLOAT_ATTRIBUTE6 AS CR_FLOAT_ATTRIBUTE6,
    CR.FLOAT_ATTRIBUTE7 AS CR_FLOAT_ATTRIBUTE7,
    CR.FLOAT_ATTRIBUTE8 AS CR_FLOAT_ATTRIBUTE8,
    CR.FLOAT_ATTRIBUTE9 AS CR_FLOAT_ATTRIBUTE9,
    CR.FLOAT_ATTRIBUTE10 AS CR_FLOAT_ATTRIBUTE10,
    CR.DATE_ATTRIBUTE1 AS CR_DATE_ATTRIBUTE1,
    CR.DATE_ATTRIBUTE2 AS CR_DATE_ATTRIBUTE2,
    CR.DATE_ATTRIBUTE3 AS CR_DATE_ATTRIBUTE3,
    CR.DATE_ATTRIBUTE4 AS CR_DATE_ATTRIBUTE4,
    CR.DATE_ATTRIBUTE5 AS CR_DATE_ATTRIBUTE5,
    CR.DATE_ATTRIBUTE6 AS CR_DATE_ATTRIBUTE6,
    CR.DATE_ATTRIBUTE7 AS CR_DATE_ATTRIBUTE7,
    CR.DATE_ATTRIBUTE8 AS CR_DATE_ATTRIBUTE8,
    CR.DATE_ATTRIBUTE9 AS CR_DATE_ATTRIBUTE9,
    CR.DATE_ATTRIBUTE10 AS CR_DATE_ATTRIBUTE10,
    IM.STRING_ATTRIBUTE1 AS IM_STRING_ATTRIBUTE1,
    IM.STRING_ATTRIBUTE2 AS IM_STRING_ATTRIBUTE2,
    IM.STRING_ATTRIBUTE3 AS IM_STRING_ATTRIBUTE3,
    IM.STRING_ATTRIBUTE4 AS IM_STRING_ATTRIBUTE4,
    IM.STRING_ATTRIBUTE5 AS IM_STRING_ATTRIBUTE5,
    IM.STRING_ATTRIBUTE6 AS IM_STRING_ATTRIBUTE6,
    IM.STRING_ATTRIBUTE7 AS IM_STRING_ATTRIBUTE7,
    IM.STRING_ATTRIBUTE8 AS IM_STRING_ATTRIBUTE8,
    IM.STRING_ATTRIBUTE9 AS IM_STRING_ATTRIBUTE9,
    IM.STRING_ATTRIBUTE10 AS IM_STRING_ATTRIBUTE10,
    IM.NUMBER_ATTRIBUTE1 AS IM_NUMBER_ATTRIBUTE1,
    IM.NUMBER_ATTRIBUTE2 AS IM_NUMBER_ATTRIBUTE2,
    IM.NUMBER_ATTRIBUTE3 AS IM_NUMBER_ATTRIBUTE3,
    IM.NUMBER_ATTRIBUTE4 AS IM_NUMBER_ATTRIBUTE4,
    IM.NUMBER_ATTRIBUTE5 AS IM_NUMBER_ATTRIBUTE5,
    IM.NUMBER_ATTRIBUTE6 AS IM_NUMBER_ATTRIBUTE6,
    IM.NUMBER_ATTRIBUTE7 AS IM_NUMBER_ATTRIBUTE7,
    IM.NUMBER_ATTRIBUTE8 AS IM_NUMBER_ATTRIBUTE8,
    IM.NUMBER_ATTRIBUTE9 AS IM_NUMBER_ATTRIBUTE9,
    IM.NUMBER_ATTRIBUTE10 AS IM_NUMBER_ATTRIBUTE10,
    IM.FLOAT_ATTRIBUTE1 AS IM_FLOAT_ATTRIBUTE1,
    IM.FLOAT_ATTRIBUTE2 AS IM_FLOAT_ATTRIBUTE2,
    IM.FLOAT_ATTRIBUTE3 AS IM_FLOAT_ATTRIBUTE3,
    IM.FLOAT_ATTRIBUTE4 AS IM_FLOAT_ATTRIBUTE4,
    IM.FLOAT_ATTRIBUTE5 AS IM_FLOAT_ATTRIBUTE5,
    IM.FLOAT_ATTRIBUTE6 AS IM_FLOAT_ATTRIBUTE6,
    IM.FLOAT_ATTRIBUTE7 AS IM_FLOAT_ATTRIBUTE7,
    IM.FLOAT_ATTRIBUTE8 AS IM_FLOAT_ATTRIBUTE8,
    IM.FLOAT_ATTRIBUTE9 AS IM_FLOAT_ATTRIBUTE9,
    IM.FLOAT_ATTRIBUTE10 AS IM_FLOAT_ATTRIBUTE10,
    IM.DATE_ATTRIBUTE1 AS IM_DATE_ATTRIBUTE1,
    IM.DATE_ATTRIBUTE2 AS IM_DATE_ATTRIBUTE2,
    IM.DATE_ATTRIBUTE3 AS IM_DATE_ATTRIBUTE3,
    IM.DATE_ATTRIBUTE4 AS IM_DATE_ATTRIBUTE4,
    IM.DATE_ATTRIBUTE5 AS IM_DATE_ATTRIBUTE5,
    IM.DATE_ATTRIBUTE6 AS IM_DATE_ATTRIBUTE6,
    IM.DATE_ATTRIBUTE7 AS IM_DATE_ATTRIBUTE7,
    IM.DATE_ATTRIBUTE8 AS IM_DATE_ATTRIBUTE8,
    IM.DATE_ATTRIBUTE9 AS IM_DATE_ATTRIBUTE9,
    IM.DATE_ATTRIBUTE10 AS IM_DATE_ATTRIBUTE10
 FROM PCM_SOURCING_LANE SL
 JOIN ITEM_MASTER IM ON SL.ITEM_KEY = IM.ITEM_KEY
 JOIN BUSINESS_ENTITY BE ON IM.BUSINESS_ENTITY_KEY = BE.BUSINESS_ENTITY_KEY
 LEFT OUTER JOIN PCM_COST_RECORD CR ON SL.SOURCING_LANE_KEY = CR.SOURCING_LANE_KEY
 LEFT OUTER JOIN PCM_COST_RECORD_RANGE CRRNG ON CR.COST_RECORD_KEY = CRRNG.COST_RECORD_KEY
 LEFT OUTER JOIN PCM_COST_RECORD_VALUE CRV ON CRRNG.COST_RECORD_RANGE_KEY = CRV.COST_RECORD_RANGE_KEY
 LEFT OUTER JOIN PCM_COST_VALUE_DETAIL CRDV ON CRV.COST_RECORD_VALUE_KEY = CRDV.COST_RECORD_VALUE_KEY
 LEFT OUTER JOIN PCM_PRICING_SCENARIO PSC ON PSC.PRICING_SCENARIO_KEY = CR.PRICING_SCENARIO_KEY
 LEFT OUTER JOIN BUSINESS_ENTITY SBE ON SL.SUPPLIER_KEY = SBE.BUSINESS_ENTITY_KEY
 LEFT OUTER JOIN BUSINESS_ENTITY CPBE ON CR.COST_PROVIDER_KEY = CPBE.BUSINESS_ENTITY_KEY
 LEFT OUTER JOIN SITE FS ON SL.FROM_SITE_KEY = FS.SITE_KEY
 LEFT OUTER JOIN SITE TS ON SL.TO_SITE_KEY = TS.SITE_KEY
 LEFT OUTER JOIN BUSINESS_ENTITY BTS ON TS.BUSINESS_ENTITY_KEY = BTS.BUSINESS_ENTITY_KEY
 LEFT OUTER JOIN BOM_HEADER BH ON BH.BOM_KEY = SL.BOM_KEY
 LEFT OUTER JOIN BUSINESS_ENTITY BBE ON BBE.BUSINESS_ENTITY_KEY = BH.BUSINESS_ENTITY_KEY;

Insert into PCM_WORKFLOW (WORKFLOW_KEY,WORKFLOW_NAME,WORKFLOW_GROUP,WORKFLOW_PARENT_KEY,WORKFLOW_URL,DISPLAY_ORDER,WORKFLOW_URL_TARGET)
values ('PriceTAM','Manage XLOB Price and Allocation','MCM','FUNCTIONAL_GROUP','priceTAMUI.do',8,null);


CREATE TABLE PCM_DB_CONFIGURATION (
	ID NUMBER(19) NOT NULL,
	CONFIG_KEY VARCHAR2(255) NOT NULL,
	CONFIG_VALUE VARCHAR2(255),
	CONFIG_VALUE_TYPE VARCHAR2(255)
)TABLESPACE AUDIT_DATA;

CREATE SEQUENCE PCM_DB_CONFIGURATION_KEY_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;

CREATE OR REPLACE TRIGGER T_ITEM_RESPONSIBILITY
	AFTER INSERT OR UPDATE OR DELETE ON PCM_ASSIGNMENT
	FOR EACH ROW
DECLARE
	v_item_key item_master.item_key%TYPE;
	v_item_type item_master.item_type%TYPE;
	v_config_value pcm_db_configuration.config_value%TYPE;
	v_item_config_exists number(1);
	v_continue NUMBER(1) := 0;
BEGIN
	IF DELETING THEN
		IF :old.assignment_type = 'I' THEN
			v_item_key := :old.object_key;
			v_continue := 1;
		END IF;
	ELSE
		IF :new.assignment_type = 'I' THEN
			v_item_key := :new.object_key;
			v_continue := 1;
		END IF;
	END IF;
	v_item_config_exists := 0;
	IF v_continue = 1 THEN
        SELECT ITEM_MASTER.ITEM_TYPE INTO v_item_type FROM ITEM_MASTER	WHERE ITEM_KEY = v_item_key;
		SELECT COUNT(config_value) INTO v_item_config_exists FROM PCM_DB_CONFIGURATION WHERE CONFIG_KEY = 'pcm.db.config.item.types.for.item.owner.extract' AND CONFIG_VALUE LIKE '%' ||  v_item_type || '%';
        IF v_item_config_exists != 0  THEN
            INSERT INTO ITEM_CHANGE_AUDIT
            (ITEM_CHANGE_AUDIT_KEY,ITEM_KEY,LAST_CHANGE_DT,OP_CODE)
            VALUES
            (ITEM_CHANGE_AUDIT_SEQ.NEXTVAL,v_item_key,SYSDATE,'OWNER');
        END IF;
	END IF;
END T_ITEM_RESPONSIBILITY;
/

CREATE INDEX LOAD_EVENT_JOB_KEY ON LOAD_EVENT(LOAD_JOB_KEY)TABLESPACE audit_index;