WHENEVER SQLERROR EXIT 5 ROLLBACK
WHENEVER OSERROR EXIT 10  ROLLBACK


ALTER TABLE BOM_LINE_ITEM ADD GROUP_ID VARCHAR2(255) NULL;
ALTER TABLE BOM_LINE_ITEM ADD BOM_LINE_ALT_TYPE VARCHAR2(64) NULL;
ALTER TABLE BOM_LINE_ITEM ADD PRIORITY NUMBER(2) NULL;
ALTER TABLE BOM_LINE_ITEM ADD REASON_CODE VARCHAR2(255) NULL;
