INSERT 
WHEN NOT EXISTS (SELECT 1 FROM ITEM_CATEGORY  WHERE ITEM_CATEGORY_KEY = -1 AND ITEM_CATEGORY_IDENTIFIER=-1 AND ITEM_CATEGORY_NAME= 'ALL' AND 
BUSINESS_ENTITY_KEY = 10  AND PARENT_CATEGORY_KEY IS NULL AND PRODUCT_FAMILY IS NULL AND MANAGED_FLAG IS NULL) 
THEN
INTO ITEM_CATEGORY (ITEM_CATEGORY_KEY,ITEM_CATEGORY_IDENTIFIER,ITEM_CATEGORY_NAME,BUSINESS_ENTITY_KEY,PARENT_CATEGORY_KEY,PRODUCT_FAMILY,MANAGED_FLAG) 
SELECT  -1 as ITEM_CATEGORY_KEY, -1 as ITEM_CATEGORY_IDENTIFIER,'ALL' as ITEM_CATEGORY_NAME,10 as BUSINESS_ENTITY_KEY,null as PARENT_CATEGORY_KEY,null as PRODUCT_FAMILY,null as MANAGED_FLAG  FROM DUAL;


DROP TABLE USER_COMMODITYPROFILE_MAPPING;

create table USER_COMMODITYPROFILE_MAPPING
(
	USER_KEY Number(19,0) NOT NULL,
	PROFILE_NAME varchar2(255) NOT NULL,
	CONSTRAINT USER_PROFILE_PK PRIMARY KEY (USER_KEY, PROFILE_NAME),
	CONSTRAINT userid_fk FOREIGN KEY (USER_KEY) REFERENCES PCM_USER(USER_KEY)
);

create table PCM_REGIONAL_REGION_MAP
(
	REGION_ID Number(19,0) NOT NULL,
	ASSIGNMENT_KEY Number(19,0) NOT NULL,
    SITE_KEY Number(19,0) NOT NULL,
	CONSTRAINT riogionId_pk PRIMARY KEY (REGION_ID) USING INDEX TABLESPACE AUDIT_INDEX,
	CONSTRAINT ASSIGNMENT_KEY FOREIGN KEY (ASSIGNMENT_KEY) REFERENCES PCM_ASSIGNMENT(ASSIGNMENT_KEY),
    CONSTRAINT SITE_KEY FOREIGN KEY (SITE_KEY) REFERENCES SITE(SITE_KEY)
);


CREATE SEQUENCE REGION_ID_SEQ
        INCREMENT BY 1
        START WITH 1
        NOMAXVALUE
        NOMINVALUE
        CACHE 20
        NOCYCLE ORDER;
        
ALTER TABLE PCM_ASSIGNMENT ADD REGION VARCHAR2(255);


CREATE OR REPLACE VIEW IV_ITEM_RESPONSIBILITY_EXTRACT AS
SELECT 
  ICA.ITEM_KEY, 
  I.DATA_SOURCE,
  I.ITEM_IDENTIFIER,
  I.ITEM_TYPE,
  B.BUSINESS_ENTITY_IDENTIFIER, 
  T.BUSINESS_ENTITY_TYPE_NAME,
  CAST(ICA.LAST_CHANGE_DT AS TIMESTAMP) AS UPDATE_DT,
  ICA.OP_CODE,
  A.RESPONSIBILITY,
  A.USER_ID,
  S.SITE_IDENTIFIER,
  S.SITE_TYPE,
  S.SITE_DESCRIPTION
FROM
  (SELECT
   ITEM_KEY,OP_CODE,MAX(LAST_CHANGE_DT) LAST_CHANGE_DT
   FROM ITEM_CHANGE_AUDIT
   GROUP BY ITEM_KEY,OP_CODE) ICA
  INNER JOIN ITEM_MASTER I ON I.ITEM_KEY = ICA.ITEM_KEY
  INNER JOIN BUSINESS_ENTITY B ON I.BUSINESS_ENTITY_KEY = B.BUSINESS_ENTITY_KEY
  INNER JOIN BUSINESS_ENTITY_TYPE T ON B.BUSINESS_ENTITY_TYPE_KEY = T.BUSINESS_ENTITY_TYPE_KEY
  LEFT OUTER JOIN PCM_ASSIGNMENT A ON A.OBJECT_KEY = ICA.ITEM_KEY
  AND A.ASSIGNMENT_TYPE = 'I'
  LEFT JOIN PCM_REGIONAL_REGION_MAP RRM ON A.ASSIGNMENT_KEY = RRM.ASSIGNMENT_KEY
  LEFT JOIN SITE S ON RRM.SITE_KEY = S.SITE_KEY; 