/*
 * Auto-generated by extract-backlog-features.ps1
 * Runs all backlog stories extracted from SCPLATFORM_BackLogCucumber_Scenarios.md
 */
/**
 * Copyright (c) 2026 Kumara Swamy — github.com/bkumars22
 * Supply Chain Intelligence Platform
 * Licensed under MIT License — see LICENSE file for details
 */
package com.test.selenium.scplatform.cucumberRunners;

import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.test.selenium.api.e2na.navigation.ConsoleThemeHelper;
import com.test.selenium.common.cucumber.GenerateCucumberReports.REPORT_TYPE;
import com.test.selenium.scplatform.base.E2CukeBase;

import io.cucumber.testng.CucumberOptions;

@CucumberOptions(
    plugin = {"json:target/cucumber-html-report/batch_backlog.json",
              "html:target/cucumber-html-report/cucumber.html",
              "junit:target/cucumber-junit-report.xml"},
    features = {"src/test/resources/com/scplatform/selenium/scplatform/cucumberFeatures/backlog"},
    glue = {"com.test.selenium.common.steps",
            "com.test.selenium.api.e2na.steps",
            "com.test.selenium.scplatform.steps"},
    tags = "@mvc and not (@pending or @bug or @skip)")
public class BatchBacklogWorkflowRunner extends E2CukeBase {

    @Override
    @BeforeSuite
    public void beforeSuite() {
        super.beforeSuite();
        setReportTitle("Backlog MVC Workflow Test Plan");
        setReportGenerationType(REPORT_TYPE.SkipReportGeneration);
        setConfigKeyForStack("stack.mcm");
        setSoftwareVersionsForBuild(new String[] {"scplatform"});
        setSystem();
        ConsoleThemeHelper.setE2NAStack();
    }

    @Test
    public void doNothing() {
        // allows the class to be run as a TestNG test
    }
}
