-- ============================================================
-- Flyway Migration V1 — Baseline Schema for PostgreSQL
-- Replaces H2 auto-DDL for production deployment
-- ============================================================

-- PCM_ROLE
CREATE TABLE IF NOT EXISTS PCM_ROLE (
    ROLE_KEY    BIGSERIAL PRIMARY KEY,
    ROLE_ID     VARCHAR(50)  UNIQUE NOT NULL,
    ROLE_NAME   VARCHAR(100) NOT NULL
);

-- PCM_USER
CREATE TABLE IF NOT EXISTS PCM_USER (
    USER_KEY    BIGSERIAL PRIMARY KEY,
    USER_ID     VARCHAR(50)  UNIQUE NOT NULL,
    USER_NAME   VARCHAR(200),
    EMAIL_ID    VARCHAR(200),
    PASSWORD    VARCHAR(200),
    IS_ENABLED  BOOLEAN DEFAULT TRUE,
    ROLE_KEY    BIGINT REFERENCES PCM_ROLE(ROLE_KEY)
);

-- ITEM_MASTER
CREATE TABLE IF NOT EXISTS ITEM_MASTER (
    ITEM_KEY        VARCHAR(50) PRIMARY KEY,
    ITEM_NAME       VARCHAR(500),
    UNIT_COST       NUMERIC(18,4),
    CATEGORY_CODE   VARCHAR(50),
    UOM             VARCHAR(20),
    CREATED_DATE    TIMESTAMP DEFAULT NOW()
);

-- BOM_HEADER
CREATE TABLE IF NOT EXISTS BOM_HEADER (
    BOM_KEY     VARCHAR(50) PRIMARY KEY,
    BOM_NAME    VARCHAR(500),
    BOM_DESC    VARCHAR(1000),
    STATUS      VARCHAR(50),
    BOM_VERSION VARCHAR(20),
    IS_TOP_LEVEL BOOLEAN DEFAULT FALSE,
    ITEM_KEY    VARCHAR(50) REFERENCES ITEM_MASTER(ITEM_KEY)
);

-- BOM_LINE_ITEM
CREATE TABLE IF NOT EXISTS BOM_LINE_ITEM (
    BOM_LINE_KEY VARCHAR(50) PRIMARY KEY,
    BOM_KEY      VARCHAR(50) REFERENCES BOM_HEADER(BOM_KEY),
    ITEM_KEY     VARCHAR(50) REFERENCES ITEM_MASTER(ITEM_KEY),
    ITEM_QTY     NUMERIC(18,4),
    LEAD_TIME    INTEGER,
    DESCRIPTION  VARCHAR(1000)
);

-- ALERT_DETAIL
CREATE TABLE IF NOT EXISTS ALERT_DETAIL (
    ID                  BIGSERIAL PRIMARY KEY,
    ALERT_TYPE          VARCHAR(100),
    ALERT_LABEL         VARCHAR(200),
    ALERT_ID            VARCHAR(100),
    SHORT_SUMMARY       VARCHAR(500),
    LONG_SUMMARY        TEXT,
    STATE               VARCHAR(50) DEFAULT 'ACTIVE',
    DISMISSED_BY        VARCHAR(100),
    USER_LOGIN_ID       VARCHAR(100),
    CREATED             DATE,
    EXPIRATION_DATE     DATE,
    PUNCHOUT_URL        VARCHAR(500),
    STRING_ATTRIBUTE1   VARCHAR(500),
    STRING_ATTRIBUTE2   VARCHAR(500),
    STRING_ATTRIBUTE3   VARCHAR(500),
    STRING_ATTRIBUTE8   VARCHAR(500)
);

-- SUPPLIER_PROFILE (MS3)
CREATE TABLE IF NOT EXISTS SUPPLIER_PROFILE (
    ID              BIGSERIAL PRIMARY KEY,
    SUPPLIER_NAME   VARCHAR(500) NOT NULL,
    OTD_SCORE       NUMERIC(5,2),
    QUALITY_SCORE   NUMERIC(5,2),
    TIER            VARCHAR(50),
    AT_RISK         BOOLEAN DEFAULT FALSE,
    CONTACT_NAME    VARCHAR(200),
    CONTACT_EMAIL   VARCHAR(200),
    CONTACT_PHONE   VARCHAR(50)
);

-- SUPPLIER_DELIVERY (MS3)
CREATE TABLE IF NOT EXISTS SUPPLIER_DELIVERY (
    ID                  BIGSERIAL PRIMARY KEY,
    SUPPLIER_ID         BIGINT REFERENCES SUPPLIER_PROFILE(ID),
    DELIVERY_DATE       DATE,
    ON_TIME             BOOLEAN,
    PO_NUMBER           VARCHAR(100),
    QUANTITY_ORDERED    INTEGER,
    QUANTITY_RECEIVED   INTEGER
);

-- MS3_COST_RECORD
CREATE TABLE IF NOT EXISTS MS3_COST_RECORD (
    ID              BIGSERIAL PRIMARY KEY,
    ITEM_KEY        VARCHAR(50) REFERENCES ITEM_MASTER(ITEM_KEY),
    PROPOSED_COST   NUMERIC(18,4),
    PREVIOUS_COST   NUMERIC(18,4),
    STATUS          VARCHAR(50) DEFAULT 'DRAFT',
    JUSTIFICATION   TEXT,
    EFFECTIVE_DATE  DATE,
    CREATED_BY      VARCHAR(100),
    APPROVED_BY     VARCHAR(100),
    APPROVED_AT     TIMESTAMP,
    REJECTED_BY     VARCHAR(100),
    REJECTED_AT     TIMESTAMP,
    REJECTION_REASON TEXT,
    CREATED_AT      TIMESTAMP DEFAULT NOW()
);

-- PCM_FORECAST (MS4)
CREATE TABLE IF NOT EXISTS PCM_FORECAST (
    ID              BIGSERIAL PRIMARY KEY,
    ITEM_KEY        VARCHAR(50),
    FORECAST_TYPE   VARCHAR(50),
    START_PERIOD    VARCHAR(20),
    END_PERIOD      VARCHAR(20),
    CREATED_BY      VARCHAR(100),
    CREATED_AT      TIMESTAMP DEFAULT NOW()
);

-- PCM_FORECAST_VALUE (MS4)
CREATE TABLE IF NOT EXISTS PCM_FORECAST_VALUE (
    ID              BIGSERIAL PRIMARY KEY,
    FORECAST_ID     BIGINT REFERENCES PCM_FORECAST(ID),
    PERIOD          VARCHAR(20),
    PERIOD_LABEL    VARCHAR(50),
    FORECAST_QTY    NUMERIC(18,2),
    ACTUAL_QTY      NUMERIC(18,2)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_alert_state    ON ALERT_DETAIL(STATE);
CREATE INDEX IF NOT EXISTS idx_cost_status    ON MS3_COST_RECORD(STATUS);
CREATE INDEX IF NOT EXISTS idx_supplier_risk  ON SUPPLIER_PROFILE(AT_RISK);
CREATE INDEX IF NOT EXISTS idx_delivery_supp  ON SUPPLIER_DELIVERY(SUPPLIER_ID);
CREATE INDEX IF NOT EXISTS idx_bom_line_bom   ON BOM_LINE_ITEM(BOM_KEY);
